### ISSUE TITLE
Initial request for confirming permissions can be dismissed

### ISSUE THREAD

**Issue by theAkito** [mendhak/gpslogger#1000]
When you start the app for the first time, it tells you in a pop-up, that permissions need to be given. However, if this pop-up is dismissed (**not** confirmed), then the permission requests do not pop-up, rendering the app useless and the app does not even notice it, because it assumes the initial pop-up, and therefore the following requests, were not dismissed.

## Solution
Make the initial pop-up undismissable.

**Comment by mendhak** [comment]
Thanks for noticing that, I've made it less dismissable now. 

v124 is now on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v124).
