### ISSUE TITLE
Custom URL request interval

### ISSUE THREAD

**Issue by klopp** [mendhak/gpslogger#1001]
"Auto Send" => "Custom URL". I set the interval to 10 minutes. 5 minutes. 30... Regardless of the interval, it beats once a minute.

```

```

**Comment by mendhak** [comment]
Do you have both of the toggles enabled? The top one is for logging (once a minute) the bottom one is for sending (once an hour)

![image](https://user-images.githubusercontent.com/746276/188276859-b0139c29-f67e-411a-9e98-37d3114804e5.png)
