### ISSUE TITLE
Sending csv to custom url

### ISSUE THREAD

**Issue by algor512** [mendhak/gpslogger#1002]
I noticed that when both log to CSV and log to custom URL are enabled, gpslogger sends time to time CSV to the custom url. I propose:

1. Mention this behaviour in documentation and/or settings, as I guess it is not something obvious.
2. Make it optional, i.e. make it possible to log to both CSV file and custom URL without sending CSV to the URL.

**Comment by mendhak** [comment]
Do you have 'allow auto sending' checked in 'custom URL' screen? Along with 'log to custom url'? 

The auto sending is what gets sent every 1 hour by default.  The log to custom URL is every 60 seconds by default.
