### ISSUE TITLE
Android 13 support

### ISSUE THREAD

**Issue by basings** [mendhak/gpslogger#1006]
gpslogger does not support the latest version of android (13). Hence it can't write to the storage and no gps logging is saved, if Photos and videos permission is given. However, if I don't allow it and grant a storage scope, it works as expected.

**Comment by basings** [comment]
That was my fault due to a false error message of gpslogger not supporting the newest android version. It was resolved in https://github.com/zhanghai/MaterialFiles/issues/852

**Comment by mendhak** [comment]
Oh I see what you mean, OK thanks for sharing that outcome too.
