### ISSUE TITLE
[FEATURE] Add intent to upload data

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#1007]
It will be useful to have an intent to upload data.
A lot of time I have an inconsistent Internet connection and sometimes it happens that some files are not sent.
With the intent, I can schedule with Tasker a profile that automatically upload the files when I'm in a certain location where I'm sure to have a good Internet connection.

**Comment by mendhak** [comment]
Well this is embarrassing.  I just started looking at this and realized it already exists, just with a bad name.  You can apparently send `emailAlarm:true` and it initiates the file uploads.  This must be a name from before there were other upload options.  

As they say [one of the hardest problems](https://twitter.com/secretGeek/status/7269997868) in programming is naming things.  

I am going to break this name in the next release and call it `immediateautosend`, and add it to the FAQ page.

**Comment by mendhak** [comment]
Test APK with the new name here.  Hoping to find some time to test it.  https://github.com/mendhak/gpslogger/releases/tag/v126-rc1

**Comment by andreapx** [comment]
I've installed, but I still see the version 125.
Should I uninstall that one first?

**Comment by mendhak** [comment]
Yes I think you will lose all settings and all files if you install this APK. Android doesn't allow the same package name!

**Comment by andreapx** [comment]
Can you name this one as GPSLoger_beta or something like this?

**Comment by mendhak** [comment]
I can't, it's the `com.mendhak.gpslogger` package name which is what the OS is complaining about.  It's fine if you're unable to test, I'll test it in an emulator. 

In the meantime with your existing version, you can try passing `emailAlarm: true` from Tasker and see if the upload is still working.

**Comment by andreapx** [comment]
I'm trying it, but I don't see any connection from the smartphone to my server. All my files have been already updated, can this be the "problem"? If yes, then I don't know how to test it, sorry... :(

**Comment by mendhak** [comment]
It may not be sent if logging is turned off, the auto send relies on the logging to be on. I just tried it with the new name and it worked fine.  



![Image](https://user-images.githubusercontent.com/746276/215347979-cc6823c6-18c1-4c50-960d-87c16a50d95d.png)

**Comment by mendhak** [comment]
v126 is now in [releases](https://github.com/mendhak/gpslogger/releases/tag/v126) and [fdroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/).
