### ISSUE TITLE
trouble uploading to openGTS server

### ISSUE THREAD

**Issue by exekutive** [mendhak/gpslogger#1018]
connection seems to be OK, but no points are showing up on server.
I have a debug log I'd love to provide, but I don't think I want to share it here publicly.

**Comment by mendhak** [comment]
You can send it to `gpslogger at mendhak.com` and link to this issue, thought it can take me a while before I get to go through it.

**Comment by exekutive** [comment]
Thank you for the assistance. I got the logging working.
By the way, what is the difference between all these options?

- 
- Menu -> Logging Details -> Log to OpenGTS Server (on/off)
- Menu -> OpenGTS -> Allow auto sending (on/off)
- Menu -> Auto send, email and upload -> Allow auto sending (on/off) and OpenGTS (on/off)

**Comment by mendhak** [comment]
Sorry I missed this.  

Log to OpenGTS is basically logging every time there's a new point received. 
Open GTS Allow auto sending is allowing all the points to be re-sent every (by default) 60 minutes as part of the auto sending feature. 
The main Allow auto sending toggle enables or disables the auto-send feature across the app.

**Comment by exekutive** [comment]
Are these two the same?

Menu -> OpenGTS -> Allow auto sending (on/off)
Menu -> Auto send, email and upload -> OpenGTS (on/off)

**Comment by mendhak** [comment]
Yes they're the same, just a convenience to be in two places.

**Comment by exekutive** [comment]
maybe it adds more confusion than convenience

![phonetrack](https://user-images.githubusercontent.com/4755215/204163748-96a43b84-9edf-45ad-9bdb-100ed8312daf.png)
