### ISSUE TITLE
Notification show negative duration

### ISSUE THREAD

**Issue by JanHellwig** [mendhak/gpslogger#1027]
If the app is running for a long time, the duration that shows up in the persistent notifaction starts showing negative numbers. My guess would be that it's caused by some integer overflowing.
It seems to only have a visual impact, logging still works without problems.

![negative_time](https://user-images.githubusercontent.com/6281990/203734061-9e968c14-a1c2-47c6-8c41-92db9bd0deeb.jpg)

**Comment by scmyxp** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/11432989/206351367-8b1be420-6475-47df-a63a-b72e6a08c6b0.png)

**Comment by mendhak** [comment]
I found the issue, it's because I was converting a large long to an int, losing precision.  I've now made the method that converts it to a descriptive string, take a long and added a test for it too.

**Comment by mendhak** [comment]
v125 is now in [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [release](https://github.com/mendhak/gpslogger/releases/tag/v125).
