### ISSUE TITLE
 [Feature request] Send notification in different channel in case of error

### ISSUE THREAD

**Issue by neilguertin** [mendhak/gpslogger#1053]
If a session is in progress but logging fails for some reason, the app should send a notification to let the user know.

I generally leave the app running 24/7 and have hidden the constant notification from the device's notification settings. Several times now the logging has failed and I only noticed several days later because I happened to open the app.

The logging has failed for several reasons, for example when logging to a local file and storage fills up or permissions get changed. Basically any time red warning text gets printed to log view.

It might be useful to have notifications for warnings too (timeout reached, etc) but they should be in a separate channel from errors.

**Comment by mendhak** [comment]
I've done some work on this yesterday.   
Discussion and test APK is here: #1138   
I'll close this thread and move to that one.

**Comment by mendhak** [comment]
v131 is in the [releases](https://github.com/mendhak/gpslogger/releases) and [FDroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
