### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [mendhak/gpslogger#1055]
Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-21-00-30-49-991_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220197888-a9b69526-cc94-470c-b986-48bc8342fe88.jpg)

Thanks.

**Comment by mendhak** [comment]
The good news is I had already got adaptive icons via SVG, so all I've done is given the same colour to everything in the SVGs. But I could do with a better version, there's probably a nice neater way of drawing the satellite. 

What are you using to display those icons? I am using the 'Themed icons' toggle in an Android 13 emulator, and the icons are only themed on the home screen but not in the app drawer. 

This is what it looks like 
![image](https://user-images.githubusercontent.com/746276/230640546-f0b90b79-ee4d-4a47-a0d0-d67382c2a01a.png)

The SVG is here for reference if it's possible to somehow make it more 'solid' looking. 

![gpslogger_monochrome](https://user-images.githubusercontent.com/746276/230640916-03b381f0-3ba9-45c4-ab3c-897eaefb32f3.svg)

**Comment by xmha97** [comment]
Thanks. 🙏

**Comment by mendhak** [comment]
v127 is on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and the [Releases](https://github.com/mendhak/gpslogger/releases/tag/v127) section.
