### ISSUE TITLE
Map view of current GPS track

### ISSUE THREAD

**Issue by dfabbro** [mendhak/gpslogger#1060]
Create a simple map view of the GPS track currently being logged.
Currently app users do not have the ability to identify where they have been when using the GPS Logger application.
Offline view of the basemap (caching) would be great.

**Comment by zhangziran** [comment]
This feature may make the application bigger, and my current approach is to simultaneously assist other maps such as Google to determine the location. If using online methods, it is necessary to support various maps from different countries, and if using offline maps, the volume will be even larger. I hope that the GPSLogger can maintain its original intention, perform necessary core functions and minimize power consumption. As for other peripheral analysis, matching, display and other functions, they can be entrusted to a third party.

**Comment by mendhak** [comment]
Yeah it would add quite a bit to GPSLogger and make it harder to maintain, my aim is to focus on the core as @zhangziran has mentioned. 

I currently use [OsmAnd](https://osmand.net/), it lets me import a GPX file and shows it on a map. It also allows for downloading the map tiles for offline use. Would be good to hear what other people use as well.
