### ISSUE TITLE
Feature Request: Noforeignland.com integration

### ISSUE THREAD

**Issue by nookits** [mendhak/gpslogger#1066]
It would be nice to integrate seemlessly with noforeignland. 

I am happy to work on this but don't want to spend time on such a matter if it is not the direction the owners want the project to go.

**Comment by mendhak** [comment]
Hi I'm not sure exactly what integration means in this context, but if you mean ability to send positions I can see that they accept [emails with GPX files](https://test-dot-noforeignland-cloud.appspot.com/help/boat/move-gpx), so it should be possible to automate sending to that email address on a regular basis. 

The Custom URL feature could work with API requests, and there seems to be some [third party API integration here](https://test-dot-noforeignland-cloud.appspot.com/help/boat/move-at). 

As for direct native integration no that's not something I'd want added thanks for the offer though.
