### ISSUE TITLE
Feature request - Log at predicted distance

### ISSUE THREAD

**Issue by LordSimpson** [mendhak/gpslogger#107]
Hi after using the app for a couple of days the distance setting doesn’t seem to work as I would expect it to. 

I'm using 5 minutes / 10meter logging, but when I travelled a large distance I still only got new data points when it was time to log (every 5 mins).

Would it be possible to have a predictive distance setting which checks the distance between the last 2 points to obtain speed then alter the next call for logging accordingly.

e.g. point 1 at x=0m y=0m, then when point 2 5 minutes later is logged at x=1000m y=0m (1km change)

1000/(60*5) = ~3mps so if logging is set at 10m the next log would fire ~3 seconds later so

0:00:00 x=0 y=0
0:05:00 x=1000 y=0
0:05:03 x=1010 y=0
0:05:06 x=1020 y=0
etc, but with some error calculations so it doesn’t think your zipping around your local area due to poor gps availability in buildings.

**Comment by mendhak** [comment]
Closest way to do this now would be a smaller logging interval and setting a distance filter.  That does the calculations/differences.  However, doing it predictively would require constant logging which can't be done with GPSLogger
