### ISSUE TITLE
Faster CustomURL uploading.

### ISSUE THREAD

**Issue by krusic22** [mendhak/gpslogger#1073]
Currently, when using Auto Send to upload a CSV, only about 5 rows per second are sent. As a result, files such as 3-hour long tracks with 1-second logging take more than 30 minutes to upload.

Is it possible to add an option that enables users to adjust the speed at which requests are sent?

**Comment by mendhak** [comment]
The 5 per second is a good observation it's because each line in the CSV gets queued as a single background job, and the background jobs are I think 5/second. I've now made a change in Milestone 130, where the requests get grouped together.

**Comment by mendhak** [comment]
v130 is now on FDroid and the releases.

**Comment by krusic22** [comment]
Can confirm. Custom uploads are now fast AF. 🚀
