### ISSUE TITLE
A guide to obtain a Forever Service on Android

### ISSUE THREAD

**Issue by busslina** [mendhak/gpslogger#1080]
Hello, first of all, congrats about this app.

I want to know if you can provide a brief guide or comment about achieve a forever foreground service like you achieved on this app.
If you have some documentation or links that you used to do it. Or simply the main keys.

I want my forever foreground service to be connected to a server via websocket.

Thank you

https://gist.github.com/varunon9/f2beec0a743c96708eb0ef971a9ff9cd
https://github.com/urbandroid-team/dont-kill-my-app/issues/639

**Comment by busslina** [comment]
https://gist.github.com/varunon9/f2beec0a743c96708eb0ef971a9ff9cd

**Comment by mendhak** [comment]
I think I can point at the various things I've done to keep the app alive, but note that it's not always successful, some manufacturer's implementations are quite aggressive and still manage to kill it. Also in some cases I'm not able to achieve the 'kinda guaranteed' 5 minutes interval in doze mode, despite following the Android guidance. 

So main thing is to create a service with a notification, that's the important bit. 
https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L90-L97

In the onstartcommand of the service, I'm also returning a sticky variable:
https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L144  - it's from so long ago I can't remember what this is doing, I think it tells the OS to restart the service in case it's killed. 

There's more, in the onDestroy, where the OS might destroy the app while it's running, I've sent a broadcast to the app itself to restart. 
https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L155-L158

You can see as well, on low memory, an attempt to log the next point after a few minutes have passed, to give the OS some time to rest. https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L163-L170

When I set the alarm for the next point I'm using the AlarmManager. Not sure if it's the best approach and I think JobManager is recommended now but I haven't had time to look into it. Anyway the AlarmManager: https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L1012

I _think_ that's it, aside from that some attempts at not being too aggressive with battery usage. eg, adding a bit of sleep in the loops. Not trying to use too much memory.  No science behind these last bits, it's more superstition than anything else.
