### ISSUE TITLE
The final ZIP files contain incomplete tracks

### ISSUE THREAD

**Issue by JanisE** [mendhak/gpslogger#1082]
I've been trying GPSLogger out for a week now, configured to automatically upload zipped tracks to Drive each hour.

When I now look at all the files in the storage directory on the phone – GPX files mixed with ZIP files –, I notice that (most?) of the ZIP files contain incomplete GPX files compared to the actual non-zipped GPX files.

As I understand, if GPS logging is going on for a while, when an automatic upload needs to be done, the incomplete GPX – as it is at the moment – gets zipped and uploaded. When the next time to upload comes, the updated GPX file gets zipped and uploaded and overwrites the older ZIP file.

However, it seems that when the logging is stopped, the last track bit never gets zipped and uploaded.

**Comment by mendhak** [comment]
So far what you've described sounds just about right. When the transfer needs to happen, the GPX is zipped and the zip is uploaded. If the last upload doesn't happen have a look at the setting "When I press stop" which is under the Auto send settings. If that's unchecked then that could be why nothing is sent right at the end.

**Comment by JanisE** [comment]
Yes, that option was disabled, thank you!

**Comment by mendhak** [comment]
That makes sense to me because it's a way of completing the track, if you're auto sending you want the final thing to be sent too. Added in milestone 128

**Comment by mendhak** [comment]
It's on FDroid now.
