### ISSUE TITLE
Custom URL - Parameter %SPD sends a wrong knot speed value

### ISSUE THREAD

**Issue by djelloul78** [mendhak/gpslogger#1094]
Bonjour,

I'm discovering your Gpslogger app and it's a very nice piece of SW with many features for GPS logging and capacity to be programatically used.
I'm using your app to supply gps tracking data to a Traccar server using OsmAnd protocol.
I can receive "live" and updated position thanks to your job.

However, I'm observing a knot speed that is underestimated during all the recorded trip.
I'm familiar with my work path, and I have 2 areas were I'm driving at 70km/h and another one at 80km/h during 2 min in average, tightly and regularly due to the presence of speedcams in these locations.

When I consult these point on my Traccar server, I'm reading a speed around 30-35km/h when at 70km/h in real condition, and 35-45km/h when at 80km/h IRL.

I took a look at the live log view during the trip and I confirm the data sent are the one coming from the app and not a re-treated data made by the server.
But when switching back to the Simple View, I can see the expressed GPS speed is right.

I'm a little bit puzzled as I was thinking the %SPD will send a speed that is exactly the one used to show it on smartphone screen.

Do you have an idea of why this behavior is occuring?
There's maybe something wrong with my phone or an app setting that I didn't take attention justifying such speed calculation difference?

I'll be glad if I can have some help to confim if my trouble is an issue or a case limited to my phone.
I can share data on request, just let me know which one you're expecting and the format to be used.

My phone characteristics:
Realme X2 Pro
256GB Dataflash
12GB RAM
SoC: Snapdragon 855 Plus

If there's any additional question, please feel free to ask.
Thank you for your attention.

**Comment by mendhak** [comment]
Sorry for the late reply. I'm not sure where you are seeing knots? If you mean the imperial units, that should be displaying feet per second (the code just converts meter to feet) but important to note that's only for display purposes. All values are in SI so the value being sent is meter/second.

**Comment by djelloul78** [comment]
Thank you for your reply and I also apologize for taking so long to give you some feedback.
Your answer makes sense and I confirm your statement as I've controlled the content of the data sent to my Traccar server and converting them does perfectly fit to a speed expressed in meter/second.

To give you more insight about why I'm talking about knots speed, this is because the Traccar server application I'm using is usually managing raw data coming from NMEA sentences spit by GPS devices.
In order to have the application compliant with a majority of solution, it uses the minimal information that could be retreived from GNSS devices and usually the common speed information available in all GNNS variant is the ground speed expressed in **Knots** instead of regular speed units (m/s, km/h, etc...).

The issue I'm facing now is clearly explained by another Traccar user in this [forum post](https://www.traccar.org/forums/topic/osmand-speed-unit-other-than-knots/
).

I've dropped a support request in the same topic as it seems the issue can be managed by playing with some configuration file.
If you're OK, I'll close this topic if I receive no answer in the next 30 days or if I eventually find a solution in this expected delay.
Do you agree with that?

Thank you again for your kind attention.

**Comment by djelloul78** [comment]
Replying to myself.

My issue is in fact handled by my Traccar web server system.
It has a specific setting to manage data expressed in m/s to be displayed in km/h, but it isn't document, explaining why I wasn't able to find it by myself.
After applying the modification in my server configuration file, everything is now working perfectly.

Thank you for the attention you shared on this topic.
It can be closed without issue.
