### ISSUE TITLE
Custom URL: Why is the HTTP Body empty?

### ISSUE THREAD

**Issue by dancesWithCycles** [mendhak/gpslogger#1096]
Hi folks,
Thank you so much for providing and maintaining this repository.

I stumbled over it and could straight setup the `Custom URL` use case. Kudos!

Anyhow, I did not manage to receive a HTTP Body.

Is that because my HTTP Headers are empty?

Here are my settings.

```
# performance
## log gps/gnss locations
Checked

## log network locations
Checked

## log passive locations
Unchecked

## logging interval
60s

## keep gps on between fixes
Unchecked

# log to custom url

## log to custom url
Checked

## allow auto sending
Checked

## discard offline locations
Unchecked

## Url
https://<host>/get-log?lat=%LAT&lon=%LON&time=%TIME&s=%SPD&id=%AID&ser=%SER

## Http body
{"position":{"lat":%LAT, "lng":%LON}, "speed":%SPD, "satellites":%SAT, "accuracy":%ACC, "battery": %BATT, "travelled":%DIST, "direction":%DIR, "id":%AID, "ser":%SER}

## Http headers
Empty

## Http method
POST

## Basic Authentication
Empty
```

Every hint is appreciated! Cheers!

**Comment by mendhak** [comment]
I think your best start would be to follow the [troubleshooting here](https://gpslogger.app/#troubleshooting). There should be a hint in the logs about why the request failed.

**Comment by dancesWithCycles** [comment]
@mendhak 

Please do not get me wrong. My requests do **not** fail. My web service is receiving and processing the `HTTP POST` request in a successful manner. It only seems that the `HTTP Body` is empty.

```
 debug log:post() req.body: {} +0ms
  debug log:post() req.query: {"lat":"52.2659442","lon":"10.439493","time":"2023-09-07T09:52:43.633Z","s":"0.0","id":"e947f7532e668010","ser":"e947f7532e668010"} +0ms
```

I attached the corresponding `debuglog.txt` file.

[debuglog.txt](https://github.com/mendhak/gpslogger/files/12547417/debuglog.txt)

Every hint is appreciated! Cheers!

**Comment by mendhak** [comment]
So I've had a look through the debug log, nothing stnads out. I also retried it myself, on device and emulator too, and passing the body is working just fine. I copied your settings to be sure and just changed the domain. 

![image](https://github.com/mendhak/gpslogger/assets/746276/9b46c8b4-3121-4565-b85a-5f30d8bdbb0b)

As a test to eliminate if it's  GPSLogger problem, are you able to run [docker http https echo](https://hub.docker.com/r/mendhak/http-https-echo)? It requires running a Docker image. 

Are there any extra layers in your serverside that's expecting additional information? eg on the headers you could try passing `Content-Type: application/json` if there is some kind of web filter in front?

**Comment by dancesWithCycles** [comment]
I mixed up HTTP GET und POST in the `URL` parameter attribute. Now it works just fine. Appreciate! Cheers!
