### ISSUE TITLE
Dynamic Parameters in File Names No Longer Work

### ISSUE THREAD

**Issue by aerickt** [mendhak/gpslogger#1105]
Since updating to v128, I haven't been able to use dynamic parameters in the filename. Did the format change?

![gpslogger](https://github.com/mendhak/gpslogger/assets/52895314/202131ee-de9a-43aa-a5ad-ef3d97574220)

**Comment by mendhak** [comment]
:facepalm: it's a mistake. Fixing. Please can you go back a version until it's fixed. I'll do a v129 tag just for this. Sorry!

**Comment by aerickt** [comment]
Thanks for the quick reply! I had downgraded to 127 in the meantime.

**Comment by mendhak** [comment]
I've published tag v129: https://github.com/mendhak/gpslogger/releases/tag/v129

It usually takes a few days to appear on F-Droid.
