### ISSUE TITLE
Option for accelerometer detection is gone?

### ISSUE THREAD

**Issue by mikae1** [mendhak/gpslogger#1106]
There used to be an option for logging if GPSLogger detects accelerometer changes. I can't find it anymore. Is it gone?

**Comment by mendhak** [comment]
Yes it used to exist but it had to be removed to make the app compatible with F-Droid. The library that provided activity based on accelerometer was part of Play Management Services. I don't know if there are any reliable open source ones that can be used instead, I'd imagine those libraries would be quite heavy - that's assuming they contain a small trained model.
