### ISSUE TITLE
[Feature request] Auto logging while driving

### ISSUE THREAD

**Issue by plapic** [mendhak/gpslogger#1120]
The ability to start logging when connected to car bluetooth and stop logging when disconnected so that every car trip is logged.

**Comment by mendhak** [comment]
Hey in this case I'd suggest using Llama/Tasker, which are better at automating things when an event occurs. There are tons of events that different people will want to start logging, so it makes sense to use an app dedicated to that. 

https://gpslogger.app/#howtoautomategpslogger

**Comment by plapic** [comment]
I have **AutomateIt Pro**. I will try their Launch Intent Action. Based on the link you sent I'm guessing the following
Action Name: **com.mendhak.gpslogger.TASKER_COMMAND**
Category: **?**
Data: **immediatestart:true**
Package name: **com.mendhak.gpslogger**
Component name: **?**
MIME Type: **?**

**Comment by mendhak** [comment]
I just tried AutomateIt and this worked for me
  
    Broadcast
    
    Action Name: com.mendhak.gpslogger.TASKER_COMMAND
    
    Package Name: com.mendhak.gpslogger
    
    Component Name: com.mendhak.gpslogger/com.mendhak.gpslogger.TaskerReceiver

    Add Extra > immediatestart, Boolean, true


![image](https://github.com/mendhak/gpslogger/assets/746276/4ee5dac0-7862-456a-8df3-020558617e0c)
