### ISSUE TITLE
GPSLogger vs GPS Logger

### ISSUE THREAD

**Issue by Offerel** [mendhak/gpslogger#1141]
I have found 2 apps with similar names, 
 GPSLogger (this app here) and GPS Logger (https://github.com/BasicAirData/GPSLogger). 

You  have made some statements about other apps regarding battery life and usage as companion for geotagging DSLR photos. Can you please make a similar statement regarding this app to?

**Comment by mendhak** [comment]
OK I've added a note in an upcoming PR about BasicAirData's version and Ultra GPS Logger

https://github.com/mendhak/gpslogger/pull/1126/commits/a93d29ff0cad0fdc753e199dfaf29ce37330ea24 

I haven't really tried these other apps though, so not much else to say.

**Comment by mendhak** [comment]
v131 is in the [releases](https://github.com/mendhak/gpslogger/releases) and [FDroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
