### ISSUE TITLE
Error installing f-droid version 131-RC2

### ISSUE THREAD

**Issue by jimbox51** [mendhak/gpslogger#1163]
Tried to install the version on F-droid but if failed saying unknown error.
The device is a Fairphone 5 running Android 14

**Comment by mendhak** [comment]
Are you getting that Google Play Protect warning?
You need to expand and say install anyway. 
I didn't know they had implemented this.
Is it happening because my min SDK version is quite low? 

![image](https://github.com/user-attachments/assets/8c01a494-ccf8-46d6-8562-0f86d9f24906)

**Comment by jimbox51** [comment]
Hi,

On Fri, 13 Sep 2024, mendhak wrote:

> Are you getting that Google Play Protect warning?

Yes. I've just retried this.

> You need to expand and say install anyway. 

Yes - I missed that. I expanded and it did install.

> I didn't know they had implemented this.
> Is it happening because my min SDK version is quite low? 

Not usre why it is happenning - butm with most F-droid apps, I find it 
warns that the app was built for an older version of android and connot be 
updated automatically.

Many thanks for taking the time to reply and making me revisit. I've only 
had a smartphone for a few weeks and am still getting used to things.

Jim

**Comment by mendhak** [comment]
Not a problem, any other issues feel free to post again. 
I'm going to make a note to try and figure out about this warning because it seems to be becoming more invasive. I'm hoping it's a simple fix that will still allow me to target older versions of Android, sadly that's where  a lot of the issues come from!

**Comment by bengan** [comment]
Think you need to open this again. I could not install from neither f-droid nor local apk. It didn't work with expand and install. I had to actively turn off Google Play Protect and then install. Tried several times with f-droid and local apk and expand. After installing it, you can enable Google Play Protect again. Nothing seems to happen with the app after that.

I'm on Nothing Phone (1), Nothing OS 2.6, Android 14.

**Comment by bengan** [comment]
I saw that your about to release 132. From what I read it should fix this issue. Sorry about the fuzz.

**Comment by mendhak** [comment]
Reopening. I've got a [branch going here](https://github.com/mendhak/gpslogger/pull/1168) which is only updating the SDK versions. There are quite a few behaviour changes in there, and I think I will have to drop Android 4.x support as well.  I'll add this issue to that PR.

**Comment by mendhak** [comment]
I've put an APK with latest SDK version here: https://github.com/mendhak/gpslogger/releases/tag/v132-test1

If possible would be good to know if this new version throws a warning or blockers for you. If it's not possible that's OK too, I'll try to test in an emulator or something. 



In this newest APK, when I tried installing it I got a Google Play Protect dialog saying, it had never seen this app before, so it wanted to scan it. After it scanned it it proceeded as normal.

**Comment by bengan** [comment]
Sorry for the late reply.

No warnings or blockers just the usual about permissions (location, notification, run in background (always)) on installation. It worked as expected.

thanks

**Comment by podkilla** [comment]
yeah, same here with the v132-test1 release. had the same issues with the f-droid version (131-rc2).
i am on android 14 (grapheneos) on pixel 9 xl pro.

**Comment by licaon-kter** [comment]
Note that Play Protect is not a monolithic thing, it changes over time as more users press "install anyway", you can usually repro in a short time span, but later it might never popup again for the same appid and signature.

**Comment by mendhak** [comment]
v132 is now in [FDroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [Releases](https://github.com/mendhak/gpslogger/releases/tag/v132).
