### ISSUE TITLE
Translation (Hungarian)

### ISSUE THREAD

**Issue by BLaszlo001** [mendhak/gpslogger#1172]
Some texts translated into Hungarian (weblate) are published in English.

**Comment by BLaszlo001** [comment]
![IMG_20241028_212240](https://github.com/user-attachments/assets/20432f6a-5321-4efe-ab66-d4b53678cb8e)
![IMG_20241028_212213](https://github.com/user-attachments/assets/d739be55-53a1-4694-b9f8-894586ba6491)
![signal-2024-10-28-18-27-41-523](https://github.com/user-attachments/assets/89697440-ccf0-47e4-a827-c10d1f0d7e0f)

**Comment by mendhak** [comment]
I've pushed up a few changes, it should use some existing language strings, though no idea if it makes sense. For the annotation view it says "Mentett Hely 0" and 1 and 2 and 3 etc. 

For the 'Hide notification from lockscreen' that was completely hardcoded all these years, so I've moved it to strings.xml and should get some translations at some point. 

I've put [an APK here](https://github.com/mendhak/gpslogger/releases/tag/v132-rc3) if you want to test, if not that's fine, hoping to release soon.

**Comment by BLaszlo001** [comment]
I modified what I could.

**Comment by BLaszlo001** [comment]
I modified what I could.

**Comment by mendhak** [comment]
v132 is now in [FDroid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [Releases](https://github.com/mendhak/gpslogger/releases/tag/v132).
