### ISSUE TITLE
Last update: app crashes as soon as I open it

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#1177]
After I've updated the app to the latest version (132 from F-Droid), it doesn't work anymore.
As soon as I open it, it close. I see the icon in the center of the screen and it closes.
I've cleared cache (no, not data, please no!).
I've rolled back to 131-rc2 and it works.
I'm on a Pixel 7 with Android 15

**Comment by mendhak** [comment]
I've tried multiple ways but I wasn't able to recreate it https://github.com/mendhak/gpslogger/issues/1176

If you are able to look at the logcat if you could capture the stacktrace that appears that would be useful. I've tried all sorts of combinations but clearly something is 'happening' at startup which I'm simply not able to get in my testing. 

Or... I wonder... in 131-RC2 enable debug logging, then update, then let it crash, then grab the log file?

**Comment by andreapx** [comment]
> Or... I wonder... in 131-RC2 enable debug logging, then update, then let it crash, then grab the log file?

I wanted to do this and...I've found out that I'm on 132! 😆 It probably updated automatically after I've rolled back to 131.rc2.
Well...it works! 🤷‍♂️

**Comment by mendhak** [comment]
OK kind of worrying though, there have been a few reports of crashes but I can't recreate it. I will close this for now then.
