### ISSUE TITLE
App saving only 3 minute data

### ISSUE THREAD

**Issue by Namnamkuraka** [mendhak/gpslogger#1182]
I need to get data on the satellite position and snr for a long period of time. In the rinex file in the time column the time is written correctly, but the accompanying txt file has only 3 minutes of records. I tried to disable the power saving mode for this application, but it did not help.

Here is an example of a 5 minute recording
[gnss_log_2024_12_17_22_55_04.zip](https://github.com/user-attachments/files/18168511/gnss_log_2024_12_17_22_55_04.zip)

**Comment by mendhak** [comment]
Hi, the files you've posted seem to be from a different app called GnssLogger. https://play.google.com/store/apps/details?id=com.google.android.apps.location.gps.gnsslogger&hl=en_GB

This repo is for GPSLogger which is unrelated to that one. You can try the 'app support' section on that Play Store page they might be able to help you.
