### ISSUE TITLE
Feature request: Support for higher-frequenzy (i.e 10hz) logging

### ISSUE THREAD

**Issue by haaninjo** [mendhak/gpslogger#119]
I bought a Qstarz 818xt 10hz logger that can send 10 positions a second, making 0.1 seconds between positions. This makes the 1 second lower cap (brought on by minimumSeconds being an int) on time intervals in gpslogger too big to log all received positions.

I tried setting the time interval to 0 but the results were not nice with a largely unresponsive system as result.

As a hack to get all my wanted positions logged i changed 3 occurrences of minimumSeconds*1000 to minimumSeconds*100, effectively making the least considered unit of time a tenth of a second rather than a second. If minimumSeconds is set to 1, gpslogger now receives positions every 0.1 seconds as wanted.

A proper fix would probably be to make minimumSeconds a float instead.

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup.  For further discussion consider creating a new issue. 

Additional notes: None
