### ISSUE TITLE
Start GPS Logger on phone startup

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#12]
<b>mendhak[CodePlex]</b><br />Need to investigate a way if it&#39;s possible to start GPSLogger on phone startup and start logging. Need to also investigate if this isn&#39;t unaesthetic to the user.

**Comment by Namec** [comment]
hello,

does this feature have been implemented since 2011

**Comment by mendhak** [comment]
Hello yes it's there.  Go to the 'General' options screen and you will see 'start on bootup'

[See screenshot](https://gpslogger.app/#generalsettings)
