### ISSUE TITLE
Invalid second last point tracks made with external gps in Cyanogenmod

### ISSUE THREAD

**Issue by dittaeva** [mendhak/gpslogger#122]
See these tracks:
http://www.openstreetmap.org/user/Guttorm%20Flatab%C3%B8/traces/1289236
http://www.openstreetmap.org/user/Guttorm%20Flatab%C3%B8/traces/1289236

They look like they only have two points, when in fact they have several hundred, which you'll see if you download them. If you open them in Viking or JOSM you'll see that the second last track point is at lat/lon 0.0, but when looking at the source of the gpx I have found no such point, so there must be something broken in the syntax or something.

This has only happened when I have tracked with a external Holux bluetooth tracker connected to Android with the GPS source setting in Cyanogenmod, I do not interrupt the tracking in any way.

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: None
