### ISSUE TITLE
Phone Reboot on no-gps signal

### ISSUE THREAD

**Issue by cberetta** [mendhak/gpslogger#132]
I'm having problem with phone-reboot when GPS-Logger is running and cannot find a GPS-Sygnal.

Phone Detail:
* HTC Desire
* CyanoGenMod 7.2.0.1-bravo
* Android 2.3.7
* Kernel 2.6.37.6
* Baseband 32.56.00.32U_5.17.05.23

__I'v made 2 test today:__

_experiment 1_: I've started logging from my office to home (about 1 hour by car) and no problem till I get into my house, at that time after few minutes the phone rebooted without telling anything. I log in GPX Format and file appears to be completed, (closing tags are presents)

_experiment 2_: I've started the logging directly inside my house but first I've enabled the logging feature, no GPS-signal and after few minutes phone rebooted and no log file found on the phone.

Ideas?

**Comment by mendhak** [comment]
Should no longer be occurring due to architectural changes.  Closing.
