### ISSUE TITLE
File content options

### ISSUE THREAD

**Issue by wworldtraveler58** [mendhak/gpslogger#141]
There is much information in the .gpx file that is not needed for many purposes. For many uses only time, lat and long are required.  It would be nice to be able to select the items to be recorded, or at least "compact" and "verbose" settings.  This would result in smaller files.  This is definitely a low priority and does not impact functionality.

**Comment by mendhak** [comment]
Unfortunately the way the files are generated makes this too complicated.  Only took me 3 years to reply. :disappointed:
