### ISSUE TITLE
Record only when moving / increase frequency when moving

### ISSUE THREAD

**Issue by bagilevi** [mendhak/gpslogger#142]
I would like it to automatically start logging when I start to move, then stop logging when I stop. 

For example, it should check the location every minute, and if I'm more than 200m away from the previous point, start logging with the highest precision. Then, when I stay within 200m for 3 minutes, stop logging. 

I would be happy to pay $10 for a pro version that would do this.

**Comment by mendhak** [comment]
Closest I could do is using activity recognition; upon detecting movement it's logging regularly.  When user activity stops it will stop logging until user moves again.  (Performance menu, right at the bottom).  Having it figure out distance from previous point would require continuous logging.
