### ISSUE TITLE
Time in text file output and altitude on display and in output files

### ISSUE THREAD

**Issue by fepeacock** [mendhak/gpslogger#146]
Hello Mendhak

Thanks for this great app. It works perfectly for my purposes except for one small time zone output problem and one large altitude value problem.

Regarding time output: Is the usage of UTC on text file output due to GPX output requirements? Am I right to understand that local time output within the text file is impossible?

Regarding altitude values: For the altitude I am getting unusual negative values on the display and output file. I am in Sri Lanka and am expecting altitude/elevation values of roughly 20 to 30m but am getting values between -65m and -75m both on the display and in the text file. I have verified the altitude using other GPS apps and DEM data from satellites. If I set imperial units it seems to produce negative values but now in feet. Hence instead of 60 to 95 feet I am getting -210 to -249 feet. I do not see any settings for altitude calculations. Is the altitude values due to some assumption about the Earth as a spheroid or something else?

Thanks

Frank

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes:  Altitude offset feature pull request was merged (sorry never updated this thread).
