### ISSUE TITLE
Accuracy: Adding components of HDOP and mean SNR

### ISSUE THREAD

**Issue by mayeulk** [mendhak/gpslogger#149]
In assessing the precision of a GPS track for mapping, HDOP is useful but is only part of the story. (see http://www.outdoormaps.org/?p=138 for discussion and links).

First: HDOP (horizontal dilution of precision) is the quadratic mean of "EDOP" (easting DOP) and "NDOP" (northing DOP).
If we had both EDOP and NDOP, we could represent the DOP in JOSM as an ellipse instead of a circle (as in http://www.outdoormaps.org/?p=128).
Use case: You have two GPS tracks. On both, you went through Queen's road and King's road.
On Queen's Road, the two GPX tracks are 50 meters apart, one (track A) on the east, the other on the west (track B). Track B has both high EDOP and NDOP on all points. Track A has high NDOP but very low EDOP. So, for the purpose of mapping a road oriented north-south, track A is very good. You discard track B and map Queen's Road on top of track A.

On King's Road, the two GPX tracks are 50 meters apart, one (track A) on the east, the other on the west (track B). Both tracks A and B have high EDOP and NDOP on all points of King's road. You draw  King's Road in the middle, at an equal distance of tracks A and B. (In OpenStreetMap, you may add those tags: fixme=resurvey; note=averaged from 2 low-precision GPS tracks).

Editors like JOSM would show the DOP like an ellipse, not like a circle

I provide some working prototype code (in R) and alink to the maths on how to do this at http://www.outdoormaps.org/?p=138; nothing hard here, tell me if I can help.

(A further improvement would be actually to store the direction of the highest DOP: this may not always be north-south or east-west).

------
Second: DOP conveys only the information on the position of the satellite. As discussed in the above link, SNR is equally important. One or more satellite(s) with a very low SNR may signal reflections or signal that is so low that it becomes barely usable.
Mean SNR (accross all used satellites) is probably an excellent start.
In particular according to one scientific reference[1], it is useful in combination to the number of satellites. 
Ref [1] presents a use case. Another one would be to have circles/ellipse in JOSM that would show the accuracy based on combining xDOP and SNR.

Mayeul Kauffmann

[1] Pigott, "Inferring Transportation Mode using Smartphone Sensor Data", 2011, p. 42
http://www.piggott.me.uk/blog/2011/08/25/inferring-transportation-mode-using-smartphone-sensor-data/

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: Note that none of this information is available via the Android SDK.  SNR is available but I'd like to understand a use case and that it isn't a niche case
