### ISSUE TITLE
Possibility to transfer $GPGGA

### ISSUE THREAD

**Issue by interconn** [mendhak/gpslogger#160]
Hi, 
it would be great if the app could also transfer $GPGGA in OpenGTS-mode because it contains more informations than $GPRMC, e.g. accuracy and number of satellites.

The whole definition can be seen at http://aprs.gids.nl/nmea/

Thanks

**Comment by mendhak** [comment]
(Very very late but...) I'd suggest using the custom URL feature instead, modifying OpenGTS' url would cause more trouble than is worth.
