### ISSUE TITLE
Option to have logging turn on when application starts

### ISSUE THREAD

**Issue by buzz42** [mendhak/gpslogger#163]
I would like to be able to choose whether logging is turned on when start the application. The background of my question: I start the application under certain conditions using a task scheduler (SmartActions/Motorola), but I have to turn on logging manually.

Could you implement an option to have initial logging turned on/off?

Thank you for your support and you very smooth running software,

Buzz

**Comment by yrtimiD** [comment]
latest version does have this feature! :)

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: As yrtimiD said.  Sorry for not updating.
