### ISSUE TITLE
Feature Request : enable/disable GPS

### ISSUE THREAD

**Issue by tkasp** [mendhak/gpslogger#166]
Hi, I'm using GPSlogger with Locus which is configured to disable GPS on sreen off and enable it again on screen on. With this GPS logger does no log on screen off, so if would be very helpfull if there could be a config option to enable the logger to check for GPS status before logging, enable it if neccessary and after logging disable it if previously enabled.

Thanks for this very nice app.

**Comment by mendhak** [comment]
There is now a mechanism to do this. Will do as part of :

https://github.com/mendhak/gpslogger/issues/330
