### ISSUE TITLE
IGC logger + small change in API

### ISSUE THREAD

**Issue by dkm** [mendhak/gpslogger#175]
I'm currently trying to make a small set of patches for adding support of different loggers (IGC file, skylines livetracking, livetrack24 livetracking).

I'm first trying to add the IGC logger. The thing is that for some usage (paraglider competition), a signature should be added at the end of the file. Problem is that gpslogger does not have a callback for "closing" a logger (only write, annotate and getName).
I can see that f-e for the GPX logger, for each point, it writes at a given offset within the output file.
Following this approach would require the IGC logger to update the signature with every point, which is overkill.

Do you think it would be possible to add a callback for that ? I guess that should be possible, but I'm only starting to look into gpslogger :). I'm not asking you to do it, I will happily provide a patch, I simply would like to know if it is something easy and doable :)

Thanks !

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: None
