### ISSUE TITLE
Option to start logging automatically when app is launched

### ISSUE THREAD

**Issue by jheinitz** [mendhak/gpslogger#178]
Hello,

I really think that GPSLogger is a very great app. I'm using it to log data to my personal OpenGTS server. What I miss is the possibility to start the logging once the app is launched. I want to start the logging as soon as my phone connects to my cars bluetooth hands free system. With the app "MyProfiles" I can launch GPSLogger as soon as the phone is connected via BT in my car, but unfortuneatly the app is not logging data without starting it manually. 

So I think an option in the Settings Menu would be a good choice to customize the app.

Thanks and best regards

Jens

**Comment by bgirardot** [comment]
Just adding my voice to the request for this feature. I am hoping to simply automate daily log collections from a fleet of drivers. They don't want to do anything, they just want to drive so it the app could just start up and start logging based on the configuration, that would be great.

**Comment by mendhak** [comment]
Here's an APK if you want to test.  https://www.dropbox.com/s/lmrltkpskbgdy7z/gpslogger-66-issue178.apk?dl=0

**Comment by bgirardot** [comment]
Works perfectly for me both just starting the app, and restarting the device auto start app and it starts logging. Nexus 7, Android 5.0.2.

The only thing I noticed was the green "stop logging" button did not have the animation along the bottom edge that it displays if I manually click the blue "start logging" button, but as I said, it still starts logging as expected.

Thank you very much for the feature!

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: None
