### ISSUE TITLE
New "http" sender ?

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#195]
Hi mendhak, I'm the Italian translator :-)

I'm looking for a GPS app that can be used as a real time tracker, as www.greenalp.com and its Real Time GPS Tracker app do.

I want, just for fun, build a simple web tracker public viewer. More or less as OpenGTS or GreenALP.
And GPSLogger can be the perfect Android client.

Can you add to GPSLogger a simple "http sender" : Android user provide an URL that can be expanded with variables

I.e. 
http://www.mywebsite.com/record.php?user=ambrosa&password=QwrtY18&lat=%L&lon=%G&prec=%P&battery=%B ............

where %L is expanded by GPSLogger as latitude, %G as longitude , %P as gps precision , %B battery charge level, %M as mode (GPS vs Cell tower)  and so on .....
The variables above are only provided by me as examples, but can be a good starting point.
And every time GPSLogger record a position, it contact the url above and transmit data.
Remote webserver can simple answer with strings "OK" or "NOK" (or timeout)

In next summer I'm planning a 10.000 Km trip with my motorcycle around nord Europe (including Russia and NordKapp) and I wish to develope a service like greenalp but more simple and easy.
But I've never write code for Android system. And GPSLogger already exists. Why remade job ? :-)

---
Alessandro

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: None
