### ISSUE TITLE
Sudden inaccurcy

### ISSUE THREAD

**Issue by Orvis** [mendhak/gpslogger#207]
Hi,

I don't really know if it's a bug or a mis-configuration, but here is my issue.
Sometimes, I guess mostly when I'm immobile and in a place with a lower coverage satellites, it happens that a position (or often a few position in succession) is suddenly logged (therefore likely detected by the GPS) in a totally absurd place (eg thousands kms from the previous position) .
Is this a bug ? If so can it be fixed.
Or maybe a proper configuration can get around (or circumvent) the issue ?
Regards.
Michaël.

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: Should be resolved in a separate update, where I disabled passive location provider's caching which often caused this.
