### ISSUE TITLE
Bug: share position not work in any condition.

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#210]
If you:
- press three dot icon
- press 'share'
- select file from 'Location Only"
then choose mail, whatsup or something else.

1a)
the problem is that position (http://maps.google.com/maps?q= ...) into mail,whatsup.... is showed ONLY when a track recording is running.
1b)
If a track recording is NOT running and you record a single point (yes, you have obtained correctly the position), there are no info to share into mail,whatsup....

2)
if you have not any position showed in main screen (i.e. you have just started the app) and if you want to share your position, the app should be automatically start a "single point" process to obtain the position.
Now you should manually click on "record a single point" and then choose to share it: very annoying. But in doesn't work (see 1b above)

**Comment by mendhak** [comment]
Inaction if no location available.  Since log-fix is asynchronous, forcing a point capture on location-only would require freezing the UI.
