### ISSUE TITLE
Google Drive upload problem: wrong MIME type

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#217]
Today I've made a trip with my motorbike and I've recorded it as usual with GPSLogger.
And then, as usual, I've uploaded .KML file into my Google Drive. Upload was ok.

But I cannot view the 'preview' using the Google Drive web interface.
Since about 1 years ago I've uploaded and previewed kml file without any problem.
Old files are ok: I can see the preview.
New files are NOT ok: I cannot see the preview. Strange.

I've found the difference:
old files have MIME type "application/vnd.google-earth.kml+xml" example: https://docs.google.com/file/d/0B7FOsjwNpro_NTFFZ2pMcTlNVGs

new files have MIME "application/xml" and obviously GDrive cannot preview them example: https://docs.google.com/file/d/0B7FOsjwNpro_N3hNUERpdnNtT1k 

If I open both files with a text editor, I cannot see any difference. New files are really correct KML file. The problem it's only the MIME type
GPSLogger now set the file type during upload as XML and not as KML.
9-12 months ago all was fine, today not.

If I download the file into my PC and simply I re-upload it into GDrive (always using my PC), magically now it has the correct MIME: GDrive recognize it as KML and set the correct MIME. So it looks to be a GPSLogger issue.

Mendhak, Have you changed something ? Or are the new Google Drive API ?

**Comment by kweng2** [comment]
Hey @mendhak you mentioned that you changed something such that files of various extensions when uploaded to GDrive, gets assigned the correct MIME type. How did you do that?

**Comment by mendhak** [comment]
Hello, it's in [this commit](https://github.com/mendhak/gpslogger/commit/a022a2fa400ec6df6f100d9169bbc4602b6763c3), specifically:

    private String GetMimeTypeFromFileName(String fileName){
          if(fileName.endsWith("kml")){
              return "application/vnd.google-earth.kml+xml";
          }

          if(fileName.endsWith("gpx")){
              return "application/gpx+xml";
          }

          if(fileName.endsWith("zip")){
              return "application/zip";
          }

          return "application/vnd.google-apps.spreadsheet";
    }
