### ISSUE TITLE
Upload fails and queued data

### ISSUE THREAD

**Issue by LoZio** [mendhak/gpslogger#248]
Hi, I cannot understand after some trials the logic for uploads.
When you are logging to a file it is easy to accumulate fixes. But what happens when you have only uploads (i.e. to OpenGTS) and the network is not available? Does the fix is queued for next available upload slot or is discarded? In the latter case, it would be a serious handicap to require 100% network availability everywhere.
Thanks

**Comment by lcgerke** [comment]
I've been using btsync (aka sync on google play store) to synchronize the data folder from gpslogger to my other machines with very good success.  

seems like it sort of makes all the other auto-send stuff moot.  highly recommended.
