### ISSUE TITLE
time between points.

### ISSUE THREAD

**Issue by MrPiet** [mendhak/gpslogger#260]
hello

i use te latest GPSlogger available by this time.

when i set the time between two log-points gpslogger write points 1/10e of that time.
example i set the time between 2 log-points to 60 seconds then gpslogger is writing
a new point at every 6 seconds.
if i make it 600 seconds (10 minutes) i have a log point every 60 seconds.

Piet

**Comment by mendhak** [comment]
I think I remember this bug, it was a divide by 10 or 100 error... but it should be fixed now.
