### ISSUE TITLE
Default settings for accuracy are not shown

### ISSUE THREAD

**Issue by jimis** [mendhak/gpslogger#262]
I click to change the settings to a little bit less than the current values, but the dialog box shows no value at all. The following settings are affected:

"Time before logging", "Distance filter", "Accuracy Filter", "Retry time interval for accuracy filter", "Absolute timeout".

If the value is set to the maximum accuracy then it should show "0". But "time before logging" for example is sure to have some greater value, else my tracks would be much denser than they currently are.

Thank you for this great and open program!

**Comment by mendhak** [comment]
Implemented

**Comment by jimis** [comment]
Thanks!
