### ISSUE TITLE
Can't find GPSLogger on HTC Incredible 2

### ISSUE THREAD

**Issue by howiewok** [mendhak/gpslogger#268]
I installed GPSLogger using a Wi-Fi connection to my HTC Incredible 2 and now I can't find GPSLogger in the Applications. If I try to install again, it says that it is already installed. I can't find GPSLogger in the Remove Applications either. Do you have any suggestions of things to try? 

This phone has NO actual phone account. I was going to use it just for logging.

Thank you for any help.

**Comment by mendhak** [comment]
You can try a [direct APK](https://github.com/mendhak/gpslogger/releases/tag/v61) if necessary but aside from that, it's too specific to your phone and setup.
