### ISSUE TITLE
Support for ownCloud maps

### ISSUE THREAD

**Issue by brantje** [mendhak/gpslogger#276]
Hello,
I''m the author of ownCloud maps. (http://github.com/owncloud/maps)
Currently i offer an option to update the current location with an URL.
Would it be possible to add an ownCloud option in the `Loggin settings`?
So users just have to enter their hash and server url and they are done.

**Comment by mendhak** [comment]
Closing this, sorry - I won't be adding more loggers/upload destinations, there's simply too many to manage right now.
