### ISSUE TITLE
allow some predefined custom texts in anotations

### ISSUE THREAD

**Issue by scphil** [mendhak/gpslogger#277]
Predefined custom annotations ( to be customized by users as favorites for example)could help standardize and later automated analasys. 
Example, people could choose certain predefined texts as standardizing events. Example:
1 going to work
2 stuck in traffic
3 on my way home
4 recommended !
5 avoid this place !

Or. (Photographers interested in geotag)

A lens: tamron FD 80 mm 
B lens: canon FD 135 f2.8

External tools could later use the logged info to merge in automated ways, such as ifttt scripts, or tools like exiftool to merge  geotag info into exifdata.

I see all different ways how this could be helpful for team collaboration (different people annotating in a systemic way)

**Comment by lenucksi** [comment]
If there would be a simple GUI, e.g. a list of buttons matching the currently loaded set of custom annotations that would allow to create annotated trajectories in a really nice way. 
Combined with my proposal from #299 that would be really awesome.

**Comment by mendhak** [comment]
The latest v126 has an 'annotation' view which should now be able to do what's listed here.  The annotation button view allows setting some text and picking a color for the button too.
