### ISSUE TITLE
Display default values?

### ISSUE THREAD

**Issue by pd3** [mendhak/gpslogger#282]
Would it be possible to show the current default values in logging settings? 

And a question related to this: the FAQ item "How can I define a preset file with my own values" seems to suggest that the recommended way of using non-default values is to provide a config file. Does that mean that gpslogger will not remember modified settings on phone restart? 

Thanks for the great app by the way, this is exactly what I was looking for.

**Comment by mendhak** [comment]
Default values shown in textboxes
