### ISSUE TITLE
The Displayed Speed in Miles Per Hour is Wrong

### ISSUE THREAD

**Issue by agude** [mendhak/gpslogger#290]
When using imperial units the displayed speed in MPH is incorrect. If I switch the display to metric it shows me roughly the speed (this time in KPH) that I expect. Here is a table roughly correlating the speedometer in the car I was using to the displayed speed in GPSLogger (but the GPSLogger number bounces around a bit, so take the exact number as a very rough estimate):

Car Speed (KPH) | GPSLogger Speed (MPH)
------------ | -------------
30 | 5
50 | 9
60 | 11

The phone I'm using is a Nexus 5 running 5.0.1 with stock everything. The GPSLogger version is 56. I don't think this is a regression from the previous version as I remember thinking the speed in MPH was odd before, but I normally use metric so I haven't really paid attention.

This might be a duplicate of #200, but it's hard to say without more information in that report.

**Comment by mendhak** [comment]
Published to market
