### ISSUE TITLE
"Less Features" Request  ;-)

### ISSUE THREAD

**Issue by ghost** [mendhak/gpslogger#299]
Dear Sir,

We are a german water rescue organisation and we would like to use your app to track our boats.
It would be very very helpful, if we could get a "foolproof" version:
- NO configuration possible at all. Just the possibility to type in a 1-2 digit boat number before activating the sending of positions.
- 10 colored buttons (1-9 and 0) as the only visible objects beneath LAT and LON while sending is activated. Number of last pressed button has to be sent within the link.
- Send positions only via link to our perl script at www....../cgi-bin/....?id=%boatno;stat:$button;lat=%LAT....

Could that be possible?

It would be a giant help for us and our targets!

Feel free to contact me by mail:  webmaster@wasserwacht-kiel.de

Thanks, Michael

**Comment by lenucksi** [comment]
I would like to modify or extend this Feature request as follows:
- Summary: Add functionality to easily remote provision settings / a profile 
More detailed proposed workflow:
 - User registers on a web page. 
 - User is assigned a profile by an administrator
 - User photographs a QR code on the webpage using GPS Logger, this directs him or her to a web page containing a settings profile
 - GPS Logger then configures a profile (i.e. upload configuration, gps/network/etc, recording interval, selection of sensor data, additional metadata) and activates it
 - User only has to press the start / stop button to use the settings provided by the third party
 - If desired user can switch over to other profiles provided by either himself or provided via different QR codes as described above.

**Comment by mendhak** [comment]
Unfortunately due to lack of time and attention I can't maintain variants of the app. I'll close this issue now.
