### ISSUE TITLE
No or inaccurate point

### ISSUE THREAD

**Issue by Desmorider** [mendhak/gpslogger#300]
When use networkin the location provider screen, and in the Android (4.1.2) GPS settings WIFI/ 3G is activated you will get no GPS ( satelite) loging points, only sporatic good points are availabe.
on the Detail screen you will get the masseage 
point is not accurate, 
and the gps signal is only on for 2or 3 sec, recardles of retry time for fix and absolut timeout settings,
if you turning of the network setting, you will get good points from the gps

Regards Florian

**Comment by Desmorider** [comment]
may you can make a intergartion for LLama  to set network on or off in the location provider screen

Regards Florian

**Comment by mendhak** [comment]
In the Tasker bit [here](http://code.mendhak.com/gpslogger/#18) (which should be same for Llama, send an intent to do a thing)

I've added a `setprefercelltower` option.  Sending `setprefercelltower:true` will disable the GPS listener and enable the tower/passive listener.  Sending it as false will enable the GPS listener and disable the tower/passive listener.
