### ISSUE TITLE
Effect of annotate button

### ISSUE THREAD

**Issue by icrf2000** [mendhak/gpslogger#301]
It would be good if the coordinates of a waypoint created by the "annotate" button were taken at the time the button is tapped. Currently, obviously the coords are taken at the time when the descriptive text is finished. This can be a long time and spatial distance away. Imagine you are driving (co-driver) on a highway with 100km/h and want to set a marker for a nice bridge. If typing in the text "nice bridge" takes you 20 seconds, the generated waypoint is >500m away from the actual point of interest.

**Comment by mendhak** [comment]
Unfortunately this would require the app to be constantly logging, and the variable nature of GPS-reported speeds would mean the calculation will be wrong more often than not.

**Comment by icrf2000** [comment]
Why this? Scenario: You are in motion and currently at (example) 49.0N 7.0E when you press the "annotate" button. You expect the waypoint in GPX to have coords 49.0N 7.0E. But it takes you some time to write the annotation text, so you have finished the text and press OK a bit later. At this time, you are at 49.1N 7.1E already. As the app does it now, the GPX contains coords 49.1N 7.1E. Means coords of where you are at the time you finish the annotation text, not the position you were at when you first pressed the pen button.

Am writing this again, trying to make my concern more clear. Just in case you had something else in mind. I don't understand why this means "require the app to be constantly logging". Actually, it means "when user presses the PEN button, take the next available position, store it and as soon the text is ready, write it into the GPX.

**Comment by mendhak** [comment]
If a user is at position `A`, and presses 'annotate', GPSLogger can try to get the current position.  It takes a few seconds and gets position `B`, some distance away.  Seconds later, the user finishes typing their sentence and presses OK at position `C`, some further distance away.  Since GPSLogger is periodic, it doesn't know what position `A` is.  It can only know position `B` or `C`.  

In order to know what position `A` was, it would have to have been logging constantly and not periodically (eg every 120 seconds).  And since neither `B` nor `C` are the actual annotation location, the simpler way to do this is to log after the user presses OK, because the user can also cancel out.

**Comment by icrf2000** [comment]
You are probably right and me not... Last attempt to draft an example. Please apologize if it is wrong:

User has configured app with "time_before_logging_title = 20 seconds". Last regular sample logged was taken at time 0. User presses PEN when at pos. A at time 0+3 (this is a time out of the app's configured periodicity).  Next periodic pos. would be taken at time 0+20 when at a random and uninteresting pos. B. But user is faster with typing, finishes text and presses OK at time 0+7. Doesn't the app already in its current version then log a "sub-periodic" point at 0+7?? So it is already capable to log "sub-periodically". Generated point would be ... 0-20, 0, 0+7, 0+20, 0+40,...

So why not take the position at time 0+3 (PEN pressed) instead of 0+7 (OK pressed) for the GPX?

**Comment by mendhak** [comment]
The reason for "ok" pressed instead of "pen" pressed is since logging is asynchronous. It can take zero seconds to find a point and already written to file. Doing it at ok is simpler since doing it at pen would be a large amount of work in the logger architecture for a few seconds benefit. Hth

**Comment by icrf2000** [comment]
Ok, convinced
