### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by chiragchaplot** [mendhak/gpslogger#302]
App crashes as soon as I open it. I downloaded it from app store

**Comment by mendhak** [comment]
Are you using a Micromax phone by any chance, I see a few market crashes from Micromax A110Q phones.  If not, can you reopen the application, let it crash, and send the crash report?  I can then see the crash report in my developer console to see the stacktrace.

**Comment by chiragchaplot** [comment]
Yes I am using the micromax phone.
