### ISSUE TITLE
EXIT by menu item, not by Return buttion

### ISSUE THREAD

**Issue by effrit** [mendhak/gpslogger#307]
Hello!
I think it will be more suitable to make exit from application by menu item "Exit" because in current state you can exit from app and logging just by press "return" by mistake.

**Comment by mendhak** [comment]
The return/back button doesn't stop logging, it'll just continue in the background until you return to it.

**Comment by effrit** [comment]
ups. i just lose half of track today because upp was closed. seems it just crushed.
sorry for disturb :)
