### ISSUE TITLE
Doesn't seem to restore properly after the service is killed

### ISSUE THREAD

**Issue by lahwran** [mendhak/gpslogger#309]
my phone has been killing foreground services frequently, which would be just annoying, except that GPS logger doesn't seem to resume logging after being killed. the service comes back, but it just shows the app's icon and says "service running, tap to stop". I glanced through your code and didn't immediately see anything wrong; could you try a repro and comment?

**Comment by mendhak** [comment]
The main bit is [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L105) - it will be redelivered the intent when the service is killed and restarted.  

Unfortunately reproducing this isn't easy - the best way I could find was under apps, I found the `GPSLoggingService` service and terminated it.  However each time, it came back and continued logging.   Maybe I need to match with your settings.  What's your logging interval, any other frequency or filter changes you've made?

**Comment by lahwran** [comment]
I'll try the same way to repro it you did. However, I think the best way to repro it is to start several *other* foreground services, enough that you run your device out of ram and it's willing to start killing foreground services.

**Comment by mendhak** [comment]
Sorry, couldn't reproduce this. I tried to load up emulators with low amount of memory and overload it; also tried on my phone (but it has too much RAM maybe).
