### ISSUE TITLE
Add log files to media file database

### ISSUE THREAD

**Issue by dlichtistw** [mendhak/gpslogger#311]
It seems like the app does not register the newly created GPX log files in the android media files database. So, when I finished recording a GPS track and then connect my phone to my computer via USB as MTP device, the log file won't show up in the appropriate folder. However, I can see the file in the folder using a file manager on my phone.

Currently, my workaround is to cause a media rescan of the GPX folder using SD Scanner (or simply reboot the phone). But it would be much easier, if GPSLogger could simply register the file once it finished recording.

Setting the USB mode to mass storage device might be a solution, but unfortunately, this is not an option anymore on many devices.

I'm using GPSLogger 60 with Android 5.1 on a Nexus 5 and Android 5.0 on a Moto G 2nd Gen. But as far as I remember, the problem has occured on previous versions, too.

**Comment by mendhak** [comment]
v61 released

**Comment by dlichtistw** [comment]
Now, the gpx files get added to the database, but only with a few 100 bytes in size. So, when I copy them to the computer, I only get a truncated, and thus corrupt file. It seems to me, that the file is scanned when it is created, but it might be better to do that when it is closed.
