### ISSUE TITLE
KML-File

### ISSUE THREAD

**Issue by hilhof** [mendhak/gpslogger#313]
GPSLogger is a great app.
But the KML export files that I get from it do not include Trackpoints (only the GPX files do).
So I need two export files: 
one for Google Earth (where I do not miss the Trackpoints too much)
and one for the Geosetter.
This is a little inconvenient; could you integrate the Trackpoints into the KML file, too?

**Comment by mendhak** [comment]
Can you elaborate with an example of what's missing?

**Comment by mendhak** [comment]
If I'm understanding right, the trackpoints you're asking for aren't going to make it to KML.  The standard/format of KML isn't very useful for using in other software, it's much better suited for display purposes.  It's quite data-poor.

**Comment by hilhof** [comment]
Dear Mr. Mendhak,

please excuse my late answer.
I noticed that I can use your GPX-Files in the Programm Geosetter to set 
geo data into photos.
So far nothing has to be done.

But I wanted to have one file to be used both in the program Geosetter 
and in Google Earth.
So I meanwhile wrote a little Delphi-Program (for Windows) which makes 
KMZ-files from your GPX-files using gpsbabel.
If you are interested in that program I can change the interface from 
German to English and send it to you.

With kind regards
H.Hoffmann

mendhak schrieb am 14.05.2015 um 21:08:
