### ISSUE TITLE
logged GPX files disappearing in new version

### ISSUE THREAD

**Issue by pavelu81** [mendhak/gpslogger#315]
Hello,
at first, I'd like to send you a big thank for the app! It's great and the only one which meets my requirements.
I use it for months to track my car tracks and start and end the tracking automatically by tasker and intents when my phone is connected/disconnected to my HF in car.

Now in version 62 it seems not to work properly as it looks like it is deleting the recorded file (or somewhat like that) when it is stopped from tasker and the phone is not active. When I have my screen on, it seems to be OK.

Could it be related to changes in ver 61?

My scenario is to have my phone not active and automatically start and finish the logging, which is not working now.

Is there any way to downgrade the app and keep the settings?

Thx a lot for your answer.
Pavel

**Comment by mendhak** [comment]
Hmmmm... v 61 and 62 are almost the same; the only thing I did in v62 was a menu fix, no other changes.  GPSLogger also has no code to delete files, are you sure it is being deleted?  Or is it not recording points and you get small files?

In v61 I added a feature to detect activity; if the user is not moving, logging will pause.  This can be disabled under Performance menu, right at the bottom.

Older APKs are available here:  https://github.com/mendhak/gpslogger/releases

**Comment by pavelu81** [comment]
I'm not sure it's deleted, maybe id doesn't do anything, nor create the file... I've tried it with phone-on  and it works ok but with the phone off i can't see anything and don't know what it does.
There is no file neither the small. When I have my phone on, it creates two files. ZIP and GPX.

Same behaviour is with file uploads - DropBox and GDrive - goes well when the phone is on and does nothing when it is off.

I've turned on the debug logging right now, maybe it could help.
And I can switch the activity feature off too.

I have found older APK but I'm not sure how to install it with keeping the settings.

Pavel

**Comment by mendhak** [comment]
OK that's interesting.  Screen off is disabline 'something' which prevent GPSLogger from getting points.  Hopefully the debuglog.txt will give some clues.

To try an older version, go to the page I linked: https://github.com/mendhak/gpslogger/releases

And for an older version, get the apk file.  For example, to go back to 60, you will see a `gpslogger-60.apk` file.  Download to your phone.  

You will need to uninstall the newer GPSLogger and you'll lose any files it creates too.  You may also have to allow apps from unknown sources under Settings > Security

**Comment by mendhak** [comment]
Oh check if your location setting for the phone is in battery saving mode.  I wonder if it just stops trying to get points when it's in battery saving mode and screen is off?

**Comment by pavelu81** [comment]
it was set to GPS, now i set it to HighAccuracy. Battery saving mode i can try then.

**Comment by pavelu81** [comment]
Sooo, resetting the location setting of the phone did it...

Now it works like a charm and location setting neither the activity detecting setting has no unexpectable impact.

Probably it had something with the phone to do not with the app.

Thanks a lot for your help and again for the app.

Pavel
