### ISSUE TITLE
Wrong month with custom file names

### ISSUE THREAD

**Issue by craigw84** [mendhak/gpslogger#317]
I have the custom file name set as `%YEAR-%MONTH-%DAY`

But this gives the wrong filename for the month. ie today's file is `2015-4-20.gpx`, when today is the 20th of May. So it seems the month is wrong. The time/date on my phone is set correctly.

Also, it would be useful if the parameters had a leading zero. Then the filenames would properly in a list. ie the file for today should be `2015-05-20.gpx`

Using GPS Logger version 63.

**Comment by Sebutage** [comment]
Experiencing the same issue. Where does %MONTH get its value?

**Comment by mendhak** [comment]
Ah it gets it as an enumeration:  http://developer.android.com/reference/android/text/format/Time.html#month
