### ISSUE TITLE
Possible with sub-folders on uploading to Google Drive?

### ISSUE THREAD

**Issue by eklem** [mendhak/gpslogger#320]
Nice app, thanks! Is it possible to define a sub-folder for upload to Google Drive.
I'm trying to do foldername/subfoldername/subsubfoldername, but I get that whole thing as one folder name.

**Comment by mendhak** [comment]
Simplest way to do this is to specify your 'subsubfoldername'.  Let it upload a file or a test file.  Then go to Google Drive and move the folder name into foldername/subfoldername.  When uploading the app should still be able to find the subsubfoldername.

**Comment by eklem** [comment]
Cool, thanks @mendhak ! I'll try that. :+1:
