### ISSUE TITLE
How to Start / Stop GPS Logging through new Layout we have added?

### ISSUE THREAD

**Issue by hye4life** [mendhak/gpslogger#322]
Hi, please help.
What function to call to Start Logging, and what function to call to Stop Loggin from our own layout / java classes added to the project.

Also, is there a way to configure the settings programmatic through a function call passing in variables to reconfigure the gpslogger settings from our own class thats been added to the project?

Please help clarify how to interact with the GPS Logger from new layouts / classes we have added to your source code.

**Comment by hye4life** [comment]
Can anyone help guys? :)

**Comment by mendhak** [comment]
You can start logging like [shown here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/views/GenericViewFragment.java#L148). Don't forget to [register the event bus](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/views/GenericViewFragment.java#L54).

As for settings, I'd suggest simply overwriting directly.  you can get various setting names [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/Utilities.java#L147).
