### ISSUE TITLE
FTPS Upload fails

### ISSUE THREAD

**Issue by mbfoo** [mendhak/gpslogger#324]
Hi,
FTPS Upload is not working for me using Proftpd 1.3.5 on the server side. Testing FTP Upload gives me a dialog containing "FTP Test Failed."
Other clients have no problems accessing the server.

When disabling FTPS on the server and client side (using unencrypted FTP), Gpslogger uploads the file successfully, so I think it is not a problem related to the firewall or active/passive FTP mode.

Here comes the debug log:
```
23:29:27 INFO  Utilities.PopulateAppSettings:149 - Getting preferences
23:29:34 DEBUG FtpHelper.TestFtp:47 - Creating gpslogger_test.xml
23:29:34 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.Upload:85 - Uploading file to FTP server mbfoo.de
23:29:35 DEBUG FtpJob.Upload:86 - Checking for FTP directory 
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.Upload:91 - Attempting to create FTP directory 
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.Upload:104 - Failed to FTP file gpslogger_test.txt
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG FtpJob.showServerReply:159 - FTP SERVER: null
23:29:35 DEBUG GpsMainActivity.onEventMainThread:1000 - FTP Event completed, success: false
23:29:35 DEBUG AutoFtpFragment.onEventMainThread:122 - FTP Event completed, success: false
23:29:38 INFO  Utilities.PopulateAppSettings:149 - Getting preferences
```

Dont know if useful, here comes the Proftpd (verbose) log: https://gist.github.com/mbfoo/76196e013f45d5e8a0e3#file-gistfile1-txt

**Comment by mendhak** [comment]
Does Proftp have any other logs?  I can see that GPSLogger can connect to it, issue commands to it, and proftpd [knows there's an error](https://gist.github.com/mbfoo/76196e013f45d5e8a0e3#file-gistfile1-txt-L206).  

Could it also be [related to](http://www.proftpd.org/docs/howto/TLS.html):

> Question: I can login using FTPS, but I cannot see any directories. Why not?
Answer: You have most likely configured mod_tls to require SSL/TLS protection for data transfers as well as control commands, by using:
>
>     TLSRequired on
>
> However, if your FTPS client does not expect to handle encrypted data transfers (and directory listings count as data transfers, as they are sent over a data channel), you may see your client appear to hang, waiting for data it can read. Make sure your client is prepared to handle the security requirements you have configured on the server.

**Comment by mbfoo** [comment]
Sorry for the late response, I was on vacation..
you are completely right, the problem was the encryption of the data channel. It tested with vsftpd, too and got the (clear to understand) message ```522 Data connections must be encrypted.```.
Without the requirement of a encrypted data channel on the server side, GPSLogger FTPS-Upload works fine.
Thanks for your help!
