### ISSUE TITLE
google drive multiple folders

### ISSUE THREAD

**Issue by artttt** [mendhak/gpslogger#326]
Firstly great app.
I have a phone set up with it running all the time. It is uploading to google drive a kml file to every 15 minutes with a new file name each day as set up and expected. It is set to upload to a folder called GPSLogger which it does.
However every few days (havent worked out if its random or not) it creates a new folder of the same name (google drive doesnt have any issue with duplicate folder names it seems).
Im sure this isnt the expected behaviour.
It is frustrating to me as i share that folder with another google user and when a new folder is made that user cant see any new data.
hope its an easy fix.
Thanks

**Comment by mendhak** [comment]
In these times, are you deauthorizing/reauthorizing or uninstalling/reinstalling? I believe a new folder gets created in those situations.

**Comment by artttt** [comment]
neither of those. maybe you pushed out some updates that got installed?
It hasnt done it since although i didnt have in logging most of last week. I will keep it running this week and see if i can replicate the behaviour.

**Comment by mendhak** [comment]
v66 has been released.  See if this results in yet another folder being created. I tested this myself and everything seemed fine.
