### ISSUE TITLE
Speed is always 0.0

### ISSUE THREAD

**Issue by githubsrinath** [mendhak/gpslogger#327]
Hi I use custom url , all data logs but Speed is always zero.  Any idea why?

Any settings i have to change?

Many Thanks

**Comment by mendhak** [comment]
What's the custom URL look like, and is the speed zero in log files?

**Comment by githubsrinath** [comment]
Custom url looks like :

http://myapp.16mb.com/api/insertgpslog.php?orgid=myorg&uid=paresh&lat=%LAT&lon=%LON&description=%DESC&sat=%SAT&alt=%ALT&spd=%SPD&acc=%ACC&dir=%DIR&prov=%PROV&utc=%TIME&bat=%BATT&aid=%AID&ser=%SER&datetime=%TIME

Well, log file also zero... screen also when i check during the vehicle movement its zero.


Regards
Srinath Rao

**Comment by githubsrinath** [comment]
Hi I just realized that  Speed is calculated only when %PROV is GPS.  It doesn't Log  Speed for when %PROV is network or any other. 

I think what application is doing is right.  You can close this issue.

Thanks for your help.
