### ISSUE TITLE
TwelF crashes GPSlogger

### ISSUE THREAD

**Issue by Roxxor91** [mendhak/gpslogger#329]
Hi! 
TwelF(https://gitlab.com/xphnx/twelf_cm12_theme build from FDroid) crashes GPSLogger.
![gpslogger txt](https://cloud.githubusercontent.com/assets/4848448/8397497/ceda2638-1dd5-11e5-8a9c-34118d972be1.jpg)
Rename the file to .txt (Why doesnt Github allow the upload of text files?)

**Comment by Roxxor91** [comment]
Just found that in the issues on TwelF and seems to affect all Themes.
Here is how to fix the issue in GPSLogger:
https://gitlab.com/xphnx/twelf_cm12_theme/issues/66

**Comment by Roxxor91** [comment]
Hey! Especially for this great app I installed the AndroidStudio.
I compiled successfully including your fix. It didnt work :/

07-01 22:00:18.002  31404-31404/com.mendhak.gpslogger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mendhak.gpslogger, PID: 31404
    android.app.RemoteServiceException: Bad notification posted from package com.mendhak.gpslogger: Couldn't create icon: StatusBarIcon(pkg=com.mendhak.gpsloggeruser=0 id=0x7f02006c level=0 visible=true num=0 )
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by mendhak** [comment]
Can you try switching the large and small icons around, or making them both the same.  I don't have CM or any of its themes.

**Comment by Roxxor91** [comment]
I switched and also set both to notification or gpsloggericon3. No success. :/
What I found: I use Privacy Guard. So when android studio installs the app via adb, GPS is by default forbidden. Now when I click the button to track, the notification icon already appears + a question by my system to allow GPS access. Only when I allow/deny GPS access, then the app crashes. So somehow the icon gets displayed. Why does it crash then?
I have no idea about coding, but is there also another notification section in your code?
![screenshot_2015-07-02-11-43-26](https://cloud.githubusercontent.com/assets/4848448/8473185/1622cee6-20b0-11e5-8f4f-b6f547f8101d.png)
![screenshot_2015-07-02-11-43-33](https://cloud.githubusercontent.com/assets/4848448/8473186/1660b1ca-20b0-11e5-8dee-8b186987bdfa.png)

**Comment by mendhak** [comment]
If it crashes, then the icon might stay because the code to remove it isn't reached. For this issue though it's not related.

Main issue - even though the icons were placed (large/small), it still hasn't worked for you, so I'm not sure what else can be done here?

**Comment by Roxxor91** [comment]
I honestly have no clue. I'm not a programmer. The only thing I see, is
that your line looks different to that, which is posted in the
instructions. But I guess you did that code according to your
implementation. I will post something in the issues of TwelF, and maybe
somebody can jump over and help out.

**Comment by DJaeger** [comment]
@Roxxor91: Do you have a hdpi display?
Because @mendhak has forgotten to create a hdpi resource for the small icon (notification.png).
