### ISSUE TITLE
Better visibility of a failure to write to file

### ISSUE THREAD

**Issue by rstarkov** [mendhak/gpslogger#331]
Suppose that one way or another, the path configured for storing tracks doesn't exist and cannot be created. GPS Logger even shows it in red in the settings in this case.

Unfortunately GPS Logger never actually informs the user that it is unable to perform its sole function. What happens is I hit "record", I see the status change from "Obtaining GPS" to "Inaccurate point discarded" to "Only 0.0 m travelled. Point discarded" to eventually "Started". There is literally no way for the user to confirm whether a file is being written to or not (as far as I can tell).

What I'd expect to happen is to be shouted at with a huge red message to the tune of "!!! ERROR! NOTHING IS BEING RECORDED! FIX IT !!!", but nothing like that happens. I've checked the code and it looks like it's supposed to say "Could not write to file" on a write exception, but this status must be getting overwritten elsewhere. Possibly by the next call to SetStatus(R.string.started)?

Suggestions:

1. For file loggers only, try to actually write to a file when the user presses "Start", and complain right away if there's a problem. Before a GPS fix is even obtained.
2. If an error status is set, it should be sticky; it shouldn't get overridden by "Started" or other relatively inconsequential messages.

This has cost me two tracks so far, the most recent of which was pretty important to me...

**Comment by mendhak** [comment]
Indeed it was being overwritten.  I've now made the Detailed View show a list of `SetStatus` messages; it's a collapsible bit that sits just below the logging button.  I'm testing it out now so it should show up maybe in a week or so, depending on what complexities it throws up.

![image](https://cloud.githubusercontent.com/assets/746276/9028209/5ab2a2c2-3968-11e5-99c9-ca10f99857e5.png)

**Comment by rstarkov** [comment]
Looks great! Would also be great if there was some indication in the "normal" view that the full log contains red messages that I need to check. E.g. whether there is one in the last 30 minutes? Something like that, anyway.

**Comment by mendhak** [comment]
Would need to keep track if the user has 'seen' the red messages or not, I could look at that later.  

Another problem I've realized now is the lack of translations, only a handful of messages are translated but there are a lot, lot more things that can go in here.  Even setting them up for translation would be prohibitive to development.  So I need to think on this a bit more, now I am thinking of a completely separate screen.

**Comment by mendhak** [comment]
I created a separate view, the 'log view' with debug messages instead of using the detailed view.  I'm going to test it out for a bit.  If you're interested you can play with it too:

https://www.dropbox.com/s/m74rez6qlserqfe/gpslogger-65-logview.apk?dl=0

**Comment by mendhak** [comment]
v66 released with an experimental log view. By no means complete, and none of the other views show any indication of failures.  I'll leave this thread open for a while, this feature needs to be developed based on feedback and usage.
