### ISSUE TITLE
App stop after a few hours of logging

### ISSUE THREAD

**Issue by hnigit** [mendhak/gpslogger#332]
I had a trip two weeks ago and used GPS Logger to record my track every day. Usually I will turn on GPS Logger then turn off the screen. But sometimes I would be surprised to see the icon notification bar disappeared when I turned on the screen after a few hours. I was always able to click "Start Logging" again when I re-entered the app, so I knew that the previous session ended indeed and the logging had stopped. There was no error message on the screen so I don't know if the app crashed / ended gracefully / got kicked out by some other app.

I am using an OnePlus One with 3GB RAM. Clean Master is installed but the memory cleanup process is manual so it should not kick GPS Logger out behind the scene.

The version I used was the latest on Google Play as of 06/10/2015.

**Comment by ciakpey** [comment]
Same problem here,
The app is launched and sometimes the icon in the notification become blue and the logging stops, no error in the logs

**Comment by iHeadRu** [comment]
It seems that this proplem occurs due to OOM killer work.
This assumption done after dmesg analisys.
But why other user applications (e.g. Mozilla Firefox, CSipSimple, Twitter) work fine at that moment?

**Comment by iHeadRu** [comment]
I have three installations of gpslogger on my phones. On two of them memory consumption between 7-16MB and no problem. But on third a have 48MB after few hours of work.
Can it be a memory leak? 
On all devices i use URL logging with 120 seconds interval.

**Comment by mendhak** [comment]
The service is created as a [foreground service](http://developer.android.com/reference/android/app/Service.html#ProcessLifecycle) - so it should be treated like a music app, ie. disruptive if killed and only killed under pressure (low memory).

From my debugging I usually see that GPSLogger takes 30-40 MB of memory, steady, so it shouldn't be a GC.

I can't say why other apps don't get killed, perhaps foreground apps get higher priority over foreground services?  

I also use a OnePlus One like hnigit, so memory isn't an issue.  

iHeadRu - what did you see in your dmesg, was it something like GPSLogger is being killed by Android OS?

**Comment by iHeadRu** [comment]
I added swap and tune oom killer thresholds, so the problem is not actual for me now. But the fact that application could be stopped unexpectedly is depressing.

**Comment by mendhak** [comment]
What was the threshold you had to set?

**Comment by iHeadRu** [comment]
![screenshot_2015-08-08-17-31-04](https://cloud.githubusercontent.com/assets/5307928/9150786/9137a75e-3df3-11e5-99ab-b6271d82eea9.png)

**Comment by iHeadRu** [comment]
Unfortunately this not helped. 
![screenshot_2015-08-18-21-27-15](https://cloud.githubusercontent.com/assets/5307928/9351396/a57898ce-4661-11e5-949e-539abe81ee60.png)
![screenshot_2015-08-18-21-27-01](https://cloud.githubusercontent.com/assets/5307928/9351398/ab4c67a8-4661-11e5-811d-f9cc59ef88a8.png)

**Comment by mendhak** [comment]
It looks like LMK is going around killing many applications.  I've been reading around and it's really not in my control whether GPSLogger gets killed or not.  At the moment, the service [does nothing](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L178), however the only thing I can do is simply stop logging.  Would that be less or more confusing?

**Comment by mendhak** [comment]
As mentioned in the other thread, I'm giving up on trying to understand the behavior of memory killers.
