### ISSUE TITLE
Create NMEA Files

### ISSUE THREAD

**Issue by fiveds** [mendhak/gpslogger#333]
Not sure if I missed something in the "Read Me" but Under "Features", the 4th bullet states - “Log to GPX, KML, CSV, NMEA files”

Under the "wrench" there are boxes to Log to GPX - Log to KML - Log to Custom URL -  Log to OpenGTS Server - Log to Plain Text

How do I log NMEA files onto my smartphone SD card?

**Comment by mendhak** [comment]
Did you scroll down?  Should be the next entry after 'Log to Plain Text'.

**Comment by fiveds** [comment]
I did scroll down - I tried again today 23 July 2015. 
Under "Log to..."
Log to GPX
Log to KML
Log to custom URL
Log to OpenGTS Server
Log to Plain Text

Then I cannot scroll any more. Log to Plain Text is the last item on the screen (I would try a screen shot but it would not show me not able to scroll)

If it helps - 
I have a Samsung SCH-S720C
HW S720C.01
FW 2.3.6
BUILD SCH-S720C.LI02

**Comment by mendhak** [comment]
Aha, I should have realized this earlier.  According to [this site](http://www.samsung.com/us/mobile/cell-phones/SCH-S720ZKATFN-specs), you are using Android 2.3.  This feature was added later on, but the app isn't developed for 2.x any more, sorry about that.

**Comment by fiveds** [comment]
Understood - thank you for the clarification.
