### ISSUE TITLE
Log to URL with https and self signed certificate

### ISSUE THREAD

**Issue by anon6789** [mendhak/gpslogger#334]
Hi

i'm using gps logger on a daily basis, great app.
I send the data over the "send to url/webserver" feature. But as soon as i change the link from http://mydomin to https://mydomain, no data arrive at my server. Manual tests with my browser do work over https.

So is there a way to communicate to a self-signed https-webserver over the app? How do i accept the certificate? 

thanks

**Comment by mendhak** [comment]
v66 released
