### ISSUE TITLE
Discarded inaccurate first point + distance filter = 0 points logged

### ISSUE THREAD

**Issue by Doooc** [mendhak/gpslogger#339]
If the accuracy and distance filters are both used, AND the very first point logged is discarded due to the accuracy filter, then all future (accurate) points will be discarded due to the distance filter thinking we've traveled 0.0 metres. 0 points will be logged.

Excerpt from debug log:

14:06:26 DEBUG GpsLoggingService.OnLocationChanged:756 - Has description? false, Single point? false, Last timestamp: 0
14:06:26 WARN  GpsLoggingService.OnLocationChanged:790 - Only accuracy of 6.0 m. Point discarded.
14:06:26 INFO  GpsLoggingService.SetStatus:696 - Inaccurate point discarded.
14:06:26 DEBUG GeneralLocationListener.onGpsStatusChanged:130 - 16 satellites
14:06:26 DEBUG GeneralLocationListener.onGpsStatusChanged:112 - GPS Event First Fix
14:06:26 INFO  GpsLoggingService.SetStatus:696 - Fix obtained
14:06:27 DEBUG GeneralLocationListener.onGpsStatusChanged:130 - 16 satellites
14:06:27 DEBUG GpsLoggingService.OnLocationChanged:756 - Has description? false, Single point? false, Last timestamp: 0
14:06:27 INFO  GpsLoggingService.OnLocationChanged:828 - Location to update: [snip]
14:06:27 INFO  GpsLoggingService.ResetCurrentFileName:685 - Filename: 20150803140623
14:06:27 DEBUG GpsLoggingService.WriteToFile:938 - Calling file writers
14:06:27 INFO  Utilities.PopulateAppSettings:149 - Getting preferences
14:06:27 DEBUG GpsLoggingService.SetAlarmForNextPoint:917 - Set alarm for 0 seconds
14:06:27 DEBUG Kml22WriteHandler.run:215 - Finished writing to KML22 File
14:06:27 DEBUG GeneralLocationListener.onGpsStatusChanged:130 - 16 satellites
14:06:28 DEBUG GpsLoggingService.OnLocationChanged:756 - Has description? false, Single point? false, Last timestamp: 1438581987521
14:06:28 INFO  GpsLoggingService.SetStatus:696 - Only 0.0 m traveled. Point discarded.
14:06:28 WARN  GpsLoggingService.OnLocationChanged:821 - Only 0.0 m traveled. Point discarded.
14:06:28 DEBUG GpsLoggingService.SetAlarmForNextPoint:917 - Set alarm for 0 seconds
14:06:28 DEBUG GeneralLocationListener.onGpsStatusChanged:130 - 16 satellites
14:06:29 DEBUG GpsLoggingService.OnLocationChanged:756 - Has description? false, Single point? false, Last timestamp: 1438581987521
14:06:29 INFO  GpsLoggingService.SetStatus:696 - Only 0.0 m traveled. Point discarded.
14:06:29 WARN  GpsLoggingService.OnLocationChanged:821 - Only 0.0 m traveled. Point discarded.

**Comment by ciakpey** [comment]
In your log file you have 

```
14:06:27 INFO GpsLoggingService.OnLocationChanged:828 - Location to update: [snip]
```
that means that you have a point logged
So the first point IS logged I think, but the next points are the same as the one logged, so you have 0.0 m traveled.

I tried on my phone and I don't have any problem

**Comment by Doooc** [comment]
Thanks for the response. There is 1 point logged in the kml file, but the UI stays on 0 points.

And it's not that I've only travelled 0.0m. It seems to be comparing all subsequent (accurate) points to an invalid point. ALL future points say 0.0m travelled, no matter how far I move.

And note that the problem only happens if the very first point is not accurate enough.

**Comment by ciakpey** [comment]
What is your:
- filter distance
- accuracy distance

**Comment by Doooc** [comment]
In this log, both filters were 10m. But to reproduce this problem, the distance filter just has to be greater than 0, and the accuracy filter needs a value such that the first point is not accurate enough for it, but later points are.

**Comment by ciakpey** [comment]
That's what I did, but I don't have your problem, so it is weird.
Do you know if mock location is disallow ?
Try putting greater than 0 for the delay between two points

**Comment by Doooc** [comment]
Mock location in developer options is on disallow.

I just tried with 'time before logging' set to 10 seconds, same result. If the first point is inaccurate, no points are recorded. Always 0.0m travelled.

And one small correction - in the log posted above, accuracy filter was 5m, not 10m (which is why the 6m point was inaccurate).

**Comment by Doooc** [comment]
I've just tried again with version 66 and can't seem to reproduce the issue any more. I don't know what was going on, but I'll give it a couple days and if it stays fixed I'll close the issue. Thanks for the help!
