### ISSUE TITLE
Wrong resource names in country codes

### ISSUE THREAD

**Issue by icrf2000** [mendhak/gpslogger#343]
I cannot build with Android Studio anymore. Reason and fix: The names of the resource directories like for example "values-es-ES" seem to be incorrect.

The docu (http://developer.android.com/guide/topics/resources/providing-resources.html#AlternativeResources) says this should rather be "values-es-rES". If I rename it like this (and the other "values-xx-XX" analogously), Android Studio works again. 

Not sure when this issue started, in the past, building always worked. Maybe it's because I upgraded A.S. to 1.3.1.

**Comment by mendhak** [comment]
I modified the crowdin task to rename it using `r`, have a look now:

https://github.com/mendhak/gpslogger/tree/master/gpslogger/src/main/res

Let me know if there's something still missing.  Nothing some regex couldn't fix... hopefully.

**Comment by icrf2000** [comment]
Hello,

builds perfectly now, thank you!!
