### ISSUE TITLE
Annotate button to create waypoints

### ISSUE THREAD

**Issue by icrf2000** [mendhak/gpslogger#345]
I tried to understand the code, but it is not easy. Do you think it is feasible to get the following logics:

1) User presses Annotate button
2) Retrieve location from the system immediately, ignoring the configured AppSettings.minimumSeconds (at least as fast as possible, probably 1000ms, but if it takes longer that also doesn't hurt)
3) As soon as location has been delivered by the system, remember it and open the dialog to get the descriptive text from the user
4) As soon as the text is ready, the remembered location and descriptive text can be stored to the file as a waypoint

It might take the user longer to type in the descriptive text than the AppSettings.minimumSeconds value. So if possible, regular, periodic logging should continue irrespective of the pending dialog. But if this is too complicate, it is not necessary.

You are using EventBus and it's hard to understand the logics. But roughly speaking it would be
- Each point dropping out of the listener must "know" whether it is a regular (periodic) point or one created by pressing Annotate. 
- If "I was created by Annotate, then the descriptive text, as soon as it is available (OK pressed) is for me  and I can be saved as a waypoint"
- If "I am an ordinary, periodic (AppSettings.minimumSeconds) point, I can be stored immediately as a trackpoint"

What I want to achieve is having the GPX waypoint at the coordinates where the user pressed the button, not at the coordinates he/she finished the descriptive text.

**Comment by mendhak** [comment]
The relevant bit is [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L796).  

On annotation (after user fills something in and presses OK), a description is set and the gps logger is invoked.  As soon as it finds a point, it ignores any filters and writes to file.  

As you can see it doesn't do it as soon as the dialog opens, only after OK is pressed.  Also, no matter when, it still takes a while for a point to be retrieved, it's not immediate. Although it would save a few seconds, it will make the code a lot more complex than it already is, and would affect too many things, I am not comfortable doing that.
