### ISSUE TITLE
Queued logging custom url

### ISSUE THREAD

**Issue by ieperlingetje** [mendhak/gpslogger#355]
I use the custom url logging feature, however I do not have always internet access available. This means that if I'm offline for a few days, the app will send hundreds of requests to my custom logger data import script (that is running on a shared hosting) in a matter of a few minutes. So i was wondering if the logging to a custom url couldn't be changed from sending GET parameters to for example  also sending a POST request with a JSON object where all the logged points since the last sync are sent at once to the server.

**Comment by martinrolin** [comment]
I have a question regarding queued logging and sending to custom url. Har do you configure the app to do that? I use the app to log to a custom url but when return from offline logging I dont recieve the points.

**Comment by ieperlingetje** [comment]
I have the app set to always log to the custom url, but since there is no network connection, no http request is send,and only when there is an internet connection all the previous requests since the last time the device was online is sent.

**Comment by mendhak** [comment]
Yes that's right, any of the upload jobs will wait for a data connection before it tries to do the upload.

The commit that @martinrolin  saw (disable retry bit) is for when it attempts to upload but then fails, whether it should keep retrying.  Unfortunately there's no issue number against it so I can't remember why it was disabled.  OwnCloud I get - it's just a file upload, so the same file can be tried again.  

CustomURL...not so sure.  I'll have it retry on error but maximum two times.

**Comment by ieperlingetje** [comment]
@mendhak regarding my issue: would it be possible - if the device was offline for a long period of time - to group the data it sends in one HTTP POST request with multiple coordinates in a single JSON object? Or at least upload a datafile to a custom url. Setting up hundreds of HTTP request in a short timeframe is not a nice solution.

**Comment by mendhak** [comment]
It would all come down to defining what that POST body should look like, or what the data file should look like.  The custom URL screen shows what will be sent so that users can code up their own 'receiving pages'.  But anything more complicated than that probably requires a more complicated setup, like Google Drive, DropBox or OpenGTS.

**Comment by mendhak** [comment]
OK explored this a bit more.  I can't make Custom URL more complicated than it currently is.  It's a simple `GET` and doing anything bespoke over and above would break other things.  For that reason I'd recommend not changing its behavior, sticking to Dropbox/GDrive instead where reuploads aren't a problem.
