### ISSUE TITLE
GPS tracker leaves a service runnig

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#356]
After GPS  tracker has been stopped with a widget it leaves GpsLoggingSerivce running. No such issue when exiting via the Exit menu. Android 5.0, Galaxy S5.

**Comment by mendhak** [comment]
To clarify, is it with the stop shortcut/widget that comes with the app?  Or are you using some task killer kind of widget?

**Comment by lvmm** [comment]
I am using widgets which come with the app.

**Comment by lvmm** [comment]
and it looks like this:
![screenshot_2015-10-26-09-34-55](https://cloud.githubusercontent.com/assets/11752339/10723032/b2b94344-7bc7-11e5-8792-1062a9596211.png)

**Comment by mendhak** [comment]
Ok - that should be fine, service can be running in the background doing nothing.  The stop widget is simply stopping the logging, not the service itself.
