### ISSUE TITLE
stopping location service interferes with track upload

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#357]
GPS tracker is configured to automatically upload gpx tracks to google drive when logging is stopped. Stopping android location service while GPS tracker is running causes GPS tracker to terminate without uploading a track. I admit, the configuration option is called 'upload when *I* press stop', so it does exactly what it promised to do, but I'd like it to handle location service termination as plain stop.

**Comment by mendhak** [comment]
How are you terminating the location service?  

I've tried this with Dropbox for example, I turn off the location service using the slider at the top right

![notificationarea](http://i.imgur.com/y3bnXkL.png?1)

The next time GPSLogger notices that location services aren't running it initiates the 'stop' cleanup steps, one of which is to do the upload.  It shows up fine.

**Comment by lvmm** [comment]
I am stopping the location service using the notification panel button and uploading tracks to google drive. Today I tried to reproduce this issue a number of times and found out that I cannot, but that was after I've updated to v69 which promises among other things multiple file upload bugfixes. Hopefully it is fixed now.
