### ISSUE TITLE
Multi-file uploads result in failures

### ISSUE THREAD

**Issue by swildy** [mendhak/gpslogger#358]
Uploading multiple gpx files (2 or more) almost always results in one or more files failing to upload. Tried with Google Drive and FTP. Same problem with each. Haven't tried any other senders. Repeated attempts will get the files that fail to finally upload, so doesn't seem to have anything to do with the files themselves. Seems like a concurrency issue with handling multiple files.

Also, the logging simply says "Could not upload the file", and doesn't indicate *which* file failed to upload. The filename needs to included in the error message.

Version 68. Galaxy S6. Android 5.1.1.

**Comment by mendhak** [comment]
Bug fix released in v69

**Comment by swildy** [comment]
Which bug was fixed exactly?

Thx.
