### ISSUE TITLE
Custom URL variables not documented

### ISSUE THREAD

**Issue by MechanicsPal** [mendhak/gpslogger#360]
Unless I have missed them somewhere, I have not found the variables for the custom URL logging.  If anyone can point me in the right direction, I would be greatly appreciative.

**Comment by mendhak** [comment]
I haven't written it anywhere but you should be able to see it when you click on the custom URL logging row in preferences.

**Comment by MechanicsPal** [comment]
I did find it in the menu. Thank you very much.  Five stars!!

**Comment by mendhak** [comment]
Cheers
