### ISSUE TITLE
Log Files to External SD Card??

### ISSUE THREAD

**Issue by icedvolvo** [mendhak/gpslogger#361]
This has already [probably] been addressed .... i think .... but I'm not sure so I'll raise it and mendhak can kill it off.

I cannot set GPSlogger to use the external SD card as the store for log files.

As I understand the changes with later versions of android an app installed in internal memory is prevented from writing  to the SD card (it can read from it) ... or at least thats what I gather. 

Q1: is that true?

Q2: Google apps (i.e. camera)  can write to the SD card  and my backup app SuperBackup appears to be able to write to the SD card? If so how can they do it?

Q3: is the only way around this to "root" the phone and hack it to use the external SD card?

Thanks

**Comment by mendhak** [comment]
Yes, it's a [confusing situation](https://commonsware.com/blog/2014/04/08/storage-situation-external-storage.html).  In Android M, they're planning to have some means of addressing this.

However [I've set it to write to external storage](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/AndroidManifest.xml#L10) so you should be able to write to SD card.  Are you not able to navigate to it or is it failing to write?

**Comment by icedvolvo** [comment]
Sorry mendhak have been away for a few weeks.

To answer your question: no I cannot navigate to the SD card to store files there. The only option I have is on the internal storage. screen shot accompanies.
![screenshot_2016-01-25-08-39-43 1](https://cloud.githubusercontent.com/assets/5210944/12539154/10083c0c-c340-11e5-9dc1-2dd55d0774cf.png)

Am i  missing something?

**Comment by icedvolvo** [comment]
Scrap that! 

It just started allowing me to navigate to the sd card ???? Dont understand at ll but its working fine now ...... So please consider closed thanks iced.

**Comment by mendhak** [comment]
It's a [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug).  I looked at it and it started working.
