### ISSUE TITLE
HTTP Request for each location obtained

### ISSUE THREAD

**Issue by TheNilesh** [mendhak/gpslogger#362]
This app is awesome. I just want it to send custom HTTP Requests for each location obtained. These requests should be queued till they are successfully submitted to the server. So that whenever internet is connected, app will proceed submitting queued requests.
Users will be able to configure submit this data to web service, or google spreadsheet. This data can be used by webapps to show realtime location on google map.
I am implementing similar [web app for backitude](https://github.com/TheNilesh/backitude2GoogleSheet).

**Comment by mendhak** [comment]
I assume you are asking about the code implementation?

The Custom URL and Google Drive implementations already do this - when it's time to upload, they submit a Job.  This uses [Android Priority Job Queue](https://github.com/yigit/android-priority-jobqueue) which in turn does the check-for-internet, etc.   So all you have to do is submit a job request.

[Example](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlJob.java)
