### ISSUE TITLE
Feature Request: Combine GPS locations with incoming Bluetooth serial data stream

### ISSUE THREAD

**Issue by Workmandan** [mendhak/gpslogger#363]
This thing is great! Pipedream: I have a radiation detector that sends a number every second over Bluetooth SPP, which I currently record to text using a serial terminal emulator. Is it possible for GPSLogger to log: GPS Location + incoming Bluetooth Serial port data approximately every second?

Thank you,
-Daniel

**Comment by mendhak** [comment]
(Very late reply but... )

Because this is very custom, it's better off being a fork of the app; you'd need to hire a dev (or DIY) to read that data as the app is running and hold that in memory; then write to the output log file.
