### ISSUE TITLE
Unstable upload to google drive

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#364]
Sometimes track is created in the local folder but does not appear in the google drive.  Here is a debug log of the failed upload:

16:54:27 INFO  ShortcutStop.onCreate:36 - Shortcut - stop logging
16:54:27 DEBUG GpsLoggingService.StopLogging:417 - .
16:54:27 DEBUG GpsLoggingService.AutoSendLogFile:356 - Filename: null
16:54:27 INFO  FileSenderFactory.SendFiles:73 - Sending file 20151124161329
16:54:27 DEBUG FileSenderFactory.SendFiles:115 - Sender: com.mendhak.gpslogger.senders.gdocs.GDocsHelper
16:54:27 DEBUG GDocsHelper.UploadFile:89 - Submitting Google Docs job
16:54:27 DEBUG GpsLoggingService.SetupAutoSendTimers:300 - Setting up autosend timers. Auto Send Enabled - true, Auto Send Delay - 0.0
16:54:27 DEBUG GpsLoggingService.StopGpsManager:621 - Removing towerLocationManager updates
16:54:27 DEBUG GpsLoggingService.StopGpsManager:626 - Removing gpsLocationManager updates
16:54:27 DEBUG GpsLoggingService.StopPassiveManager:638 - Removing passiveLocationManager updates
16:54:27 DEBUG GpsLoggingService.StopActivityRecognitionUpdates:135 - Stopping activity recognition updates
16:54:27 INFO  GpsLoggingService.NotifyClientStopped:694 - Stopped

and nothing more. Successful uploads have GDocsJob lines in the log after the 'stopped' line, failed uploads have nothing, 'stopped' is the last line in the log. In upload settings 'Allow auto sending' and 'when I press stop' are on, 'how often' is set to 0, 'send zip file' and 'send on wi-fi only' are off, google drive is the only configured sync target, tracks are created on the card. v69 (the last one available).

**Comment by mendhak** [comment]
This would mean that the job is simply not being executed, only queued up.  Does it execute later then?

The job will get executed when a data connection is 'active'.  So this could happen in areas where there's patchy internet, but should resume later. If a file upload of `1.gpx` is pending, the next queued up job for the same file will overwrite it as well.

**Comment by lvmm** [comment]
By 'don't appear in google drive' I mean that tracks are not visible in google drive on the phone where GPSLogger is running and never synced, even after fresher tracks have been already uploaded and synced with the account. This issue affects about 5-10% of my tracks.

**Comment by lvmm** [comment]
I've another google drive-related glitch which may be related to this problem: the track in the GPSLogger folder on the card in the phone contains some data, the same track in google drive has zero length (again, checked on the phone where GPSLogger is running - zero). Debug log was turned off at this moment, but as I remember I turned the tracker off, then accidentally turned it back on and then back off - all with widgets. The second short track - it logged a couple of points between the last start/stop sequence - was uploaded without any issues.

**Comment by lvmm** [comment]
And yet another issue: for some reason GPSLogger created a second google drive folder with exactly the same name as the first one ans started uploading tracks there

**Comment by mendhak** [comment]
The Google Drive upload should be far more stable now, made several improvements in 2017/2018 and in v101 as well, so I'll close this.  Please open new issue if there is still a problem.

**Comment by lvmm** [comment]
I am afraid it did it again - track is in the local folder on the phone but not in google drive. Debugging was off at that time, but I stopped tracking in a basement where cellular signal was very poor and there could've been no data. v102
