### ISSUE TITLE
Error:(159, 13) Failed to resolve: com.afollestad:material-dialogs:a240bbe

### ISSUE THREAD

**Issue by bigfoot90** [mendhak/gpslogger#366]
Hi, I'm compiling your app from branch master,
but I'm having ```Error:(159, 13) Failed to resolve: com.afollestad:material-dialogs:a240bbe```,
it seems that commit ```a240bbe``` does not exists.

**Comment by mendhak** [comment]
Hi the [commit definitely exists](https://github.com/afollestad/material-dialogs/commit/a240bbe0eb69292d60b663c5815978b2507d38e5), is the console showing any attempts at going to jitpack.io?  Basically the way that reference works is it goes to jitpack.io and builds the commit and gives you the jar.  If it doesn't work the first time, it might be in a queue possibly, so try again.
