### ISSUE TITLE
username andpassword sent in custom url not working

### ISSUE THREAD

**Issue by Ramblin** [mendhak/gpslogger#368]
When I try to include the username and password in the url of a custom URL I get the error message (in the Log view):
"Could not send to custom URL"

the format I am using is
http://user:password@www.mysite.com/directory/script.php?lat=%lat

(I have simplified the actual URL but you get the idea)

I use the exact same format from a browser with the same user:password and it works.
The first time I used this from the browser, the server (or the browser, I am not sure which) generated a pop-up window asking if I wanted to sign in with user and password.  I said yes and all was good; no explicit typing of user or password required.

If, using GPS Logger, I use the format without the user:password@ and remove the authentication from the directory, all works (but obviously I want authentication)

My site is on GoDaddy.  Not sure if they do some funny things or not, but just wanted to share full info.

Question:
1) Am I using the correct format? 
(It works from a browser, but not sure if I am doing it right with GPS Logger custom URL)

2) Is there a step I am missing?  
The confirmation I needed to click when using the browser (Chrome) makes me wonder if the GPS Logger custom URL option is being asked to confirm as well and not doing so.

**Comment by mendhak** [comment]
Hi this should already be implemented - https://github.com/mendhak/gpslogger/issues/354

I also checked with the Play Store and it's working fine.  Can you try with a non-GoDaddy server, even a test server locally ? 

For example set up a basic auth server in Python

https://gist.github.com/fxsjy/5465353

And try posting to it

**Comment by Ramblin** [comment]
Son of a gun

I does work when I set it up on my own development server in my office

It must be the GoDaddy servers intercepting and wanting some manual confirmation from a user on a browser

Sorry to bother you with this

Thanks for your response; you have made a great app that let me develop and trouble shoot a GPS tracking system that I can use for vehicles - with minor mods to the code
