### ISSUE TITLE
Inserting a note doesn't bring the keyboard automatically

### ISSUE THREAD

**Issue by naoliv** [mendhak/gpslogger#369]
When clicking to insert a note I see one small issue: I need to press the text box to bring up the keyboard.
From what I see the keyboard should always be displayed automatically.

**Comment by dbareis** [comment]
I didn't know you could add a note, I have a pencil in the bottom left corner of screen and that asks for a "description" (not sure what that it for), however on my Nexus 6P that does automatically bring up the keyboard.

**Comment by mendhak** [comment]
@naoliv what phone do you have?  The keyboard is always displayed when this comes up.  Try the latest version in case the updated widgets have fixed this for your specific OS via `appcompat` update.
