### ISSUE TITLE
truly horrible operation of GPS in high accuracy mode

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#370]
I accidentally turned on the so called high accuracy location mode when it is supposed to use not only GPS but wifi and cellular data to improve precision. Actually it made things quite bad: notice how the track repeatedly jumps to certain predetermined locations, I presume these are the coordinates determined from the non-GPS data 
![hagps](https://cloud.githubusercontent.com/assets/11752339/11863705/2de4a7fe-a4a7-11e5-81cc-bc05b78cdcf9.jpg)
Other GPS programs I tried don't display this jerkiness so I am led to believe that this problem is not phone- or android-related but peculiar to the way GPSLogger retrieves GPS points. I didn't try turning on the "performance-keep GPS on between fixes" option yet, I think it might help but is there a way to do it without the associated power drain? Galaxy S5, android 5.0. 

Incidentally does someone know how can I turn the high accuracy mode off by default on unrooted device? The bastards at google (or maybe samsung) tweaked the settings in 5.0, once I accidentally turned the blasted thing on there is no obvious way to turn it back off again like it was in previous versions.

**Comment by lvmm** [comment]
Nope, setting "performance-keep GPS on between fixes" on has no effect at all.

**Comment by mendhak** [comment]
The old points are usually from network location, cached. If you go to
location providers within the app settings, uncheck network and uncheck
passive, you should see better results.  It's somewhat android related and
somewhat gpslogger related, but as you said ultimately down to the way app
tries to acquire points.

**Comment by lvmm** [comment]
Yes, with network unchecked everything is back to normal - missed that one.
