### ISSUE TITLE
Logging to both GPX & KML files only generates the KML file

### ISSUE THREAD

**Issue by dbareis** [mendhak/gpslogger#371]
I have set both of the options as I want both types of files, if this is not supported then the UI should prevent it (it does display icons for both types).  Also UI related, the description is misleading and I expected a "GPSLogger" directory off the root, it should mention it saves to the sdcard in the folder configured below.

If I have both types set then only the KML (no GPX) file is generated in the Google Drive Folder, if I remove "KML" the "GPX" file is being generated.  I use STOP then START logging to update Google Drive.

**Comment by mendhak** [comment]
It should upload both GPX and KML - I'd enable debugging and have a look in there, perhaps some error is being thrown when it attempts to upload the GPX file?

I didn't understand the misleading description bit - the UI shows the path to where the file is being written?

![.](http://code.mendhak.com/gpslogger/1.png)

**Comment by dbareis** [comment]
I eventually did see the filename and path on the screen posted above, but I was talking about the settings (Logging Details) screen. For example "Log to GPX" help says "Creates a GPX file in the GPSLogger folder on the sdcard", that statement is incorrect. I'd suggest it say something like "Creates a GPX file in folder configured below".

I am not specifying my own filename and I think that has fixed the issue, I will leave the option on for a while to check.

The "fix" might be because of another bug? when file not overridden the files go into a "GpsLogger Tracks" subdirectory (I've left the save location alone), with my filename specified they don't they go into it's parent folder.
