### ISSUE TITLE
Google Drive "Folder Name", can't specify subdirectories ("Apps/GpsLogger")

### ISSUE THREAD

**Issue by dbareis** [mendhak/gpslogger#372]
I'd like to be able to get as much as possible out of my root directory and like to be organised.

I tried a few variations including "Apps/GpsLogger" but nothing worked and that example created a folder off the root with that name (including the slash).

**Comment by mendhak** [comment]
I'd suggest instead - let the app create the directory.  Then later on, move the directory yourself into another directory.  I believe the app should still be able to find it.

**Comment by dbareis** [comment]
Hi,

On Sun, 10 Jan 2016 at 07:59 mendhak <notifications@github.com> wrote:

> I'd suggest instead - let the app create the directory. Then later on,
> move the directory yourself into another directory. I believe the app
> should still be able to find it.
>

OK, I tried that and now if I use "Auto Send Now" (which by the way also
"auto stops working" after a period of time), I get a "Sorry" dialog with
text "Could not upload the file" (could say filename and directory...), if
you press "OK" to that to goes into "Auto sending" "Please wait" (possibly
forever).

Thanks
Dennis

**Comment by giacecco** [comment]
I've tried @mendhak's advice above and it works for me.

**Comment by dbareis** [comment]
So did I I have have:

* 4 versions of my directory on Google Drive, the expected and a "(1)", "(2)" and "(3)" version. I will turn off the apps upload and do it myself with script.
* It still misses whole days of logging (for example an 8 day gap), but this time its the app as well so nothing to upload. Perhaps autostart after boot failing?  Will try tasker to start at boot, if this fails I'll have to stop using the app.
* No sync option and upload ui not user friendly

**Comment by liljenstolpe** [comment]
I believe sub-directories would be useful (and not having to move them later).  I also think the same kind of variable substitution as is available for file-names  For example, a directory name could be:
gps-logs/%year-%month

**Comment by mendhak** [comment]
Google Drive was removed as part of the F-Droid move, so I'm closing some related tickets now.
