### ISSUE TITLE
BUG: Just Got 2 Billion Yay! Upload confirmations - Had to kill the app

### ISSUE THREAD

**Issue by dbareis** [mendhak/gpslogger#378]
I uploaded to Google Drive, a message is shown for each selected item, the problems:

[1] There is no select/unselect all

[2] A confirmation box (or error I assume) message is show for each one requiring the app to be terminated.

[3] It uploads them them in a random? order, so can't sorted uploaded files by date/time.

**Comment by mendhak** [comment]
What phone are you using, and is there a custom ROM involved?

Do you have a screenshot of this confirmation?

**Comment by dbareis** [comment]
I'm on a rooted Nexus 6P (Android 6.0.1) without custom rom, I do have some xposed modules installed.

I tried top get the "Yay" message to capture but its now failing to upload for no obvious reason (as it doesn't say why).

As for the dialogs, none of the dialogs I have seen that allow file selection has "select all" or "un select all" buttons.

The random order statement is based on the time shown on the web version of Google drive after uploading multiple files, they could not have been uploaded in date/time order assuming a synchronous upload.

**Comment by mendhak** [comment]
v70 released and will appear in market in a few hours. Closing this thread. Please create a new issue if there are further problems.

I'll think over a select all in file dialogs for a future tweak. The sorting on Google Drive is down to Google Drive but with the file name double-digit fix this should be better.
