### ISSUE TITLE
OwnCloud Local File does not exists

### ISSUE THREAD

**Issue by 0x7878** [mendhak/gpslogger#381]
Hey Folks,

Can't upload any files to OwnCloud. The Log says that local file does not exists and owncloud could not upload the file but i choose different files from dropdown menu. It also doesnt matter which path i configured to save gpx files. I'm trying to use differents URLs but the only one to work is the WEBDAV path i guess. I would be glad if i can use ownCloud to upload these files, 

Maybe someone could help me... 

Thank you in advance

**Comment by mendhak** [comment]
Can you temporarily enable debug logging in general menu, then reproduce your error.  If you look at the log file there may be a clue in there.  You can also post it here, and if not here, then email gpslogger at mendhak.com

**Comment by 0x7878** [comment]
unfortunately, Debug log doesnt tell me more about the Problem. Here is the log. Thank you for your help.



11:19:12 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
11:19:12 DEBUG GpsMainActivity$13.onServiceConnected:1042 - Connected to GPSLoggingService from MainActivity
11:19:17 DEBUG GpsMainActivity.onMenuItemClick:719 - Menu Item: Upload
11:20:00 INFO  GpsLoggingService.HandleIntent:213 - Intent received - Get Next Point
11:20:00 INFO  GpsLoggingService.StartGpsManager:558 - Requesting GPS location updates
11:20:00 INFO  GeneralLocationListener.onGpsStatusChanged:133 - GPS gestartet, warten auf Fix
11:20:02 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:03 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:03 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:04 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:05 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:06 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:06 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455297702144
11:20:06 WARN  GpsLoggingService.OnLocationChanged:774 - Only accuracy of 358.0 m. Point discarded.Inaccurate point discarded
11:20:06 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:06 DEBUG GeneralLocationListener.onGpsStatusChanged:111 - Fix erhalten
11:20:07 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:07 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455297702144
11:20:07 WARN  GpsLoggingService.OnLocationChanged:774 - Only accuracy of 223.0 m. Point discarded.Inaccurate point discarded
11:20:07 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:08 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:08 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455297702144
11:20:08 WARN  GpsLoggingService.OnLocationChanged:774 - Only accuracy of 161.0 m. Point discarded.Inaccurate point discarded
11:20:08 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:09 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:09 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455297702144
11:20:09 WARN  GpsLoggingService.OnLocationChanged:774 - Only accuracy of 122.0 m. Point discarded.Inaccurate point discarded
11:20:09 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:10 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:10 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455297702144
11:20:10 WARN  GpsLoggingService.OnLocationChanged:802 - Only 22.0 m traveled. Point discarded., point discarded
11:20:10 DEBUG GpsLoggingService.StopGpsManager:629 - Removing towerLocationManager updates
11:20:10 DEBUG GpsLoggingService.StopGpsManager:634 - Removing gpsLocationManager updates
11:20:10 DEBUG GpsLoggingService.SetAlarmForNextPoint:904 - Set alarm for 120 seconds
11:20:10 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 16 satellites
11:20:26 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
11:20:26 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
11:20:26 DEBUG GpsMainActivity.onCreate:128 - Start logging on app launch
11:20:26 DEBUG GpsLoggingService.StartLogging:385 - .
11:20:26 DEBUG GpsLoggingService.StartLogging:389 - Session already started, ignoring
11:20:26 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
11:20:26 DEBUG GpsMainActivity$13.onServiceConnected:1042 - Connected to GPSLoggingService from MainActivity
11:20:28 WARN  GpsMainActivity.StopAndUnbindServiceIfRequired:1071 - Could not unbind service
java.lang.IllegalArgumentException: Service not registered: com.mendhak.gpslogger.GpsMainActivity$13@82ef088
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1030) ~[na:0.0]
	at android.app.ContextImpl.unbindService(ContextImpl.java:1839) ~[na:0.0]
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:557) ~[na:0.0]
	at com.mendhak.gpslogger.GpsMainActivity.StopAndUnbindServiceIfRequired(GpsMainActivity.java:1068) ~[na:0.0]
	at com.mendhak.gpslogger.GpsMainActivity.onDestroy(GpsMainActivity.java:183) ~[na:0.0]
	at android.app.Activity.performDestroy(Activity.java:6169) ~[na:0.0]
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1141) ~[na:0.0]
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3726) ~[na:0.0]
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3757) ~[na:0.0]
	at android.app.ActivityThread.access$1500(ActivityThread.java:154) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:135) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5294) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:372) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) ~[na:0.0]
11:20:31 DEBUG GpsMainActivity.onMenuItemClick:719 - Menu Item: Upload
11:20:36 DEBUG GpsMainActivity.onMenuItemClick:719 - Menu Item: ownCloud
11:20:49 INFO  GpsMainActivity$10.onSelection:921 - Selected file to upload- 20160212.zip
11:20:49 INFO  GpsMainActivity$10.onSelection:921 - Selected file to upload- 20160212.gpx
11:20:49 DEBUG OwnCloudJob.onAdded:51 - ownCloud Job: onAdded
11:20:49 DEBUG OwnCloudJob.onAdded:51 - ownCloud Job: onAdded
11:20:49 DEBUG OwnCloudJob.onRun:57 - ownCloud Job: Uploading  '20160212.zip'
11:20:49 DEBUG OwnCloudJob.onRun:57 - ownCloud Job: Uploading  '20160212.gpx'
11:20:51 ERROR OwnCloudJob.onRemoteOperationFinish:100 - Local file does not exist
11:20:51 DEBUG OwnCloudJob.onRemoteOperationFinish:106 - ownCloud Job: onRun finished
11:20:51 ERROR OwnCloudJob.onRemoteOperationFinish:100 - Local file does not exist
11:20:51 DEBUG OwnCloudJob.onRemoteOperationFinish:106 - ownCloud Job: onRun finished
11:20:51 DEBUG GpsMainActivity.onEventMainThread:1206 - OwnCloud Event completed, success: false
11:20:51 ERROR GpsMainActivity.onEventMainThread:1210 - ownCloud-Could not upload the file
11:20:51 DEBUG GpsMainActivity.onEventMainThread:1206 - OwnCloud Event completed, success: false
11:20:51 ERROR GpsMainActivity.onEventMainThread:1210 - ownCloud-Could not upload the file

**Comment by mendhak** [comment]
Ok after some investigation I've traced it to the Owncloud Android library, specifically here:

https://github.com/owncloud/android-library/blob/32ab89fc308af2a51b9b7ded7fb40fc786dfd8a6/src/com/owncloud/android/lib/common/operations/RemoteOperationResult.java#L398

The error message is misleading - it says 'local' but it's referring to the OwnCloud instance.  In other words, it's saying that the folder you're trying to upload to doesn't exist.  

Go to OwnCloud settings, under the 'Folder' option, it's looking for the folder there.  Try creating it on OwnCloud server then upload again.

**Comment by mendhak** [comment]
App will now create the owncloud directory each time.
