### ISSUE TITLE
Android 6.0: Logging stops after period of inactivity

### ISSUE THREAD

**Issue by xconstruct** [mendhak/gpslogger#382]
First of all, thank you for your awesome app, I've been using it non-stop for over a year.

I'm afraid I have another task-killer bug for you. Recently I upgraded to Android 6.0 (CM 13) and over night GPSLogger suddenly stops logging, and I have to start it manually again. This happens every night. Looks like it is related to the new Doze mode in 6.0. Here are a few infos:

* Notification is enabled and it stays, but only showing "GPSLogger is running"
* Location mode is set to "High Accuracy"
* I've disabled Android 6.0 Battery Optimization by setting the app to "Not Optimized"
* My device is plugged-in and charging the whole time
* RAM is averaging around 1.5 of 2 GB
* The debug log shows that the logging stops almost exactly 1 hour after I last used my device (every time)

Addendum: I'm currently testing it further. It's strange, looks like it happens *only* when charging - if I leave my phone unplugged for the night, it still works as expected.

Debug log excerpt (last logging attempt + manual restart in the morning):

```
01:49:59 INFO  GpsLoggingService.StartGpsManager:558 - Requesting GPS location updates
01:49:59 INFO  GpsLoggingService.StartGpsManager:569 - Requesting cell and wifi location updates
01:49:59 INFO  GeneralLocationListener.onGpsStatusChanged:133 - GPS started, waiting for fix
01:50:00 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455669599608
01:50:00 INFO  GpsLoggingService.OnLocationChanged:809 - XX.XXXXXXX,X.XXXXXX
01:50:00 INFO  GpsLoggingService.ResetCurrentFileName:686 - Filename: 20160217
01:50:00 DEBUG GpsLoggingService.WriteToFile:925 - Calling file writers
01:50:00 DEBUG Gpx10WriteHandler.run:231 - Finished writing to GPX10 file
01:50:00 DEBUG GpsLoggingService.StopGpsManager:629 - Removing towerLocationManager updates
01:50:00 DEBUG GpsLoggingService.StopGpsManager:634 - Removing gpsLocationManager updates
01:50:00 DEBUG GpsLoggingService.SetAlarmForNextPoint:904 - Set alarm for 600 seconds
01:50:00 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455670200629
01:50:00 DEBUG GeneralLocationListener.onGpsStatusChanged:128 - 21 satellites
01:50:00 DEBUG CustomUrlJob.onRun:75 - Sending to URL: https://REDACTED/?latitude=XX.XXXXX&longitude=X.XXXXX&timestamp=2016-02-17T00:50:00Z&accuracy=24.570999145507813&s=0.0
01:50:01 DEBUG CustomUrlJob.onRun:97 - Status code: 200
01:54:51 DEBUG GpsLoggingService.OnLocationChanged:731 - Has description? false, Single point? false, Last timestamp: 1455670200629
10:21:16 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
10:21:17 DEBUG GpsMainActivity.PopulateProfilesList:504 - Current profile:Default Profile
10:21:17 DEBUG GpsMainActivity$13.onServiceConnected:1042 - Connected to GPSLoggingService from MainActivity
10:21:19 DEBUG GpsLoggingService.StartLogging:385 - .
```

**Comment by mendhak** [comment]
Not ignoring this. I've been occasionally borrowing a friend's phone to test this; atm I don't have an Android 6 phone so it's a bit slow trying to get a feel for what's going on

**Comment by mendhak** [comment]
What phone do you have, and is this a CM13 nightly or stable?

**Comment by xconstruct** [comment]
No problem, it's not a critical issue for me - just wanted to make you aware of it.

I have a LG G3 d855 with CM 13 nightly 2016-02-05. Strangely it didn't happen the last 2-3 days, so it looks like even I can't reproduce it reliably any more. Afaik Doze Mode shouldn't even activate when the device is plugged in, so maybe this is an Android/CM/device bug.

I'll experiment the next few days with [Testing your app with Doze](http://developer.android.com/training/monitoring-device-state/doze-standby.html#testing_doze), maybe something comes up. I just tried it for a few minutes - the alarm was ignored when idle (as expected?), but logging resumed once the device came out of idle.

Let me know if I can help you in any other way.

**Comment by mendhak** [comment]
mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys battery unplug
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys devicidle step
    Can't find service: devicidle
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys deviceidle step
    Stepped to: IDLE_PENDING
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys deviceidle step
    Stepped to: SENSING
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys deviceidle step
    Stepped to: IDLE_MAINTENANCE
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys deviceidle step
    Stepped to: IDLE
    mendhak@COFFEE ~/Code/gpslogger (testing *) $ adb shell dumpsys deviceidle step

At the last bit, but I didn't see this in your log but it does pause here.

> 03-02 00:05:56.987  11103-11103/com.mendhak.gpslogger I/GeneralLocationListener﹕ onGpsStatusChanged:134 - GPS paused


In addition to the link you gave I'll probably also want to detect idle state:

https://gist.github.com/ccpmark/430d4ddf3a46a02672c1

And possibly use one of the other alarm managers.

**Comment by mendhak** [comment]
- [ ] Make the auto senders aware of doze mode, they should only attempt to autosend if they are out of doze mode or on the whitelist
- [ ] Make the logging service sets its polling alarm/autosend alarm infrequently (`setAndAllowWhileIdle()`) when in doze mode.

**Comment by mendhak** [comment]
[Release v72](https://github.com/mendhak/gpslogger/releases/tag/v72)
