### ISSUE TITLE
Feature Request: Ability to name and rename log files

### ISSUE THREAD

**Issue by ivankautter** [mendhak/gpslogger#385]
It can be helpful in identifying different activities and different logging events on the same or different days when log files can be given a user-specified name for the file.  I'd like to see a dialog to specify a track name at the onset of logging. I'd also like to see a dialog that shows existing track files that would allow any specified one to be renamed.

**Comment by mendhak** [comment]
Part of this is currently possible.  Under Logging details, under New File Creation, pick Custom file.  

This enables the 'Ask for a file name on every start'

**Comment by ivankautter** [comment]
No, that makes sense. Sorry to pepper with requests. There are features that weren't exactly clear as to how they were implemented. I am seeing them now.  The current ability to specify a name at the start of logging is sufficient.

**Comment by mendhak** [comment]
Ah gotcha, np!
