### ISSUE TITLE
Feature Request: Ability to save log files to user-specified folder

### ISSUE THREAD

**Issue by ivankautter** [mendhak/gpslogger#386]
My workflow and that of my colleagues with MyTracks usually consists of offloading gpx files from a folder in internal storage via AirDroid to our work PCs over wifi. While you've offered a lot of options for transferring files to cloud storage, our method is simple and convenient for us as we may be offloading any number of files including photos at the same time. Unfortunately, GPS Logger saves the log files deep further down in the file structure than many of us are comfortable traversing. I'd like to request a user-specified folder for saving log files.

**Comment by mendhak** [comment]
Go to Logging Details > "Save to folder"  

You can pick a folder there.
