### ISSUE TITLE
v72 fails to close gpx element

### ISSUE THREAD

**Issue by tsteven4** [mendhak/gpslogger#405]
i.e. </gpx> is missing

**Comment by tsteven4** [comment]
> i.e. </gpx> is missing

**Comment by tsteven4** [comment]
`</gpx> is missing`

**Comment by tsteven4** [comment]
this seems to be intermittent.  when it fails there is more than the close of the gpx element missing.

**Comment by mendhak** [comment]
I'll have a look now :fearful:

**Comment by mendhak** [comment]
Can you post a file or email it to gpslogger at mendhak dot com?

**Comment by tsteven4** [comment]
email sent with example.

**Comment by tsteven4** [comment]
This was a problem with the transfer of the files using MTP.  It appears there is either a limitation in the protocol, or an error in implementation of the protocol on my device or computer.  The problem occurs when the device is tethered and the capture is still active.  Gpslogger is updating the file on the device, which overwrites the final 12 or 21 characters.  For example when a new trackpt is added
`</trkseg></trk></gpx>`
in the previous version of the file might be overwritten with
`<trkpt lat="40.123456`
while the subsequent part of the new trkpt increases the length of the updated file.
The MTP transfer was using the length of the file before the update and transferring that many bytes of the updated file.
I can workaround the issue by disconnecting and reconnecting the tether after gpslogger has stopped logging.

I do not believe this is bug in gpslogger, I believe this is either a limitation in the usage of MTP with files that are being changed while tethered, or an error in the implementation of the protocol on my device or computer.

**Comment by mendhak** [comment]
After a file write, I make a call to add the file the [media scanner db](https://github.com/mendhak/gpslogger/blob/ec557b2f1e94d09e1356e8c7e360be03430c86d7/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L225).  So the media scanner should pick up the file and when you transfer via MTP, it gets it properly.

I have seen a few threads where sometimes this just doesn't work properly and it will be hard to pinpoint - can be phone, OS, ROM etc.  For this reason it is better to consider other ways of copying the files over.  Airdroid, adb pull, File Explorers, upload feature, etc.

**Comment by tsteven4** [comment]
I can reproduce this on a 4.4.2 device as well as the original 4.3 device.  I have installed the latest drivers on the PC which is identical without apparent effect.

I agree other methods of transferring the file seem more reliable.

I wonder if a call to disconnect would change anything, perhaps with a OnScanCompleteListener?  Unplugging and plugging in again does seem to work.

> Convenience for constructing a MediaScannerConnection, calling connect() on it, and calling scanFile(Context, String[], String[], MediaScannerConnection.OnScanCompletedListener) with the given path and mimeType when the connection is established.

**Comment by mendhak** [comment]
This can be tried.  I've commited a branch with a callback+disconnect [here](https://github.com/mendhak/gpslogger/commit/6266db83d81b2bd08b4e7ed2d850087a11462569).

If you still have time to troubleshoot, you can try this APK with the change in it. 

[gpslogger-73-issue405.apk](https://www.dropbox.com/s/xk3miy2d6ni8ogd/gpslogger-73-issue405.apk?dl=0)
[gpslogger-73-issue405.apk.asc](https://www.dropbox.com/s/psobrx0mvpz77qh/gpslogger-73-issue405.apk.asc?dl=0)
[gpslogger-73-issue405.apk.SHA256](https://www.dropbox.com/s/0elxncel7y23q5b/gpslogger-73-issue405.apk.SHA256?dl=0)

**Comment by tsteven4** [comment]
thanks for the attempt.  unfortunately it didn't appear to change anything.  I tested with the 4.4.2 device.  I did verify I was running the issue405 version.

**Comment by tsteven4** [comment]
I tried v73 on a windows 10 pc with the 4.4.2 device.  Same behavior.

**Comment by mendhak** [comment]
So the media scanner code had no effect.  I can't think it's a device problem because you've got two devices with the same problem.  Not sure where to investigate on this one.

What devices do you have?  Are they rooted, custom ROMs etc?

**Comment by tsteven4** [comment]
samsung stardust (4.3), samsung galaxy tab pro 8.4 (4.4.2), factory rom in both.

It seems like once windows explorer sees the file, it never thinks it changes unless I unplug and replug. At the same time, I think if I wait longer before I browse to the folder, windows explorer sees a later version of the file, i.e. one with more trkpts in it.  That would imply the updates are getting out of gpslogger, but not all the way to windows explorer.  I can try to verify this tomorrow.  I am wondering if the protocol is designed to support static files, not dynamic files like gpslogger creates.

**Comment by tsteven4** [comment]
I am now testing with the windows 7 pc as a virtual box host with is running a Centos 7 guest.  I watch the device with gvfs-monitor-dr.  Once nautilus sees the file it doesn't ever see a change in size.  Both nautilus and gvfs-monitor-dir detect new files gpslogger creates.  If I delete a file with ES file explorer both see it getting deleted.  If I edit it with Es File explorer they see it deleted and (re)created.  I believe gvfs-monitor-dir is suppose to report 

>
       file creation, deletion, file content and attribute changes and mount
       and unmount operations inside the specified directories

but all I see are created and deleted events, and none of these correspond to an update to the file by gpslogger.

This testing was with the android 4.3 device.

**Comment by mendhak** [comment]
I'm seeing some things around this here - http://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp

Which links to: 
* https://code.google.com/p/android/issues/detail?id=38282
* https://code.google.com/p/android/issues/detail?id=195362

So it's very likely a bug in Android.  However anecdotally, I've had no problem in recent versions of Ubuntu with MTP and phones ever since [14.04 gvfs](https://plus.google.com/+AlinAndrei/posts/a7K3PgEYxte); I tried quite a few phones and everything seems fine.  So that does muddy the waters a bit - as in, the OS may also play a part in this?
