### ISSUE TITLE
log status to gps file periodically

### ISSUE THREAD

**Issue by dabo5** [mendhak/gpslogger#406]
Hi,
gpslogger runs inside my car to track my movement.
to save battery live i use the option "activity recognition".

but with this option selected, i can not determine whether the file contains the complete data for the whole day.

I would suggest to write a point every half hour with description "LoggingStillAlive" to gpx file. 

now I have the possibility to evaluate the data. 
For example: I can say that I have recorded all day if 24*2 records with description "LoggingStillAlive" exist. Or the data is missing from 9:00 to 11:00 if there where no records with description "LoggingStillAlive" between this time. four consecutive "LoggingStillAlive" entries indicates that no motion has occurred for 2 hours...

I think that it could also speed up the GPS fix . Problem: if the cars has been standing overnight, it sometimes happens that the GPS fix  takes a long time the next day. a query every half hour could resolve the problem.

**Comment by mendhak** [comment]
I've been spending some time playing around with an 'adaptive' or 'smart' logging where it tries to add intermediate points to a file.  Two main problems:

First - it has an impact on battery life; a user logging every `x` hours will be 'given' log points every half an hour.  If making this optional, then you might as well set the period of logging to half an hour. 

Even if this were optional, the second problem is, with Android 6, 7 and soon 8, the doze mode is becoming more and aggressive with each version.  So any adaptation made to fix the first problem will be rendered useless.
