### ISSUE TITLE
OpenGTS - Add support for SSL

### ISSUE THREAD

**Issue by edwardmuel** [mendhak/gpslogger#407]
Could you add SSL support for the OpenGTS sender?
Looking at [your code](https://github.com/mendhak/gpslogger/blob/b245c04a627e43c92048d19ffa70b10b73b79565/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/opengts/OpenGTSJob.java#L112), it appears that the OpenGTS sender doesn't support SSL.
The [custom URL sender](https://github.com/mendhak/gpslogger/tree/b245c04a627e43c92048d19ffa70b10b73b79565/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl) appears to support SSL.

**Comment by mendhak** [comment]
Honestly not sure how I missed this. :frowning: 

Yes of course it should be added.

**Comment by mendhak** [comment]
v74 released
