### ISSUE TITLE
Allow user to specify app Language/Locale

### ISSUE THREAD

**Issue by wanneslier** [mendhak/gpslogger#410]
Hi there,

I installed the app and it works - but in Dutch. I'd like it to be in English. How can I change that?
P.S. I'm not at ease with Android at all, so please something a beginner can use  :-)

KR
Johan Vranken

**Comment by mendhak** [comment]
The app uses the system Locale, so I assume you are on a Dutch locale.  To get it in English you'll need to change the [locale for the whole phone](http://www.wikihow.com/Change-the-Language-in-Android).

But -  I can add in a feature, probably, to allow a user to pick a locale just for the app and that way you can keep the rest of your phone in Dutch.  In fact, I am sure I used to have this feature about 40 versions ago.

**Comment by wanneslier** [comment]
Thanks - I'll wait for it.

40 versions is an eternity  :-)
but thanks to Einstein time is relative  :-)))

KR
Johan

**Comment by mendhak** [comment]
v74 released

**Comment by wanneslier** [comment]
Woow if others would be so service oriented ...
Thanks a lot
