### ISSUE TITLE
Disable OpenStreetMap emails when uploading GPX tracks

### ISSUE THREAD

**Issue by cserpell** [mendhak/gpslogger#411]
Is there any way to disable automated emails OpenStreetMap server sends when receiving tracks uploaded from GPSLogger? I activated GPSLogger all day to contribute to OSM, uploading automatically every hour or so. It keeps sending me emails regarding the upload status.

I know this is a bad place to ask, but I didn't find any better place! You can remove this issue after a while.

Thanks for this app, it works great in my phone.

**Comment by mendhak** [comment]
Hmm, tough one. I think I've tracked it down to [the area of their code](https://github.com/openstreetmap/openstreetmap-website/blob/77c25dca8c9b60c2fd8dae6eeee1405ec24edf27/app/models/notifier.rb#L42) where the email was being [issued](https://github.com/openstreetmap/openstreetmap-website/blob/36cbda3c80beac9496316389d4f082383ed4322a/lib/daemons/gpx_import.rb#L24).  I think maybe your best bet is to create an issue in the OSM website and ask them to make it a preference?

**Comment by cserpell** [comment]
Good idea. I will do so. Thanks @mendhak
