### ISSUE TITLE
zip files created even if not going anywhere

### ISSUE THREAD

**Issue by tsteven4** [mendhak/gpslogger#412]
It seems like zip files can be created even if
allow auto sending is off, or all auto send targets are off.
It looks like the code zips the file solely based on the preference from "send zip file", which I think is related to AUTOSEND_ZIP, which is true by default.

A more restrictive qualification in FileSenderFactory::autoSendFiles might be an improvement.

I believe a workaround is to turn off "send zip file".

**Comment by mendhak** [comment]
I tried on a fresh install of GPSLogger, no zip produced by default. 

I then enabled auto sending + auto send on stop, it does produce a zip.  So I'm not getting the exact situation you're getting. 

However the code can be made restrictive, I'll just check if any senders are available first, but the zip does need to be produced before sending.  It shouldn't be too bad.

**Comment by mendhak** [comment]
v75 released to market.
