### ISSUE TITLE
Feature request: auto-email via intents

### ISSUE THREAD

**Issue by gkuenning** [mendhak/gpslogger#413]
I have found that GPSlogger's built-in SMTP client is unreliable for a few reasons; I can't get it to talk to a couple of different mail servers after quite a bit of experimentation.  In addition, it doesn't support queueing, so if I happen to be off-network when it tries to send, the mail  is lost.

However, there is also support for using intents to invoke other e-mail clients such as K-9 mail (my choice) when using the "share" button.  It would be nice if the auto-sending feature could also be configured to use those external clients.

**Comment by mendhak** [comment]
Which version are you on?  The email sender [definitely queues](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/senders/email/AutoEmailJob.java#L46) and will only send an email when a network connection is available.  

Regarding K9 - I believe during share, you the app only composes a subject and message but auto-sending in this manner is not possible, it would be open to abuse.  It's for that reason that the SMTP sender exists.  But it does come with the caveat that not all email providers work well.  I've tested with a few - namely GMail, Y!, Live, Postfix - to cover most cases. 

If there's a specific mail provider it's not working with I could have a try at it. 

You can also self-diagnose - if you try a test email from the email screen you should be able to get an error dialog and if you click show error it should show the exchange with the mail server.

**Comment by gkuenning** [comment]
> Which version are you on?  The email sender [definitely
> queues](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/senders/email/AutoEmailJob.java#L46)
> and will only send an email when a network connection is 
> available.

I'm running version 74.  I'm glad to hear that queueing works; 
that'll make my life happier.  I guess I misinterpreted the 
results of my earlier tests.

As to the built-in server, I'm one of the few people who don't use 
commercial mail services.  I run my own mail server using Postfix. 
If I leave the "Use SSL" option off and set port 587, GPSlogger 
connects and appears to handshake correctly but then gets kicked 
off with "Send HELO/EHLO first".  That's a bit odd because it 
actually sent EHLO, although it happened before the STARTTLS. 
Here's the full log:

    221 mallet.cs.hmc.edu
    ESMTP
    EHLO localhost
    250-mallet.cs.hmc.edu
    250-PIPELINING
    250-SIZE
    250-ETRN
    250-STARTLS
    250-ENHANCEDSTATUSCODES
    250-8BITMIME
    250 DSN
    STARTTLS
    220 2.0.0 Ready to start
    TLS
    AUTH LOGIN
    503 5.5.1 Error send HELO/EHLO first
    QUIT
    221 2.0.0 Bye

The same error happens on port 25.

According to the STARTTLS RFC (RFC 3207), you need to send a 
second EHLO after the STARTTLS.  From Section 4.2:

    Upon completion of the TLS handshake, the SMTP protocol is 
    reset to
    the initial state (the state in SMTP after a server issues a 
    220
    service ready greeting).  The server MUST discard any 
    knowledge
    obtained from the client, such as the argument to the EHLO 
    command,
    which was not obtained from the TLS negotiation itself.

The example in Section 5 shows a second EHLO immediately after the 
TLS negotiation.

My guess is that some of the commercial services are lenient on 
this point because there are so many misbehaving mail clients out 
there, but Postfix is stricter.  So I think that if you jsut 
re-send the EHLO after the STARTTLS, it should continue to work 
with the big services but also start working with more of the 
others.

> Regarding K9 - I believe during share, you the app only composes 
> a
> subject and message but auto-sending in this manner is not 
> possible,
> it would be open to abuse.  It's for that reason that the SMTP 
> sender
> exists.  But it does come with the caveat that not all email 
> providers
> work well.  I've tested with a few - namely GMail, Y!, Live, 
> Postfix -
> to cover most cases.
>
> If there's a specific mail provider it's not working with I 
> could have
> a try at it.
>
> You can also self-diagnose - if you try a test email from the 
> email
> screen you should be able to get an error dialog and if you 
> click show
> error it should show the exchange with the mail server.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mendhak/gpslogger/issues/413#issuecomment-200570771

-- 
    Geoff Kuenning   geoff@cs.hmc.edu 
    http://www.cs.hmc.edu/~geoff/

If at first you succeed, try to hide your astonishment.
	-- Harry F. Banks

**Comment by mendhak** [comment]
I've got a postfix server as part of my test harness, but it's never failed there.  So I wonder if it's a different configuration?  I'm using [this docker image](https://hub.docker.com/r/catatnight/postfix/)

If you're interested you can test this out in this APK

[gpslogger-74-issue413.apk](https://www.dropbox.com/s/mae1ow35aydp3a2/gpslogger-74-issue413.apk?dl=0)
[gpslogger-74-issue413.apk.asc](https://www.dropbox.com/s/hf0xdzs2cpj34dx/gpslogger-74-issue413.apk.asc?dl=0)
[gpslogger-74-issue413.apk.SHA256](https://www.dropbox.com/s/skrpohx29yk2kow/gpslogger-74-issue413.apk.SHA256?dl=0)

It sends an `EHLO` after `STARTTLS`

**Comment by gkuenning** [comment]
Gonna make me learn how to sideload, huh?  It's about time I did 
that.

I'm pleased to report that the updated APK solved the problem. 
Thanks!

> I've got a postfix server as part of my test harness, but it's 
> never
> failed there.  So I wonder if it's a different configuration? 
> I'm
> using [this docker
> image](https://hub.docker.com/r/catatnight/postfix/)
>
> If you're interested you can test this out in this APK
>
> [gpslogger-74-issue413.apk](https://www.dropbox.com/s/mae1ow35aydp3a2/gpslogger-74-issue413.apk?dl=0)
> [gpslogger-74-issue413.apk.asc](https://www.dropbox.com/s/hf0xdzs2cpj34dx/gpslogger-74-issue413.apk.asc?dl=0)
> [gpslogger-74-issue413.apk.SHA256](https://www.dropbox.com/s/skrpohx29yk2kow/gpslogger-74-issue413.apk.SHA256?dl=0)
>
> It sends an `EHLO` after `STARTTLS` 
>
>
>
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mendhak/gpslogger/issues/413#issuecomment-201006796

-- 
    Geoff Kuenning   geoff@cs.hmc.edu 
    http://www.cs.hmc.edu/~geoff/

It's is not, it isn't ain't, and it's it's, not its, if you mean 
it
is.  If you don't, it's its.  Then too, it's hers.  It isn't 
her's.  It
isn't our's either.  It's ours, and likewise yours and theirs.
                -- Oxford University Press, Edpress News

**Comment by mendhak** [comment]
> Gonna make me learn how to sideload, huh?

Well, you did make me read an RFC, it's only fair :dizzy_face: 

Good to know it worked, I'll put this out in a week or so.

**Comment by mendhak** [comment]
v75 released to market.

See, it only took a week. Or so.
