### ISSUE TITLE
Feature request: disable automatic file change

### ISSUE THREAD

**Issue by gkuenning** [mendhak/gpslogger#414]
I discovered that if I put %MIN in a custom file name, GPSlogger switches to a new file once a minute.  For my needs, that's a disadvantage.  I'd like to have hour/minute in the file name but stick to one file from the moment I start until I hit stop (at which point the entire file would be auto-sent).  Given that there are probably people who depend on the current behavior, the "use only one file" feature would probably have to be an option, but presumably a very easy one to add.

**Comment by elteto** [comment]
I realy need that "Use only one file" feature described by gkuenning.

**Comment by mendhak** [comment]
v78 released to market, should show up in a few hours.
