### ISSUE TITLE
Feature Request: Text current location periodically

### ISSUE THREAD

**Issue by starrynight1959** [mendhak/gpslogger#415]
Instead of emailing I'd like to text a short message (lat/lon/alt in KML) at a different and slower rate than my logging rate.  Say, every ten minutes send a text while I log once every fifteen seconds.  And it does this only when cell service is available - if not, ignore the attempt to text and wait another interval.  In other words, don't cache up texts simply because the cellular service is not available.

**Comment by mendhak** [comment]
Sorry I missed this one.  

I've now added a FAQ entry about SMS logging: http://code.mendhak.com/gpslogger/#loggingtosmsoremail
