### ISSUE TITLE
Feature Request: Viewing friend's location

### ISSUE THREAD

**Issue by oeoeoeooeo** [mendhak/gpslogger#416]
Dear gpslogger experts,

  Hi!!! Thanks for providing this nice gpslogger project.
  GPSlogger is such a best gps app for Android phones development. We really love it~

  Here is one idea. We all loves go mountain climbing. And everyone has a phone with the gps. If it can show all my friends' GPS location in my phone screen, then once there is a friend lost or missed the way it can send his/her current location to others for help... Or some orientation guide for him/ her to approach to the correct path.

  Is it possible for you to add this new feature into the gpslogger project? What's your view on the matter?

  Here are some android project for reference: 
  http://wptrafficanalyzer.in/blog/drawing-driving-route-directions-between-two-locations-using-google-directions-in-google-map-android-api-v2/

  We are looking forward your reply. 

Sincerely yours,
oeo

**Comment by mendhak** [comment]
I generally try to keep GPSLogger as location unintensive as possible.  Mountains generally have very poor data connectivity, which makes maintaining any sort of update impossible.  The closest thing I can think of is an auto-sender.  As an example, everyone can send locations on a regular basis to an email address.  Every x minutes, send an email to a 'shared' inbox.  However, GPSLogger will only send it when a data connection is available.  If you're more technically inclined, you can log to a custom URL which everyone has access to.  Same caveat - the custom log is only sent when a data connection is available.  

Or maybe you're looking for a more specific [location sharing](http://www.cnet.com/uk/news/location-tracking-apps/) app.  Although same problem as before applies - persistent data connections are hard to find in the mountains.  Unless you're climbing a mountain of cell towers.

**Comment by mendhak** [comment]
Closing thread as part of issues cleanup. For further discussion consider creating a new issue.

Additional notes: None
