### ISSUE TITLE
Feasibility of moving from GPX 1.0 to GPX 1.1

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#418]
- [ ] Migrate 1.0 to 1.1
- [ ] Include custom  `<extensions>`, with `<gps:acc>` for accuracy

**Comment by mendhak** [comment]
1.1 no longer allows a `<speed>` element, it is expected to be calculated from other points in the GPX file.  Hmm.

**Comment by jimis** [comment]
@mendhak what format would you suggest to use for usual GPS logging, in order to log as many parameters as possible, while being interoperable with other applications as much as GPX is?

**Comment by mendhak** [comment]
Tough call actually :(  I'd say go with 1.0 because even though 1.1 supports extensions, there is no 'standard' and everyone will have their own set of extensions.  

If you truly want to log as much as possible, then CSV is the best option, but it does mean that you have to convert those CSVs yourself afterwards to GPX/KML for other applications to understand.  Advantage - The CSVs will at least have every parameter possible while the GPX/KML will hava data loss.  The disadvantage here is you have to write extra code that watches your 'CSV folder' online

**Comment by jimis** [comment]
Thanks! I noticed that GPSLogger logs barely the basic with GPX 1.1 format, so I wondered. CSV it is then!
