### ISSUE TITLE
LOG Control

### ISSUE THREAD

**Issue by MrHae** [mendhak/gpslogger#419]
Hey, 

at first.
This App is great and runs very stable since over one week.

Now my nice to have things:
I need to delete the local Files everyday.
I need to activate / deactivate the Logger time based / or with google calender.
Alternativley or maybe much better, i just need to log if my phone is connected with some special BT device --> like a GPS Mouse --> so i would be able to just log my Tracks inside the car

Are you able to implemebt this?

**Comment by mendhak** [comment]
I think what you're looking for is something like [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) or [Llama](https://play.google.com/store/apps/details?id=com.kebab.Llama&hl=en_GB).  You can [send intents to GPSLogger](http://code.mendhak.com/gpslogger/#18) to start/stop it based on your own conditions such as timing or connecting to a BT dev.

**Comment by MrHae** [comment]
Hey, I tried Llama, it's nearly perfect for my needs. Problem is that it doesn't stop GPS logger neither with root. Easiest way would be the Stop widget as extra App. :)


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: mendhak <notifications@github.com>
Datum: 24.03.2016  20:30  (GMT+01:00)
An: mendhak/gpslogger <gpslogger@noreply.github.com>
Cc: MrHae <matthias.zschage@googlemail.com>
Betreff: Re: [gpslogger] LOG Control (#419)

I think what you're looking for is something like [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) or [Llama](https://play.google.com/store/apps/details?id=com.kebab.Llama&hl=en_GB).  You can [send intents to GPSLogger](http://code.mendhak.com/gpslogger/#18) to start/stop it based on your own conditions such as timing or connecting to a BT dev.

---

**Comment by MrHae** [comment]
ahhhh stop, I ve found the option to execute widgets so Llama works perfect with this logger.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: mendhak <notifications@github.com>
Datum: 24.03.2016  20:30  (GMT+01:00)
An: mendhak/gpslogger <gpslogger@noreply.github.com>
Cc: MrHae <matthias.zschage@googlemail.com>
Betreff: Re: [gpslogger] LOG Control (#419)

I think what you're looking for is something like [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) or [Llama](https://play.google.com/store/apps/details?id=com.kebab.Llama&hl=en_GB).  You can [send intents to GPSLogger](http://code.mendhak.com/gpslogger/#18) to start/stop it based on your own conditions such as timing or connecting to a BT dev.

---
