### ISSUE TITLE
Time sync | Logging network time and not system time

### ISSUE THREAD

**Issue by CreaRo** [mendhak/gpslogger#420]
This is more of a query, than an issue.
Say I am running this app on 2 phones. Also, the system time in one of the phones is off by 5 minutes. I need to make sure that it logs the time correctly, so that I can later sync location of both phones according to time. If the logged time in one phone is always off by 'x' minutes, on post processing I can never know where both phones were at a particular time.
Now, say I have 100 phones with this app, some following the correct time, and some being off by different amounts, is there a way to log network time, instead of system time?

I see that the PlainTextFileLogger class uses the location.getTime() method to get time, instead of using the system time. This however, still returns the same time as the system time, and not network time.

**Comment by mendhak** [comment]
I'll be honest, I've read this about ten times now and I'm thoroughly confused

> I see that the PlainTextFileLogger class uses the location.getTime() method to get time, instead of using the system time. This however, still returns the same time as the system time, and not network time.

Basically, [Location.getTime()](http://developer.android.com/reference/android/location/Location.html#getTime\(\)) should return UTC.    The UTC itself is based on the provider, for network locations it'll be what the network operators send.  But some networks can be a bit flaky at times and as you travel across towers you may get discrepancies.  In some cases I've seen them return completely nonsense values. But for most networks, it should already be network time.  

If you're looking for something reliable regarding time syncs, then you're better off using satellites only and ignoring network based locations completely.

**Comment by CreaRo** [comment]
I can understand the frustration! I tested again. I changed my mobile's time, and restarted logging. 
The logged time did not return UTC. It gave me my system time, ie the wrong time.

I'm probably going to use an online timeapi to get accurate UTC. That however requires me to be connected to the internet.

**Comment by mendhak** [comment]
If possible can you show me some of the erroneous logs with the bad times in them?  If you don't want to upload here, email to gpslogger at mendhak.com
