### ISSUE TITLE
Show the time with seconds of the last point logged on the detailed view screen

### ISSUE THREAD

**Issue by Yarrago** [mendhak/gpslogger#421]
Firstly thanks for all of the hard work, this is a really awesome application and you keep adding more useful features to it like the profiles that were added recently.

The time of the last location recorded used to be shown on the detailed view screen (e.g. hh:mm:ss), however in one of the recent updates it seems to have been removed. I used to use the time displayed here to synchronise my cameras time with the GPS time. It would be nice to have it on the simple view as well but I can understand that you might not want to clutter that interface.

Explicitly:
1) Start logging using GPS.
2) Wait for a lock and observe the time displayed on the detailed view screen.
3) Set the time on the camera to match the time displayed so that the time was synchronised.

One possible improvement over the previous implementation (for me anyway) would be to have the display so that it was shown as "hh:mm:ss (x seconds ago)" and track the number of seconds since the point was captured using the local time. Explicitly hh:mm:ss is the time of the last point taken from the location provider (gps), x seconds = local_time_when_the_last_point_was_taken - local_time_now. I know that this specific feature is tied tightly to the usecase that I have and might not suit others, but I could imagine that a fair few people would want to syncronise the GPS time with other things that they are logging and so might be a useful improvement to help people syncronise the time accurately.

Thanks,
Yarrago

**Comment by mendhak** [comment]
I think the time not appearing is a mistake, I'll try to add this back in.  Not sure how I missed it. 

The other bit, a friendly "x minutes ago" type display would require changing the UI frequently, a nice to have but cycles that can let the user be doing other things instead.

**Comment by mendhak** [comment]
v78 released to market, should show up in a few hours.
