### ISSUE TITLE
Suggested Feature: Add Version Number To Filename

### ISSUE THREAD

**Issue by Yarrago** [mendhak/gpslogger#422]
I've always thought that it would be really handy if you had an option that allowed you to automatically add the app version number to the file name. This would mean that if a bug were found or the log format was changed you would know which files were effected.

**Comment by mendhak** [comment]
Nice idea, simple to do as well

**Comment by Yarrago** [comment]
Hey thanks for implementing that so quickly!

**Comment by mendhak** [comment]
v75 released to market.
