### ISSUE TITLE
Feature request: detect if GPS is already in use

### ISSUE THREAD

**Issue by tajtiattila** [mendhak/gpslogger#424]
I would like to use different settings when the GPS is already turned on by another app like navigation or city guide. Normally I prefer to have GPS tracker enabled at all times with a relatively high time filter like 10-15 minutes with an absolute timeout of 60 seconds, so it doesn't drain my battery too much. But when the GPS is in use anyway, I'd like it to log track points every minute or so.

Perhaps a secondary set of settings would work if there is no way to detect when a GPS fix is available without actively asking for it: I would set my time filter to 1 minute and the absolute timeout to 1-2 seconds.

**Comment by mendhak** [comment]
I think you might be looking for the 'passive' listener.  Go to Performance, then under listeners/providers, the third checkbox is passive.  This should get any locations captured by other apps.  It's not 100% reliable I've seen, but it does give points ocassionally.

**Comment by tajtiattila** [comment]
Thank you, I will try the passive listener on my Nexus 4.

What is your opinion on the second aspect of my request, to have GPS Logger log track points more frequently than the default when passive data is available? That would let me use the app in a fire-and-forget mode.

Otherwise there is little point in using passive mode only. I would have to change the time setting (frequency of track points) when I know I'll be navigating or geocaching anyway, and not forget to change it back to battery friendly mode when I'm finished with it. Passive mode would not help here, because the GPS would be in use anyway in the other app, therefore GPS Logger could just use this data anyway.

**Comment by mendhak** [comment]
Since that's quite specific to your workflow, in these cases I usually recommend looking at automation apps like Tasker or Llama.  These apps can send intents to GPSLogger based on certain situations (like maps being open) and you could for example set the logging interval to a certain value then start logging. 

http://code.mendhak.com/gpslogger/#18

**Comment by tajtiattila** [comment]
I give Tasker a try with an application context. I select my map apps and use the settimebeforelogging extra to change the logging frequency. Kudos to you: testing the effects of the tasks is visible on the detailed view of GPS Logger.
