### ISSUE TITLE
Feature-Request: Android Wear Support

### ISSUE THREAD

**Issue by Bapf** [mendhak/gpslogger#425]
It would be great if there was a possibility to trigger to logging of single points from Android wear devices.

**Comment by mendhak** [comment]
I liked this idea so I played around a bit.  Documentation around Android Wear is really bad!

Getting basic communication between wear and the handheld device was alright but implementing single-point functionality is not that simple.  So I've opted for a simpler approach - just start or stop from the wear device. 

If you're up for some testing, APK is here:

[APK download](https://www.dropbox.com/s/gcsg5xwlc8cjkvn/gpslogger-75-wear.apk?dl=0)
[PGP sign](https://www.dropbox.com/s/ejg4nk90dtkn02w/gpslogger-75-wear.apk.asc?dl=0)
[SHA](https://www.dropbox.com/s/hlqou8rvc5w2m72/gpslogger-75-wear.apk.SHA256?dl=0)

Or you can just marvel at my amazing UI design skills:

![image](https://cloud.githubusercontent.com/assets/746276/14405019/77efe96a-fe7c-11e5-9bfd-c05ec882a260.png)

**Comment by Bapf** [comment]
Hi, 

first of all: Thx for considering the request.

One idea for an (perhaps simpler) approach: If it was possible to trigger the single point from the notification, it would be also possible to do it from an android watch without any additional effort, because the buttons from the notification are automatically available on the watch also. The only problem with this approach: Permanent notifications never are shown on Android Wear ...

So, off to testing the new apk. :)

Bapf
-- 
"Quis custodiet ipsos custodes?"

**Comment by Bapf** [comment]
So, I tested it for about two days now and it works quite fine.

For my usecase (having the normal log on a quite big interval [e.g. 10
minutes] to spare battery life but to be able to quickly tag important points
in between if needed) I have to "klick" the watch twice (once to stop and once
to start to trigger a point where I'm at this moment) but that's more than
ok. (And if I get tired of it I can always take a look at tasker for wear and
automate the two actions into one. ;)

So ... a big thanks!

Greetings from Munich, Bapf

On Sat, Apr 09, 2016 at 09:57:50AM -0700, mendhak wrote:
> I liked this idea so I played around a bit.  Documentation around Android Wear is really bad!
> 
> Getting basic communication between wear and the handheld device was alright but implementing single-point functionality is not that simple.  So I've opted for a simpler approach - just start or stop from the wear device. 
> 
> If you're up for some testing, APK is here:
> 
> [APK download](https://www.dropbox.com/s/gcsg5xwlc8cjkvn/gpslogger-75-wear.apk?dl=0)
> [PGP sign](https://www.dropbox.com/s/ejg4nk90dtkn02w/gpslogger-75-wear.apk.asc?dl=0)
> [SHA](https://www.dropbox.com/s/hlqou8rvc5w2m72/gpslogger-75-wear.apk.SHA256?dl=0)
> 
> Or you can just marvel at my amazing UI design skills:
> 
> ![image](https://cloud.githubusercontent.com/assets/746276/14405019/77efe96a-fe7c-11e5-9bfd-c05ec882a260.png)
> 
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mendhak/gpslogger/issues/425#issuecomment-207817826

-- 
"Quis custodiet ipsos custodes?"

**Comment by mendhak** [comment]
v75 released to market.
