### ISSUE TITLE
NETWORK position without DATA CONNECTION : Absolute timeout reached, giving up on this point

### ISSUE THREAD

**Issue by donsurgifhub** [mendhak/gpslogger#426]
Hi ! The app does exactly what I need and I like it very much, but I have a problem with the NETWORK mode (no GPS, no PASSIVE).
In fact the program isn't able to get the position if the 3G DATA CONNECTION is off.

I think that the DATA CONNECTION is not necessary to get the position of the cellular towers, in fact other programs (for example Google Map) can locate me even without data connection.

But GpsLogger doesn't? Why?
Cany you help me?

So it appears the message : "Absolute timeout reached, giving up on this point". 

I'm using "NETWORK" mode, because it is enough for me : I just want to have an approximate position log.
The parameters I use are : freq. :120, minimum distance filter:5m; gpx.

I would like to keep the data connection off to save battery.

Thanks very much !!!

Thanks in advance!!

**Comment by mendhak** [comment]
Google Map uses a fused location provider.  The fused location provider in turn uses wifi based positioning as well as GPS as well as Network (it automatically decides).  This app doesn't use [FusedLocationProvider](http://developer.android.com/training/location/receive-location-updates.html) which is on a wish-todo list for when I have time.   However note that wifi based location is only for urban areas, once you're outside cities then you need GPS or network.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
