### ISSUE TITLE
v75 bug with WAYPOINT in the GPX file

### ISSUE THREAD

**Issue by donsurgifhub** [mendhak/gpslogger#431]
The v.15 version has a bug. When the app starts logging, the word "time" is broken by other code after the indication of : " gpx.xsd"
I did the following operation : I started the app, and after few seconds I tried to note a location named "test".
It happens in the GPX file. 

<time>2016-04-18T08:17:15Z</ti

me>

``<?xml version="1.0" encoding="UTF-8" ?><gpx version="1.0" creator="GPSLogger 75 - http://gpslogger.mendhak.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
<time>2016-04-18T08:17:15Z</ti
<wpt lat="41.8502596" lon="12.4938261"><time>2016-04-18T08:17:15Z</time><name>test</name><src>network</src></wpt>
me>
<trk><trkseg><trkpt lat="45.8502596" lon="15.4938261"><time>2016-04-18T08:17:15Z</time><src>network</src></trkpt>
</trkseg></trk></gpx>``

**Comment by mendhak** [comment]
I'll have a look first thing tonight.  Not sure how this escaped testing :fearful:

**Comment by mendhak** [comment]
Bet it's [this](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L109) - needs to be increased by 3

**Comment by mendhak** [comment]
v76 published to market, should show up in a few hours.  Sorry.

**Comment by donsurgifhub** [comment]
Thanks very much !!!

Date: Mon, 18 Apr 2016 09:42:21 -0700
