### ISSUE TITLE
Manual recording only?

### ISSUE THREAD

**Issue by christopherpm** [mendhak/gpslogger#432]
Would it be possible to make it so that instead of recording at scheduled time or distance intervals, my position is logged ONLY when I press an on screen button?

**Comment by mendhak** [comment]
Hello, do you mean the `1` button?  That should log once and then stop.

**Comment by christopherpm** [comment]
Yes – what I want to do is walk a particular marathon course, and at places where I have to put signs, I want to press the button to drop a marker on the map (perhaps even with an option to put a note with the marker)

Thanks
Chris

**Comment by mendhak** [comment]
While the app isn't logging, you can press 1 - it'll just log one point.  Or you can press the pencil icon it'll ask for a note, log the point and stop logging.
