### ISSUE TITLE
Log one point while logging is active

### ISSUE THREAD

**Issue by tajtiattila** [mendhak/gpslogger#433]
I've noticed the "Log one point" button is disabled while logging is active. It seems logical not to log single point while a track is being generated anyway, but I have GPSLogger active all the time with a relatively high setting for "time before logging" and would occasionally like to log single points if possible.

I think "Log one point" should also work when logging is active, either work independent of the current track, or just add a new track point to the current track disregarding the time and distance filters (apart from absolute timeout of course).

**Comment by mendhak** [comment]
I think what you are describing fits the annotate use case - the pencil icon.  If you tap that then enter something (even a space) it will start logging to get that one point then resume silence.  You will need to enter something though, even a space.
