### ISSUE TITLE
Bug: gpx file saved when specifying plain text

### ISSUE THREAD

**Issue by giacecco** [mendhak/gpslogger#434]
I'm using GPSLogger version 76, configured to upload the data using plain text files to Google Drive. This works nicely, but I always find a gpx file, too, in the specified folder. The file is almost empty, e.g.

```
<?xml version="1.0" encoding="UTF-8" ?><gpx version="1.0" creator="GPSLogger 76 - http://gpslogger.mendhak.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd"><time>2016-04-29T13:14:03Z</time><trk><trkseg><trkpt lat="[REMOVED]" lon="[REMOVED]"><time>2016-04-29T13:14:03Z</time><src>network</src></trkpt>
</trkseg></trk></gpx>
```

Is this perhaps because GPSLogger started logging _before_ I switched setting from the default gpx to plain text?

**Comment by mendhak** [comment]
That's the only explanation I can think of - if GPX isn't checked, GPX won't be written to.  

During upload, if a filename is 'something' then the uploader will upload all the extensions with 'something'.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
