### ISSUE TITLE
"GPS Started/Stopped" for several hours

### ISSUE THREAD

**Issue by giacecco** [mendhak/gpslogger#435]
Hi All, running GPSLogger on a Nexus 6p running the latest stock Android 6.x. I keep GPSLogger always running, but this morning I found a series of

```
xx:xx Requesting GPS location updates
xx:xx Requesting cell and wifi location updates
xx:xx GPS Started, waiting for fix
xx:xx Stopped
```

... messages in the log view that go from 0:25 to about 10:14 this morning when I checked the application myself and it "woke up" from whatever status it was in. Any suggestion of what could have happened? Thanks.

**Comment by mendhak** [comment]
This is the wonderful [Android Doze](http://www.androidcentral.com/inside-marshmallow-what-doze-how-do-i-use-it-and-what-does-it-do) mode at work.  I think you can go into the phone settings and set GPSLogger as a 'battery unoptimized' app and it should be a little less subject to doze, but it'll *still* be put to sleep regardless at some point of inactivity.   Also I believe that if I prompt the user to do this, my app will be banned from the Play store.

**Comment by giacecco** [comment]
I know about "Doze", thanks, you are probably right, I've bumped in other applications having problems with it, e.g. TuneIn Radio stuttering live radio streams when I am walking, and working nicely when I am running instead (!). 

I could not find in the phone settings the option you described, though. In Settings > Apps > GPSLogger > Battery I see a "Adjust power use" section with two options: "Stop or uninstall the app" and "Select battery-saving mode". Neither appears to be what you're referring to. Any more suggestions?

**Comment by mendhak** [comment]
Try this:  http://www.greenbot.com/article/2993199/android/how-to-turn-off-doze-mode-for-specific-apps-in-android-marshmallow.html

Settings > Battery > Optimizations

I've had a few background music apps also blank out for a bit until I shake the phone or unlock it.  I think you can avoid doze mode if the phone is connected to a charger.

**Comment by giacecco** [comment]
I found the option to set GPSLogger as "not optimised", thanks. However something is also killing the app every night, or it quits by itself, even after that setting. Any ideas?

**Comment by AndreasBaer** [comment]
I have this issue too. Oneplus one with 6.0.1 / cm13 stable. Disabling battery optimization did not help. I switched from the app geotag photos, because it keeps the phone awake all the time, but maybe that is the price for the app not to be killed?

Isn't there a workaround like auto restarting the app every few hours, or bringig up a new notification from time to time? I really love this app besides this problem :(

**Comment by giacecco** [comment]
@AndreasBaer a workaround I am using at the moment is restarting GPSLogger by using [Tasker](http://tasker.dinglisch.net/), however I have not yet tested that Tasker itself is not killed by Android during the night :-) Stay tuned.

**Comment by AtomicStryker** [comment]
It has to be possible to keep the device awake during logging, any audioplayer is doing it. Incidentally, running an audio player while logging will probably fix the issue (yes at some battery cost).

**Comment by mendhak** [comment]
The docs are very badly written and I struggle to find information on this.  I have been looking at the proper way to not be affected.   From a [comment here](https://plus.google.com/+AndroidDevelopers/posts/94jCkmG4jff) and [the docs](https://developer.android.com/intl/in/training/monitoring-device-state/doze-standby.html) - Music apps should be fine as they are foreground apps and they show a notification.  I show a notification, *but* I use AlarmManagers as well.  So this may be that I have to change the foreground service to manage its own timers which is a very... big change. 


> The app has a process currently in the foreground (either as an activity or foreground service, or in use by another activity or foreground service).
> The app generates a notification that users see on the lock screen or in the notification tray.


But then I feel it is [contradicted here](http://stackoverflow.com/questions/33018306/doze-mode-and-foreground-service) and in that G+ comments thread.  Are you able to play music for up to two hours without touching the phone and without charging?  I cannot - I'm on OPO+CM13.1 and my music sometimes stops so I don't have consistent behavior. 




The phone shouldn't go into doze mode if you're charging, so if at night you have it plugged in it might be useful.  But then that is not always possible.  I'd be interested to know if Tasker is able to deal with this. Or if there's another way to deal with this.

**Comment by AtomicStryker** [comment]
Well, no, i haven't ever had any audio playing for longer than 30 minutes. However, i am using Naptime which attempts to "doze" the phone immediatly upon screen switch off, which does in fact kill your gpslogger. Only "nudging" the phone (display powers up, clock shows) results in a gps log being taken. Very problematic. Can't you look at how existing apps do it? Google Play is likely the ultimate vanilla solution. And no, it does not jitter or stop even when my phone is still. Running "stock" 6.0.1 with xposed, root, naptime.

**Comment by giacecco** [comment]
This will be interesting to @mendhak : tonight I got both [Tasker](http://tasker.dinglisch.net/) and GPSLogger running overnight, but only Tasker "survived", so either 

- GPS Logger actually fails for some reason and shuts down by itself, and it's not an Android power management issue, or 
- GPSLogger is working, but is not doing something to prevent Android 6's power management to kill it, the same something that allows Tasker not to be shut down instead. 

I had configured both apps as ["not battery optimised"](http://www.greenbot.com/article/2993199/android/how-to-turn-off-doze-mode-for-specific-apps-in-android-marshmallow.html).

Tasker is not open source, but it looks like it has a very active community around it. Someone may know what the missing magic is.

**Comment by AtomicStryker** [comment]
Well, 2 questions:
Can Tasker drag the phone out of doze mode?
Can Tasker tell if GPSLogger is enabled or not? I have read up a little on Intents, but "com.mendhak.gpslogger.common.events.CommandEvents.RequestStartStop" is not sent out, apparently

**Comment by mendhak** [comment]
I've played around a bit with the alarm managers and it's still not great (doze hates GPS). However in my testing it would manage to log a few points, just enough.  But I'm sure mileage will vary.

Anyway if you want to try it out, I've made an [APK](https://www.dropbox.com/s/ksurg1urr98qto2/gpslogger-76-issue435.apk?dl=0) ([sig](https://www.dropbox.com/s/cw8fzpwnah0lnao/gpslogger-76-issue435.apk.asc?dl=0)/[hash](https://www.dropbox.com/s/uqy47fjga3kwyq2/gpslogger-76-issue435.apk.SHA256?dl=0))

I'll probably release this anyway as almost nothing is better than nothing.  :crying_cat_face:

**Comment by giacecco** [comment]
@mendhak I did not change anything of my mobile, but since yesterday I stopped finding GPS Logger stopped in the morning, so it looks like perhaps the problem was solved already in the public version of GPS Logger distributed through the Play Store. Is that correct?

**Comment by mendhak** [comment]
Ah no, the dying is likely a coincidence or [another issue](https://github.com/mendhak/gpslogger/issues/442).

**Comment by mendhak** [comment]
v77 is in releases and has been published to market, it should show up in a few hours.

The 'dying' issue is also included, it should address some of the disappearances, overall better stability assuming it was the service being killed by the OS.

Note that doze mode will continue to be intermittent but you should see a few points overnight rather than zero points.
