### ISSUE TITLE
No new file is created until movement is recorded

### ISSUE THREAD

**Issue by giacecco** [mendhak/gpslogger#436]
I believe that, when a) creating a new file every day, b) uploading them to the cloud, and c) recording GPS location only when moving, it can happen that yesterday's last recordings are never uploaded until some movement is made today. 

This means that if - for example - I wanted to run some analytics scripts overnight over yesterday's recordings, I can't until I move today.

The easy solution to this is to force any upload in the early minutes of a new day, whether movement is recorded or not.

**Comment by mendhak** [comment]
Are you using the upload frequency, for example upload every 60 minutes?
