### ISSUE TITLE
Feature req: option to use local time for timestamps instead of UTC

### ISSUE THREAD

**Issue by giacecco** [mendhak/gpslogger#437]
It's all in the title. I'm in the UK where DST is in effect at the moment, so the logs are 1 hour behind the actual time. From a user perspective, the actual time is more significant than UTC. Of course different developers may have different opinions.

**Comment by mendhak** [comment]
The GPX/KML standard doesn't allow that - all times must be UTC without exception (I actually started with local times but it would keep failing validation for users using it with other software).  Instead the responsibility is with the processing software (GeoTagger, Lightroom, personal scripts, etc. to allow a timezone offset for the user).
