### ISSUE TITLE
CustomURLJob HTTPS Crash - Failed to read sufficient bytes from /dev/urandom

### ISSUE THREAD

**Issue by edwardmuel** [mendhak/gpslogger#438]
I just experienced a crash using HTTPS OpenGTS.

[debuglog.2016-05-03.trimmed.txt](https://github.com/mendhak/gpslogger/files/249898/debuglog.2016-05-03.trimmed.txt)

~10 points were logged before crashing. I have not yet tested your build with the background request limit.

It looks like this might be an issue with OkHttp. It doesn't look like there are any [reported issues on their GitHub](https://github.com/square/okhttp/issues?utf8=%E2%9C%93&q=urandom), but there is [at least one result on Google](https://www.google.com/search?q=%22Failed+to+read+sufficient+bytes+from+%2Fdev%2Furandom%22) (Direct link to related result: https://github.com/intercom/intercom-android/issues/127)

Are there any other HTTP clients available that might work better, or would it be easy to try/catch CustomURLJobs?

Slightly unrelated:
Is the app supposed to be constantly sending requests? In the total period of ~638 seconds from starting until the end of the log, `DEBUG CustomUrlJob.onRun:42 - Sending to URL: https://[SNIP]:443/gprmc/Data?[SNIP]` occurs 505 times (sometimes twice in one second) and there are 496 responses.
I was using the same settings found in [debuglog.2016-04-22.trimmed.txt](https://github.com/mendhak/gpslogger/files/233939/debuglog.2016-04-22.trimmed.txt)

**Comment by mendhak** [comment]
Are you using the APK posted here:  https://github.com/mendhak/gpslogger/issues/430

I think it's related - essentially there are a lot of concurrent requests being made (your 'slightly unrelated' is actually very related) and too many network requests simultaneously results in errors similar to #430 and likely this one too.

**Comment by edwardmuel** [comment]
I have not yet had a chance to try the APK posted there. I will try it next time I go for a hike/drive.

**Comment by mendhak** [comment]
v77 is in releases and has been published to market, it should show up in a few hours.
