### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by ray63** [mendhak/gpslogger#440]
Version 76 - 
When I enable debug logging, logs correctly saved to file.  If I disable logging, and then re-enable, further debug information does not appear to be saved.

Exiting the App didn't resolve, but rebooting phone did.

**Comment by mendhak** [comment]
I tried this a few times, not getting it and everything seems fine.  Are you doing anything to the file like deleting it manually in between, or viewing via a desktop computer over USB?

**Comment by ray63** [comment]
Thanks for looking into this.
Yes, I was definitely viewing on desktop via USB, since I could not find an easy way to view the log on the phone. (android novice)  Initially, I don't recall deleting the log file, but when it didn't seem to update, I probably did delete it, to see if it would recreate the file.

**Comment by mendhak** [comment]
I think this is to do with MTP - files written to the phone storage don't necessarily show up as updated right away.  Instead either you have to use the option to 'attach debug log to email' or use a file explorer like [Solid Explorer](https://play.google.com/store/apps/details?id=pl.solidexplorer2) to inspect it and move it elsewhere or try to [force a media scan](https://play.google.com/store/apps/details?id=com.gmail.jerickson314.sdscanner).
