### ISSUE TITLE
portable storage on marshmallow

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#441]
So I did a stupid thing and upgraded to marshmallow - as if I didn't know that each new android version brings new disasters. They rejigged SD card behaviour gain, I chose to use my card as portable storage as the alternative is formatting it and loosing everything, and now GPS logger cannot use it. Logging details->save to folder shows the path to /storage/extSdCard/... in red - quite understandable as it no longer exists, but won't let me change it: folder selection dialogue starts in /storage/emulated/0 which also no longer exists, shows the contents of /sdcard instead as far as I can see, won't let me change the folder up and go to /storage/<volume-id>/... where the card is now mounted, and there is no way to enter the path manually although I seem to remember that at some time it was possible. Can you restore the manual path entry? Or do something else to make it work with portable storage? Version 76.

Also something bad happened to the shortcuts/widgets: start and stop shortcuts which I placed on the desktop before the upgrade lost their names and are now both called GPSLogger although they retained their functionality, and widget list now holds only one shortcut for GPSLogger which is also called just GPSLogger instead of two for start and stop, don't know which one.

**Comment by mendhak** [comment]
This is a tough one.

I'm making a guess and this may or may not work. Connect it to your computer, place a file called 'gpslogger.properties' either in the 'inaccessible' directory or in `/sdcard` itself.  This file should contain

    gpslogger_folder=/storage/emulated/0/Android/data/com.mendhak.gpslogger/files

Open the GPSLogger app.  It should read that file and set a path.  Exit the app.  Reopen the app and see if that worked.  Remove the `gpslogger.properties` file afterwards.

Another way I can think of - connect the phone to your computer.  Copy your old log files off.  Then uninstall and reinstall GPSLogger which should clear its settings, you will lose any tweaks you made though.

**Comment by mendhak** [comment]
One more thing - when you ran the app for the first time on Marshmallow it should have prompted you for permissions.  This could happen if you denied it write permission.  Try to check by running logging again, it should prompt you unless you told it not to bother you again.

Go to phone settings > apps > gpslogger > permissions and have a look in the list there.

**Comment by lvmm** [comment]
Setting the path via /sdcard/gpslogger.properties did the trick - thanks.

And by the way, the problem with widget/shortcut names was a one-off bug caused by the upgrade. Deleting and re-creating the shortcuts restored proper names.
