### ISSUE TITLE
Retry time for accuracy filter/Absolute timeout problems

### ISSUE THREAD

**Issue by Tony-il-Capo** [mendhak/gpslogger#443]
Hi
I'm using GPS Logger to log GPS coordinates to my own server. This process works great.

I have set accuracy filter to 3m for not logging inaccurate GPS positions. Many times I see the app dropping points because it "says" (activity log screen) that accuracy has timed out, sometimes it happens right at the start of GPS Logging process, most of the times it's random during logging, but just after a couple of seconds after trying to get GPS position.

I still receive many GPS positions on my server, but also many are dropped supposedly because accuracy has timed out. I tried increasing values (120s/480s), but watching GPS Logger working (log screen) I still see it dropping GPS points just after a couple seconds of GPS searching

Shouldn't it wait for the defined timeout value, and then drop position?

**Comment by mendhak** [comment]
Can you show a screenshot(s) of what you mean? 

Also I am curious to know what phone you have, I didn't know any phone could get 3m accuracy with GPS which is very impressive

**Comment by Tony-il-Capo** [comment]
Phone is Sony Xperia S (aka Lt26i)
Screenshot of GPS Essentials - Accuracy test
![1](https://cloud.githubusercontent.com/assets/15948151/15405237/f7f879b0-1df8-11e6-8ee5-d5b92250a8ea.jpg)

Here's the problem I have:
Settings set:
- Accuracy Filter=3m
- Retry time interval for accuracy filter=240s (was 120s before, same problem)
- Absolute timeout=480s (was 240 before, same problem)

Took quite some time (more than  a minute to get the first lock (inside a building) and then getting the second point it says right away "Timeout Reached"!
![12](https://cloud.githubusercontent.com/assets/15948151/15405271/17389fda-1df9-11e6-8d97-dfef56c94a29.jpg)

Log Attached:
[debuglog.txt](https://github.com/mendhak/gpslogger/files/273237/debuglog.txt)

**Comment by mendhak** [comment]
The timeout wasn't being reset, so as soon as the next point fixing started, it would think that a long time had passed.  I've reset it when it finds a point now so it should be OK.

**Comment by Tony-il-Capo** [comment]
OK, many thanks.

**Comment by mendhak** [comment]
v77 is in releases and has been published to market, it should show up in a few hours.
