### ISSUE TITLE
Remove the notification

### ISSUE THREAD

**Issue by yLark** [mendhak/gpslogger#444]
Hey,
This app is awesome. I'm using it all day long in background.
Would it be possible to add an option to disable the notification and let the app to work silently in background?

**Comment by mendhak** [comment]
Hello, the notification exists specifically to allow the app work in the background. Else it gets killed. 

See:  http://code.mendhak.com/gpslogger/#4

**Comment by yLark** [comment]
Sorry for not reading all the FAQ.
So the only option is to uncheck "show notification" in the app property, in the app manager.

**Comment by mendhak** [comment]
Yes, via the app manager.  Note that if you do that, the Android OS is more likely to kill the app so any background logging can 'abruptly' stop.
