### ISSUE TITLE
widget names change spontaneously in android 6.0

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#445]
Since the upgrade to marshmallow 'Start' and 'Stop' widget names change to 'GPSLogger' after each reboot, also after GPSLogger has been upgraded. Not sure if the problem is with android or GPSLogger

**Comment by mendhak** [comment]
What launcher? The shortcuts (widgets)  only have a single label against them, so I'd imagine it's something about the way it's rendering it.   

I tried against Nova Launcher, and the shortcut name is preserved as 'start' or 'stop'

**Comment by lvmm** [comment]
Yes, looks like it is a launcher issue (touchwiz), cannot reproduce it with google now.
