### ISSUE TITLE
Permissions not allowed

### ISSUE THREAD

**Issue by g8dhe** [mendhak/gpslogger#451]
Just installed this on a Nexus 5 running Android 6.0.1, installs fine, but will not allow me to tap "Allow" for either location or media access, only "Deny" both buttons are shown green.  Hence unable to use at all.
Have this installed on several other devices with no problems, so I can only assume its a device/OS problem ?

**Comment by mendhak** [comment]
I've got the same setup - N5 and Android 6.0.1 - so it shouldn't be any such problem. 

Might be related to this - https://code.google.com/p/android/issues/detail?id=213120

Until they release an OS update you can try giving the permissions explicitly: https://code.google.com/p/android/issues/detail?id=213120#c28

**Comment by g8dhe** [comment]
Yes it would seem to be that problem I am updated to 1 June 2016 patch, and manually setting the permissions has resolved the problem!
Thanks very much indeed for the rapid response as well!
