### ISSUE TITLE
create accuracy range check

### ISSUE THREAD

**Issue by jlmalet** [mendhak/gpslogger#453]
hello
it would be really great to create an accuracy range check : 
for example I want my GPSlogger to log each 15s, with a target accuracy range of 4m but I accept to have an accuracy of 15m if nothing better obtained in the accuracy timeout

some chronogram : 
|sleep-----------|wakeup-----|first fix|try to reach accuracy------|accuracy reached|sleep---------|
|sleep-----------|wakeup-----|first fix|try to reach accuracy-----------|timeout|sleep--------|

if target accuracy is reached, log the point and exit
if the target accuracy timeout, il there is a point below the "max acceptable accuracy" then log it (choose the point with the best accuracy)

thanks and regards

**Comment by mendhak** [comment]
My understanding is - when logging a point, keep logging until `accuracy timeout` is reached and pretty much picking the best point that falls within the range (unless target accuracy is reached first).

Will need to play around to have a look at how complex this makes the accuracy logic.

**Comment by jlmalet** [comment]
yes, the way you rephrase it seems to fit what I was meaning

**Comment by bjohas** [comment]
So the suggestion is this: When accuracy timeout is reached, log whatever point you have (rather than not logging anything). That would be good.

**Comment by jlmalet** [comment]
Well in a way yes, but the point with the best accuracy would be better...
thanks and regards!

**Comment by mherrmann3** [comment]
Great Idea! I would appreciate such a feature A LOT! (This would save me from using multiple profiles with different Accuracy Filters).

FYI: The same feature is also suggested by issue #591, where @thinrope also proposes a code suggestion: https://github.com/mendhak/gpslogger/issues/591#issuecomment-413028810.

Another approach is suggested by #654: after reaching Accuracy Filter, try to improve the accuracy for some X seconds. This behavior could also be understood as: set a minimum desired accuracy, with the possibility of improving it. Hence, it leads to a more restrictive logging than proposed here (#453) or in #591.

**Comment by khimaros** [comment]
sorry for the "me too", but i would also really appreciate this feature!

**Comment by mendhak** [comment]
I've been working on an accuracy option, description and test APK here: https://github.com/mendhak/gpslogger/issues/654#issuecomment-1973452236

**Comment by mendhak** [comment]
v130 is now on FDroid and the releases. 

The new option uses the time period to pick the best location it can find. I didn't want to make it complicated by having a range, as there is already a lot going on in there.  This should help with jumpy lines and make things smoother at the expense of time. So you'll probably want to experiment here, eg, don't make the duration too long, maybe 5-10s will give it a better chance of getting a good point. 

![image](https://github.com/mendhak/gpslogger/assets/746276/25e434fc-c4af-4c0c-9c30-17447ac8ceaa)

**Comment by khimaros** [comment]
@mendhak thank you so much for implementing this. i've been using it today and it's working very well.

one thing i noticed is that the next log is not scheduled until after the first one is logged, which results in an entry every (logging interval + accuracy duration) instead of just (logging interval).
