### ISSUE TITLE
be able to write logs to sdcard

### ISSUE THREAD

**Issue by jlmalet** [mendhak/gpslogger#456]
Hi
on android 6.0+ you have to request access to be able to write on sdcard... it would be great to be able to save data on a shared folder to share it amongst all gps applications
thanks and regards

**Comment by mendhak** [comment]
(Sorry late reply.  As usual :stuck_out_tongue: )

Are you currently being prevented from writing to SD card?  The app is already requesting permissions to write to external storage, so this should work.  If you go to the logging settings and try the folder browser and it should let you go up up to other folders.

**Comment by jlmalet** [comment]
you're welcome
even activating storage permission don't allow me to go outside internal
storage... other app do use some kind of "select sdcard" method (see xplore
app for example) to gain sdcard acces
thanks and regards

**Comment by mendhak** [comment]
In release v80, I changed the folder picker, this should now allow going to SD card and writing.  Sorry forgot to update this thread.
