### ISSUE TITLE
HDOP, VDOP, ageOfDGPS, DGPSId not working with Bluetooth GPS

### ISSUE THREAD

**Issue by stewartbholt** [mendhak/gpslogger#457]
I have been looking for an Android app which records the parameters introduced in version 79:  HDOP, PDOP, VDOP, dgpsid, ageofdgps, geoid height. These are very important for doing critical mapping work and the recent update makes this application very attractive where you need to verify accuracy.
Has anyone checked the above parameters when using a Bluetooth provider? I am using Bluetooth GPS by GG MobLab to connect a SXBlue II GPS to my Android tablet as a mock provider. GPS Logger seems to work in all respects except getting these new items.  Using the NMEA screen in Bluetooth GPS, I see  the sentences $GPGGA and $GPGSA with the correct data in them. When using GPS Logger with the tablet's GPS, I do get the parameters except those related to DGPS. I would be glad to help debug, if there is any diagnostic output available. The Log View only shows Filename and Location. I do not have the development environment setup. I realize the problem may well be in the Bluetooth GPS app. I have also tried Bluetooth GPS Provider by mobile-j.de but it didn't seem to work at all. If anyone is using a Bluetooth connected GPS, what Bluetooth connector app are you using?

Thanks

**Comment by mendhak** [comment]
I've definitely heard of users using external GPS devices, it's just not something I've ever tested as I have no devices.

You can try enabling debug log in the general settings.  Then try connecting again - the debug log should show a little bit more information than the others. 

You can also try enabling GPX as well as NMEA log files to see if one of them is populated over the others.  If it's raw NMEA strings being sent to the phone that may explain why the CSV/GPX aren't being populated.

**Comment by mendhak** [comment]
Have you had any luck with this?

**Comment by stewartbholt** [comment]
I think the problem is that the Bluetooth Apps do not populate these in the
location object. I found an app, Ultra GPS Logger, which connects directly
to  BT GPS and  logs NMEA sentences. I wrote a program to extract the data
in several formats. Thanks for following up.
