### ISSUE TITLE
not autologging initially

### ISSUE THREAD

**Issue by abhi-84** [mendhak/gpslogger#458]
Hi
I m using this app on my android phone and trying to log coordinates on dropbox. it does the job but on every start, i need to select the file to be uploaded, authorise dropbox access, upload appropriate file and later auto-update happens.
Is there any way by which when I open app in my phone, it automatically select file of today's data and start logging coordinates there without need of file selection. 
This would automate the process and normal user would not be struggling to upload the correct file.

See that in case, it could be implemented so please do that. Thank you !

**Comment by mendhak** [comment]
I'm not sure I understand what you're saying.  Are you saying you need to re-authorize DropBox every time you open the app?

**Comment by abhi-84** [comment]
Thank you for replying

Yes sir. I have to re-authorize when I start logging for the very first time in a day. later in the same day, when I open app, it can connect and update dropbox well. What I am actually interested is that the moment I open my the app, it should start connecting to dropbox and filename of the very date should get updated in dropbox. I should not authorise every time dropbox and select for auto-send. It would be of great help if this could be implemented. 
One more thing I need to ask. I believe that this app is open source so can I use the name and functionality of your app in my research work (with due credits to you) so that it does not violate any copyright issues.

**Comment by mendhak** [comment]
It sounds like something is clearing your application settings; normally once you've authorized DropBox, the authorization stays.  I wonder if you have some aggressive task or cache cleaners.  Or are you perhaps low on storage space?


Yes you can use whatever parts of the application, code, etc. as it pleases you.
