### ISSUE TITLE
Switch off GPS module after each save-to-file (and back ON 10 sec before next logg.) for intervals 10+ mins - for looong yachting!

### ISSUE THREAD

**Issue by Overtonesinger** [mendhak/gpslogger#461]
Please, consider adding this **feature**.

This will enable extremely **long** battery life, especially for those phones with 5000+ mAh battery.

This feature will enable probably _all the users from the yachting community_ to do GPS logging during their _long_ sails. Even if they have just normal old smartphone and just ONE 10 000 mAh powerbank.

Think about the possible future:
 All those many and _many_ **excited and HAPPY** smiling users from the world of yachting! :-)

**Comment by manu09** [comment]
I would also like to see such option. I'm using this app for **quantified self** tracking, thus I don't need that much points but a long lasting battery. I think it is already possible with tasker to toggle gps and send an intention to gps logger. But I would prefer an option in the app itself as well!

**Comment by bjohas** [comment]
Unless I misunderstand, this is already possible, see
http://code.mendhak.com/gpslogger/
and look at
- Time before logging - How long to wait after a point has been logged to try logging again.
- Keep GPS on between fixes - Normally, the app stops using GPS between points, to save battery. This means when it's time to log the next point, the GPS needs to be 'woken up' again and this takes a little time. Keeping GPS on between fixes causes this 'wake up' time to be reduced.

**Comment by mendhak** [comment]
Gaah why did I miss this thread.  Yes it's as bjohas pointed out, this is already there. The GPS *requests* are turned off for 10 minutes and the GPS is not kept on.  You just need to set the time interval to 10 minutes or whatever you'd like, by default the app won't keep GPS on.
