### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Tony-il-Capo** [mendhak/gpslogger#465]
Hi
I have some suggestions for you:

- I think a dark theme would be nice to have, across menus and main interface

- Could you possible do a "light" version where you would remove all proprietary libraries used in getting network location, those used when sending data using various services and leave it to a bare minimum?
Many people I know and myself use this app to log gps data to our own server, so we don't need any of other logging methods, also we don't need network location.

- This light version would have only these features: get gps signal; send data to custom url plus the time between logs, accuracy filter, distance filter, absolute timeout...

- After successfully  removed all proprietary libraries then you could put this "light" version on F-Droid

At least think about it ;)
Thanks.

**Comment by mendhak** [comment]
I've wanted a dark theme too, or at least give options to switch.  My UI skills, as you'll have noticed, aren't very good so I'm hoping for a contribution in themes/styles XML to accomplish this. 

I've also had requests for lighter/focused versions, the problem there becomes maintenance; on each release I'd have to ensure the multiple versions aren't breaking or deviating in some way.

**Comment by Tony-il-Capo** [comment]
I would help, but I'm afraid I don't have the skills and specially free time. :(

As for the lighter version, I understand this would bring more work, but when you feel like you want to add/change features or optimize current app, I would suggest you go try to do this light version instead.

Of course don't feel obligated.
