### ISSUE TITLE
Google Drive -- autosend creates multiple copies of the same folder

### ISSUE THREAD

**Issue by TheGeographer** [mendhak/gpslogger#466]
I'm not sure if this is by design, but gpslogger is creating a new folder "GPSLogger for Android" in Google Drive each time I use it. Each folder has a single zipped gpx file. This is making a bit of a mess of my Google Drive and makes combining and extracting the gpx files more difficult.

I'd prefer for GPSLogger to identify the existing "GPSLogger for Android" folder (or whatever's been specified), and append zipped gpx files to that single folder.

Thanks for all work everyone's done on this incredibly useful tool.

Eric

**Comment by mendhak** [comment]
Definitely not by design.  Are you moving the folders about, changing permissions on them...  or revoking authentication on your phone somehow?  The only time a new folder is created is if its permissions have been revoked.

**Comment by TheGeographer** [comment]
I don't believe I'm doing any of those things. Definitely not moving folders or changing permissions.  When I review apps connected to my Google Drive account (https://security.google.com/settings/security/permissions), I see (and have seen) that GPSLogger for Android "Has access to Google Drive." I've never revoked that permission since granting it.

Details -- using a Nexus 5X on Android 7.0 with latest version (v79) of app.

Let me know if I can do anything to help debug this issue.

Thanks,

Eric

**Comment by mendhak** [comment]
Hmm, worth trying revoking then.  Back in the Google Drive preference screen you should be able to revoke.  Then re-authenticate and try a few test uploads.  

While doing this you can also enable debug logging in general settings and it should record any problems that occurred during this testing.  Be sure to turn it off afterwards
