### ISSUE TITLE
"gps is temporarily unavailable"

### ISSUE THREAD

**Issue by bjohas** [mendhak/gpslogger#470]
In the log view, I sometimes get "gps is temporarily unavailable". This seems to be after a successful log (GPS started / L,L / Filename / gps is temporarily unavailable). Does this matter?

**Comment by mendhak** [comment]
It doesn't matter, it's more of an event occurring OS side where it turns the GPS off for a while until needed again (so it's more debug/diagnostic).

**Comment by Tony-il-Capo** [comment]
I seem to get "gps is temporarily unavailable" but current point don't get logged, only this exact message at specific time.
From what I remember I saw that the last point logged was 2 min before this message (log interval) and next log 2 min after (4 min between logs, missed one).
Is OS 'blocking' gps?
It seems OK on other apps right after this.

**Comment by mendhak** [comment]
That usually appears right after it's given up - so at the 2 minute mark it may have tried, stopped, then shown that message - the 'failure' to log could be inaccuracy or simply failing to find a fix or a timeout.  In any case it's uncontrollable and entirely up to the OS, see: http://stackoverflow.com/questions/5213815/android-locationprovider-takes-too-long-to-become-temporarily-unavailable
