### ISSUE TITLE
Suggestions for renaming of options

### ISSUE THREAD

**Issue by bjohas** [mendhak/gpslogger#471]
I would suggest renaming the following options:

**Time before logging -> Logging interval.** "Time before logging" suggested to me that there would be some time before the first log.

**Retry time interval for accuracy -> Duration to improve accuracy.** "Retry time interval" suggests several events, rather than a duration.

**Absolute timeout -> Time to (initial) GPS fix.** "Absolute timeout" suggested to me that this would be for the whole operation (initial fix + improved accuracy).

**Comment by mendhak** [comment]
So simple but this makes so much more sense.  Thanks will do this

**Comment by mendhak** [comment]
v80 released to market
