### ISSUE TITLE
Feature request: upload session summary

### ISSUE THREAD

**Issue by matteobrusa** [mendhak/gpslogger#474]
I'd like to upload the session summary (start and stop coordinates, distance, duration) into a Google drive spreadsheet. 
I understand this is not currently possible; any suggestion?

Cheers!

**Comment by mendhak** [comment]
Should be easy to do it yourself:  Log to plain text (CSV) and upload that to Google Drive.  Google spreadsheets should work fine with CSV but you'll have to apply your own formulas to extract the information. 

Start stop coordinates - first and last lines
Duration - subtract times
Distance - OK, this is the complicated one, search for Haversine Formula with Google Spreadsheets and you should find something you can apply
