### ISSUE TITLE
Receive intent from Automate

### ISSUE THREAD

**Issue by flipside555** [mendhak/gpslogger#475]
I'd like to switch profiles using Automate. This is the relevant documentation http://llamalab.com/automate/doc/block/broadcast_send.html   Attached is a screenshot of the associated screen in the app. The Receiver Field class has to be filled in using a picker. The two classes it offers are 

1. com.mendhak.gpslogger.senders.AlarmReceiver
2. com.mendhak.gpslogger.StartupReceiver

The Extras field is free format. It need a dictionary. I've tried various combinations for these two fields without success. 
![automategpslogger](https://cloud.githubusercontent.com/assets/6238085/20060090/bbab4aa4-a4f9-11e6-851d-cf4e06b8d0db.png)

**Comment by mendhak** [comment]
Ok after a lot of trying I think I've got it. This broadcast class seems to indicate it can also send intents but I don't think the documentation is correct.  Broadcasts are something else... 

Instead I used Start Service, extras as you've shown.  Service class is the GpsLoggingService.

I've exported a `.flo` file but no idea what's in it, it seems to be binary.  Hopefully it contains the service start!


https://dl.dropboxusercontent.com/u/51905631/switchprofile.flo
