### ISSUE TITLE
Feature request: show coordinates in DD.mmmm or DD.mm.ss

### ISSUE THREAD

**Issue by tohis** [mendhak/gpslogger#476]
Hi,
There are at least 3 common ways to show GPS coordinates. The only way the GPSLogger is currently displaying them is decimal degrees: **DD.dddddd°**
I'm kindly requesting the options to display coordinates in degrees and minutes (**DD°mm.mmmm'**), and in degrees, minutes and seconds (**DD°mm'ss.ss"**).
For example **62.505621°** would then be shown as **62° 30.3373'** or **62° 30' 20.24"**, respectively. There are tons of coordinates published in those ways (geocaching locations, camping locations etc.), and any printed maps you purchase for hiking will almost certainly _not_ have coordinate lines in decimal format. This option would greatly improve the usability of GPSLogger for many purposes, if all of those ways to display coordinates would be available.

**Comment by mendhak** [comment]
For my own reference, various formats distinguished here - https://www.maptools.com/tutorials/lat_lon/formats

**Comment by mendhak** [comment]
v81 relesaed to market

**Comment by tneu33** [comment]
While the format is now user-selectable, it makes the lines longer in the display, and the N/S/W/E direction indicators disappear from the end of the line. Attached screenshot is from Galasy S7, where the system font size is set around midpoint of the scale. I suggest decreasing the coordinate font size by 25% to make the whole line fit into the display.

Sorry about the Finnsh language screensot. But I've checked that changing the language setting to English results in similar lines that exceed screen width.

![screenshot_20161219-125922](https://cloud.githubusercontent.com/assets/24492505/21335365/3dd11312-c62c-11e6-88e6-44c11cfc5e90.png)
