### ISSUE TITLE
Calories consumed

### ISSUE THREAD

**Issue by tkrajina** [mendhak/gpslogger#478]
Hi,

I was thinking to add a counter of calories consumed during my walks/runs or bike trips. I started experimenting with it here https://github.com/tkrajina/gpslogger/commit/72eb37b656b8e65054814da0d46cd15b3a1686e5 . The user would need to set her/his weight in the settings, and (if he did set it) when starting a track, the app will ask him the activity type (walking/running/cycling). Maybe I could write a code to detect the activity type -- for example, if the average speed is < 5kmh it's probably walking. If between 5-15kmh and without big extremes it's running. If it's 12kmh with extremes of >25kmh downhill it's probably cycling. 

So, I just wanted to ask if you think this would be something of interest for you (in case I finish it and send a pull request)?

tk

PS. There are a couple of considerations in my commit. It's just an experiment. I'm not 100% sure if the apache 2.0 license from MyTrack allows embedding the code in gpslogger (probably not). The alternative is extracting the code in a library, and using it in gpslogger.

**Comment by tkrajina** [comment]
A better implementation (but not yet complete) implementation: https://github.com/tkrajina/gpslogger/commit/f22693a35a58563337a7380d73ae2084e0190643 .

**Comment by mendhak** [comment]
Hi, thanks for your effort.  I'm not looking to add calorie info to the app, my main focus is around logging rather than running info which would require a more constant and frequent logging.  However thanks, I'll close this now to clear up
