### ISSUE TITLE
description does not get uploaded to OSM traces

### ISSUE THREAD

**Issue by PontiacCZ** [mendhak/gpslogger#480]
I love this app and use it for automatic uploading traces to Openstreetmap. Sometimes it might be useful to change the preset track description, but GPSLogger does not upload it.

How to reproduce:

1. set the autosending:
   - Allow auto sending
   - When I press stop
   - Openstreetmap - set the authorization, visibility to identifiable and description to "My automatic description" (this is important)
2. now start logging and get at least several points
3. for whatever reason you decide to change the description for this track - tap the pencil icon and add a description "Manually changed description"
4. stop logging, GPSLogger uploads the trace to your OSM account
5. browse your traces on Openstreetmap and find the last uploaded one - it will still have the default "My automatic description" description

**Comment by mendhak** [comment]
Hello, these are two different things.  The description in the OSM screen is for the file upload as a whole, an OSM specific feature.  

The pencil is an annotation for a point; it adds a `wpt` to the GPX with the location.  So a single GPX can contain dozens of annotations.  It's not meant to be a description for an OSM upload.  In other words if you download the trace and view the GPX it will have your annotations in there. HTH

**Comment by PontiacCZ** [comment]
Aha, I see. Good idea to be able to insert a named waypoint, this app can nearly replace the OSMTracker. :) But the pencil icon and the "Add a description" header are confusing, made me believe it was a description for the entire tracklog.

Well, an idea: why not rename it from "Add a description" to "Add a waypoint" - I am new to this app as many others and if read "Add a waypoint" (or "Add a point description"), it would be perfectly clear what I was doing. :)
