### ISSUE TITLE
Feature request: Show elapsed time since last logged point

### ISSUE THREAD

**Issue by tneu33** [mendhak/gpslogger#485]
I'd appreciate a feature that would show on the gpslogger's status display the time that has elapsed since the last point was actually logged, even (or especially) when the gps has lost the location fix.

Depending on the situation, this time may range from seconds (normal operation) to tens of minutes, or even hours (if no fix is available) although the location keeps changing continuosly.

Some background for this request:
Occasionally I use gpslogger in an environment with weak gps signals, like inside an airplane (almost a faraday cage), where even the phones with the most sensitive gps receivers occasionally lose the location fix. When I happen to notice the gps has lost the fix, it would be a nice feature to see in the app's front page the elapsed time since the last point was logged - if it was just a while ago, I could simply let the gps to try to get a new fix on it's own. But if the time exceeded what I find reasonable, then it might be worth trying to "help" the gps somehow, for example by keeping the phone closer to a window for some time.

**Comment by mendhak** [comment]
Does log view solve a bit of what you're after?  It should show some errors if the GPS is unable to find a proper fix.  It also shows the times against each line, which you could compare to the device time

I've taken a conscious decision not to show any 'elapsed time' since that requires updating the UI frequently and I'd rather avoid draining battery for this.

**Comment by tneu33** [comment]
Thanks, that's a good idea!
At the first sight it looks that the log view solves it. I don't know yet if the app keeps old enough logs available. There is a checkbox to show only locations in the log, that way it should be easy to see the last acquired location and make the necessary simple calculation, as long as these lines won't roll away from the log, say, in a couple of hours. More recent error messages obviously don't provide the necessary information.

I'll test that some day - it will need a place with no gps coverage for a few hours. Preferably also with no cellphone coverage either. Maybe I'll need to wait until my next transcontinental flight in couple of weeks... I'll update it here when I know more.

But what comes to my original idea: I'don't know if the  power consumption were a problem, since there were no need to update that infirmation every second in the UI - update could be done once a minute or even more seldom, especially after the very first minutes. But I'm not an Android app developer, I don't know the exact problems that might arose.

**Comment by tneu33** [comment]
My test of today failed, since the latest gpslogger (82) discards points with speeds around 800..900 km/h :-(
I'll try it later again, if the logging with that speed becomes possible again.

**Comment by mendhak** [comment]
Yes fix is coming soon for this, increased the maximum speed.

**Comment by tneu33** [comment]
Sometimes just studying the existing features fullfills the new feature request... This seems to be close enough to The Perfect Solution:
Notification bar has a timestamp that is updated when a new point is logged. So if that timestamp gets too old, it's time for the user to try to help the gps somehow...

![screenshot_20170110-164053](https://cloud.githubusercontent.com/assets/24492505/21811734/72df3032-d759-11e6-9ef5-b5850406838f.jpg)
