### ISSUE TITLE
duplication of OSM uploads

### ISSUE THREAD

**Issue by PontiacCZ** [mendhak/gpslogger#487]
The GPS logger often uploads the tracklog to OSM twice. I have set up auto upload to Openstreetmap.

![reuploads on the osm](https://cloud.githubusercontent.com/assets/9153595/21130446/cd6f956c-c108-11e6-8464-3a727b9d2e69.png)

**My settings:**

![gps logger - upload settings](https://cloud.githubusercontent.com/assets/9153595/21130491/3348d542-c109-11e6-9e3d-be16e6b03fd5.png)

![gps logger - openstreetmap](https://cloud.githubusercontent.com/assets/9153595/21130490/33488326-c109-11e6-9990-dc6ffdacc88c.png)

**Comment by mendhak** [comment]
I've been trying to reproduce this, but I'm still getting single uploads, so everything looks fine here.  I think there may be something on your phone.

Two options 

Option 1 - Debug log:
Can you do this - go to general options.  Enable 'write to debug file'.
Now get the app to double-upload.
Go back to general options, and attach the debug log to email, and email it to gpslogger (at mendhak.com) 
Be sure to disable the debug file option after this!

Option 2 - Reset it:
Clear OSM authorization, then re-authorize with OSM.  Then try logging as usual.  If the problem goes away, may have been a bad setting somewhere.  If the problem doesn't go away, go to Option 1!

**Comment by PontiacCZ** [comment]
Aha, I see what you mean. That is not my case,  I have **New file creation** = "Every time I start" and the following three options are all grayed out.

![screenshot_20161213-204621](https://cloud.githubusercontent.com/assets/9153595/21156233/62c28720-c175-11e6-9303-bf76ea7913ea.png)

**Comment by mendhak** [comment]
OK didn't expect that.  When you do a manual upload does it double upload? In which case can you enable debug logging in general options, do the double upload, then send me the log file -> gpslogger (at mendhak.com)

**Comment by PontiacCZ** [comment]
Sure, logging already on  and I'm going to send you the logfile as soon as I record two uploads of the same file again.

**Comment by mendhak** [comment]
Debug log helped!  I found a bit where you had stopped the logging.  You resumed it about an hour later and then this:

> 18:06:25 DEBUG GpsLoggingService.resetCurrentFileName:687 - New file name, should auto upload the old one

Basically it was storing the old name and the logic thought it was time to reupload.

**Comment by PontiacCZ** [comment]
Well, maybe I do not quite understand but it is important that you do. :-) Great that the debug logs helped! I'm stopping creating them.

**Comment by mendhak** [comment]
Forgot to add.  If you want to sideload, an APK is ready if you want the fix now now.  Or if you want to wait I'll probably push to market in a week or so.

APK -https://dl.dropboxusercontent.com/u/51905631/gpslogger-82.apk
PGP Signature - https://dl.dropboxusercontent.com/u/51905631/gpslogger-82.apk.asc
Checksum - https://dl.dropboxusercontent.com/u/51905631/gpslogger-82.apk.SHA256

**Comment by PontiacCZ** [comment]
I'll wait, no problem. I'd like to keep the auto-update function of the app which I probably would lose if I used the APK, right? Anyway, thank you for the offer. :-)

**Comment by mendhak** [comment]
v83 released to market.
