### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by lwis** [mendhak/gpslogger#488]
Would it be possible to add support for publishing to an MQTT broker?

**Comment by mendhak** [comment]
I had a quick search around about this.  What is MQTT about and what kind of use cases are there?  Is it used by popular devices?  I am trying to see how popular it is, where it would be used etc.

**Comment by lwis** [comment]
@mendhak It's essentially a message bus, you publish a message to it and then anyone listening can pick up the message and perform whatever actions they desire - rather than telling multiple endpoints about your message, the broker handles it for you.

I'm a fan of HiveMQ's docs on MQTT - http://www.hivemq.com/blog/mqtt-essentials-part2-publish-subscribe

**Comment by mendhak** [comment]
I have been looking through many resources around MQTT.  It's going a bit slow as I have to try to understand it better.  So it will take more time but yes I'm more interested in this.  

There is a [Paho MQTT client](http://www.hivemq.com/blog/mqtt-client-library-enyclopedia-paho-android-service) for Android but it creates a WakeLock which I am very uncomfortable with.  There's also a [Java client](https://github.com/eclipse/paho.mqtt.java) which I hope could work on Android without such a requirement.  


Nice to see that MQTT supports SSL, it will fit in nicely with the custom SSL validation mechanism I added recently.  


This HiveMQ site is really nice - it has the [essentials](http://www.hivemq.com/blog/mqtt-essentials-part-1-introducing-mqtt) and a public [tryout site](http://www.hivemq.com/try-out/).

**Comment by lwis** [comment]
@mendhak cool, great to hear that you're interested. I'd much rather have a good implementation than a rushed one 👍

**Comment by mendhak** [comment]
@lwis or anyone listening - what would a typical payload look like?

Would a user send a payload with just

`12.131342,-5.1834824`

or would they expect a timestamp as well

`12.131342,-5.1834824,2017-12-25T05:09:17`

What's the most common separator?

When I do a search I see some people with elaborate JSON objects being sent over MQTT.   How often is JSON expected?

**Comment by mendhak** [comment]
Other findings - 
The Android client is lighter :+1: but simply won't work without wakelocks :-1: 
The Java client is heavier :-1: but will gladly work without wakelocks :+1:  

Both ways the user is punished.

Most likely options that would be configurable in settings screens
* Topic - don't allow starting with a `/`
* Client ID - either generate or allow blanks
* Payload format 

Not sure if these options should be configurable:
* QoS - I want to hardcode this to 0, any reason it shouldn't be?
* [Retained](http://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages) - hardcode this to false?

**Comment by lwis** [comment]
@mendhak I'd make the QoS and Retained flag configurable, with those defaults. 

Is there not a lighter alternative library?

**Comment by Mobizyng** [comment]
@mendhak, Hi. Would it be possible to check again if can implement support for publishing to an MQTT broker? Is there any other way that don't punished the user, or leave this to user option?

Thanks
