### ISSUE TITLE
Add Milliseconds to timestamp

### ISSUE THREAD

**Issue by billbonney** [mendhak/gpslogger#490]
I've been using GPS unit that is 5Hz updates, but the timestamp is only at 1 second resolution. The fix is to change this line to add fractions of a second and still comply with ISO8601 time standard for GPX files https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java#L196

to 
```
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'", Locale.US);
```

Example output now reads as 
```
<trkpt lat="38.xxxxxx" lon="-78.xxxxxx"><ele>141.7</ele><time>2016-12-16T20:34:50.400Z</time><course>0.0</course><speed>0.022635555</speed><src>fused</src></trkpt>
<trkpt lat="38.xxxxxx" lon="-78.xxxxxx"><ele>141.7</ele><time>2016-12-16T20:34:50.600Z</time><course>0.0</course><speed>0.0015433333</speed><src>fused</src></trkpt>
<trkpt lat="38.xxxxxx" lon="-78.xxxxxx"><ele>141.7</ele><time>2016-12-16T20:34:50.800Z</time><course>0.0</course><speed>0.010288889</speed><src>fused</src></trkpt>
<trkpt lat="38.xxxxxx" lon="-78.xxxxxx"><ele>141.7</ele><time>2016-12-16T20:34:51.000Z</time><course>0.0</course><speed>0.008231111</speed><src>fused</src></trkpt>
<trkpt lat="38.xxxxxx" lon="-78.xxxxxx"><ele>141.7</ele><time>2016-12-16T20:34:51.200Z</time><course>0.0</course><speed>0.011832222</speed><src>fused</src></trkpt>
```

**Comment by mendhak** [comment]
Nicely spotted, I did not realize this so thanks for pointing it out you also traced it down to the code. I will make this change.

**Comment by mendhak** [comment]
So while doing this I learned that Android devices don't report at higher than a second resolution; all the timestamps I was getting were ending in 000. :disappointed: Is this the main reason for using external/bluetooth GPS devices?

Anyway if you want to test in advance, here is the installer:

APK - https://dl.dropboxusercontent.com/u/51905631/gpslogger-82-issue490.apk
PGP Signature - https://dl.dropboxusercontent.com/u/51905631/gpslogger-82-issue490.apk.asc
Checksum - https://dl.dropboxusercontent.com/u/51905631/gpslogger-82-issue490.apk.SHA256

**Comment by billbonney** [comment]
That's correct the external GPS updates at a much faster rate... 5Hz the one we tested with.

Thanks for the update I will see if we can get some tests done.

**Comment by billbonney** [comment]
BTW. I have noticed another issue with the <time></time> added to the GPX file. The time that is added is the logged time and not the time as reported by the Location object by Android. The time for the location from android may not be consecutive, so logging the gps time is more important.

I'm doing some tests with that changed. I will report back with more info when I have it.

**Comment by mendhak** [comment]
Have a test, it should be OK - the `.getTime()`, logic is here:

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java#L55

The system time is only used if `.getTime()` is reported as 0.

**Comment by mendhak** [comment]
v83 released to market.

**Comment by billbonney** [comment]
Thanks for the update
