### ISSUE TITLE
How a permanent lock-screen notification with a button to start logging

### ISSUE THREAD

**Issue by ryanbinns** [mendhak/gpslogger#493]
This is basically the opposite of #491 that you've just done. I would like the lock-screen notification to show permanently (whether logging or not), with a button to allow me to start logging without having to unlock the phone. I log every driving trip I make, and it would be nice to be able to start logging a bit quicker. A button that changed between Start and Stop depending on logging state would be ideal.

**Comment by mendhak** [comment]
It is better to consider [Tasker](http://www.androidauthority.com/system-info-lollipop-lock-screen-tasker-613868/) for this - it is designed to stay resident as much as possible so it can have a notification with buttons running and one of those buttons could in turn be the toggle for starting/stopping logging.  

If the aim is to simply have logging start when driving then you can have Tasker detect car mode (eg - connected to USB, landscape mode) and invoke an action based on that.  

GPSLogger codebase doesn't lend itself to always showing a notification, it would require a massive refactor which will have further regression impacts on performance.
