### ISSUE TITLE
Bug: Adding a note to a track breaks gpx file

### ISSUE THREAD

**Issue by tneu33** [mendhak/gpslogger#495]
Adding a note (if the term is incorrect, I mean the use of the pen-shaped tool in the lower left corner) to the track breaks gpx file that is being written.

Attached is a very simple gpx file. The second line (starting "<wpt lat=") of the file that contains the note "qwerty" is placed in the middle of </time tag that starts ( </t ) at the end of the first line, but the rest of that tag ( ime> )are only in the beginning of the 3rd line of the file.

GPS Logger version 83, on Samsung Galaxy S7 Duos, Android 6.0.1
I noticed this when logging to both kml and gpx, but reproduced it when logging gpx file only.

[20161229-xx.zip](https://github.com/mendhak/gpslogger/files/677945/20161229-xx.zip)

**Comment by mendhak** [comment]
Really sorry about this :disappointed:  I tested a lot but sometimes it's the ltitle things that slip past. 

I've pushed a fix to the market, v84 should be visible soon.  

[20161229-updated.gpx.zip](https://github.com/mendhak/gpslogger/files/678091/20161229-updated.gpx.zip)
