### ISSUE TITLE
Sending wrong SPD param value to custom url

### ISSUE THREAD

**Issue by vijaykarla** [mendhak/gpslogger#498]
I have observed that the app sends wrong speed value to custom url (parameter SPD) even though correct value is displayed on the app UI. I observed this on Lenovo K4 Note for GPS Logger v85 with Provider is GPS

**Comment by mendhak** [comment]
The speed displayed will be 'human' friendly, so it may be km/h or m/s, but the speed sent to a file or logger will be in meters/second

http://code.mendhak.com/gpslogger/#whataretheunitsinwhichthevaluesarelogged

**Comment by vijaykarla** [comment]
Thanks for the clarification :)
:+1:
