### ISSUE TITLE
offer some name format choices

### ISSUE THREAD

**Issue by liljenstolpe** [mendhak/gpslogger#499]
I see there is a 'greyed-out' option to set custom filenames.  This may be a subset of that future(?) feature, or maybe something similar.

I would like, for example, to change the order of <serial#>-<yyyymmdd>.<type>.  I would like it to be <yyyymmdd>-<serial#>.<type> to allow for correct ordering in the shared directory.  I also wouldn't mind seeing <serial#> be able to be replaced by a text field (i.e. human-readable name of the phone - to be entered by the user).

Also, I wouldn't mind setting the <yyyymmdd> to be <yyyymmddhhmmss> of the start of the log (for the multiple logs per day).

**Comment by mendhak** [comment]
If you go to New file creation and in there choose custom file, then you can set a custom file name in the next settings.

In that custom file name dialog you can do something like `hello-%ser`

**Comment by liljenstolpe** [comment]
I didn't find that initially (the "custom name" is greyed out unless you select it first in the file rotation dialog.  Closing
