### ISSUE TITLE
GPS data per SMS or REST api for low data rates / GSM

### ISSUE THREAD

**Issue by Awienke** [mendhak/gpslogger#500]
Hi,
we would need a GPS logger that can send GPS locations per SMS over GSM.
Use case: send GPS data every ten minutes on the sea where poor data connection / or at least a low gsm signal is available.

**Comment by mendhak** [comment]
GPSLogger doesn't have SMS sending.  It does have a Custom URL feature, if there's no data available at the time of sending it can 'queue up' the requests until the phone detects that a data connection is available.  That's the closest I can think of for your scenario.

**Comment by Awienke** [comment]
Thank you very much, and it's not worth a new feature? ;)
I think anyway the queue thing is good enough for our scenario.

**Comment by mendhak** [comment]
I'd have to think on this a bit.  I do get SMS as a logging feature request not-infrequently but I don't want to be sending an SMS every 1 second (which is possible), which gets this app classified as abusive - SMS permissions are classed as dangerous on Android 6+ so it has to be dealt with carefully.  On the other hand I don't want to have to write special logic around SMS either for maintenance reasons.
