### ISSUE TITLE
 Feature request: barometer logging #502 

### ISSUE THREAD

**Issue by F6F** [mendhak/gpslogger#503]
for several projects its interesting to have the barometer data logged with the GPS track.
Many phones are equipped with such a sensor.
The data can be used to calculate accurate hights using correction values.

Is such a feature supported by the application owner?
I guess a toggle option whould be nice to enable or disable the feature.

**Comment by mendhak** [comment]
I've wanted to do this in the past (https://github.com/mendhak/gpslogger/issues/152) and had to abandon it after seeing what's involved, so it's not implemented.  Sorry!

Unfortunately it's not as simple as a toggle, I haven't ever had a phone with a barometer either so it would also make testing - and more importantly maintenance - super difficult. 

Normally I'd welcome a pull request around an unimplemented feature but even if I got one, the debug/maintenance part is still very tough.

**Comment by ireun** [comment]
Hi @mendhak has anything changed in terms of complexity of this being implemented after 9 years?
