### ISSUE TITLE
Wrong timestamp 

### ISSUE THREAD

**Issue by jogecg** [mendhak/gpslogger#504]
Hello, when I am recording the gps data, the timestamp that appears is wrong, in my phone is set correctly, but in the application I dont see how to set it. I really would appreciate a solution or instructions to resolve this issue.

Thank you.

**Comment by mendhak** [comment]
Is it utc you're referring to?

http://code.mendhak.com/gpslogger/#itsusingthewrongtimezonecanyoumakeitusemytimezone

**Comment by jogecg** [comment]
Well, I want to handle the data in csv format, for example I got this in txt for one location,
2017-01-26T23:46:32.708Z,19.291608,-99.501613
The date is correct, but the time "23:46:32" is completly wrong, maybe from the source code the timezone can be set,, but I really dont know how to do it.

**Comment by jogecg** [comment]
Guess I need to simple convert the utc to my timezone, thank you.
