### ISSUE TITLE
Custom URL Help

### ISSUE THREAD

**Issue by keepcarlson** [mendhak/gpslogger#506]
Hi - Don't know if you can help me as this isn't so much an "issue" but more of a tech support question.  What is needed for the file to be uploaded with the Custom URL option?  For example, is it just a folder (ala http://my.server.com/logging) that would be in the inetpub/wwwroot folder or is there something else needed?  

And I'm afraid I don't understand the instruction on self-signed certificates....  Specifically the part about "Just go into a setting screen where you have specified a custom SSL URL or server, and click Validate SSL Certificate"

What "setting screen"?  Would this be on the phone?  For example, opening safari and navigating to the URL...is this when the validate message appear?  Or will this validate message appear once the URL is entered on the Log to custom URL screen in the GPS Logger app?

Since I cannot get GPS Logger to accept my Custom URL I am clearly doing something wrong.  I am eager to use your program for a research project and it appears as though it will be perfect for the job if I can get the Custom URL to work!

**Comment by mendhak** [comment]
Note that you can't upload files to Custom URL but you can only log locations to it while the app is running. 

So on the web server, `my.server.com`, you will need some application listening for the HTTP `GET` requests coming in.   It will then need to take those requests, parse the URL, extract querystring parameters and store it to a file or a database.  If that isn't your area of programming then you should probably look at the other file upload mechanisms instead (Google Drive, Dropbox, etc) and parse the uploaded file from there. 

Now if you are logging your location to a custom URL then the self-signed certificate instruction only applies if you're using https.  

First enter the custom URL that you want, such as `https://my.server.com/logging?lat=%LAT...` and then press "Validate SSL Certificate".  The app will try to connect and present you with a dialog if it is an unrecognized certificate.  

![validate](http://code.mendhak.com/gpslogger/images/21sslvalidation.gif)

**Comment by keepcarlson** [comment]
Thank you very much!  I get it now....I have another application running on the server (my.server.com) that I believe will be able to "listen" for the requests coming in (and someone to help me with it)!  It helps to know what to look for in that application.  And, it seems as though once I enter the URL for that (once it is set up properly) your logger application will be what is prompting me for the certificate.  Thanks again - coffee on the way!
