### ISSUE TITLE
Use the FusedLocationProvider for better estimates

### ISSUE THREAD

**Issue by nateyoder** [mendhak/gpslogger#507]
Hi @mendhak great app!! I was wondering if you had any plans to migrate to the FushedLocationProvider?  I'm hoping to get the most accurate locations possible for my research project and would love the additional accuracy it brings with poor fixes.

Thanks!!

**Comment by mendhak** [comment]
I don't have any plans yet for a few reasons - 

Time: it's a large rewrite of the main GpsLoggingService class, so it's a matter of finding the time to do it and test it extensively and figure out which current features have to be canned or modified.

China: Google Play Services should be making its way to China this year but it'll take some time to spread.  At the moment not having Play Services only prevents Google Drive functionality.  Moving to Fused will essentially block the application for a lot more users. 

But mainly time.

**Comment by nateyoder** [comment]
Makes sense.  Just thought I'd check.  Thanks!
