### ISSUE TITLE
Log files end prematurely after ~618 bytes

### ISSUE THREAD

**Issue by fred-rum** [mendhak/gpslogger#508]
I am using the application for the first time.  If I record just one or two points, the log file is created just fine.  But if I log more points, the log file cuts off after 618 or 620 bytes.  If I output to two different files (e.g. KML and TXT), both files cut off after the same number of bytes.  Note that I tell the app to "stop logging" before I grab the file.  I also tried force-quitting the app to see if that flushes any cached data, but it didn't.

This is on a Moto G4, with KML and TXT files stored to internal memory in my Downloads directory.  I also tried changing the save directory back to Internal storage\Android\data\com.mendhak.gpslogger\files , but I got the same problem.

I've attached a sample KML file (zipped so that GitHub will accept it), a TXT file that was created in the same session, and the associated debuglog.txt file.

[20170205141836.zip](https://github.com/mendhak/gpslogger/files/753398/20170205141836.zip)
[20170205142611.txt](https://github.com/mendhak/gpslogger/files/753395/20170205142611.txt)
[debuglog.txt](https://github.com/mendhak/gpslogger/files/753396/debuglog.txt)

**Comment by mendhak** [comment]
How are you grabbing the files? If over usb then the media database might
not have refreshed.  Instead try from the app itself for example upload to
Dropbox or Google drive or email to yourself. Or even have a look at the
files with a file explorer.

**Comment by fred-rum** [comment]
Thanks for the quick feedback.  Yes, I am using USB to retrieve the files.  I prefer to avoid the cloud as much as I can.

Your guess is correct that with a file explorer (Astro) on the phone, I can read the full, correct file.  I can also move or rename the file, after which I am able to correctly transfer it via USB to my computer.

I'm not yet knowledgeable about the Android media store and how its storage differs from a traditional file system.  Is there anything that the GPS logger app can do to fully flush these files to be visible over USB?  If not, I guess I'll just keep whacking them with Astro.  Thanks.

**Comment by fred-rum** [comment]
After messing around with it some more, I've discovered that my PC can read the file correctly without the aid of the Android file manager if I do either of the following:
- Plug in my USB cable and select "USB for file transfer" after creating the GPS track, or
- Disable "USB for file transfer" and then re-enable it after creating the GPS track.

Which is to say, it only fails when I'm sitting at my desktop playing with my new GPS logging app, rather than actually using it in the field.  Given that, I guess this bug is no longer a priority for me.

**Comment by mendhak** [comment]
GPSLogger does ask the OS to ['rescan' media database](https://github.com/mendhak/gpslogger/blob/ddef203035c0a491763a51b02149db0224ce66be/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/Files.java#L73) but this is just a suggestion, the OS can ignore it or do it later.  That's what you're running into here.  

If you are trying to avoid cloud services, you could consider emailing yourself if you run your own SMTP server or FTP server or OwnCloud if you have one hosted yourself. 

Another option - use something like [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&hl=en_GB) with its schedule to keep taking things from the GPSLogger folder and copying it to a SMB/UNC share.

Another thing you can try is using the `adb` command to `adb pull` the file from the phone and this file should be in a complete state.  But it depends on how comfortable you are with commandline tools.

**Comment by fred-rum** [comment]
Your code rewrites the file and calls scanFile() every time it adds new location data to the file.  I'm guessing that Android processes the first call and records the associated file length in its media metadata, but then it defers all later rescans until something gives it a kick, e.g. making a new USB connection.  So there's probably no way to fix this without fundamentally changing the way you write files, which is probably something you don't want to do.

Thanks for the additional fetch suggestions.  But in real-life usage, I'll normally be plugging in a USB cable to retrieve the file after I've stopped logging, and it looks like that will then properly sync the completed file.  Thank you very much for your help.
