### ISSUE TITLE
'Log to Text' option logs to .txt file with MS Excel encoding when uploading to Google Drive.

### ISSUE THREAD

**Issue by Jona-L** [mendhak/gpslogger#509]
When selecting 'log to plain text' to log to a .csv file, the app actually logs to a .txt file which cannot be opened in a simple text editor, but when opening it in Microsoft Excel it shows the data just fine. There is even more data then in the .gpx and .kml file format variants. So i'd like to use this dataset but then as an plain .csv text file rather then it presumably being a .xlsx file.

I attached a .txt log file as an example.
[20170204.txt](https://github.com/mendhak/gpslogger/files/754497/20170204.txt)

Update: uploading to my FTP does generate a plain .txt file. The excel file mentioned above is when I upload to my Google Drive, which indeed seems a feature now as it then works with Google Sheets. However, as the setting in the app says that a plain text file is created, and the result in Google Drive is a .txt file, it does seem confusing. Furthermore: a user can now not create plain text files when he/she want to upload to google drive only.

**Comment by Jona-L** [comment]
Update2: It seems that google drive convert the .txt csv file to xlsx when downloading a file. Even when downloading a list of files in a .zip, while it does not change the file format in the filename then. This can be fixed by opening the file in google sheets and then exporting to a csv file.
As this problem thus actually arises from weird google drive behaviour and not because of this app, I shall close this issue accordingly.

**Comment by mendhak** [comment]
Thanks for clarifying - what I can do (albeit low priority) is clear up the confusion by calling it a CSV file instead of plain text.  And change extension to .csv - better to call it what it is

**Comment by Jona-L** [comment]
Yeah, unrelating to the above problem, that might be a good idea, seeing as .kml and .gpx files essentially are text files as well..
