### ISSUE TITLE
custom help?

### ISSUE THREAD

**Issue by jacknab** [mendhak/gpslogger#512]
Hello developer,

Would you be willing to do some custom changes to the app for a fee?

I am not asking for any new features. 
I would just like to hide all the options and just use the openGTS Server  (but not sure if that works just like the custom url.

*

**Comment by mendhak** [comment]
Is this related to #511? You're trying to build a somewhat focused app?

You can email me, _gpslogger at mendhak.com_ with what you're trying to do.
