### ISSUE TITLE
Perfomance setup and bad route.

### ISSUE THREAD

**Issue by uzazzap** [mendhak/gpslogger#516]
Hello! For a long time I use your program and eventually matured a few questions:

1. For a long time trying to pick up the performance parameters for the most accurate recording routes.
Now I have the following settings:

Logging interval - 20 sec.
Distance filter - 100 m.
Accuracy filter - 100 m.
Duration to match accuracy - 20 sec.
Absolute time to GPS fix - 120 sec.
Do not log if i'm not moving - enabled.
The sources used GPS only.

Configured AutoSend OpenGTS data and text file (.csv) on the FTP server.
It should be noted that the performance parameters chosen brute force, almost at random, and do not give the expected result.
See attached screenshot for bad track.
![example](https://cloud.githubusercontent.com/assets/25898530/23198633/4f408b6a-f90c-11e6-8f6f-3c0d8d9b821d.png)

I would like to read description of performance settings in complex and how they affect each other.
Are there any plans for writing such a reference?

2. Application is configured to send info to OpenGTS and CSV file (sended via FTP).
Some devices not send info. I think the reason is bad internet connection.
OpenGTS info lost for bad internet period - it is clear, but CSV file has not these points too.

2.1 Are different ways to send data works in parallel? And when one of them fail (OpenGTS) - other (CSV) also not record point
If I use "log to custom URL" instead of OpenGTS - will it resolve issue with not recorded point to file?

2.2 If I disable autosend to OpenGTS - will CSV file has points while bad internet time?

3. If your device Samsung Galaxy Tab 4 (sm-t231 Android 4.4.2) setting is ignored "Do not log if i'm not moving", the tablet for a long stay in motionless position continues to record and transfer points.
If I understand correctly, this function uses the accelerometer data? Can we somehow fix this problem? 

P.S. Translated via google translate.

**Comment by mendhak** [comment]
Hi first thing I notice - that accuracy filter is too high!  100m is really bad, even the default 40m is quite generous.  I don't have any detailed descriptions, but you can have a read through the [FAQ](http://code.mendhak.com/gpslogger/#frequentlyaskedquestionsandissues). 

When you have no data connection, the app will queue up the items/files to send.  The next time your phone reports that an Internet connection is available, it will send the file.  Same applies for OpenGTS.  

If the Galaxy Tab4 doesn't have an accelerometer, then there isn't anything that can be done to detect if the user is 'standing still'.

**Comment by uzazzap** [comment]
Why between A and B points on track jumps about few km?
In this time about A and B points on server haven't info. But internet on device working all this time.
And reading your previous answer, i'm thinking about points what was registered without internet, just send after getting internet connection again (OpenGTS sending). But server not getting their.

In general, there are more questions:
What is hidden under the name Absolute time to GPS fix? This option ignores all general parameters of filters and writes the point that gets every 120 seconds?
What happens if at the same moment of time will be another attempt to get the point with all the filters?

To increase the number of points necessary to reduce the value Logging interval?

**Comment by mendhak** [comment]
For both the A and B jump as well as the server not receiving info - Really can't say without looking at a debuglog.  It's likely related to the accuracy filter being too high, the OS will report bad points but the application can ignore it based on the filters you've set. 

The absolute timeout is described [here](http://code.mendhak.com/gpslogger/#whatdothevarioussettingsmeanaccuracyretryintervalforaccuracyetc):  

> Absolute timeout - When searching for a point and trying over and over, the app will give up when this timeout is reached. This is useful for when you're inside buildings, GPS tends to keep searching and finding nothing.

The app only tries to log one point at a time so there won't be an overlap.

**Comment by uzazzap** [comment]
```
I suppose the app works as like (based on my current settings):
|----| - first logging interval (20sec)
  A   - moment when app get first point in logging interval
  |----| - Duration to match accuracy (20 sec)
  B - point which match accuracy filter
|------------------------| - absolut timeout interval (120 sec)
                         |----| - second logging  interval?

or

|----| - logging interval (20sec)
  A   - moment when app get first point in logging interval
|----| - Duration to match accuracy (20 sec)
|------------------------| - absolut timeout interval (120 sec)

or

|----| - logging interval (20sec)
  A   - moment when app get first point in logging interval
  |----| - Duration to match accuracy (20 sec)
  |------------------------| - absolut timeout interval (120 sec)

or 

|-----| - got no one point
      |------------------------| - absolut timeout interval (120 sec)
                               |----| - second logging  interval?
                               
or

|-----||-----||-----||-----||-----||-----||---...
A                                       B - points taked every 120 sec?
^-----^ - logging interval 20 (sec)
^ absolut timeout interval (120 sec)     ^
                              
                               
B - the only one point in 120 sec timeout interval?

Or there will be from 0 to 6 point in 120 sec timeout interval?
0 - when app did not got point, that meet accuracy filter
6 - maximum point when point accuired with good accuracy and no one discarded by filter

```
How these intervals related to each other?

How much points logger can get with my current settings (min\max values) ?

Please look to this scheme and say which of these variants right, or draw right scheme.
For draw scheme used monospaced font.
Debug log i will send little later.

**Comment by mendhak** [comment]
It's likely closest to the first one.  I'm not in a position to draw any kind of scheme, the logic is not going to be something that can be represented with a few lines.  If you want a deep dive I'd suggest having a look at the code directly: 

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L732

**Comment by uzazzap** [comment]
Hi again. I have new tablet Lenovo Tab 3 Plus TB-7703X for new expirience. Now i have better accuracy, but logger make jumps over half city map again.
![route_lag](https://cloud.githubusercontent.com/assets/25898530/25367752/5df4af8c-29aa-11e7-9758-fa9d08004997.png)
Have this lag at GpsLogger v86. Will try v76 tomorrow, and get feedback about it.

**Comment by uzazzap** [comment]
GPSlogger v76 have this lag too. Have you any ideas why i have that jumps?
