### ISSUE TITLE
Feature request: Config/settings export/backup

### ISSUE THREAD

**Issue by checkds** [mendhak/gpslogger#518]
One for the wish list.
After my phone became barely functional, I went and bought a new phone and proceeded to get it set up with my apps and settings.
Thought it would be a good feature to be able to backup/export the configuration of gpslogger, ideally including all user selectable settings in the app (finding the ftp login password I setup for the app years ago took a while)
May seem at little bit over the top but I spent a lot of time over a period of months tweaking my accuracy settings in the app to get the traces I needed and did not think to write them down. Had I lost my phone all this would be gone.
A good way to get the file off the phone would to be to treat it like the log files. Select backup/export settings in the options and choose the method like you do for exporting logs.
An import function would be nice but simply instructions on where to move a manually downloaded settings file to would suffice if it would get them restored.
Thanks.

**Comment by mendhak** [comment]
What phone + Android version did you have before, and what phone + Android version do you have now?

If you have 6.0+ now, then this should happen the next time you switch phones.  This is done via Google's [auto backup](https://arstechnica.co.uk/gadgets/2015/10/android-6-0s-auto-backup-for-apps-perfect-data-backup-for-the-1-5/) feature.  

You can see what's being backed up if you open the Android Google Drive app, left menu, Backups, and have a look in there, it should list which apps are being backed up.  

What you're saying isn't impossible though, already a `.properties` file gets created if you start using the profiles feature and create a new profile.  Could be just add a new menu option to import/export the file, or be lazy and tell the user to put it there

**Comment by checkds** [comment]
I went from a 4.3 to a 6.0.1 device.
I had a look in Drive and can see a new phone backup and GPSlogger listed in apps. So I am correct in thinking that if I wipe this phone or move to another 6.0+ device, if I re-install gpslogger then the settings will automatically restore? Or are more manual steps required?

**Comment by mendhak** [comment]
Hmm I could have sworn I replied to this earlier :(

Yes that's right , according to [this](http://www.androidcentral.com/how-restore-your-apps-and-settings-new-android-phone) you should be able to restore settings on a new phone.

**Comment by acambitsis** [comment]
Is the export/ import config likely to still be implemented?  Our usecase is somewhat different in that we have quite a complex custom url config that we want to apply to multiple devices and need a way of doing this less manually.

**Comment by mendhak** [comment]
I think what you're asking is slightly different - you want to apply the same setting to different devices.  So you can define that custom URL propert(ies) in a `gpslogger.properties` file  - see

https://code.mendhak.com/gpslogger/#howcanidefineapresetfilewithmyownvalues

See if that matches up with what you want

**Comment by acambitsis** [comment]
Thanks for the super quick response.  Yes this should address the issue. I’m pleased to say that we have gpslogger configured to post to Azure IoT hub using the custom URL feature. This is a great use case to be able to handle though pure config.

**Comment by mendhak** [comment]
Loading from a URL, work in progress:  https://github.com/mendhak/gpslogger/pull/760

**Comment by mendhak** [comment]
v103 released to market
