### ISSUE TITLE
Spooky checkbox on "Log view" screen

### ISSUE THREAD

**Issue by Wikinaut** [mendhak/gpslogger#521]
My new smartphone with Android 7 shows a spooky checkbox (marked in the screenshot):

![20170226-11 33 19_auswahl](https://cloud.githubusercontent.com/assets/1151915/23338947/bdb44498-fc17-11e6-914a-ee01d7bdde9e.png)

**Comment by mendhak** [comment]
Looks like the top of the layout doesn't work nicely with long strings.  The third checkbox gets pushed.

**Comment by Wikinaut** [comment]
What is the 3rd checkbox good for ?

**Comment by mendhak** [comment]
It will auto scroll to bottom of the log messages. If you uncheck, it stays
in place. Normally just leave it checked. I'll play around with the layout
to see how to fit it

**Comment by Wikinaut** [comment]
Now, with an empty log file, I do not even see the spooky third checkbox.

**Comment by amarradi** [comment]
I only this bug on portrait view, but on landscape is it good

**Comment by mendhak** [comment]
[v87 released](https://github.com/mendhak/gpslogger/releases/tag/v87) to market
