### ISSUE TITLE
Noisy precision for degrees/minutes/seconds display format

### ISSUE THREAD

**Issue by 123unix** [mendhak/gpslogger#522]
Considering that:

- one angular second equals roughly 30 meters, and
- the highest GPS precision in consumer phones is about 3 meters, 

I think four fractional digits for coordinates' seconds is overkill.

- One digit after decimal point for the coordinates' seconds seems adequate, and
- two would be more than enough for precision freaks,
- anything over two is pure noise.

Could that be good for an ad-hoc RNG, perhaps?

**Comment by mendhak** [comment]
Reduced to 6 but forgot to update. 

https://github.com/mendhak/gpslogger/blob/ca25caba64a4510d9883d464e009e014f60ae765/gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java#L463
