### ISSUE TITLE
Feature request: write last coordinates before closing file

### ISSUE THREAD

**Issue by oztourer** [mendhak/gpslogger#527]
If I stand in one spot my coordinates get written once to the output file. If I take a photo shortly after but do not move, then close the file, the time of the photo is later than the last filed coordinate so Lightroom fails to associate the photo with the location. Writing current location immediately before closing the file would prevent this issue.

**Comment by mendhak** [comment]
I suggest looking at Jeffrey Friedl's plugin instead  - http://regex.info/blog/lightroom-goodies/gps  
Or Geosetter - http://www.geosetter.de/en/ 

Both of these allow for extrapolating the location based on nearest points
