### ISSUE TITLE
Feature Request: Battery Level

### ISSUE THREAD

**Issue by p1647803mvrhtcom** [mendhak/gpslogger#528]
Hi,

it would be helpful to have the phone battery level logged as well with each GPS point.

Thank you.

**Comment by lumanews** [comment]
Hi, 
I would appreciate this too.
I would like to use this app as GPS tracker on my bike and as GPS locator also (in case someone would steal it).
The perfect combination would be something like:
- if phone in charge (I am riding) then GPS sampling ratio = setting1 (20 seconds)
- else (I am in a trouble) GPS sampling ratio = setting2 (5 minutes)
   and send the phone battery status so to know for how long I can find the bike :-)

thx!

**Comment by mendhak** [comment]
It's currently done in Custom URL logging, it can be done in CSV - is this the format you're using?  It can't be done for NMEA, GPX, KML.  KML and GPX do allow custom extensions but I wouldn't want to do that as it's not a standard so this would be hard to maintain.

**Comment by mendhak** [comment]
[v87 released](https://github.com/mendhak/gpslogger/releases/tag/v87) to market
