### ISSUE TITLE
GPX files are sometimes corrupted

### ISSUE THREAD

**Issue by FalkTannhaeuser** [mendhak/gpslogger#530]
Sometimes, there appears a corruption in the GPX files generated by GPSLogger, as for example in the 2<sup>nd</sup> of these three lines (you may need to scroll vertically):
```XML
<trkpt lat="48.13287851" lon="-1.68026814"><ele>78.0</ele><time>2017-04-18T19:55:47.000Z</time><course>184.2</course><speed>5.5</speed><geoidheight>48.0</geoidheight><src>gps</src><sat>16</sat><hdop>0.7</hdop><vdop>0.8</vdop><pdop>1.0</pdop></trkpt>
<trkpt lat="48.13268448" lon="-1.6803329"><ele>76.0</ele><time>2017-04-18T19:55:51.000Z|otmme~|gouvwe~u}tnt|ogouvwe~|wteed~unwu|owteed~|geomdlemglt~t|nt|ogeomdlemglt~|wvg~gtw|owvg~|wet~uv|owet~|ldot~tnw|oldot~|vdot~tn||ovdot~|tdot~unt|otdot~|otvott~N|tvottdlet}ft|nuwvt|tv|fdlon}fmunv|ttwwuuf~|ele~wvnt|oele~|tmme~vtuwmttmu|Tu}~uu~uunttt^|otmme~|gouvwe~vttnu|ogouvwe~|wteed~unwu|owteed~|geomdlemglt~t|nt|ogeomdlemglt~|wvg~gtw|owvg~|wet~uv|owet~|ldot~tnw|oldot~|vdot~tn||ovdot~|tdot~unt|otdot~|otvott~N|tvottdlet}ft|nuwvww}vfdlon}fmunv|tuuw|vf~|ele~wunt|oele~|tmme~vtuwmttmu|Tu}~uu~u|nttt^|otmme~|gourse>201.6</course><speed>5.75</speed><geoidheight>48.0</geoidheight><src>gps</src><sat>16</sat><hdop>0.7</hdop><vdop>0.8</vdop><pdop>1.0</pdop></trkpt>
<trkpt lat="48.13220892" lon="-1.68058228"><ele>74.0</ele><time>2017-04-18T19:56:01.000Z</time><course>196.3</course><speed>5.5</speed><geoidheight>48.0</geoidheight><src>gps</src><sat>16</sat><hdop>0.7</hdop><vdop>0.8</vdop><pdop>1.0</pdop></trkpt>
```
A complete list of corrupted files I encountered so far is found in the attached ZIP file.
[corrupt_gpx.zip](https://github.com/mendhak/gpslogger/files/966263/corrupt_gpx.zip)
This corruption prevents the files from being opened e.g. in [Google Earth](https://www.google.com/earth/) or [GPXViewer](https://sensortower.com/android/co/mtk-software/app/gpx-viewer/jp.matsukubo.gpxviewer/); however it is possible to fix the files in a text editor.
Note that I have been using GPSLogger on a nearly daily base since September 2013 (version 86 since 2017-02-15) and the issue begun to appear only very recently (since April 18). My phone is a Samsung Galaxy S4 (GT-I9505) running under Android 5.0.1. The logging interval is set to 3 s. The logging folder is `/storage/extSdCard/Android/data/com.mendhak.gpslogger/files`.

**Comment by mendhak** [comment]
Are you writing to SD card?  If yes - are you able to verify or find out if that SD card is corrupt?  Probably using one of the methods [here](https://www.techwalla.com/articles/how-to-check-an-sd-card-for-errors), but backup any files first.  Or you can also try another SD card and see if it happens with that.  I don't think you can test an SD card from within Android without being rooted.

The reason for mentioning this, is you can notice that each string of corruption or garbled text is 512 bytes in length, that's the usual size of a sector on an SD card.  So the file's probably being written to card right on top of a bad block, and that block is appearing inside the files.  

If not using an SD card does this corruption happen with other file types like CSV, NMEA, KML?

**Comment by FalkTannhaeuser** [comment]
You're right - not only the length of the corrupted text sections is a multiple of 512 bytes, but they also start at offsets being a multiple of 512 bytes... After ejecting and putting back the Flash SD card, the problem did not occur any more during several weeks of daily use. So I conclude it was a problem of the card and GPSLogger is not to blame.
