### ISSUE TITLE
CustomURL : add new %TIMESTAMP parameter in URL

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#531]
Dear Mendhak,

I'm a fan of your logging app. Since about 1 years ago I use GPSies.com platform for record my tracks.
GPSies team has recently added the Live Tracking feature, compatible with your CustomURL transmission.
But there is one problem: time
Live Tracking API http://www.gpsies.com/liveTracking.do?showAll=true  says:

_Live tracking mandatory parameter:
?username=myusername
&pin=0000
&latitude=<double value, e.g. 52.45334>
&longitude=<double value, e.g. 13.33677>
&requestTimestamp=<**UTC timestamp (phone clock) in seconds**, e.g. 1493621971>_

GPSlogger send time in ISODateTime format using %TIME parameter. In CustomURL can you add a new URL parameter like %TIMESTAMP that send UTC Unix timestamp in seconds ?

Thank you very much.

Best Regards.

**Comment by mendhak** [comment]
Added `%TIMESTAMP` to custom URL.  You can try a test APK, see if this works:

APK : https://drive.google.com/open?id=0B6IOK82n4BkAazlVd2JMZTB3ZmM
Signature: https://drive.google.com/open?id=0B6IOK82n4BkAbHN3b2pvaE5jUHM
Checksum: https://drive.google.com/open?id=0B6IOK82n4BkAWTlQWmFyWDZLc3M

**Comment by ambrosa** [comment]
Ok  I will do the test this afternoon.

**Comment by ambrosa** [comment]
It works fine :-)

For example (from GPSLogger debug log):
_http://www.gpsies.com/liveTracking.do?username=*MYUSERNAME*&pin=*MYPIN*&latitude=45.62795132182774&longitude=9.6425035657943&requestTimestamp=1493639047_

and GPSies accept LiveTrack data.

Thanks.

**Comment by ambrosa** [comment]
_PS: Hello good to see you again. Looks like a nice find. I remember you had a custom site you used once, was thinking of asking you to share the code, but gpsies.com looks quite good, if this app works with gpesies then I could recommend it to users in the FAQ_

I was "out of service" for two big car crash. While I was driving my motorcycle, in August 2015 and then in June 2016 cars crashed against me. Many hospital months in 2015 and also in 2016. Many problems with my health.
Now I'me back at 80% :-(

**Comment by mendhak** [comment]
Ah that's bad news then good news, glad to know you're recovering. 

OK closing this one now - [v87 released](https://github.com/mendhak/gpslogger/releases/tag/v87) to market
