### ISSUE TITLE
Update Italian translation in next release

### ISSUE THREAD

**Issue by ambrosa** [mendhak/gpslogger#532]
Today I've reviewed all italian strings in strings.xml @ Crowdin
Please add new italian strings.xml in next GPSLogger release.

Anyway, past GPSLogger releases were not automatically updated with italian language translations. I see in Crowdin other translations made 1 year ago never included in GPS Logger.
Perhaps do you need to approve the translations in Crowdin ??

Regards.

**Comment by mendhak** [comment]
I've been using an automated build task to download from Crowdin, I haven't been there in ages.  I think I see the problem:

![image](https://cloud.githubusercontent.com/assets/746276/25577740/912bab52-2e60-11e7-9acd-59872f480e1e.png)


I've now made you proofreader, in the future you can auto approve.

Meanwhile I am trying to figure out why Italian is a special case needing approval, all the other languages get downloaded just fine.

**Comment by mendhak** [comment]
Now I'm less sure what's going on - I did a redownload and I see your translations. Last download was 8 days ago

**Comment by ambrosa** [comment]
Yes, but months ago two other Crowdin users made some translations to GPSLogger.
And till now, none of their translations are applied in last GPSLogger releases (lacks of validations ???).
BTW we will wait next releade.
This afternoon I will check %TIMESTAMP feature.

**Comment by mendhak** [comment]
[v87 released](https://github.com/mendhak/gpslogger/releases/tag/v87) to market

**Comment by ambrosa** [comment]
AHAHA  Sgrunt !
I've 'approved' in Crowdin the italian translation .... yesterday !
So version 87 is build with old , not approved, italian strings.

We hope you release in future a release number 88....

**Comment by mendhak** [comment]
Yep I always get update from Crowdin, so it'll be included, but still not
sure why Italian is the only language needing approval for strings 😢

**Comment by ambrosa** [comment]
I've just now checked Play Store and revision is still 86. No version 87 there.
BTW When you have build 87, I'had not approved italian strings yet. So I suspect that version 87 has not the correct italian strings.
Build version 88 ?

**Comment by mendhak** [comment]
Should show up in the next few hours.  They changed the Play Store console for releasing and it's a bit confusing. It stopped at 10%, I had to go in make it 100% now

**Comment by ambrosa** [comment]
Till  now (15.40 UTC), Google Play show version 86.
From GitHub I've downloaded and manually installed 87.apk. 
It shows correctly all strings in italian language.

**Comment by mendhak** [comment]
I just tried - now the Play store shows the v86 in the "What's new" section, but when I installed, I get v87, so it may just be a caching issue.  

I'll wait 24 hours then check again.

**Comment by mendhak** [comment]
Found it.  http://stackoverflow.com/a/43750273/974369

The "What's New" text that they got me to enter during app update gets ignored, I have to duplicate it for some reason.  What a shame, the update has gone out and nobody will have seen it.
