### ISSUE TITLE
Feature request: upload to NextCloud

### ISSUE THREAD

**Issue by EugenVau** [mendhak/gpslogger#535]
Is it possible to implement uploading to a custom NextCloud instance?

Thanks in advance!

EugenVau

**Comment by mendhak** [comment]
Have a look to see if the current OwnCloud uploader works, supposedly it's WebDAV so it should.  I don't want to add too many upload targets, just a few focused ones, I already feel that there are too many upload targets at the moment. If that doesn't work have a look at [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&hl=en_GB) which does do webdav.
