### ISSUE TITLE
Question: iOS Option? 

### ISSUE THREAD

**Issue by poblabs** [mendhak/gpslogger#538]
Hi mendhak - I didn't see a way to contact you other than here. 

Thank you very much for GPSLogger! It is working great. We use it to put storm chasers onto a map at https://tornadochannel.com using Log to custom URL. 

Some chasers use iPhone and they don't have an app that can upload GPS to custom URL. 

Do you have any plans to develop an iOS version of GPSLogger? Or do you know of an app on iOS that can log to custom URL?

Thank you again!

**Comment by keepcarlson** [comment]
I would be VERY grateful to have an iOS version as well!  I've searched and searched for an equivalent in the 
 app store, and here on github, but haven't found anything

**Comment by mendhak** [comment]
Well this has to be one of the more unexpected questions! Sorry no plans at all - the ios platform is a massive investment (app store fees, buying hardware, language) and the platform itself has quite a few restrictions which make it difficult/impossible to implement many of the features in this app.  

After your question came up I tried looking for ways to accomplish the same on ios and I understand what you're saying, you're going to be hard pressed to find something simple for storm-chasers while being live.  

There *is* something you can look at but it isn't going to be easy.  [OpenGTS ](http://www.opengts.org/)is generally used as a fleet tracking system.  Consider it a 'standardized' custom URL - it sends data over HTTP/UDP.  It also comes with a server-side listener that you can install.  It's not exactly a straightforward install, there's a [PDF manual](http://opengts.sourceforge.net/OpenGTS_Config.pdf)!

And I did find an [OpenGTS app](https://itunes.apple.com/gb/app/opengts-tracking-client/id597107014?mt=8) that hopefully works!

So if this seems to be the closest option to Custom URL on ios:

* You could set up a fully fledged OpenGTS server (or possibly in [docker](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=opengts&starCount=0)) then have a cron to pull from the DB
OR
* You could write a custom server-side listener page that receives the OpenGTS URLs, parses out the NMEA strings and converts it to lat-long. You'll notice in the screenshots, it takes an account id and vehicle id - perhaps those could be mapped as "tokens" or identifiers on the customer side to identify a storm-chaser?  I've got some [example OpenGTS URLs](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/test/java/com/mendhak/gpslogger/senders/opengts/OpenGTSManagerTest.java#L124).  You'll then need to convert the NMEA coordinates to lat long, [here's an example](http://stackoverflow.com/questions/20292114/converting-gprmc-gps-data-to-decimal-format-in-php).  One advantage of doing it the OpenGTS way is - you don't have to stay tied to GPSLogger, app you can use other OpenGTS apps on other devices.  

Hope that helps sorry for long winded answer

**Comment by poblabs** [comment]
@mendhak This is a great answer, and more than I expected! I love the GPSLogger app and will continue to use that for Android users. 

I see there's some other GPSLogger-type app on iOS where they log to a URL, but it's the app owner's URL and their own map. A bummer for someone trying to do location ingesting via custom URL :) I'll look into OpenGTS as you've provided, and the examples too. Perhaps this is an option, but looks like some work to get it going. Hmm :) 

Thank you again for the detailed answer!

**Comment by keepcarlson** [comment]
Yes thank you very much for the help.....the Android app has been terrific for interfacing with ESRI's GeoEvent Server.  Some users will be using iPhone's however.....  

I found this possibility which I thought might work, but so far I have been unable to compile using xcode.  Since I'm not a programmer I cannot decipher the errors to determine why it is not compiling....  :-(  
Clearly missing something....

https://github.com/aaronpk/GPS-Logger-iOS

It doesn't have nearly as many options as yours but I've spent hours searching app store and this is as close as I've gotten.  Well, there is another one called Send Location, but it works only sporadically and many points are highly inaccurate.

**Comment by mendhak** [comment]
I tried to approach this another way - Tasker itself can do it; you can get it to get the location and make it do an HTTP GET.  So some ios equivalent of Tasker could do it too, possibly.  

I tried asking around at work, but there aren't many ios users here.  The ones I did find gave me a polite laugh when I asked what they were doing for task automation.  

The closest I could find was [Workflow](http://my.workflow.is/) - it's hard to tell from the docs but can it do timer based HTTP GETs?  This could help the ios users log their storm chasing?

**Comment by poblabs** [comment]
Yeah I think iOS has to be the difficult one in the group. I'm not sure of any task automation either. I'm thinking it would require a full-blown app with hooks into not letting iOS kill the background GPS process? I have a spare iPhone that's my backup device. I'll dust it off and see if Workflow is something.

**Comment by keepcarlson** [comment]
Hi - I just found an iOS that is working for me and might for you as well.  It is called SensorLog.  Author is Bernd Thomas.  From Itunes store.  Not free but at $2.99 worth it for me.  Has all the sensors.  Stores in files and or uploads to custom url.  I literally just foind this a couple days ago so have not done extensive testing.  But looks very promising.  Maybe it will work for others needing iOS option. Lynn Carlson Sent from TypeApp

**Comment by mendhak** [comment]
v88 has been released to market. Closing thread as part of cleanup work.
