### ISSUE TITLE
SFTP: FileNotFound exception when validating

### ISSUE THREAD

**Issue by runfalk** [mendhak/gpslogger#539]
I just tried to set up the SFTP upload feature but get a FileNotFound exception (ENOENT: No such file or directory). I've provided a domain name, port, folder, username and password. I have not provided a private key or a private key passphrase.

Android version is 6.0.1. It's an Samsung Galaxy 5 and seems to be equipped with something called SE for Android, if that affects things.

**Comment by mendhak** [comment]
In the dialog box did you get a stack trace, can you paste that here

Also ensure does the folder exist on target server

**Comment by runfalk** [comment]
```
java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
java.io.FileNotFoundException: : open failed: ENOENT (No such file or directory)
[com.jcraft.jsch.KeyPair.load(KeyPair.java:543), com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40), com.jcraft.jsch.JSch.addIdentity(JSch.java:407), com.jcraft.jsch.JSch.addIdentity(JSch.java:388), com.mendhak.gpslogger.senders.sftp.SFTPJob.onRun(SFTPJob.java:62), com.path.android.jobqueue.Job.safeRun(Job.java:145), com.path.android.jobqueue.JobHolder.safeRun(JobHolder.java:90), com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:306), java.lang.Thread.run(Thread.java:818)]
```

This happens before I even get a prompt about accepting the server's key fingerprint.

**Comment by mendhak** [comment]
Oh that's pointing [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/senders/sftp/SFTPJob.java#L62).  So it's trying to load your non-existent private key and failing. 

I am sure I had validation in place there :confused: as I had tested it extensively.  Merge problem?   I'll add this in now.

**Comment by mendhak** [comment]
Here's a fixed version if you can sideload (if you install this you will still get play store updates)

[APK](https://drive.google.com/open?id=0B6IOK82n4BkAQlRCbzlWYXVDVkU), [Signature](https://drive.google.com/open?id=0B6IOK82n4BkAZER2cE9ET19TQzQ), [Checksum](https://drive.google.com/open?id=0B6IOK82n4BkAaUhPNHZHUUxaVGc)

**Comment by runfalk** [comment]
I tried the APK and it seems to work now without issues. Thank you for the quick fix!

**Comment by mendhak** [comment]
v88 has been released to market.  Closing thread as part of cleanup work.
