### ISSUE TITLE
Consider integrating Gitter.im?

### ISSUE THREAD

**Issue by lenucksi** [mendhak/gpslogger#549]
How about adding Gitter.im integration to the repo? Gitter is one of those services similar to Slack but strongly integrated into GitHub. It has existed and been free for quite some time now and is pretty well accepted.

I've added it for demonstration purposes into my fork: https://gitter.im/lenucksi/gpslogger
You can login via GitHub and it yields a badge similar to the badge here as a link from the repo the  chat: https://github.com/lenucksi/gpslogger/tree/gitter-integration

If you would like to integrate it, you can just log into their service and have a PR generated for it.

**Comment by mendhak** [comment]
Hey that's an interesting idea. I've used gitter in the past with other projects but never even considered it for GPSLogger, are there enough people :stuck_out_tongue: . I could try it as an experiment, see how it goes.

**Comment by mendhak** [comment]
OK added - https://gitter.im/gpslogger/Lobby in #550

**Comment by mendhak** [comment]
Gitter webhook added to this repo, should start working soon

**Comment by mendhak** [comment]
v88 has been released to market.  Closing thread as part of cleanup work.
