### ISSUE TITLE
Feature request: send intent upon start/stop recording

### ISSUE THREAD

**Issue by droscy** [mendhak/gpslogger#551]
Hello, it could be useful to have GPSLogger sending an intent on recording start or stop, this way Tasker can react and perform additional actions. In my specific case I need to disable ForceDoze when GPSLogger start recording, and reactivate it when recording stops.

Thanks

**Comment by danielfaust** [comment]
This works as intended. Best solution for #551

**Comment by danielfaust** [comment]
It would be good to also hand over the filename of the related session, so that when it gets posted to a server, it knows which session the fetches refer to..

**Comment by mendhak** [comment]
Sorry @danielfaust I didn't understand can you explain again.  Do you mean pass the filename as an extra in the intent being sent to Tasker?  You mentioned server so I got confused since Tasker is on the user's phone itself

**Comment by danielfaust** [comment]
Issue #543 (Feature request: Add %START time to Custom URL) wants the App to send START/STOP-Events to the CustomUrlLogger.

What you are doing is delegating this task to Tasker. Tasker can then make a http fetch to @fatcat386 server, indicating a start/stop event. If you not only pass `gpsloggerevent`, but also `gpsloggerfilename` and `gpsloggertimestamp` to Tasker, then he will be able to notify his server and correlate these start/stop events with the respective location events by using the filename or the timestamp.

The nice thing about this is that if he wants reliability, he can also instruct Tasker to send his server an email (assuming he sets one up, I used to do that) containing this data, which won't be dependent on him having direct network access when Tasker receives the event from GPSLogger.

I had a Tasker task which started My Tracks recording, set all the volumes accordingly, display to full brighness and started Podcast Addict, so with one click I was able to do a lot of stuff automatically.

**Comment by danielfaust** [comment]
If you feel like it, it would also be great to have it the other way around. Let Tasker send Intents to GPSLogger to start/stop logging and also to add annotations. This way one could instruct AutoLocation to insert GeoFenced annotations through Tasker directly into the CSV/GPX files.

**Comment by mendhak** [comment]
Ok I understand now, basically providing a bit more startup-information.  I will experiment with this later today or tomorrow.  The timestamp itself though is 'now' so it would be redundant information - I mention this because I think I'm limited in the amount of info I can send through.  

For your last point that should already be possible - have a look at the list here:

http://code.mendhak.com/gpslogger/#howdoesthisintegratewithtaskerllamaorotherautomationframeworks

That is what you meant right?

**Comment by danielfaust** [comment]
Oh, nice, I didn't know that list existed. I will check it out now.

Sorry, with timestamp I meant the %STARTTIMESTAMP parameter in CustomUrlLogger.

**Comment by fatcat386** [comment]
For a long time I use android, but did not know anything about Tasker. Shame on me) Thanks for the tip. I'm sure it will be useful, among other things.

**Comment by droscy** [comment]
Thanks @mendhak, it works correcly!

**Comment by droscy** [comment]
Feature added in merge #552, thanks.
