### ISSUE TITLE
Feature request: Send stop notice to Custom URL when user stops GPS

### ISSUE THREAD

**Issue by poblabs** [mendhak/gpslogger#554]
Hi there, 

Just curious if you could add the ability to send a Stop Notice with Custom URL. Maybe something like %NOTICE or something?

This way my server can mark the user as something like `GPS OFF` when they stop sending their coordinates. I know this could be troublesome with crashing the app, or losing data coverage, but my thought is when they press the "Stop" button, it sends 1 last item to the Custom URL that they have stopped.

Thank you

**Comment by mendhak** [comment]
Hmm, the timing of your request is interesting.   I direct your attention to [this issue here](https://github.com/mendhak/gpslogger/issues/543) - I'll close this issue and have a read through that.  tl;dr -  too complex.

**Comment by poblabs** [comment]
You're right! I saw that thread about the start timestamp, but did not see the STOP request. I've had the STOP request in my mind for the last few days. Anyways, I will follow that thread. Thanks
