### ISSUE TITLE
Automatic upload using existing (ownCloud/e-mail) accounts

### ISSUE THREAD

**Issue by osirisinferi** [mendhak/gpslogger#555]
Hi there! Like your app very much! But.. ;)

I couldn't find any existing issue about this, so I'm opening this new one.

While I'm totally enthusiastic about the automatically uploading of files through many transport types, the way it currently works is more difficult as it should be. From a user perspective that is, obviously.

For example, I have the ownCloud Android app installed and my Android has a ownCloud account set up. So my first thought was: cool! A way to use ownCloud to automatically upload the files! Without any hassle!

But when I went into the configuration in GPS Logger, I found out I had to specify the ownCloud URL, user, password et cetera et cetera.

To me, this sounds kinda redundant: I already have an account set up to use.

The same for e-mail. I have `K-9 Mail` installed for my emailing. Unfortunately, `K-9 Mail` doesn't add a "global" Android account for the e-mail address used in the app. Therefore, that isn't something you could have used anyway. *But*! It does have [third party app integration](https://github.com/k9mail/k-9/wiki/ThirdPartyApplicationIntegration) through the Intents/Content Providers Android functions. So I guess you could read that as a feature request ;)

In essence, I would like to use this issue as a two-sided feature request:

* Use 'global' Android accounts for automatically uploading files, such as ownCloud or GMail;
* Specifically add support for automatically e-mailing of files through `K-9 Mail`.

Thanks a lot for your effort in general and your answer to this issue in advance :)

**Comment by mendhak** [comment]
Main reason for not using any of those methods is that GPSLogger needs the ability to do the email/upload in the background without any user interaction. 

With ownCloud Android, their own app uses the [owncloud Android library](https://github.com/owncloud/android-library) to perform the upload, so this app uses that same library too. 

With K9, they do expose intents but only for other apps to consume; so K9 can inform other apps when a message has been received.  Similar with the content provider - its URIs expose account info and messages but no means to send emails.  It can probably be done via Share but that's user interaction. So the email has to be sent direct.  The emails bit here is done via [Apache Commons Net](https://commons.apache.org/proper/commons-net/)

Those apps probably won't allow for silent invocations/uploads, that would be a security risk.  But even if they did allow it, it would require the user to install ownCloud/K9 but many users simply run GPSLogger on barebones devices so not having the extra dependency is helpful.  

Yep totally agree, this becomes user unfriendly as they have to go through many steps.  Another example is SFTP - I would have preferred to invoke Juice SSH to do the file transfers but again that's requiring users to install something. 

If you're looking to reduce the number of apps doing the same thing, I often recommend [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&hl=en_GB) - you can get it to sync your regular owncloud folders and point it at other specific folders (including GPSLogger's) to upload.  Although that doesn't solve email.

**Comment by osirisinferi** [comment]
@mendhak Thanks for your elaborate explanation and answer, makes total sense.

I'll use the existing features of GPS Logger to uplad the files. It's not that big a deal, I was just hoping the app could get even better :wink: 

I'll close this issue now, as it answered my question perfectly :slightly_smiling_face:
