### ISSUE TITLE
Generic intentsupon GPSLogger Start/Stop and intent for status

### ISSUE THREAD

**Issue by rlarranaga** [mendhak/gpslogger#557]
In my use case, i start and stop gps logging through intents. 
I see that gpslogger sends an intent to tasker when the gps starts/stops. It would be great if this intent could be made generic so other programs can tap into it. 

In my case, that would allow the program that launches the intent to make sure the start/stop was succesful, without needing tasker (I would actually update a remote bluetooth device about the status of the action. I don't know if i can tap into intents even if  they are not directed to my program, but from what i see in the code, the tasker intent is not sent if tasker is not installed anyway.

It would also be great if an intent could be added to check the status of gpslogger (logging or not logging).

Thanks!

**Comment by mendhak** [comment]
I've put an APK here if you are able to test it:  https://github.com/mendhak/gpslogger/pull/558

**Comment by rlarranaga** [comment]
Sounds great, i will test it as soon as i get home.
However, i did made an extra moficiation, that would allow you to query
status on the loggingservice by using an intent.
Is that something you would be interested in merging?
Thanks.
Regards

**Comment by mendhak** [comment]
Could you push it up to your github, I'd like to take a look to see what's involved.

Reason for not pull request - I've already got a [Content Provider](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/ContentApi.java), want to see if it can solve a similar problem statement (later anyway)

**Comment by rlarranaga** [comment]
Yeah, i can, but ill update it with your new code if that is ok with you?
Regards

**Comment by mendhak** [comment]
Yes please thanks for the help.

**Comment by rlarranaga** [comment]
You can look at it here:

https://github.com/rlarranaga/gpslogger-issue557/

Its only very simple changes, i basically added an intent that lets you
call the broadcast event that you changed. That allows external apps to
query the status. I use it because i remote controll the gps logger with my
pebble, and like to be able to query status of the logger :)

Let me know if it is good enough for you guys to use.

Regards

**Comment by mendhak** [comment]
I see how you've done it, OK that makes sense.  

I've manually grabbed and merged your changes here: https://github.com/mendhak/gpslogger/pull/558/commits

**Comment by rlarranaga** [comment]
Cool, glad i could contribute, and it helps me a lot too.
Regards!

**Comment by mendhak** [comment]
v88 has been released to market.  Closing thread as part of cleanup work.
