### ISSUE TITLE
Battery in CSV, force to Integer (very low prioity issue)

### ISSUE THREAD

**Issue by danielfaust** [mendhak/gpslogger#559]
I just noticed that in the CSV the Battery occasionally has some "precision issues", a screenshot is attached.

It would be good to force it to an int in order to get rid of this issue. It may affect other file formats as well, I have not checked.

![battery-to-int](https://user-images.githubusercontent.com/320098/27014886-da1c4292-4f01-11e7-8ce8-b8255646d65a.png)

**Comment by mendhak** [comment]
v89 released to market

\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
