### ISSUE TITLE
Items out of order

### ISSUE THREAD

**Issue by danielfaust** [mendhak/gpslogger#562]
In the CSV file items occasionally get logged out of order. This also occurs in kml files, haven't checked the other ones.

Google Earth is intelligent enough to correct this internally, so maybe it should be left as-is, since post-processing software can always reorder the items.

2017-06-13T17:59:31.000Z,0.0,0.0,467.0,4.0,252.0,1.1047624,13,gps,0.7,0.7,0.9,48.0,,,,100.0,
2017-06-13T17:59:34.000Z,0.0,0.0,467.0,3.0,233.0,0.5536244,13,gps,0.7,0.7,0.9,48.0,,,,100.0,
2017-06-13T17:59:37.000Z,0.0,0.0,468.0,3.0,,0.0,12,gps,0.7,0.7,0.9,48.0,,,,100.0,
2017-06-13T17:59:40.000Z,0.0,0.0,468.0,3.0,,0.43,13,gps,0.7,0.7,0.9,48.0,,,,100.0,
_2017-06-13T17:59:**36.427**Z,0.0,0.0,,20.602,,,0,**network**,,,,,,,UNKNOWN,100.0,_
2017-06-13T17:59:45.000Z,0.0,0.0,468.0,3.0,189.5,3.56,13,gps,0.7,0.7,0.9,48.0,,,,100.0,

Or would it make sense to discard these items? Possibly not, right? Google Earth is ignoring these items. It doesn't include them in the path (just noticed that it doesn't ignore all of them, no idea on how it decides; not by distance).

**Comment by mendhak** [comment]
I've seen this plenty with network time - quite often networks have their [NITZ](https://en.wikipedia.org/wiki/NITZ) clocks off and their accuracy falls behind.  NITZ is loosely enforced.  One user even tried to chase this with their operator but the network insisted it was still valid time.   I eventually found in [their reference](http://www.etsi.org/deliver/etsi_ts/122000_122099/122042/14.00.00_60/ts_122042v140000p.pdf): 

> Universal time indicates the time at which this information element (see 3GPP TS 24.008 [2]) may have
been sent by the network. Thus it can be assumed that the accuracy of the time information when it
arrives at the MS is usually within a couple minutes.   

I've also seen some network time implementations send strange alphanumerics.

Ignoring location-network time and using the system time instead - that doesn't work either as most phones internally use NITZ to sync their own time and very few users use other sources.

**Comment by danielfaust** [comment]
Do you have any recommendation on how to deal with this during post-processing? Those timestamps are then the sensors' timestamps, ie the one sent along in the NMEA sentence and mobile-network packets?

I've also experienced that the Network Provider's time is off by a ridiculous amount of time as I'm running my own GPS based NTP server (Raspberry Pi) since I required precise time on the entire intranet.

This "network" (as in not "gps") time. When it is generated for GPSLogger, is it possible that the request gets issued, and a couple of seconds later the answer comes in, or does the answer follow the request almost immediately, as if the device is using a cached value? I'm asking because I'm not sure if it then makes sense to reorder the items if it is indeed the Network Provider's time which is off, because then at least the position would be "accurate" (if that's even a possible term considering that it is a network based location)

**Comment by mendhak** [comment]
It's hard to say - I can't think of a reliable way of doing this in post processing.  And it's possible that any location received (be it satellite or network) is cached, but there isn't a way in the location object to know if it was cached.

I am now thinking again that this should be done in the app itself.  What if - simply filter out/ignore any locations that come in whose `location.getTime()` is less than the `Session.getLatestTimeStamp()`.  Makes sense, right? This would surely eliminate some of the cached locations.  I'm trying to poke holes in this idea in my head.  I can see that this should result in fewer network based locations relative to satellite based.  Possibly.

**Comment by danielfaust** [comment]
I wouldn't discard them. How about modifying the time so that is is `Session.getLatestTimeStamp() + 1 ms` (and possibly flag it)?

Wouldn't discarding them be a possible cause for messing with annotations, eventually losing them or delaying them so much that it could get overwritten with a new annotation? I'm not sure, I can't really remember how that desc variable turns into an annotation, If I recall it correctly it is a global static variable, right? I'm worried that if an annotation is "attached" to such an out-of-order location update and that update gets discarded, that the annotation might get lost, or "attached" to the next update which could come with a big delay. This sounds very improbable, but is worth to take into consideration.

On the other hand I'm also not sure if modifying the delayed updates' time is the correct way of handling it. Couldn't it have some weird cascading effect, as this modifies the `Session.getLatestTimeStamp()` and thus makes this last, modified insert an "authoritative" one for the next updates to come? That sounds even more improbable to cause problems than the issue with loosing an annotation.

**Comment by mendhak** [comment]
Yeah it's possible that if the app keeps receiving a bunch of bad locations eventually any new annotation will overwrite the old.  However modifying the time is misleading - basically the `getTime()` indicates when the fix occurred.  Don't want to go down that weird route. 

Safest option is to just let GPSLogger keep writing to file whatever it is told. 
For better accuracy/time, disable network based locations. 
Network locations are a real headache always.

**Comment by danielfaust** [comment]
Yes, maybe it's better left as-is. Assuming that it just got delayed somewhere inside the Google Play Services (that library serves the location updates, right?), but has a relatively precise location, then modifying the time would cause a jump to a past location for one update, which sounds bad.

I'm ignoring "network" updates all together in post processing, but I can do that because I'm getting a GPS update every second, so it's just a solution for my scenario. Also I fully control post-processing and don't do it in realtime (I just upload the CSV and analyze it), which isn't the case with OpenGTS.

To me this issue isn't really an issue anymore. I'd place it in the backlog at the last position with the lowest priority.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
