### ISSUE TITLE
Data input system

### ISSUE THREAD

**Issue by danielfaust** [mendhak/gpslogger#568]
I'm planning on building a Raspberry Pi 3 based datalogger for my bike to collect wheel rotation frequency, environment temperature and humidity and the like. I'm planning to use the RPi3's Bluetooth chip to connect it to the phone.

Maybe it would make sense to think about creating input sources similar to how loggers and senders work, where the current GPS data source would be one of them.

What do you think of this?

**Comment by lenucksi** [comment]
One could also use this to provide remote controls to make anotations - as in "button x pressed on BTLE remote, add annotation x with current timestamp" or the likes.

**Comment by danielfaust** [comment]
Good idea.

As I stated in another issue, I'm having AutoLocation together with Tasker annotating GPSLogger recordings with a location name when I enter a GeoFence, which is nice.

`2017-07-06T18:22:23.000Z,lat,lng,453.0,3.0,203.0,8.450999,11,gps,0.7,0.7,0.9,48.0,,,,95.0,"Brücke Wanderweg - lat - lng - 57.0 - 2017-07-06T20:22:22.145+0200 - Inside"`

But my issue with this is that the annotation triggers a GPS lookup and gets attached to it. As I'm logging with an interval of 1 second, this works.

But I think that it would be somehow better to allow for positionless insertions into the file, ie have a CSV entry only consist of a timestamp and the annotation. I don't know if this can work with KML files and the other ones, but it shouldn't be a problem with CSV.

`2017-07-06T18:22:23.000Z,,,,,,,,tasker,,,,,,,,,"Brücke Wanderweg - lat - lng - 57.0 - 2017-07-06T20:22:22.145+0200 - Inside"`
`2017-07-06T18:22:23.000Z,,,,,,,,raspi,,,,,,,,,"temp:20;humid:40;freq:12;pulse:120"`
`2017-07-06T18:22:23.000Z,,,,,,,,raspi,,,,,,,,,"button:1"`

where `tasker` and `raspi` is the provider field. Eventually file formats which can't handle locationless inserts can ignore these providers then.

**Comment by mendhak** [comment]
I can see what this is useful for, though it's not suited for GPSLogger.  That's more of a 'data logger' or a convenience function to make post processing easier.  Ultimately only so much can be done while keeping resource usage low; receiving from Bluetooth requires looping+reading forever, a battery drain.  Easier method is to expose the latest data over HTTP on the RPI3, get Tasker to HTTP GET that URL every few seconds and act upon it when necessary.  However that is also going to become a battery drain quick and won't work in doze mode.

**Comment by lenucksi** [comment]
@mendhak idea of using a HTTP get together with Tasker sounds interesting as well.
@danielfaust If you are interested in coding up stuff even if it will take more battery when activated you are welcome to provide a PR to my fork of GPSLogger.
As long as it can be deactivated neutralizing any effects on the battery in the final executable I'd be fine with it. I currently have a closed beta in Play Store for it, but I may end up publishing it as a normal release in some time too.
