### ISSUE TITLE
FTP Test Upload Error: recvfrom failed: ECONNRESET

### ISSUE THREAD

**Issue by kcole16** [mendhak/gpslogger#569]
When trying to test the ftp upload, I'm receiving the following error (after a successful login and 203 code):

recvfrom failed: ECONNRESET
(Connection reset by peer)

My ftp server is secured via username and password, no SSL. Any ideas?

**Comment by mendhak** [comment]
What settings, preferences do you have set on the FTP screen? You can also
try to enable debug log in general settings then try connecting again and
have a look at the debug log file.

**Comment by kcole16** [comment]
I'm seeing the same message in the debug log. 

For settings, I have the host, username, password, and port filled out, and everything else as default.

**Comment by mendhak** [comment]
You must be seeing some of the commands being sent in the debug log for example it'll be connecting, showing a banner, then attempting some command and failing. Can you show the debug log.  You can email it to gpslogger at mendhak.com

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
