### ISSUE TITLE
Wrong TIME / TIMESTAMP values

### ISSUE THREAD

**Issue by jacaato** [mendhak/gpslogger#572]
I am on UTC+02 summer time (at winter UCT+01) in Poland.
I have got some problems when logging to custom url.
Here is my issue:
```
{"alt": 23660, "lat": "50.28458666666667", "lon": "18.67645", "tim": "Thu, 03 Aug 2017 16:21:16 GMT"}

{"alt": 23780, "lat": "50.28451666666667", "lon": "18.676248333333334", "tim": "Thu, 03 Aug 2017 16:21:27 GMT"}

{"alt": 23810, "lat": "50.28447666666666", "lon": "18.67618", "tim": "Thu, 03 Aug 2017 16:21:38 GMT"}

{"alt": 23810, "lat": "50.28447666666666", "lon": "18.67618", "tim": "Thu, 03 Aug 2017 16:21:49 GMT"}

{"alt": 26500, "lat": "50.2845726", "lon": "18.6765213", "tim": "Thu, 03 Aug 2017 17:22:00 GMT"}

{"alt": 23810, "lat": "50.28447666666666", "lon": "18.67618", "tim": "Thu, 03 Aug 2017 16:22:11 GMT"}

{"alt": 23810, "lat": "50.28447666666666", "lon": "18.67618", "tim": "Thu, 03 Aug 2017 16:22:21 GMT"}

{"alt": 23810, "lat": "50.28447666666666", "lon": "18.67618", "tim": "Thu, 03 Aug 2017 16:22:31 GMT"}

{"alt": 24040, "lat": "50.284394999999996", "lon": "18.67627", "tim": "Thu, 03 Aug 2017 16:22:42 GMT"}
```

As you can see it sometimes logs right (~17:22) but more often it is wrong (UTC+03) time. The same comes to TIMESTAMP.
As far as I can see it is corelated with rounding problems in lat/lot values.

**Comment by jacaato** [comment]
This is how it looks like in html get:
```
?lat=50.28429833333333&lon=18.676238333333334&time=2017-08-03T16:47:47.000Z&alt=257.6&timestamp=1501778867
?lat=50.2845726&lon=18.6765213&time=2017-08-03T17:47:26.316Z&alt=265.0&timestamp=1501782446
```

**Comment by mendhak** [comment]
I have seen this problem a few times. What's usually happening is - the points are coming from both satellite as well as network; the problem is the network operator is providing incorrect timestamps and that's showing up as the wrong time in your URLs.   To prove or disprove this you can try to add `%PROV` to your Custom URL and you should see that whenever the time is wrong, it's network rather than gps (satellite).

You should get a better result if you go to performance settings, then in the location providers, uncheck network.

**Comment by jacaato** [comment]
Thank you for feedback.
Well, actually in my case it's reversed:
```
/trip/position?lat=50.28458333333333&lon=18.676468333333332&time=2017-08-03T17:47:05.000Z&alt=236.1&timestamp=1501782425&user=b5d50ebf-4938-47bc-b5c9-a7d62e8522b8&prov=gps
/trip/position?lat=50.2845726&lon=18.6765213&time=2017-08-03T18:46:54.299Z&alt=265.0&timestamp=1501786014&user=b5d50ebf-4938-47bc-b5c9-a7d62e8522b8&prov=network
```
GPS gives wrong time but network gives proper time.

**Comment by mendhak** [comment]
Well that's certainly new.  Not seen that before - since the satellite time is provided by the hardware, not network. What phone is this?

**Comment by jacaato** [comment]
It is Lenovo P780.
Phone time seems ok.
I have got set automatically setting time and timezone from network.

**Comment by mendhak** [comment]
Yeah the GPS time is provided by the satellites themselves. 

More stuff you can try (to isolate the problem)

Try logging to NMEA file, and show some lines from there or just post the file here.  In NMEA, the `GPGGA` line contains a time that we can look at.

Another thing you can try - another [GPS Logging application](https://play.google.com/store/apps/details?id=eu.basicairdata.graziano.gpslogger&rdid=eu.basicairdata.graziano.gpslogger) - I've not used this but its source code indicates that it uses satellite time

**Comment by jacaato** [comment]
At first, sorry for delay :)
There must be something wrong with my phone, with other phones everything seems OK, but with mine regardless of application, the results are wrong. So I think this issue can be closed.

**Comment by mendhak** [comment]
No problem, I'm also a very delayed person :)  Thanks for update!
