### ISSUE TITLE
altitutude unit conventions for display

### ISSUE THREAD

**Issue by tsteven4** [mendhak/gpslogger#576]
Should the altitude units be either feet (if Imperial units are being used) or meters?  Does it make to use miles and km when the altitudes are large?  getDistanceDisplay currently uses miles if meters is > 804 or km if meters > 1000.  This seems reasonable for horizontal distances but not for altitude.  The altitude conventions I am familiar with would be either feet or meters regardless of the magnitude, at least for things that are close enough to the earth to have a GPS fix.

**Comment by mendhak** [comment]
v89 released to market

\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
