### ISSUE TITLE
Logging more frequently if connected to AC charger

### ISSUE THREAD

**Issue by mehrdadn** [mendhak/gpslogger#582]
Hi,

I just wanted to suggested a feature for allowing different parameters to be set based on the charging state and the remaining battery (e.g. if charging and we have at least 25% battery then log at maximum frequency). I frequently connect the phone to my car's charger and it would be wonderful if it could log at maximum frequently at that point, since frequent sampling opens up a number of possibilities with regards to the data (such as traffic analysis).

Thank you!

**Comment by mendhak** [comment]
Have a look at an automation tool like Tasker - you can use such a tool to detect what it's connected to (I think) and based on that condition, control GPSLogger and increase its logging frequency. 

http://code.mendhak.com/gpslogger/#howtoautomategpslogger

The reason for using an automation tool is it's an external condition and many people have different external conditions to trigger different kinds of behaviors.

**Comment by mehrdadn** [comment]
Oh, I already use Tasker, but I didn't realize it was possible to trigger GPSLogger from it! If that's the case, that sounds great; I'll take a look and if there are any issues I'll report back; thanks!

**Comment by mendhak** [comment]
#
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
