### ISSUE TITLE
Start on bootup fails after some time on some devices

### ISSUE THREAD

**Issue by jaimevives** [mendhak/gpslogger#589]
I've been using this great app for some weeks, and it works very well for my purposes, but I've a strange problem: on some devices (2 out of 7), the setting for the start on bootup fails after some days, and the app will not start automatically anymore (even if the setting is still checked). Opening the app manually works fine, and the app starts to register fixes correctly until the phone is turned off. 

I don't know if this is an issue with the app or the phones, but is perhaps worth mentioning the phones are all the same brand and model, with the same settings and apps installed.

Has anyone any idea about what could be causing this problem?

Regards,

--
jaime

**Comment by dtraub** [comment]
I am seeing this as well on a Galaxy S7.  I do not see it on the Nexus 6p or a Droid Turbo.  Its most noticeable on the Galaxy when the battery dies.  Every time the battery dies and it boots back up after being charged you have to manually start it.  After that it works fine until the battery dies again.

**Comment by jaimevives** [comment]
In my case, it has nothing to do with the phone going out of battery. Usually they are turned off each night with some remaining battery load, and put to charge overnight. The phones are 2 Alcatel One Touch Pop C9... arguably a really crappy and old device, so I am planing to replace them soon.

**Comment by mendhak** [comment]
Sorry for delay - did find a bug.  I'll issue fix soon.

**Comment by mendhak** [comment]
v91 is released to market.

**Comment by jaimevives** [comment]
Seems to working fine so far: I'm turning the phones off every night, and in he morning it gets up and running automatically when the phone is turned on. Thanks again...
