### ISSUE TITLE
Feature request: ulogger server support?

### ISSUE THREAD

**Issue by fm444fm** [mendhak/gpslogger#590]
Would it be possible to add among the list of providers (near to the "Log to custom URL" and "Log to OpenGTS") the "ulogger" server [https://github.com/bfabiszewski/ulogger-server] ?
I currently use gpslogger with "log to custom url" via phonetrack [https://gitlab.com/eneiluj/phonetrack-oc] but I cannot use that option with ulogger as there is no way (as far as I could discern) to specify authentication (user:password) using the "Log to custom url" interface.
The Ulogger server has the possibility to select and show a list of tracks, and would combine perfectly with the "new track every day" option of GPSlogger, sending %FILENAME as trackid for ulogger and hence saving and sorting the gps data correctly for each day.

Thank you

**Comment by mendhak** [comment]
Hi can you try something like

Http://username:passwd@example.com/etc/etc

I believe it should parse the credentials and send as a basic
authentication header. I forgot to document it somehow

**Comment by fm444fm** [comment]
Thank you mendhak for the quick reply. I tried what you suggested, and also added some code to the ulogger-server client.php to automatically look for a trackname named %FILENAME and retrieve its "trackid" or create a new one if the trackname is not found in its db... but still the authentication is the major obstacle. Unfortunately, ulogger-server does not use the basic http authentication but authenticates through /auth.php

**Comment by mendhak** [comment]
Sorry been on long holiday.   Since `/auth.php` is bespoke, that can't be supported, since it would be a specific code change just for ulogger server.  I've posted a question in your thread on ulogger-server/36

**Comment by mendhak** [comment]
Hey @fm444fm I'm closing this - my aim is to avoid extra work and just let custom url logger do the work (otherwise I'd end up with a lot of extra custom loggers due to minor differences) however the author of ulogger would need to make some changes to allow for machine-machine comms.  One example is a non expiring token, or some kind of API token, or HTTP Basic-Authentication.  If that does get implemented, do start a new thread.
