### ISSUE TITLE
Feature request - Accuracy filter options

### ISSUE THREAD

**Issue by aaaaaa111111** [mendhak/gpslogger#591]
Hi,

First I want to thank you for this very good gps logging app.

The feature I request here is (I hope) quite simple to implement. It is about accuracy filter:

It would be usefull to have option to not discard any point if it had at least some coordinates informations, even if it does not match the accurarcy limit fixed by user. So the ap will still wait for the time fixed by user (Duration to match accuracy) to reach the accuracy threshold, if it goes under it saves the point as usual, but if not it still keeps the best accuracy found within this duration, whatever the level and the source (gps or network). And of course it also save the accuracy value like for any point. Then later it is easy to filter out all the saved points by accuracy levels and use the levels we need.
So in this case the accuracy filter would be here to incite to find some level of accuracy winthin fixed duration, but without discarding less precise levels if there is no other choice.
The old Backitude app permits this behavior I think. Maybe there is a way to do that already in GPSLogger, if it is the case sorry but I didn't find it.

Regards

**Comment by thinrope** [comment]
I am still trying to figure out how using many filters work in combination (and poking the code). If I am right in my understanding a simple one-line change of this code near [GpsLoggingService.java#L817](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L817) can make it happen:
````Java
                if (currentTimeStamp - session.getFirstRetryTimeStamp() > preferenceHelper.getLoggingRetryPeriod() * 1000) {
                    LOG.warn("Only accuracy of " + String.valueOf(loc.getAccuracy()) + " m and timeout reached." + getString(R.string.inaccurate_point_discarded));
                    //Give up for now
                    stopManagerAndResetAlarm();
````
Instead of giving up, record that at the and of the interval.
Now that will change the logic, so other users may be affected and thus documentation and UI needs to be changed.

This seems like a more reasonable behavior (i.e. do not loose data, even if inaccurate) than the current, @mendhak what do you think?

**Comment by mherrmann3** [comment]
This would be a very useful feature, as GPS accuracy can often vary greatly (e.g., when being in a city with large houses). Until now, I have profiles for different environments, which would not be necessary anymore with such a feature. BIG VOTE! 👍 👍 👍

**Comment by mherrmann3** [comment]
FYI: similar (if not duplicate) to #453

**Comment by mendhak** [comment]
I've been working on an accuracy option, description and test APK here: https://github.com/mendhak/gpslogger/issues/654#issuecomment-1973452236

**Comment by mendhak** [comment]
v130 is now on FDroid and the releases. 

The new option uses the time period to pick the best location it can find. I didn't want to make it complicated by having a range, as there is already a lot going on in there.  This should help with jumpy lines and make things smoother at the expense of time. So you'll probably want to experiment here, eg, don't make the duration too long, maybe 5-10s will give it a better chance of getting a good point. 

![image](https://github.com/mendhak/gpslogger/assets/746276/25e434fc-c4af-4c0c-9c30-17447ac8ceaa)
