### ISSUE TITLE
email issue when using ssl

### ISSUE THREAD

**Issue by updatede** [mendhak/gpslogger#593]
when sending email with "Use SSL" on , gpslogger will issue starttls, lead to handshake fail with mail server. it should use starttls only at plaintext channel not ssl/tls channel.

**Comment by mendhak** [comment]
Which mail server are you using? I've tried this against the common ones (GMail/Yahoo etc) and locally with postfix.  If you're using postfix can you show your main.cf or any extra config

**Comment by updatede** [comment]
My mail server is smtp.qq.com ,it offers port 587 for ssl-upgradeable cleartext  and port 465 for ssl/tls. When I send test email, I try port 587 with "Use SSL?" off , it's fine. But when I try port 465 with "Use SSL?" on , "Connection Error." occur with details " Could not send email handshake failed 220 ready to start TLS Handshake failed . So I guess gpslogger wrongly issue starttls command on ssl/tls channel. Because ssl/tls need not to upgrade to ssl/tls , starttls should only be used on cleartext port. I prefer pure ssl/tls, because starttls need extra round trips for upgrading to ssl/tls.

**Comment by updatede** [comment]
And Gmail apparently can't work with gpslogge.r I tried gmail's ssl/tls channel  smtp.gmail.com on ssl/tls port 465, when connected and issue command starttls , it return error "Authentication Required". You can test gmail server using this command:" openssl s_client -crlf -connect smtp.gmail.com:465" and manaully input smtp commands.

**Comment by updatede** [comment]
You may misunderstanding the ssl connection of smtp, there are two ways , one way is connect to smtp through cleartext and upgrade this connection to ssl by using command "starttls", the other way is connect directly through ssl, "starttls" should not be issued  when using this way.

**Comment by mendhak** [comment]
Interesting about the Gmail test you did.  I did the same as you - smtp.gmail.com, port 465, Use SSL=true, I'm able to successfully send an email. 

I'll do a little more testing today but I suspect the "use SSL" setting is just an issuance of `STARTTLS`, although over [here](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/senders/email/AutoEmailJob.java#L116) I'm setting implicit=true.

**Comment by updatede** [comment]
execTLS() will send STARTTLS, source code is:
public boolean execTLS() throws IOException
 {
      if (!SMTPReply.isPositiveCompletion(sendCommand("STARTTLS")))
       {
           return false;
           //throw new SSLException(getReplyString());
        }
        performSSLNegotiation();
        return true;
    }
smtp.gmail.com  return error on starttls over ssl, performSSLNegotiation() inside exeTLS() will not be called, so you can send email. But smtp.qq.com return ok on starttls over ssl, handshake perform over ssl again, so failed.
Since you set ssl implicit , ssl handshake complete when call connect(), you should not call execTLS(), because that's explict, will send starttls and  second ssl handshake is possible .You should change it like this, so it can work with every mail server:
 if(!smtpUseSsl && client.execTLS()){
     client.ehlo("localhost");
 }

**Comment by mendhak** [comment]
Yep just making some changes, thanks for narrowing it down.  

I've now created an APK if you want to sideload and test it out. I've also edited the "Use SSL?" text to "Implicit SSL".  

[APK](https://drive.google.com/open?id=1u8S9h7d53fRi25C6DmWy0R4FAf18G8lS), [Signature](https://drive.google.com/open?id=1vzlvrtHY4i2nAQyeB_oeA9yNH5UufIlw), [Checksum](https://drive.google.com/open?id=1ruIddk_J_f-YdjktkIqhP6LIP8vo4gTg)

Just to address your earlier comment - I wouldn't necessarily say I'm misunderstanding, it's that the RFCs are not clear and so there are dozens of implementations of SMTP servers I have had to deal with.  To further add to the mixup, [port 465 is deprecated](https://en.wikipedia.org/wiki/SMTPS) in favor of [port 587 ESMTP](https://en.wikipedia.org/wiki/Extended_SMTP) - however many servers continue to support both.  It's the same nightmare with FTP/S.

**Comment by updatede** [comment]
yes, the new APK works. I can successfully send email with smtp.qq.com using "implicit ssl" on. For me, I prefer 465, because 587 starttls need more round trips for every mail. Even gmail can send mail successfully on 465 by refusing starttls command,  it also produce unnecessary error and round trips. Maybe every mail sever should close connection when receive starttls on a tls connection, that make troubleshooting easier.
Another issue: gpslogger often upload before current successful log, so I can see position only at least a log interval ago , not current position.  In log view I see log interval and upload interval are independent,  no matter what log and upload interval setting, they always interlace, especailly when eligible gps fix need more time.  So could you add a option , that automatically upload just after a successfully log? so I can always get the current new log.

**Comment by mendhak** [comment]
v90 released to market.

The upload and logging timers have been kept deliberately separate - a successful log is not guaranteed, points can be skipped, so it introduces unpredictable behavior in the timings of the upload.
