### ISSUE TITLE
When is the position of an annotation being taken?

### ISSUE THREAD

**Issue by simonschllng** [mendhak/gpslogger#596]
Will an annotation be saved at the current location of when I press the _pencil_ button or when I hit ok in the annotation dialog?

From looking into the code I guess it takes the position and timestamp when user hits _ok_ in the dialog. Is it the same for the notification and the MainActivity button? I am not a Java developer. 

I see big jumps in my gpx paths, all occurring at annotations.

**Comment by mendhak** [comment]
Hi, it's actually a lot cruder than that; the annotation button only opens a dialog. When you then type some text and press OK it then starts searching and when it finally gets a location fix it records it with the annotation.  One difference is, when an annotation is being recorded, many of your filters get ignored, that would explain why you see jumps.  There is likely a better way to do this.

One way you can reduce jumps is in location listeners, go in and disable network listener, just use satellites.

**Comment by simonschllng** [comment]
Thanks. This explains everything. I need to annotate while moving with
10-60km/h. Writing the text takes a while. So this is not working for me.
Better would be to take the last waypoint, wait for the next and use the
middle in between.

Nobody else with this scenario?

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
