### ISSUE TITLE
Do you think getting battery level is costly ?

### ISSUE THREAD

**Issue by eneiluj** [mendhak/gpslogger#597]
There is a discussion in an [Ulogger issue](https://github.com/bfabiszewski/ulogger-android/issues/15) about the cost (in battery) to get battery state in Android.

Considering GpsLogger gets it and is battery-saving-oriented and gets the battery level for each logged point, what do you think about it ?

**Comment by eneiluj** [comment]
Thanks for you answer !

**Comment by mendhak** [comment]
#
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
