### ISSUE TITLE
Logging interrupts after a minute

### ISSUE THREAD

**Issue by meklema** [mendhak/gpslogger#598]
Hello!
Thank you for a great app!
I'm sorry but I have a problem with GPS Logger.
Usually I start GPS Logger, start running and everything is Ok but today it stopped logging after may be a minute. Actually it has happened several times during a month or so. It starts logging and works all the time required (about an hour usually), but only about 100-200 metres are actually logged.
I use it on a smart phone with Android 7 and I changed the battery setting for GPS Logger as to protect it from doze function but it hasn't helped. It seems that GPS unit stops supplying data to the GPS Logger after a while. I have no idea how to fix it.
Do you have any suggestions?
Thank you!

**Comment by mendhak** [comment]
What phone? What settings have you got?  Time interval, which location listeners?

One thing you can try is - enable the debug log.  Then start logging again and reproduce the problem, then have a look at the debug log or post it here.  If there are big pauses in the debug log then it's likely an indication of the phone dozing the GPS anyway, regardless of the battery setting.

**Comment by meklema** [comment]
Hello.
Thank you for your application and your help!
I use Huawei Honor 6X.
The logger takes GPS data every minute. It has been pretty enough.
GPS on this phone usually works great even in a wild forest. The module uses both sattelites and info from mobile phone network and we have lots of towers here for mobile network.
I used to navigating via different apps. There has been no problems.
I haven't checked other navigating programs on the phone now.
In my practice your application has always worked rather good, thank you for the great work.
The problem emerged this autumn possibly after I had installed several oficial updates from Huawei.
After these updates the phone has Android 7 installed.
I suppose the updates are to blame.
But I am not 100 % sure.

Here I supply log-file and gpx-file.
This experiment supports my suggestion that after starting the app writes down one or two points than stops logging.
Let me describe my movements on the 28th of November.
I went from home at about 7 o'clock in the morning and started the logger. After several seconds I stopped logging because there were no coordinates on the screen displayed so I started recording again. Coordinates this time were on screen. After I had covered about 1 km I stopped recording, closed the app from it's menu, cleared the phone memory and turned off phone's gps unit.
In the evening I decided to write another track for more information to analyse. I was in my friend's house. At about 23 o'clock I went out and started the logger. Again there were no coordinates displayed on it's screen even though 25-27 sattelites were detected. I turned off recording and started recording again. This time coordinates were on screen. Than I spent about 15 minutes going home and covered about 1,5 km. When I reached my house I stopped recording, closed the app from it's menu, cleared the memory and turned off phone's gps unit.
Surprisingly the app wrote all my movements in one file.
It wrote the very beginning at my home at 7 a.m. when I first started logging and it wrote the point(s) at the next start of logging at 11 p.m. Eventually it looks like I spent a plenty of hours moving from home to my friend's house which is totally incorrect.
I hope my experience will be useful for improoving this aplication which is great in fact.
Sorry for my English.
Thank you!
[message-11703.zip](https://github.com/mendhak/gpslogger/files/1514865/message-11703.zip)

**Comment by olejorgenb** [comment]
I don't have much to add besides that I strongly suspect something similar happening to me too. (xperia Today I'm almost certain I checked that the app was running in the morning. When leaving from work I notice the status icon is missing and starts the app again. When checking the files all points from the start of the day are gone (assoc: data loss?).

It's not the first time I've noticed the app suddenly stopping (I've also excluded the app from the battery saver) but it's the first time I've checked the files afterwards. I've enabled the debug log and will report back if it happens again.

**Comment by scrunchy** [comment]
Hi. Love the app!   Been using this great app and also the pedometer app (j4velin on github) for 6 years or so with no worries up til last month. Was on S5 running Lineage 14.1 (Android N).  Got a new S9+ phone last month running Touchwiz version of Android 8.0 and now whenever I start to log using gpsLogger it locks up the pedometer app and also fails to log the gps track with any accuracy and a bunch of missing points.  Both gpsLogger and pedometer excluded from battery optimization and aloowed to run in background. Will go and test again now and upload resulting log file from the logger.

**Comment by scrunchy** [comment]
OK, Tried again after whitelisting GPSLogger through adb (using adb -d shell settings put global location_background_throttle_package_whitelist "com.mendhak.gpslogger" command).  No change in behaviour with gps logger still causing the pedometer to lock up immediately upon the gps location notification in the top of the home screen turn off when the fix is completed. Looking at the log file (attached) the lock up occurs at the same tim the logfile has the "WARN  GpsLoggingService.onDestroy:142 - GpsLoggingService is being destroyed by Android OS." warning written to it.  I've attached a short log file showing the event.
[debuglog 01.txt](https://github.com/mendhak/gpslogger/files/2006072/debuglog.01.txt)

**Comment by mendhak** [comment]
I had a play with Pedometer + GPSLogger at the same time, but they're both working just fine in parallel.  I tried it on OnePlus 3T and Nexus 5X.   The location notification that appears temporarily is the GPS satellite one used by the OS.  You should see it with Google Maps as well - could you try seeing if pedometer locks up while Google Maps is open and actively tracking.  

The logging line in debuglog about the service being destroyed is normal - that's what Android OS does when a service is stopped, to save on resources.

**Comment by scrunchy** [comment]
Thansk for getting back.  You're right, I tried with Google Maps and also Orux Maps and found the same behaviour in all cases so it's not your app for sure, it's more likely something Touchwiz 8.0 is doing. Unfortunately I'm stuck as I have the snapdragon S9+ so the locked bootloader....   Thanks again, I'll have to pursue other avenues.....

**Comment by ELY3M** [comment]
I have same problem with my weather app too.  samsung devices is making me not happy lately.  
Thank you for infos.

**Comment by mendhak** [comment]
In v97 uploaded a few hours ago, the app should be a bit more reliable.  I've added a 'restarter' logic - when the app gets killed, it will send a broadcast, the broadcast gets received and restarts the application.  It does mean the notification has to be more prominent now.  

It doesn't combat doze mode though so the application will still have those 20 minute pauses for example when the phone OS gets aggressive. But it should compat the service killing that kept happening.
