### ISSUE TITLE
Get gpslogger.properties from external server

### ISSUE THREAD

**Issue by cbfischer** [mendhak/gpslogger#601]
Hello,

First, congratulations... Your app is the best !
There is a easy way to improve to get gpslogger.properties from a external server (https), using a custom time interval? After received the properties file, automatically reload APP using the new config.

Thanks a lot.

**Comment by mendhak** [comment]
Thanks glad you like it 😁 

I suggest having a look at an automation tool like Tasker, Llama, AutomateIt - these can allow for custom use cases like this.  Have it download a file to one of the [preset locations](https://code.mendhak.com/gpslogger/#howcanidefineapresetfilewithmyownvalues) - then close and reload the app.  This also allows for more flexibility for you.

**Comment by cbfischer** [comment]
TKS a lot. I'll try llama automate.
