### ISSUE TITLE
SessionID doesn't change when new session is started

### ISSUE THREAD

**Issue by HCMPO** [mendhak/gpslogger#606]
Logging to URL always gives the same sessionID string even if a new session is started. Is this by design?

**Comment by mendhak** [comment]
What does your custom URL look like? I'm not aware of a session id
parameter that you can enter.

**Comment by HCMPO** [comment]
Thanks for your kind reply
Following line was taken from appache access log 

2018-01-07T16:31:11+01:00 Syno 62.205.82.166 - - [07/Jan/2018:16:31:11 +0100] "GET /GpsData/updaterold.php?latitude=51.205220064245005&longitude=4.404250681132969&accuracy=16.0&speed=1.0438341&sessionid=c7fc98c3dc9fe425&username=bertje&direction=0.03814277&date=2018-01-07T15:31:10.999Z&eventtype=android&locationmethod=special&extrainfo=&phonenumber=4100fc5ccab6a2e3 HTTP/1.1" 200 25 "-" "okhttp/3.2.0"

**Comment by mendhak** [comment]
I mean the custom URL in the settings screen, it will contain various
parameters with percentage signs like %lat and %alt, etc.

**Comment by HCMPO** [comment]
I'm sorry for mistake
URL
GpsData/updaterold.php?
latitude=%LAT&
longitude=%LON&
accuracy=%ACC&
speed=%SPD&
sessionID=%AID&
username=bertje&
direction=%DIR&
date=%TIME&
eventtype=android&
locationmethod=special&
extrainfo=%DESC&
phonenumber=%SER

**Comment by mendhak** [comment]
The `%AID` is the [Android ID](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID) of the device.  Your setup just happens to be using it against a 'sessionId' querystring parameter.  Android ID is normally static until a factory reset

**Comment by HCMPO** [comment]
Can you tell me which session string I should use to obtain a unique session ID?

**Comment by mendhak** [comment]
The %AID is unique to you, the %SER is also unique to you.  They are long lived, so normally they should reset if you factory-reset the device.  

You can also use %FILENAME which basically reflects the file name being written, which is determined by the other setting - how often to create a new file - which can be once a day, static, or based on dynamic parameters in the filename.

**Comment by HCMPO** [comment]
The reason why I want this sessiionID is to be able to query my database for separate sessions, i.e. to identify each time the GPSLogger is turned on and off. Basically this could also be done with the extraInfo parameter but it would be more interesting if such a sessionID was created automatically by the app.

**Comment by mendhak** [comment]
The application lifecycle on Android doesn't really match up with something like that - the app can be killed over the course of its usage and brought back, so the concept of a session ID doesn't match up with web applications.  But the closest to what you're describing is using %FILENAME and in the logging details screen, set "New file creation" to  "Every time I start"  or a custom file name which you input every session. Then from the Apache logs you can use that as the matching tokens.

**Comment by HCMPO** [comment]
Ok. Thank you so much for the feedback. I'll try that one. I didn't know about that %FILENAME parameter. Are there any more parameters than I already mentioned earlier?

**Comment by mendhak** [comment]
In the Custom URL screen just click on the 'parameters' option, 2nd from top. It should bring up a list of what's available. 


![image](https://user-images.githubusercontent.com/746276/34653139-7cdbe96a-f3df-11e7-9e63-362e9af8c9c2.png)

**Comment by HCMPO** [comment]
I found it. Tested your method with a custom file creation and it works perfectly well. Thanks a lot.

**Comment by mendhak** [comment]
Cheers, hope it works!  

Will close this issue soon

**Comment by HCMPO** [comment]
I found an even bettter alternative! The %STARTTIMESTAMP parameter delivers identical UTC time throughout the session. As a result all separate sessions can be easily be identified in the database records.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
