### ISSUE TITLE
Custom URL logging not working

### ISSUE THREAD

**Issue by evertonsmith** [mendhak/gpslogger#611]
Hi there,
I've set the url to my server: [serverName]/info/php
with the addition of ...?lat=%LAT
on my page I have setup: echo $_GET['lat']
And this returns nothing. I've also tried isset and it is never set.
Why is the information not getting to my server?
no errors on the apps log, connects fine

Thanks

**Comment by mendhak** [comment]
I'm not sure what you mean by getting to the server - are you seeing it in your webserver logs?  

Note that simply doing an echo in your page will echo it back to GPSLogger.  You won't see it reflected anywhere though.

You'll need to get your PHP page to capture the values (lat, long... etc) and write it to a file or a database.  

See this similar thread:  https://github.com/mendhak/gpslogger/issues/492

Hope that's what you meant.

**Comment by evertonsmith** [comment]
Working now thank you,

Funny I searched your open and closed issues looking for a solution and couldn't seem to find that one! Darn. This is what happens when you learn while coding I guess.

Will be sending coffee when this project is done!

**Comment by mendhak** [comment]
No problem. Just thinking out loud, you're not the first person to ask about writing their own custom URL receiver.  I am wondering if there's any value if I write a 'sample' Custom URL receiver which writes to a file.

**Comment by evertonsmith** [comment]
setting up the app was a breeze and clear, it was my own coding prowess that was lacking!

**Comment by mendhak** [comment]
Ah I did it anyway.  

https://github.com/mendhak/gpslogger-customurl-receiver

I'll point to it in future questions.
