### ISSUE TITLE
allow for OSM description change during tracking

### ISSUE THREAD

**Issue by PontiacCZ** [mendhak/gpslogger#616]
Hello,
I use this great software often for collecting tracklogs for OSM. I use automatic upload after finish.

The filenames are created like 20180130130134.gpx and my preset GPX description is "autem" (that means "by car" in Czech). You may see [my traces](http://www.openstreetmap.org/user/Pontiac_CZ/traces).

Sometimes I would love to change the description to be more descriptive :-) regarding current trip, for instance "Napajedla - Staré Město" so it would be easier for me to find it later on the **Your GPS traces** page.

Would it be complicated to display the current description on the main screen and make it editable during the tracking process?

![description_change](https://user-images.githubusercontent.com/9153595/35566786-ed08df0a-05c2-11e8-86cb-bbe9eba9c98a.png)

**Comment by mendhak** [comment]
Unfortunately that description field is too specific to OSM, I haven't a way to cater to every kind of uploader or logger and their specifics.  So for that reason the screens are kept generic.

**Comment by PontiacCZ** [comment]
I understand, it actually came to my mind later. OK, it was worth a shot. :)
