### ISSUE TITLE
start widget doesn't work when GpsLoggingService is stopped

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#617]
Since the update to version 91 GPSLogger runs but fails to write a track about 80% of the time, it also crashed 2-3 times. I am attaching the debug log of today's failed attempt: GPSLogger was started and stopped via widgets as usual and failed to write a track. Another navi program was running in parallel and GPS was functioning properly all the time. Android 6.0.1, Samsung galaxy S5. 
[debuglog.txt](https://github.com/mendhak/gpslogger/files/1705946/debuglog.txt)

**Comment by mendhak** [comment]
Hey same as the other - can you choose to report the crash and add a message such as 'LVMM' if possible.  Doesn't look like it's being recorded in debuglog.txt

**Comment by lvmm** [comment]
Since GPSLogger was updated in mid-January I used it about 50 times. I don't always check the logs, but when I finally looked in the local track storage folder on the phone I found about 10 tracks there - 40 runs created no tracks - not even empty ones, no files at all.  As GPSLogger crashed only 2 or 3 times during this period crashes and non-creation of tracks are not related, it just won't work. Although I might add that before version 91 it was rock solid stable and didn't crash at all. Anyway, I enabled debug logging and as soon as it happened again I filed this issue. The attached log is for the situation when GPSLogger runs, does not crash but creates no track.

**Comment by lvmm** [comment]
I found the cause of this issue: track is not created when 'start' widget is used while GpsLoggingService is not already running. If logging is stopped with a 'stop' widget service remains running (which is WRONG, programs should clean up after themselves) and subsequent invocation of 'start' widget will work, but if logging was stopped with a 'stop logging' button from the GPSLogger app the service will be terminated and the next invocation of start widget will fail, same situation when the service is terminated from application manager. Also I determined a potential cause of crashes. The following scenario: 
* make sure that GpsLoggingService is stopped
* invoke 'start' widget
* invoke 'stop' widget

leads to a crash.

**Comment by mendhak** [comment]
I think problem was with a recent change to the start stop shortcuts, I've now added the lines in to send the right intents.   Believe this also takes care of the crash I was trying to stop a non-existent activity recognition service.

If you sideload you can try this out - 

[APK](https://drive.google.com/file/d/1RZc6IXG8lZ8aW7RQcFYW8qI0_jmIO5Cc/view?usp=sharing), [checksum](https://drive.google.com/file/d/1tttv2aFk6QxNNgBu4_LYPAuQjArcOqND/view?usp=sharing), [signature](https://drive.google.com/file/d/1b5l_j-Iy2bZI0RaPaeSUzYny9fauS10s/view?usp=sharing)

Also added a bit in to `stopSelf` in the service so it should disappear from the service list.  Updated APKs just now with that too

**Comment by mendhak** [comment]
v92 released to market.

We can reopen this if problem is still around

**Comment by lvmm** [comment]
I tested the v91-issue - as far as this issue is concerned it works fine, however the service still remains running after the stop shortcut is used

**Comment by lvmm** [comment]
...but the service IS terminated in v92, all is fine
