### ISSUE TITLE
Some issues in approved German translations

### ISSUE THREAD

**Issue by dadosch** [mendhak/gpslogger#621]
**informal "du" instead of formal "Sie"**
It's more modern and adequate to use the informal "du" version. This is already the case in most translations, but it needs to be changed in the following approved translation:

_osm_lbl_authorize_description_ (see suggestion by "wein")

**missing comma**
_dropbox_authorize_description_ (see my or wein's suggestion)

**Comment by mendhak** [comment]
Hi all the translations come from [Crowdin](https://crowdin.com/project/gpslogger-for-android), I normally automate the download from there every few weeks.  

https://crowdin.com/project/gpslogger-for-android

If you have an account on Crowdin could you make that correction thanks

**Comment by mendhak** [comment]
Oh sorry - you are talking about Crowdin already.  OK I have approved it and in the next download I'll get that string
