### ISSUE TITLE
Google Drive Sync - Creating duplicate folders

### ISSUE THREAD

**Issue by digdilem** [mendhak/gpslogger#624]
For reasons I don't know, sometimes GPSLogger creates another folder of the same name when logging to Gdrive.

I have the folder set as "Gpx", and Gpslogger uploads once a day. The files are created fine, but as you see from the picture, sometimes it creates another folder of the same name. Each folder contains between 1 and 4 days .gpx files, so it's not happening every day, but enough to create quite a few folders over a fortnight.

![gpx](https://user-images.githubusercontent.com/4052275/36736329-4064d65e-1bd0-11e8-8f18-3bb9a879bd2e.jpg)

**Comment by mendhak** [comment]
You're not the first to report this.  I've been trying to get this to happen to me for a while now but never been able to.  So finding a fix becomes very difficult.

One odd thing I notice is that you have duplicate files in there. Example 20180217.gpx is there twice.  And 20180214.gpx is in there four times.  

Is your auto send interval set to 1440 or something else?  I could try to match with your values.

**Comment by mendhak** [comment]
This should be fixed in v95/96, at least I'm not getting any more emails about this.  If it happens again please reopen
