### ISSUE TITLE
Do you want Filipino Translation?

### ISSUE THREAD

**Issue by josephbuarao** [mendhak/gpslogger#625]
Hi mendhak,

Good day and how are you? I hope this message finds you well.

I am Joseph Buarao (@josephbuarao),  who has been doing high quality Filipino and Tagalog translations for several projects.

However, lately Utopian temporarily halted its support for crowdin.  So sad. That's why I'm delighted to know that just today, Utopian is back to supporting translation contributors with a condition: I must be ENABLED BY YOU AS A PROOF READER.

Consider this message as my letter of application. I am a web developer by profession and an experienced Utopian translator -these are on top of being an experienced web developer with more than 6 years of experience and specialized in the following scripting languages and technologies (HTML, CSS, JS, JQUERY, PHP, WORDPRESS and CONCRETE5). This means I know which codes are to be translated, and which ones that are to remain as it is. I am a strong advocate of thought-by-thought instead of word-by-word style of doing the translations, and I am carefully strict in grammars and spellings and proper word conjugations of my languages, Filipino and Tagalog. 

I hope to hear from you soon and work with you in the translations. You can count on me that I will do my job with utmost dedication. Thank you and more power to you.

Best Regards,
Joseph Buarao

**Comment by mendhak** [comment]
Hi it's possible to add you as proofreader - if you join the [project](https://crowdin.com/project/gpslogger-for-android) on Crowdin I can mark you as proofreader for Tagalog.

**Comment by josephbuarao** [comment]
Hi Mendhak, I already joined to the translator team. Please create Filipino Language on the project so that I can start. Thank you!

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
