### ISSUE TITLE
java.io.IOException when using custom URL with an HTTP2/SPDY target server

### ISSUE THREAD

**Issue by tessus** [mendhak/gpslogger#626]
I'm using the `Log to custom URL` setting, but I get an error in the log file, when GPSLogger tries to log a point.

Please note that I was able to take the URL from the debuglog.txt and paste it in a web browser. So doing the request via a browser or by some other means (curl, wget, ...) works perfectly fine.

I looked at my web server log, but there aren't any errors for the GPSLogger requests.

Here's the [debuglog.txt](https://github.com/mendhak/gpslogger/files/1773904/debuglog.txt)

Please let me know, if you need any additional info.

**Comment by mendhak** [comment]
Is it an `https` URL, if yes have you [validated](https://code.mendhak.com/gpslogger/#customsslcertificates) the server certificate? 

Reason for asking is, I can see

> Checking for certificate - HashCode: -1143122353, Subject: CN=REMOVED, **in keystore: false**

So the app is unable to find the target CA in the keystore

**Comment by tessus** [comment]
Yes, it is an `https` URL and I clicked the `Validate SSL Certificate`. I got the following message:

```
Success

The certificate is vaild
```

I can give you an endpoint URL, although I don't feel comfortable posting it here. Maybe you can send me an email (in my gh profile)? Do you use gpg?

**Comment by moarf56** [comment]
Hi !

I have a similar issues.
The certificated name's and the server name is different... 

They are a way for forcing that ?

**Comment by tessus** [comment]
@moarf56 Your issue is not similar to mine at all. My certificate is perfectly valid, while yours is not.

**Comment by mendhak** [comment]
Hey @tessus I'm currently on holiday so limited access. Returning on Wednesday. Yes I do use pgp can you check top of the readme you will see my key. You can email gpslogger @ mendhak.com or I'll email you when I return

Is it also ok to send test data to your url

**Comment by mendhak** [comment]
@moarf56 can you start new thread

**Comment by tessus** [comment]
@mendhak have fun at your vacation! ttyl.

**Comment by mendhak** [comment]
I think I've found it - looks like a bug on OKHTTP library which was fixed in [3.4.2 or 3.5](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-342) and it had something to do with the SPDY/HTTP2 frames.  

I simply updated the library to a later version and I'm seeing requests go through.  You should be seeing some data at that endpoint you've sent me. 

If you are able to sideload and test you can try this APK

[APK](https://drive.google.com/file/d/1c-sMvVatenJkbyYJpspWzs1PtCY_xZ4q/view?usp=sharing), [checksum](https://drive.google.com/file/d/1LUMnPOb6WPAIGqBRWtDphJCOjqL4wfWn/view?usp=sharing), [sig](https://drive.google.com/file/d/12drJNNOhvKmdgIoHm8CejcVn9Kk_A7bz/view?usp=sharing)

Otherwise I will push in the next release

**Comment by tessus** [comment]
Eureka! I've installed the APK and it works!

Btw, there was no data sent to the endpoint. Or at least there was no data recorded, since I don't see anything in the database for that endpoint.

**Comment by mendhak** [comment]
Good to know, will add this in the next release.  

I think the lack of data might be a possible encoding issue?  The last part of the URL was like this:

`lat=3D%LAT&lon=3D%LON&sat=3D%SAT&alt=3D%ALT&acc=3D=
%ACC&timestamp=3D%TIMESTAMP&bat=3D%BATT`

**Comment by tessus** [comment]
> Good to know, will add this in the next release.

Great, thanks.

> I think the lack of data might be a possible encoding issue? 

Hmm, this is weird. I've just opened the mail I sent you and it definitely looks like this:

`lat=%LAT&lon=%LON&sat=%SAT&alt=%ALT&acc=%ACC&timestamp=%TIMESTAMP&bat=%BATT`

I have no idea where the 3Ds are coming from.

**Comment by mendhak** [comment]
v93 released to market
