### ISSUE TITLE
Configured Interval not working correctly

### ISSUE THREAD

**Issue by jenslauterbach11** [mendhak/gpslogger#628]
Related to Version 92
Mobile Phone: Honor 9, Android 8.0

I have configured a logging interval of 60s.
App is running in background.

According Debuglog.txt the app only wakes up each 5min.
[debuglog_1.txt](https://github.com/mendhak/gpslogger/files/1785913/debuglog_1.txt

Regards
Jens Lauterbach

**Comment by mendhak** [comment]
I'm going to close this one - although not obvious, it's the same as #629
