### ISSUE TITLE
Start on app launch not working

### ISSUE THREAD

**Issue by doktorinjh** [mendhak/gpslogger#632]
Not sure which update broke this, but I have the "start on app launch" option selected and it will not start on launch. It has previously worked, but not in the past couple of months. Best I can tell is that it stopped working in late January or early February.

**Comment by mendhak** [comment]
Just tried, seeing the same.  I'll have a look at this later.  The 'line' appears in the debug log but nothing afterwards.

**Comment by doktorinjh** [comment]
For what it's worth (and probably not much), but I also setup a task in Tasker and tried to invoke it to start with the immediatestart switch and that didn't seem to work, either. They're probably related, but thought that I'd mention it. Thanks for your quick response!

**Comment by mendhak** [comment]
Found the problem - required a sticky event.  This should work now.  In case you want to test now I have an APK you can use (you'll still get update via Play Market)

[apk](https://drive.google.com/file/d/1YswXFysJyFF0OoVutzl4XXLxE8RBmaV1/view?usp=sharing), [signature](https://drive.google.com/file/d/1jrOZ7WD6xhL2mqyulUPUT0kNJc-P10CK/view?usp=sharing), [checksum](https://drive.google.com/file/d/1C1fYBBCF2fvWuhu5WOTE1IB6S_9ltAE9/view?usp=sharing)

**Comment by mendhak** [comment]
Regarding Tasker - I'm able to start/stop the app just fine,  possibly something else going on with your setup?

**Comment by mendhak** [comment]
v94 released

**Comment by doktorinjh** [comment]
Thanks!
