### ISSUE TITLE
GPS Speed Inaccurate

### ISSUE THREAD

**Issue by BalsDroid** [mendhak/gpslogger#634]
Hi

In GPS Logger the speeds show accurate but, when logging to file or server, it shows the speed as a different value. The attached file (a CSV recording only saved as Excel) show the speed as less than hundred km/h although some part was driven on highway/freeway where the speed actually have been above 100.

Please assist.

[20180312.xlsx](https://github.com/mendhak/gpslogger/files/1805534/20180312.xlsx)

**Comment by mendhak** [comment]
Hi see - https://code.mendhak.com/gpslogger/#whataretheunitsinwhichthevaluesarelogged

**Comment by BalsDroid** [comment]
Hi Mendhak

Many thanks for the quick response!

Thank you for clarifying, I should have picked up that it is m/s and apologize for asking such a dumb question.
