### ISSUE TITLE
GPS not disabled after Activity is recognized (re-open)

### ISSUE THREAD

**Issue by jenslauterbach11** [mendhak/gpslogger#635]
To #633 
I still think this is a problem of the GPSLogger App.

There was no other GPS Receiver App active.

The Trace shows at 17:17:42 that a new position was received.
Because of

if (!session.hasDescription() && !session.isSinglePointMode() && (currentTimeStamp - session.getLatestTimeStamp()) < (preferenceHelper.getMinimumLoggingInterval() * 1000)) {
**_return;_**
} // in onLocationChanged

the processing is stopped (position and quality is not checked!!!) but GPS stays active until minimum interval time is passed. Depending on the configured interval, GPS might stay active for a long time and drains battery.

I would expect that
- GPS reception is not activated when an Activity Update is received within configured minimum interval or
- the received point is used (and maybe later dropped due to some filters) and GPS will get disabled. Maybe some kind of force-flag is needed.

**Comment by mendhak** [comment]
We can continue in #633, no need for duplicate
