### ISSUE TITLE
Feature request: Use HTTP response for notification

### ISSUE THREAD

**Issue by vitekf** [mendhak/gpslogger#638]
Hi,
few years I used [BBG](https://play.google.com/store/apps/details?id=org.gnarf.bigbrother.gps) for logging to custom URL. And there is one nice feature - "Use HTTP response for notification - _Select this if you want the HTTP response to be displayed in the notification bar instead of the current location_"

I miss it very much in GPSLogger which is now preferred for online tracking for paragliders - https://github.com/vitekf/MultiTracker
Could you please add this feature to the GPSLogger?

**Comment by mendhak** [comment]
I am struggling to see any reason for this.  Why should a notification show the contents of an HTTP response? It becomes another avenue of support in which there will be expectations on how that content is to be displayed.  

The notification exists mainly to tell Android OS not to kill the service if possible (foreground service).  Aside from that it's a bit of information for the user to know that the app is running (or stopped) and shortcuts to the annotation/stopping action.

**Comment by mendhak** [comment]
That's really niche, and sounds more along the lines of debugging.  The HTTP requests are sent out through a job queue so they get bunched up in case a missing connection returns - adding these responses to the notification would greatly complicate this workflow, so I'm not looking to do this.  

The closest thing to that in the app is the log view where you can see the response code coming back, and the debug log might contain (I think) the response body, but that's it.
