### ISSUE TITLE
Issues with Huawei 9 and Android 8

### ISSUE THREAD

**Issue by digdilem** [mendhak/gpslogger#642]
To be fair, I have had problems with other apps since my Huawei 9 auto-upgraded to Android O earlier in the week, such as background apps being frozen by aggressive battery management. This management appears to be Huaweis own "Phone Manager" or "EMUI" apps, both also upgraded to v.8 along with Android, and they ignore Android's own battery management system...

It's very frustrating when trying to listen to an audiobook and it keeps pausing every 9 minutes. Unlocking the phone shows that app's widget still shows it playing, but until it's brought to the foreground it stays silent. That suggest a kernel-level freeze of apps to me, rather than an forced shutdown.

Anyway - since the upgrade, files don't seem to be created by GPSLogger any more. Whenever I open GPSLogger, it shows the normal "Stop logging" button showing all is okay.

Also, the auto-upload (which has always worked okay before) no longer works.

Additionally, when I opened GPSLogger and tried to Manual Upload button for Gdrive, I was met with the following error.

![screenshot_20180413-214114](https://user-images.githubusercontent.com/4052275/38757735-078f983c-3f66-11e8-81a5-b7970078fea0.jpg)

Forgive me if you deem this is not strictly a gpslogger issue - and if you think it is not something you can or should fix, feel free to mark this issue as closed.

Thanks

**Comment by digdilem** [comment]
Note: Email upload works fine when done manually (for files created before the update), but I suspect the auto upload will fail for that too.

**Comment by mendhak** [comment]
And the second issue, that's really strange that you should see 127.0.0.1 and port 80 when trying a Google Drive upload.  

You're sure you're getting that error for Google Drive upload?  That looks like... somehow your `www.googleapis.com` (which is where Google Drive requests go to) is resolving to 127.0.0.1 or localhost.  Is there an adblocker of some sort running there, some kind of proxy or VPN perhaps.  If you have a terminal emulator you can try pinging www.googleapis.com to see what it resolves to.  

But that's still not explaining why it points at port 80.

So what you can try is enable the [debug log](https://code.mendhak.com/gpslogger/#troubleshooting).  For both issues.  However I don't think much will be revealed with the aggressive doze, but still worth trying.  And for the second issue, after enabling debug log, try another Google Drive upload.

**Comment by digdilem** [comment]
Thank you.

It's clear that Huawei has had badly behaved power management software for
some time, from various forums and reports - although the latest EMUI
(their phone manager software) seems to have caused further issues, perhaps
by combining badly with Android 8's own aggressive power manglement.

It did record one fair track yesterday (a 1 hour drive to a location), but
not the two hour walk (when it was suspended), nor the drive back. Both the
drives were on charge and awake.

Anyway, not a Gpslogger issue, but thanks for your input.

**Comment by digdilem** [comment]
Oh. This is embarrassing.

Your thought about adblocking triggered a though. I am running Pihole on
the network. Whilst it's never caused an issue before, their blacklists are
updated daily.

I just turned it off and retried the Gpslogger upload to gdrive and... Of
course it worked perfectly. Thanks again!

**Comment by mendhak** [comment]
Yes I agree about Huawei phones - I get a lot more emails than Github issues and it feels like there's a spike of Huawei related problems recently, mostly entirely around power management. 


You should be able to [whitelist](https://github.com/pi-hole/pi-hole/wiki/Whitelisting-and-Blacklisting) www.googleapis.com and that should allow you to use the app + keep PiHole on.  But I wonder why googleapis.com is being blocked.  :thinking:
