### ISSUE TITLE
Adaptive Logging Intervals

### ISSUE THREAD

**Issue by pecohen** [mendhak/gpslogger#643]
I used gpslog last week and would like to suggest what would be a big improvement.

By monioring cellphone handoffs and recent gps readings it should be easy to get a reasonable etimate of speed and distance since the last-logged position. Given that, why not allow logging to be determined on a basis of distance moved or perhaps on speed?

And of course every stop location hould be logged. I noticed in examining a log that where I stopped for lunch was not logged!  That should not happen and in fact when motion stops there should be two log entries, one when motion stops and again when motion starts again (or when logging is stopped).

**Comment by mendhak** [comment]
The biggest blocker to adaptive logging is [doze mode](https://code.mendhak.com/gpslogger/#sometimestheappwillnotlogforlongperiodsoftime) which is likely the same issue you're hitting with no logging during lunchtime.  The app may increase or decrease the logging interval but that will simply be ignored by the doze intervals.

There are ways to bypass these - one way is forced intervals... hold a wakelock on the CPU, which is what several running apps do.  GPSLogger's intention is to be battery friendly so I've been avoiding anything to do with wakelocks.

**Comment by pecohen** [comment]
Thanks for the reply.  That information is helpful to me.  

I probably would be better off switching to a different that puts more emphasis on creating log files, even if I have to attach an external battery.
