### ISSUE TITLE
Implementing start/stop as an Android 7+ pinned shortcut (long press)

### ISSUE THREAD

**Issue by adhawkins** [mendhak/gpslogger#645]
Hi,

Would it be possible to add the ability to long-press on the icon for GPS Logger and select 'Start' and 'Stop' (similar to if I long press on Google Maps, I get options to navigate to Home and Work).

This would mean a single icon on the phone's home screen could be used to easily start and stop logging.

Thanks

Andy

**Comment by mendhak** [comment]
Yes that sounds like a good idea and it should be straightforward to implement. 

https://developer.android.com/guide/topics/ui/shortcuts

I'll need to figure out if this is a static, dynamic or pinned shortcut.

**Comment by adhawkins** [comment]
Excellent, look forward to seeing it appear.

**Comment by mendhak** [comment]
v95 released to market.
