### ISSUE TITLE
Log speed to GPX file

### ISSUE THREAD

**Issue by adhawkins** [mendhak/gpslogger#647]
Just getting started with GPS Logger, and notice that the GPX file exported does not contain speed. Is this something that could be added?

**Comment by mendhak** [comment]
Are you logging gpx 1.1 format? That format doesn't allow speed. If you're in the default 1.0 format, then you may be getting cell tower locations, which doesn't give speed. You'll need to disable network locations under performance. So using satellite only you can get speed values.

**Comment by adhawkins** [comment]
It was the gpx 1.1 format that did it. I assumed that using the 'newer' format would give more features!

Thanks for the pointer.
