### ISSUE TITLE
Log to custom URL - HTTP Test ignores HTTP Method from settings

### ISSUE THREAD

**Issue by gigerdo** [mendhak/gpslogger#648]
A minor issue:

When testing "Log to custom URL" by using the "HTTP Test" function, it will always test using a GET request. Even when "HTTP Method" is set to "POST". This only affects the "HTTP Test" functionality. The actual logger works fine and uses the configured request method.

**Comment by mvn23** [comment]
Same with the custom HTTP headers. They are only used for the actual logger, not for the HTTP test.

**Comment by mendhak** [comment]
I can see the confusion - the HTTP test is meant to be a basic HTTP GET just to test the connectivity to the server.  This is because even after a valid SSL cert check, that's not enough to know whether the hostname verification will work.   

So that was the intention - it's not meant to emulate an actual request since most of the values are only available at runtime

Suggestions?  Should I rename it to something else?

**Comment by gigerdo** [comment]
OK, that makes sense and is fine for me. 

Another issue:
For me the offline storage of locations is not working. Locations are only shared when the phone is online. Do I have to do anything specific to sync all the locations that were saved while the phone is offline?

**Comment by mendhak** [comment]
Sharing location - using what?  I attempted a test - turned off mobile data, turned off wifi.  Ran the logger and was able to share the location to another app.

**Comment by gigerdo** [comment]
I mean the "Log to custom URL" function. Typically I have it running all the time, but am only connected to the Internet from time to time (when I am near a WIFI). Only the points captured while connected to a WIFI are sent to the custom URL. I would have expected that the other points are saved and then sent to the URL as soon as a WIFI is available.

I repeated your test by setting my phone to airplane mode and the locations were actually shared. 

Looking through the logs I now noticed some errors that are probably the reason why 
`15:24 error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@def8a52
15:24 Could not send to custom URL`

I noticed before that the custom URL Job sometime times out before my Heroku server is able to spin up an instance. Maybe the same is happening here.

**Comment by mendhak** [comment]
The app should try up to 3 times before giving up, so after that error there may be another 2 attempts, hopefully that is enough for the app to spin up?  Does it take longer than 10s to spin up?  I believe the default timeout in OKHTTP is 10s.

**Comment by gigerdo** [comment]
Unfortunately I was not able to debug the problem in detail. I switched over to importing the files from time to time.
