### ISSUE TITLE
Upload whenever network is available

### ISSUE THREAD

**Issue by a-bali** [mendhak/gpslogger#650]
Would it be possible to collect logs and only try upload them in a batch whenever there is a network connection available, preferably also being able to decide if 3G or Wifi should be used? Or alternatively, expose an "Upload all logs created since last upload" event to Tasker?

**Comment by mendhak** [comment]
This should already be happening - if you have set something like Dropbox/Google Drive upload, then the upload doesn't get attempted unless a network connection is present.   There's also an option in upload settings to upload on Wifi only.

**Comment by a-bali** [comment]
Sorry, I must have missed this... Does this also work with the custom HTTP upload and is there a limit how much data is stored locally if there is no network connection?

**Comment by mendhak** [comment]
Yes same applies for custom HTTP upload.  Anything that requires network will wait.  

As for limit, well - the task of queuing up these custom jobs is handled by [this library](https://github.com/yigit/android-priority-jobqueue) which in turn uses SQLite to store the metadata.  That means about 140 TB worth of jobs or the available free space on your device - whichever is smaller.  The metadata isn't very large, so you should be fine to have jobs queued up for a long time.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
