### ISSUE TITLE
Custom URL won't use POST method

### ISSUE THREAD

**Issue by gitmayer** [mendhak/gpslogger#651]
I cannot get GPS Logger to use the POST method in my Custom URL. I saw the other issue stating that the test function only does GET requests, but even the reporting uses GET for me.  It's like it's ignoring my setting completely.

I've tried setting it back to GET and then to POST, but it never uses the POST method.

I've check debug files, but they don't really show anything odd.

**Comment by mendhak** [comment]
Can you write or screenshot the settings you're using in the Custom URL screen?   And seeing the debug log will also be helpful.  You can post it here or email it to me - gpslogger at mendhak.com

**Comment by gitmayer** [comment]
Sorry, a lot of things came up after I tried to use this app.  

After playing around in curl to replicate, I realize that I needed a trailing slash on my URL.  I've got it working now. Sorry for opening a non-issue, I swear I tested it for half the day before it dawned on me to try and replicate it outside the app.

**Comment by mendhak** [comment]
No that's alright -you gave me a good idea for the future, I will ask users to try to `curl` outside to help with troubleshooting.
