### ISSUE TITLE
Upload to osm not working anymore

### ISSUE THREAD

**Issue by HolgerJeromin** [mendhak/gpslogger#653]
I use the upload to osm since a few years.

It now stops with the message:
"Datei konnte nicht hochgeladen werden"
German for: "file could not be uploaded"

I suspect the new redirect from http://www.openstreetmap.org to https://www.openstreetmap.org is causing the problem.
But this change seems to be active since a few month:
https://github.com/openstreetmap/operations/issues/190#issuecomment-355287409

My last upload was 13 days ago   :-/

**Comment by mendhak** [comment]
Thanks for the issue *and* the fix. 

Indeed changing to `https` seems to do the trick.

**Comment by mendhak** [comment]
v95 released to market.

**Comment by HolgerJeromin** [comment]
That was quick!

Working perfect. Thanks a lot
