### ISSUE TITLE
How to use Direction value?

### ISSUE THREAD

**Issue by kapilpaul** [mendhak/gpslogger#657]
How can I use the direction value I get from the app. lets say

`{"lat":"23.78043553","lng":"90.41009385","spd":"1.36","dir":"245.9","provider":"gps"}`

How to use the dir value? Can you give me a solution?

**Comment by mendhak** [comment]
The directions are degrees from north.  in your example that's 245.9 degrees, or in terms of a compass that would be West-SouthWest.

**Comment by kapilpaul** [comment]
okay Got it. Thanks. and btw it's a nice app. working smoothly.
