### ISSUE TITLE
Error 500 when testing against homeassistant URL

### ISSUE THREAD

**Issue by gnkarn** [mendhak/gpslogger#661]
Configured as indicated on the app and home assistant , and it always ends on error 500

**Comment by mendhak** [comment]
Ah that is just meant to be an HTTP GET request but it doesn't send any actual values.  So if you're seeing a 500 response, Home Automation is receiving a request with the `%blah` in place so correctly throwing a 500.  The real test would be once you've set the URL do some actual logging and it should go to your HA server.

You're not the first person to have a similar question around the HTTP test feature so I believe the feature itself is implemented and named in a confusing way.  I will remove it.

**Comment by mendhak** [comment]
https://github.com/mendhak/gpslogger/commit/e83b1e5003c2000238266868b96ac99c811c5ad1
