### ISSUE TITLE
Email only sends to first email address

### ISSUE THREAD

**Issue by sengsational** [mendhak/gpslogger#662]
AutoEmailJob takes a parameter which populates this.csvEmailTargets String.  The code splits on comma, as expected, but it only does a "header.addCC(ccTarget)".  This is not sufficient.  It also needs "client.addRecipient(ccTarget)".

Just adding client.addRecipient() doesn't work, though, because it's too late.  So all this code must be moved up to just after the existing "client.addRecipient(target)":

            SimpleSMTPHeader header = new SimpleSMTPHeader(fromAddress, target, subject);
            //Multiple email targets?
            for (String ccTarget : csvEmailTargets.split(",")) {
                if (!ccTarget.equalsIgnoreCase(target)) {
                    ccTarget = ccTarget.trim();
                    header.addCC(ccTarget);
                    client.addRecipient(ccTarget);
                    LOG.debug("adding additional email recipeint [" + ccTarget + "]");
                }
            }

**Comment by mendhak** [comment]
v97 released to market.
