### ISSUE TITLE
Log to InfluxDB?

### ISSUE THREAD

**Issue by OliPassey** [mendhak/gpslogger#665]
Hi, thanks for the app, works great so far.
I am trying to setup logging to InfluxDB via the remote url option, but so far all i get is **Method not available**, which according to influxdb docs suggests the request is being sent incorrectly as POST when i have specified GET.
Its possible it could be something else though - im no developer....

Has anyone succeeded in sending data onto Influx? End result is to see results on a Grafana set up i already have running.

I've set up the app as such:
URL: http://local-lan-ip:8086/write?db=telegraf  (existing db)
Body: GPS.SamsungS7, value={"key": "UK", "latitude": %LAT, "longitude": %LON, "name": "United 
Kingdom"} %TIMESTAMP
Headers: Content-Type: application/json
Method: GET (GET nor POST work, both give Method not Available)

**Comment by mendhak** [comment]
According to [this](https://docs.influxdata.com/influxdb/v1.6/tools/api/#write) it should be a `POST`

But I would suggest try to do it manually first.  You can use `curl` if you have bash, or try [Fiddler](https://www.telerik.com/download/fiddler) or [Postman](https://www.getpostman.com/) if you want a UI to try it.  If you get the same method not found problem from desktop as well, then there may be a config problem with your Influx.  Else it'll be some value that may need escaping or entered in a different way in the POST body.  Either way this will help narrow down the problem.

Looking at the examples on that page though, I see most fields go in with commas but you have `{` and `:` - I'm not familiar with Influx so I don't know if those are valid or not

**Comment by OliPassey** [comment]
No worries, i got over one hurdle n onto the next.
Looking to achieve this: https://github.com/grafana/worldmap-panel/pull/144

Will post-back if i ever get there, feel like im close. 
Thanks for the reply none-the-less!

**Comment by OliPassey** [comment]
Got it working :) 
GPSTracking,Country=UK,Subject=Oli latitude=%LAT,longitude=%LON  etc...

**Comment by thinrope** [comment]
Great @OliPassey ! Please write a short blob (or edit your previous comments) on what and how you did, add a screenshot and close this issue.

**Comment by OliPassey** [comment]
I’m using a Samsung android to log and send the data to my InfluxDB server, specifically GPSLogger.app, it makes light work of sending onto a remote server.

In order to get this running as I did use the below details in GPSLogger:

URL: http://local-lan-ip:8086/write?db=telegraf (existing db)
Body: GPSTracking,Country=UK,Subject=Oli latitude=%LAT,longitude=%LON
Kingdom"} %TIMESTAMP
Headers: Content-Type: application/json
Method: POST
There are load more variables that you can send over, I also log speed, altitude, battery life & GPS Accuracy. Next steps for me will be to find a nice way to trigger this with some custom options, you want different configurations for walking, driving, in the country, in a city, on a bike etc.

More info here: https://olipassey.me.uk/mapping-gps-data-in-grafana/

**Comment by cagnulein** [comment]
i don't know why it's not working, the output from my query is this:

```
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/query",
    "params": {
      "db": "telegraf",
      "q": "SELECT last(\"latitude\") AS \"latitude\", last(\"longitude\") AS \"longitude\" FROM \"gsm_cell_id_position\" WHERE time >= now() - 6h GROUP BY time(1d) fill(previous);SELECT last(\"value\") AS \"metric\" FROM \"gsm_band\" WHERE time >= now() - 6h GROUP BY time(1d) fill(previous)",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms"
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "gsm_cell_id_position",
            "columns": [
              "time",
              "latitude",
              "longitude"
            ],
            "values": [
              [
                1566518400000,
                "44.52935",
                "10.849022"
              ]
            ]
          }
        ]
      },
      {
        "statement_id": 1,
        "series": [
          {
            "name": "gsm_band",
            "columns": [
              "time",
              "metric"
            ],
            "values": [
              [
                1566518400000,
                3
              ]
            ]
          }
        ]
      }
    ]
  }
}
```

any hints?

**Comment by thinrope** [comment]
Great! I haven't tried this, but the Body: above seems a truncated, @OliPassey, can you have a look (it is same in the blog).

**Comment by cagnulein** [comment]
@thinrope i've solved, i changed the metric value with a great number and it worked out! I don't know why. Which unit has metric?

**Comment by OliPassey** [comment]
Sorry, i havent looked at this in a year and don't have it running anymore.
Looks like you've got it sorted though.
