### ISSUE TITLE
GPSLogger buffer Livelog when connection is lost

### ISSUE THREAD

**Issue by r100gs** [mendhak/gpslogger#666]
Hello,

I realized some gaps in my livetracked (phonetrack) gps positions on my way to work. Maybe sometimes internet connection is lost.
Does GPSlogger buffer logs when mobile internet connection is lost to upload it later on?

Best regards,
r100gs

**Comment by mendhak** [comment]
Yes - [mentioned here](https://gpslogger.app/#usingthecustomurlfeature).  The 'points' to send to the server get queued up until a network connection is available again.

**Comment by r100gs** [comment]
Thx for the link. So, its buffering somehow.
I made some further tests and realized that I have still some gaps with gpslogger alone.
I use an Oneplus6 device.
If you would like to have more information I can turn logging on and make a new gps track tomorrow morning.

This is what I get with gpslogger alone:
![gpslogger_alone](https://user-images.githubusercontent.com/12609988/43817351-3f5cb01e-9ad9-11e8-8a6f-5bae430fb708.jpg)

This is gpslogger together with µlogger:
![gpslogger_and_ logger](https://user-images.githubusercontent.com/12609988/43817363-5451746e-9ad9-11e8-8c13-10abd5114421.jpg)

This is µlogger alone:
![logger](https://user-images.githubusercontent.com/12609988/43817370-5ed10ea4-9ad9-11e8-87b8-036641e7ef56.jpg)

Best regards,
Stefan

**Comment by mendhak** [comment]
Yes - if you enable the debug log that may highlight issues why certain areas have gaps.  It may also have to do with settings. For example if you only have GPS checked under location providers, but not network.  Does ulogger have similar settings or does it use both satellite + network?

**Comment by Helium314** [comment]
I think it does not have to do with settings. The gaps appear when GPSlogger tries to send to custom URL, but it fails for some reason like bad internet connection. Apparently µlogger tries again later, while GPSlogger just skips the position after a failed attempt. This can be easily reproduced by blocking internet access for GPSlogger, which gives some error messages and 'could not send to custom URL' in the log.

**Comment by mendhak** [comment]
How are you blocking the internet access?  

I've set the Custom URL logger to [retry 2 times](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlJob.java#L106) - however the only time it will try is if there is a data connection available.  The definition of 'data connection available' is [defined by the OS](https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/common/WifiNetworkUtil.java#L102).

**Comment by roydenyates** [comment]
I think I am seeing the same - Lineage OS 15.1 (Android 8.1), latest GPSLogger.
Best way to see this is to compare the uploaded gpx with the locally stored one - in general I see that the uploaded gpx has about 2 out of 3 of the positions logged locally. That's fine (and likely may vary in relation to log interval). On occasion large gaps appear in the uploaded track and I surmise this is where the data connection was intermittant and fragile, From what the dev says, it is likely that the phone says link available and so GPSLogger makes the two tries but if this link in fact is just nominal, it  not be capable.

**Comment by mendhak** [comment]
In the next release I've increased number of requests to 5 but aside from that the reliance of the OS knowing of a good internet connection still remains
