### ISSUE TITLE
Version v96 Notifications remaining On.

### ISSUE THREAD

**Issue by g8dhe** [mendhak/gpslogger#671]
Just updated to v96 and the notification button appeared and despite turning notifications off and restarting the phone itself it continues to re-appear.
![screenshot_20180903-155828](https://user-images.githubusercontent.com/2537879/44993546-df39e700-af92-11e8-8f45-b08aab2eb889.jpg)
![screenshot_20180903-155840](https://user-images.githubusercontent.com/2537879/44993548-df39e700-af92-11e8-967d-8a52e7d98d83.jpg)

**Comment by mendhak** [comment]
I'm able to hide the buttons in the notification area.  OnePlus 3T, Android 8.  

Can you mention your phone and OS. 

However... I don't know what that second screenshot is.  Is that a reimplementation of notification area?

**Comment by g8dhe** [comment]
Yup its Huawei P20 Pro, Android 8.1.0, EMUI 8.1.0
The second image shows the pop-up when you long hold on the Badge that pops up on the App Icon as the Notification.  
I've managed now to turn it Off by Disabling the "Badges" option for the App, as well as the Notifications, so it might be some interaction between "Badges" and "Notifications" ?
![screenshot_20180904-153719](https://user-images.githubusercontent.com/2537879/45038248-c3007d80-b058-11e8-9563-615a339b2393.jpg)

**Comment by mendhak** [comment]
v97 released to market.  As part of this you may see the notification more prominent - Android 8 onwards requires that the app's notification be shown to the user where previously I was able to set it to a minimum priority notification this is no longer allowed.
