### ISSUE TITLE
Android 9 and GPSlogger

### ISSUE THREAD

**Issue by cogneato** [mendhak/gpslogger#673]
Are there any tips or settings for getting it to stay on? Seems like 9 is constantly putting it into the background somehow. Turning off adaptive battery doesn't make a difference either.

**Comment by cogneato** [comment]
I've found that allowing it to use notifications in every way possible is helpful. I'm guessing this keeps it in the foreground.

**Comment by mendhak** [comment]
Hi do you mean all the notification toggles on a single screen?  if you could share a screenshot that would be great, may be useful for other Android 9 users. 

With each Android release the OS is getting more aggressive against background tasks and it's becoming very difficult to have any kind of consistency.

**Comment by cogneato** [comment]
Sure, here are the settings I currently use which get closest to the old behavior, but still not as consistent.

GPSLogger settings in General Options:
(No hiding of notifications)

![screenshot_20180913-093628](https://user-images.githubusercontent.com/2456810/45499356-83612200-b739-11e8-8124-d33994024340.png)

Settings > Apps & Notifications > GPSLogger > Advanced > Battery:
(check that GPS Logger is not optimized)

![screenshot_20180913-093908](https://user-images.githubusercontent.com/2456810/45499452-b1466680-b739-11e8-8343-3fcbf02c93ca.png)

Settings > Battery > Adaptive Battery:
(check that GPSLogger is NOT in the restricted apps)

![screenshot_20180913-093833](https://user-images.githubusercontent.com/2456810/45499613-fe2a3d00-b739-11e8-8b40-82ee6224e3de.png)


You are right about it getting more aggressive. GPSLogger has been great for me combined with Home Assistant but since 8.1 it has been a challenge. We have 2 phones that report in "just ok" now and 2 that don't work at all even when I check these settings (I may try reinstalling for these 2).

I read here about power management in Android 9 but there doesn't seem to be much that the user can do about it. <https://developer.android.com/about/versions/pie/power>

**Comment by mendhak** [comment]
No, not good enough.  I found that the service was _still_ being killed.  I'm now experimenting with a different technique.  In the `onDestroy` I send out a broadcast to a receiver within GPSLogger and that receiver restarts the `GPSLoggingService`.  I'll test this out a bit but this in combination with the `.startForegroundService` above should help.  

I'm trying to be careful with this - currently it will send out the broadcast if and only if the application was logging, not indiscriminately.

**Comment by mendhak** [comment]
v97 released to market.
