### ISSUE TITLE
Tasker error: code 3: java.lang.illegalStateExeption: Not allowed to start service Intent

### ISSUE THREAD

**Issue by mvaneijken** [mendhak/gpslogger#674]
In GPSLogger version 96 the following error occurs when starting service intent com.medhak.gpslogger.GpsLoggingService. 

code 3: java.lang.IllegalStateExeption: Not allowed to start service Intent { act=com.medhak.gpslogger.GpsLoggingService cmp=com.medhak.gpslogger.GpsLoggingService/.GpsLoggingService (has extras) }: app is in background uid UidRecord{fc7f3b8u0a275 CAC bg:+55m18s713ms idle procs: 1 sec(0,0,0)}

This problem started to occur on my device on the 5th of September. 

The intent is allowed when the GPSLogger app is started before the service intent is given. So it happens only when it's not running. This is a work-around.

There is an article on StackOverflow that might has a possible cause for this problem. https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

According to article https://developer.android.com/about/versions/oreo/background there should be a setting to allow this app to start in the background, but I can't find it on a Samsung Galaxy S8.

**Comment by mvaneijken** [comment]
Yes I do.

Op ma 10 sep. 2018 16:22 schreef mendhak <notifications@github.com>:

**Comment by atapio** [comment]
First of all, thanks for a great app!

I have the same issue, the intents work for a while (I assume until GPSLogger is killed) if I start the app manually, but otherwise I get the following error:

```
09-10 09:20:32.717  2513 11695 E Tasker  : 09.20.32#E: error: code 3: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.mendhak.gpslogger.GpsLoggingService cmp=com.mendhak.gpslogger/.GpsLoggingService (has extras) }: app is in background uid null.
09-10 09:20:32.717  2513 11695 E Tasker  : 09.20.32#E: error: prefsException/Send Intent: Not allowed to start service Intent { act=com.mendhak.gpslogger.GpsLoggingService cmp=com.mendhak.gpslogger/.GpsLoggingService (has extras) }: app is in background uid null
```

The same setup worked perfectly with previous versions of GPSLogger. I have an Oneplus 3 with Android 8.1.0 (OmniROM).

**Comment by mvaneijken** [comment]
My Android version is indeed 8.0 (Oreo).

Op wo 12 sep. 2018 om 11:23 schreef mendhak <notifications@github.com>:

**Comment by mendhak** [comment]
Here's a lovely unpleasant workaround in the meantime. 

Launch the app. Wait a few seconds. Send the intent as usual.  Go home. 

The reason for this - the service needs to be 'started' and Tasker can't start a foreground service.  I cannot find out how either.

 (Ignore 1st item)

![image](https://user-images.githubusercontent.com/746276/45455359-b4f8cf80-b6de-11e8-8802-e30c8536b071.png)

It's also possible to try this if you have a rooted phone - instead of a send intent, it's a Tasker shell command.  

    am start-foreground-service --ez immediatestart True -n com.mendhak.gpslogger/.GpsLoggingService

**Comment by mvaneijken** [comment]
That's what I'm using currently indeed. It works well for now.

Op wo 12 sep. 2018 om 23:56 schreef mendhak <notifications@github.com>:

**Comment by mendhak** [comment]
If you have an un-rooted phone could you also try the 

    am start-foreground-service --ez immediatestart True -n com.mendhak.gpslogger/.GpsLoggingService

And see if that works for you?  I tried on OnePlus 3T, didn't work.  But just wanted to confirm that `am` requires root.

**Comment by mendhak** [comment]
Well here's something to try.  I've created a [Broadcast Receiver in a branch](https://github.com/mendhak/gpslogger/compare/tasker-issue674).  I tested by sending Tasker an intent but this time I had to set a few extra fields. If you have the ability to sideload APKs you can try this APK below. (It's signed, so if you install it you will still get Play Store updates)

    Action: com.mendhak.gpslogger.TASKER_COMMAND
    Extra: immediatestart:true
    Package: com.mendhak.gpslogger
    Class: com.mendhak.gpslogger.TaskerReceiver
    Target: Broadcast Receiver 

That extra can be any of the usual extras from [the list](https://gpslogger.app/#controllinggpslogger).  
That Action can actually be something super simple but Android docs recommend it have the namespace in there... 


[APK](https://drive.google.com/file/d/1nLAAUK1zxw76p_p4DhJPldoCIPvJt0e7/view?usp=sharing),
[checksum](https://drive.google.com/file/d/1BJVqSZW9XneX8cGGAfbBEXuCXnsRGRuK/view?usp=sharing), 
[signature](https://drive.google.com/file/d/1zaMcpFu3vU81lqTbFtndA-FTIF6iqPH3/view?usp=sharing)

**Comment by mendhak** [comment]
Updated APK

[APK](https://drive.google.com/file/d/1v6R4V_Ay1HfFR2WIOb5GojSucBtNcesT/view?usp=sharing),[Signature](https://drive.google.com/file/d/1mctJ3yCXqPXY_5GT0sx03WsGyqXJTgao/view?usp=sharing),[Checksum](https://drive.google.com/file/d/1fe-hlkYr6cp6kc_u3_2FFN9ndESbg2eL/view?usp=sharing)

**Comment by mvaneijken** [comment]
On my device (not rooted) it seems to work fine using this new way. I will
test it further the comming days.

Op wo 19 sep. 2018 23:26 schreef mendhak <notifications@github.com>:

**Comment by mendhak** [comment]
v97 released to market.
The new instructions are here: https://gpslogger.app/#controllinggpslogger
