### ISSUE TITLE
Feature suggestion: Different colours for the widget icons

### ISSUE THREAD

**Issue by cbsva** [mendhak/gpslogger#682]
Could you please change the background colour of the start widget to green and stop widget icon to red? This would make distinction a bit easier. 
![gpslogger](https://user-images.githubusercontent.com/20813553/46369368-0dd6da80-c683-11e8-8223-96f29d1eb91c.jpg)

**Comment by mendhak** [comment]
This is a neat idea. I will need to figure out if I have to create 2 more copies of the same icon or if there's a way to programmatically apply an alpha/layer when a shortcut is being created.  This needs some investigation.

**Comment by mendhak** [comment]
What about icons instead?  The color tinting won't be so great for accessibility but icons could serve the purpose of distinguishing start/stop

![image](https://user-images.githubusercontent.com/746276/47319528-d4243e80-d646-11e8-948f-32c1a7bb555b.png)

**Comment by Krzysiu** [comment]
I think that mini icon overlay is a good solution - the icons clearly shows what they do and in my opinion they are nicer. With my bad sight I'd prefer colors than icons, but still, I think that's the solution which would appeal to most people and as author said - it's accessible.

**Comment by mendhak** [comment]
I'm really bad at UI/artwork stuff.  Don't know if you noticed haha. 

I tried coloring the background part of the GPSLogger but just can't get it to look acceptable, not all parts are able to be selected.

I tried coloring the insides of these icons, how about this.  Are the colors more visible?  Any other ideas from other icons you may have seen? 

![image](https://user-images.githubusercontent.com/746276/48962054-81ee7a00-ef72-11e8-8e49-650055f98c71.png)

**Comment by mendhak** [comment]
Another option - @cbsva - how did you color those icons in?  Do you happen to have the PNGs for it, can you share it?

**Comment by mendhak** [comment]
Wait, I tried again and I think I have it.  How about this?

![image](https://user-images.githubusercontent.com/746276/48962215-cda22300-ef74-11e8-9d86-62c134bcac0a.png)

Got the icon and the background color.  Looks OK @Krzysiu ?

**Comment by cbsva** [comment]
I was just searching for my original file, but your last version looks pretty cool now - and better than mine, which I made only by exchanging colors of your original icon in Photoshop. Thank you for your efforts, it would be nice to have this solution!

**Comment by cbsva** [comment]
I don't know if it is possible, I try to send you my .tif file with 3 layers.
It doesn't show up when I add it.
If you can see my email address, please drop me a mail with your icon file and I will make you 2 versions of it.

**Comment by mendhak** [comment]
Yeah github won't allow tiff files I'm sure. I can't see your email address. 

The icons are at : https://github.com/mendhak/gpslogger/blob/master/assets/icons/gps_icon02.png

And my email is gpslogger @ mendhak.com

**Comment by luziferius** [comment]
> I don't know if it is possible, I try to send you my .tif file with 3 layers.
> It doesn't show up when I add it.

Github accepts ZIP archives, so you can ZIP compress your files and attach them.

**Comment by mendhak** [comment]
v98 released to market

**Comment by mendhak** [comment]
But if someone with better skills can improve on it I'm happy to replace these
