### ISSUE TITLE
start shortcut doesn't work when location permission is not granted

### ISSUE THREAD

**Issue by lvmm** [mendhak/gpslogger#683]
When GPSTracker has no location permission "start" shortcut (widget) shows GPSTracker icon on the status bar and it looks like it works but the track of course is not created. Found it the hard way - installed GPSTracker on a new phone, immediately created start and stop shortcuts and started using them. Only when I started investigating and tried starting tracking from the app it prompted me to grant location permission. It would've been nicer if shortcut either prompted for permission too or informed of the problem in some other way or at least didn't show the icon when something is wrong.

**Comment by mendhak** [comment]
Unfortunately no prompt can be shown without any activity.  So the best I can do is just not log and not show a notification (by stopping the service) if the start shortcut is invoked without permissions being granted.

**Comment by mendhak** [comment]
v98 released to market
