### ISSUE TITLE
Autosend to OwnCloud not working anymore

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#684]
Hi!
the auto upload to OwnCloud function seems not to be working anymore.
The test upload works without any problem, but the GPX files are not uploaded.
The manual upload works.
Is there a log somewhere that I can send?
Andrea

**Comment by andreapx** [comment]
Thanks, the log helped me realizing that the files where actually uploaded, but in ZIP format which my software was not able to read. I may have enabled it sometime in the past...
After disabling the ZIP upload everything looks good.
Thanks,
Andrea

**Comment by mendhak** [comment]
Neat, I like when the log file is useful 😁
