### ISSUE TITLE
connections of custom url logger

### ISSUE THREAD

**Issue by updatede** [mendhak/gpslogger#686]
Custom url logger always keep 5 connections to server, it continually create new connection and close old connection, but concurrent connections are always 5. My web server is a http2 server, so it should be only single persistent connection during data transfering. The server connection idle timeout is 180s and gpslogger log interval is 30s. Maybe should use the same http client object everytime as possible, so can benefit from http2 persistent connection and http1 keepalive connection.

**Comment by mendhak** [comment]
Hello. The library in use is [Okhttp 3.7](https://github.com/mendhak/gpslogger/blob/master/gpslogger/build.gradle#L206) - it should automatically reuse connections if Android 5+, ALPN.  I can't say why the connection isn't being reused, however it's important to note that the Custom URL logger feature is not made for efficiency, it is designed to work across sporadic connections - eg no data for some miles, so the logging requests will queue up.  So I can't persist or work towards a single client object across connections.

**Comment by updatede** [comment]
I think the reason why custom url logger keep so many concurrent connections is everytime it logs it create a new okhttpclient object, so older unused okhttpclient objects keep connections untill server or client connection idle timeout reached or garbage collection occured. I think there is no need to generate so many garbage okhttpclient objects and connections. If logs share one CustomUrlJob object, okhttpclient should be class variable, if it's one CustomUrlJob object per log, okhttpclient should be global variable. okhttpclient will reconnect automaticlly if connection closed because of no data for some miles. If connection still alive, many logs can reuse the same connection and okhttpclient object to avoid waste memory and network resources by filling up garbage okhttpclient objects.
