### ISSUE TITLE
Intent to close the app

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#688]
Hi, is there an intent command to close the app?
I start it with tasked, but even if I kill it, it still stays in background with an icon in the notification bar saying that it's still active.
Thanks!

**Comment by mendhak** [comment]
How are you killing it? can you try to send the stop command.

**Comment by andreapx** [comment]
I'm killing it with the tasked kill function, after I've sent the stop command.
Here is the task:
`
<TaskerData sr="" dvi="1" tv="5.5">
	<Task sr="task56">
		<cdate>1508865358394</cdate>
		<edate>1540157762976</edate>
		<id>56</id>
		<nme>GPSLoggerOFF</nme>
		<pri>100</pri>
		<Action sr="act0" ve="7">
			<code>547</code>
			<Str sr="arg0" ve="3">%gpsLogging</Str>
			<Str sr="arg1" ve="3">0</Str>
			<Int sr="arg2" val="0"/>
			<Int sr="arg3" val="0"/>
			<Int sr="arg4" val="0"/>
		</Action>
		<Action sr="act1" ve="7">
			<code>877</code>
			<Str sr="arg0" ve="3">com.mendhak.gpslogger.GpsLoggingService</Str>
			<Int sr="arg1" val="0"/>
			<Str sr="arg2" ve="3"/>
			<Str sr="arg3" ve="3"/>
			<Str sr="arg4" ve="3">immediatestop:true</Str>
			<Str sr="arg5" ve="3"/>
			<Str sr="arg6" ve="3"/>
			<Str sr="arg7" ve="3"/>
			<Str sr="arg8" ve="3"/>
			<Int sr="arg9" val="2"/>
		</Action>
		<Action sr="act2" ve="7">
			<code>1909508005</code>
			<on>false</on>
			<Bundle sr="arg0">
				<Vals sr="val">
					<ShortcutBeforeUse>#Intent;component=org.traccar.client/.ShortcutActivity;S.action=stop;end</ShortcutBeforeUse>
					<ShortcutBeforeUse-type>java.lang.String</ShortcutBeforeUse-type>
					<ShortcutIntentString>#Intent;component=org.traccar.client/.ShortcutActivity;S.action=stop;end</ShortcutIntentString>
					<ShortcutIntentString-type>java.lang.String</ShortcutIntentString-type>
					<ShortcutLabel>Traccar Client: Stop service</ShortcutLabel>
					<ShortcutLabel-type>java.lang.String</ShortcutLabel-type>
					<com.twofortyfouram.locale.intent.extra.BLURB>Traccar Client: Stop service</com.twofortyfouram.locale.intent.extra.BLURB>
					<com.twofortyfouram.locale.intent.extra.BLURB-type>java.lang.String</com.twofortyfouram.locale.intent.extra.BLURB-type>
					<net.dinglisch.android.tasker.extras.VARIABLE_REPLACE_KEYS>plugininstanceid plugintypeid ShortcutIntentString ShortcutLabel </net.dinglisch.android.tasker.extras.VARIABLE_REPLACE_KEYS>
					<net.dinglisch.android.tasker.extras.VARIABLE_REPLACE_KEYS-type>java.lang.String</net.dinglisch.android.tasker.extras.VARIABLE_REPLACE_KEYS-type>
					<net.dinglisch.android.tasker.subbundled>true</net.dinglisch.android.tasker.subbundled>
					<net.dinglisch.android.tasker.subbundled-type>java.lang.Boolean</net.dinglisch.android.tasker.subbundled-type>
					<plugininstanceid>1eed919c-636b-4745-ac46-20c0589eaca1</plugininstanceid>
					<plugininstanceid-type>java.lang.String</plugininstanceid-type>
					<plugintypeid>com.joaomgcd.autoshortcut.IntentAutoShortcut</plugintypeid>
					<plugintypeid-type>java.lang.String</plugintypeid-type>
				</Vals>
			</Bundle>
			<Str sr="arg1" ve="3">com.joaomgcd.autoshortcut</Str>
			<Str sr="arg2" ve="3">com.joaomgcd.autoshortcut.ActivityAutoShortcut</Str>
			<Int sr="arg3" val="0"/>
		</Action>
		<Action sr="act3" ve="7">
			<code>30</code>
			<Int sr="arg0" val="0"/>
			<Int sr="arg1" val="2"/>
			<Int sr="arg2" val="0"/>
			<Int sr="arg3" val="0"/>
			<Int sr="arg4" val="0"/>
		</Action>
		<Action sr="act4" ve="7">
			<code>18</code>
			<App sr="arg0">
				<appClass>com.mendhak.gpslogger.GpsMainActivity</appClass>
				<appPkg>com.mendhak.gpslogger</appPkg>
				<label>GPSLogger</label>
			</App>
			<Int sr="arg1" val="0"/>
		</Action>
	</Task>
</TaskerData>
`

**Comment by mendhak** [comment]
In the most recent release the interaction with Tasker had to change.  

See this now: https://gpslogger.app/#controllinggpslogger

The main difference you'll notice it's now doing a broadcast rather than talking to a service which isn't allowed.

**Comment by andreapx** [comment]
Oh, I didn't notice that.
It now works like a charm!
Thanks again!!!

**Comment by mendhak** [comment]
No prob, closing.
