### ISSUE TITLE
Feature Request: support for Android Auto

### ISSUE THREAD

**Issue by carldebilly** [mendhak/gpslogger#690]
It would be cool if GpsLogger would be able to track the position of both the car and the phone when connected to Android Auto. This way, when the cable is disconnected from the car, only the phone position would be updated.

According to the documentation, we can use the UiModeManager to access the `ACTION_ENTER_CAR_MODE` and `ACTION_EXIT_CAR_MODE` (from the [Android Documentation](https://developer.android.com/reference/android/app/UiModeManager#ACTION_ENTER_CAR_MODE)). I don't know if a _normal app_ can access this, but if yes, it would be very nice to log where I left the car when I disconnect it from my phone...

**Comment by mendhak** [comment]
Hey I didn't understand this.  The car position and phone position, when connected, would be the same.  I don't know much about Android Auto but it also appears to use the phone's GPS/navigation anyway?

**Comment by dshanske** [comment]
I don't know what @carldebilly is suggesting, but why not be able to note time and location entering and exiting auto mode as a way of tracking driving habits in your file?

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
