### ISSUE TITLE
Getting battery charge status

### ISSUE THREAD

**Issue by Namec** [mendhak/gpslogger#691]
Hello,

Currently looking for a way to  the statue of thé battery (connected or not connected) instead of having the battery level.

Best

**Comment by SeLLeRoNe** [comment]
I would love to have that piece of information too with the battery level as it is now :)

Thanks

**Comment by mendhak** [comment]
Sorry for such a late reply.  I think this is possible, but I wanted to understand why this would be useful, what's the use case.   It's additional values for me that I'll have to be passing around so I want to make sure this isn't a niche case

**Comment by SeLLeRoNe** [comment]
In my specific case (but I think this might apply to many) is because I wanna have a non-cloud based to track my phone, battery and charging status via Home Asaiatant.
Basically this App does already 2/3 of what I need without having to play with tasker for the GPS part.

**Comment by livarb** [comment]
Would like to be able to pass this as a parameter in custom HTTP logging. I.e. is the phone connected to power or not. 

My use case: I've placed a few phones with GPSLogger in buses, and it's nice to be able to see if it's connected to power or not, to be able to detect a phone on it's way to discharge faster than just watching the battery level.

**Comment by mendhak** [comment]
(Only 3 years later...) I've added this feature in the current pull request.  

I've got an APK here:  https://github.com/mendhak/gpslogger/releases/tag/v120-rc1  if you are able to test it.  Note that the APK is not compatible with F-Droid so if you install it you will lose all previous GPSLogger data.  

It's got a CSV field `battery_charging` and a Custom URL parameter `%ISCHARGING`

**Comment by mendhak** [comment]
v120 is in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v120) and [on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
