### ISSUE TITLE
Crash when tapping below add profile button in profile view

### ISSUE THREAD

**Issue by luziferius** [mendhak/gpslogger#695]
Type: Crash due to a NullPointerException
Reproducible: Always
Steps to reproduce:
- Open the Menu
- On top, tap on the active proile name/ downwards arrow to open the profile chooser
- Tap _below_ the new profile button.
- GPSLogger crashes with an NPE.

I enabled the show outlines option in the Android developer options and looked at the spot. A screenshot is attached below. You can see there is an empty element below the add button. Tapping it causes the NPE.
![screenshot_20181111-233649_gpslogger](https://user-images.githubusercontent.com/2143820/48723681-999ec900-ec27-11e8-9992-f36aa5db888d.jpg)

This seems to be the function responsible for filling the UI:
https://github.com/mendhak/gpslogger/blob/c4665a481d0298dfbbaa75bc54382228ebba820d/gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java#L600-L657
It seems to find _something_ which passes the existence check but result in a Null being inserted.

**Comment by mendhak** [comment]
Wow!  Thanks for this bug report, I don't think I would have noticed that problem at all, it's so common to only test a happy path.

**Comment by luziferius** [comment]
Seemed to be a simple fix ;)
I totally didn't see/notice that stray call in the varargs argument list when I looked over it.

**Comment by mendhak** [comment]
v98 released to market
