### ISSUE TITLE
Feature Request: Visible Wifi SSID List

### ISSUE THREAD

**Issue by Slyke** [mendhak/gpslogger#697]
What:
Sends and logs a list of Wifi SSIDs, MAC addresses, along with signal strength when getting GPS location if Wifi is turned on. This feature should be able to be toggled off too. This should only record public broadcast beacons and not log hidden SSIDs.

Why:
GPS can fail when inside larger buildings or underground. There are some APIs (mainly provided by Google) that will allow you to trilaterate your location based off visible wifi SSIDs and signal strength.

How:
The list could be attached to a JSON object, such as:
```
{
  ...otherJsonData,
  "wifiSignals": [
    {
      "SSID": "MY SSID",
      "MAC": "12:34:45:67:89:01",
      "RSSI: "-98db"
    },
    {
      "SSID": "MY OTHER SSID",
      "MAC": "01:98:76:54:32:21",
      "RSSI: "-50db"
    }
  ]
}
```
Or in CSV, the fields can be seperated with a `:` and `;`:
`..., "WIFI:MY SSID;MAC:12\:34\:45\:67\:89\:01;RSSI:-98db", "WIFI:MY OTHER SSID;MAC:01\:98\:76\:54\:32\:21;RSSI:-50db"`

The CSV method could also be used for spreadsheet entries.

**Comment by mendhak** [comment]
I've been thinking about both this as well as [connected bluetooth devices](https://github.com/mendhak/gpslogger/issues/707).  I'm not looking to implement either, the complexity that these introduce is just too high. And with SSID logging I'm just uncomfortable doing it, even though to be honest I'm struggling to articulate why.  On the other hand, logging a tower ID, if such a thing is available, is a little less uncomfortable for me.  So I am closing this now and sorry for the late reply.

**Comment by Slyke** [comment]
All good! Thanks for the update.
