### ISSUE TITLE
Unable to Log to SD card--internal RAM only--on Oreo (8.1)

### ISSUE THREAD

**Issue by tl3000** [mendhak/gpslogger#698]
Been a long time user of GPSLogger without any issue until now.  Just got a new phone (Moto e5 XT1920DL) running Android version 8.1.0, and GPSLogger (version 97) produces an error when attempting to select the SD card (SanDisk Extreme 128 GB) as the 'Save to folder' location.  Please see attached screenshot below for the pop-up error message.  Other apps are able to read and write to that SD card without issue.  The GPSLogger app would only auto-select and use the internal memory located at:

/storage/emulated/0/Android/data/com.mendhak.gpslogger/files

The desired SD card location:

/storage/3734-3838/GPSLogger

Please investigate and advise.  Thank you!

![screenshot_20181204-144610](https://user-images.githubusercontent.com/5431188/49479564-73fdec00-f7f1-11e8-8bfd-b103812c56a4.png)

**Comment by Slyke** [comment]
Check if the app has permission to write to the folder. It's possible you denied it when it initially tried.

**Comment by mendhak** [comment]
Does an Android folder already exist on the SD card - Android should have prompted you and 'formatted' the card for you. 

Your path will need to be

    /storage/3734-3838/0/Android/data/com.mendhak.gpslogger/files

Due to restrictions the app is only allowed to write to its 'own' path and nowhere else and I think that same `.../data/com.mendhak.gpslogger...` path is required.

**Comment by tl3000** [comment]
@**mendhak**, thanks for the insight.  That was the problem.  All is well once changing the folder selection to:

/storage/3734-3838/Android/data/com.mendhak.gpslogger/files

My previous phone running KitKat (Android version 4.4.4) and GPSLogger (version 97) didn't exhibit such issue.  I was able to write to my own designated folder on the SD card as shown here:

![screenshot_2018-12-05-03-29-53](https://user-images.githubusercontent.com/5431188/49500873-b4845680-f83f-11e8-96ee-077e5e3bbba5.png)

Anyway, logging is working fine as before with the new phone now.  Much thanks again, and sorry for the false alarm.
