### ISSUE TITLE
App gets killed by Android

### ISSUE THREAD

**Issue by iandees** [mendhak/gpslogger#699]
I'm on a Pixel 3, having just updated to the December security update of Android P. Ever since I've had this phone, I've been trying to keep GPS Logger running, but the phone really likes to kill the logging service.

My configuration:
- Start on bootup and start on app launch are both enabled
- Logging to GPX is the only format enabled
- Location providers are set to GPS, Network, and Passive; Interval is set to 30 seconds; Distance filter is set to 20 meters; Accuracy filter is set to 40 meters; Don't log if I'm not moving is enabled

I'll start the app, sit around working for a while, and when I go for a walk or for a short car ride I'll look down and see the app has been killed at some point since I started it.

How can I keep the app running 24/7?

**Comment by mendhak** [comment]
Any task killer or battery saver type applications?  Lots of other apps running?

All the settings you mentioned look fine.  When the app starts, do you see the notification persist in the status area?  

Although I'm not very hopeful could you try to enable [debug log](https://gpslogger.app/#troubleshooting).  Start logging and let it die.  Do that a few times.  

If there's a legitimate error there may be a crash in there, but more likely it will simply confirm that Android OS is killing it (but won't know why).

**Comment by iandees** [comment]
Of course after I post this it hasn't been killed since. I may have been experiencing [a bug in Android P](https://www.androidpolice.com/2018/10/22/pixel-3-memory-management-issue-kills-background-apps/). I'm going to close.

**Comment by mendhak** [comment]
Thanks for finding that link, the 2nd video on that page is quite useful.
