### ISSUE TITLE
Remove contacts permission from Systems.NecessaryPermissions requirements check

### ISSUE THREAD

**Issue by tessus** [mendhak/gpslogger#700]
I love this app, but it is truly annoying to get a popup (and see the permission requirements) every single time I open the app.

Any chance you could add a checkbox `don't show again`?

**Comment by tessus** [comment]
> If you go to application list, then find GPSLogger, then tap permissions, you should see which permissions are enabled and which aren't. Try enabling them all then the prompt should go away.

I don't want to give the app all permissions. I do not use Google Drive functionality, thus the app does not need access to my contacts.
Also, afaik the app should ask for that permission as soon as it is requested for the first time.
The `Permissions required` popup is a nice for an explanation of the reqs, but I don't want to see it every time I start the app.

**Comment by mendhak** [comment]
That used to be the case. The app used to ask at the time of the feature usage, but it turns out that automation users were hitting problems since the prompt wouldn't show and there was no way of knowing things weren't working.  So the permissions up front needs to happen.  

I think what I could do is get the contacts requirement to not be a prerequisite for the prompt but I will need to verify that Google Drive is the only thing that needs it.  

Marking for milestone 99 but that's not going to be soon.  So in the meantime you can avoid the prompt by accepting contacts permission, then when v99 comes out you can re-deny it.

**Comment by tessus** [comment]
Thanks for the info.

On the other side, you could still allow people to dismiss this prompt forever (or until re-activated in settings).
I mean a user should be able to decide not to get a prompt that is only there for newbies anyway.
An expert checks the app permissions, if something is not working.

**Comment by tessus** [comment]
I can only speak for myself, but I have deleted 2 apps in the last 3 weeks, because they showed me a popup every time I started the app (and I was not able to get rid of it). Such a behavior is highly disruptive and annoying. For me this is in the same category as ads. (I'm more than happy to pay for an app to get rid of ads, but some apps are ads-only with no paid version.)

Just my 2 cents. (I also believe I'm not the only one who feels that way.)

**Comment by mendhak** [comment]
The '1 of 3' permission prompts aren't from the app, they're from the OS.  What happens is if any of them are permenantly denied, on the next permission check Android will simply jump to "Nope!" without prompting,  and that in turn means there is not a lot of room for flexibility there.  Once denied there is no way to get back to it.   Google's documentation suggests to show the rationale for asking permissions, so I'm doing that (until they change their minds (they often do that...)).   

So I do get what you're saying, but this is the best workflow I can find that adheres to their policies and caters to different kinds of users.

**Comment by tessus** [comment]
I also do understand why you have this popup.

I'm just saying that there should be a checkbox to dismiss it forever (or create an option in settings, something like: `don't show permission requirements`).

**Comment by mendhak** [comment]
Aha however, however - In the normal workflow (after the fix) you'd only see it once, and you'd see it before you can get to the checkbox that says "Don't show me permission rationale".   The only workflow where that would help is if you get the prompt, deny all, go into settings, set the checkbox, then reopen the app.  That is not a normal path that I can see.  

Second - I want to be up front and transparent about why a permission is being requested, expert or not.  If I understand you correctly are you equating that to advertising? If so I cannot agree with that.

**Comment by mendhak** [comment]
But some workflow I could be missing?  Let me know if you think of any.

Assuming Google Drive is the only place that uses contacts.  So when a user is activating Google Drive, I could simply ask for the permission directly without the long rationale?   I can investigate doing that too at that point of feature request.

**Comment by tessus** [comment]
>  If I understand you correctly are you equating that to advertising? If so I cannot agree with that.

No, but it is just as annoying as ads. If I get a popup every time I open an app, it is very, very annoying, especially if I can't get rid of it. After I have read it once I think I know why they the permissions are needed and I don't need to read it again (unless I'm a person with no memory, but in that case, I couldn't use a smartphone anyway). Besides, if I really wanted to read that again, I could still go to Settings and click on the menu item that shows this window again.

I think, if the check for the contacts permission was removed from the check to show that window, it would solve this issue.

**Comment by mendhak** [comment]
Yeah definitely everytime is very very offputting.  I'll make sure to do that contacts bit you mentioned.  In the meantime definitely please accept the contacts permission (don't worry, not being used!) and I'll get it in v99. 

What do you think of my Google Drive question?  What is your expectation in that case?  Suppose a user has seen the reason, then granted the main permissions.  Then they go to Google Drive - would you expect to directly be asked the permission?   Unless you think otherwise I will try to aim for that

**Comment by tessus** [comment]
The long rationale is definitely great and explains the permissions nicely. For me personally it would be enough to have the menu item (which you have already implemented) to show the explanation.

Thus directly asking the permission sounds good to me. But maybe others would like to see the long rationale again. 
For the Google Drive situation, it doesn't really matter whether you ask for the permission directly or  additionally show the long rationale, because the user wants something from the app right at that moment.

**Comment by mendhak** [comment]
v100 has been released to market.

**Comment by tessus** [comment]
Great, thanks.

**Comment by mendhak** [comment]
Reopening this.  I did the change but it never made it to v100. -_-  Some kind of git fart occurred. 

I'll do this now then close after v101

**Comment by mendhak** [comment]
I shouldn't celebrate so early but I think I don't need the contacts permission anymore, using the Google Drive token workflow removes this need since Play Services acts as the oauth delegate... I should test properly first but I really want this to happen

**Comment by mendhak** [comment]
v101 pushed to market.
