### ISSUE TITLE
Latest update broke logging to a custom URL on the Nextcloud app Phone track.

### ISSUE THREAD

**Issue by sollermun** [mendhak/gpslogger#702]
I am using the Phone track app on nextcloud 14. After I updated to the latest version of GPSLogger, today, I am starting to get unexpected response code 400 errors.

**Comment by mendhak** [comment]
Are you able to test with a previous version to confirm? 

https://github.com/mendhak/gpslogger/releases

There was a Custom URL change introduced but not sure why it would cause a problem.  but would be good to get confirmation that an older version works.

**Comment by sollermun** [comment]
I just tested v97 and it works. Looks like it's definitely something with the latest update.

**Comment by mendhak** [comment]
I'm pushing out a fix now, reverting one of the commits

**Comment by mendhak** [comment]
Thanks for testing

**Comment by mendhak** [comment]
I've pushed v99 out to market.  

You can also get the APK here if you are feeling impatient:  https://github.com/mendhak/gpslogger/releases/tag/v99

**Comment by sollermun** [comment]
You're welcome, and thank you very much for this wonderful app.

**Comment by mendhak** [comment]
Glad you like! 
Please do let me know if v99 works.   I did do a lot of testing with Custom URL and everything seemed fine.  I'm going to investigate this particular case when I can as it's quite unexpected... but in the meantime  I am hoping this works fine for you.

**Comment by sollermun** [comment]
Just tested v99 and it is working great! Thank you for the quick fix.

**Comment by flamingm0e** [comment]
Confirmed working.  Thank you for the support.
