### ISSUE TITLE
Homeassistant Authorization Token

### ISSUE THREAD

**Issue by MikeFrizz** [mendhak/gpslogger#704]
Hello
I'm really desperate. I haven't found a suitable answer to my problem. So here's my question: In the instructions for the Homeassistant component gpslogger it says that I have to insert an authentication token into the area of the HTTP header. But which one is it? A token for homeassistant, for the user, for gpslogger? My line looks like this: 
`Content-Type: application/x-www-form-urlencoded Authorization:Bearer xxxyyyzzz`
But unfortunately the error message always appears in the log:
`Unexpected response codde (protocol=http/1.1,code=401, message=Unauthorized, url=https://xyz/api/gpslogger?lat......)`
How to write the line correctly. Or which token must I use.
Thanks for the fast support

**Comment by mendhak** [comment]
I think you are referring to this page:  https://www.home-assistant.io/components/device_tracker.gpslogger/

It's the token for Home Assistant.  Somewhere in your account pages you'll have a Long Lived Access Token (LLAT), that's what to put in place of xxxyyyzzz.  I think there are some [instructions here](https://www.home-assistant.io/docs/authentication/).  

And also you should either remove the `Content-Type` bit

    Authorization:Bearer xxxyyyzzz

Or if you need to keep it, put the `Authorization` bit on the next line
 
    Content-Type: application/x-www-form-urlencoded
    Authorization:Bearer xxxyyyzzz

**Comment by mendhak** [comment]
Also make sure the URL that you've got has no spaces in it.   I noticed that in the docs the URL given to copy paste does have a space/newline  between the `SER&` and the `accuracy`.  And between `PROV&` and `activity`


`https://YOUR.DNS.HOSTNAME:PORT/api/gpslogger?latitude=%LAT&longitude=%LON&device=%SER&accuracy=%ACC&battery=%BATT&speed=%SPD&direction=%DIR&altitude=%ALT&provider=%PROV&activity=%ACT`

**Comment by wsw70** [comment]
> Somewhere in your account pages you'll have a Long Lived Access Token 

_(in case someone is still looking for the information)_

This is in the profile, at the very bottom of the page (the profile is available by clicking on the circle with a letter (the first letter of your username), on the top left of the main page:

![image](https://user-images.githubusercontent.com/1345886/50679016-d4a36300-1001-11e9-9c1c-1770cf7c7f2b.png)

I just made it work on my HA installation.

**Comment by mendhak** [comment]
Is the Content-Type header necessary for Home Assistant to work?  I shouldn't think so, I had only left it in as an example and I wonder if the docs are just propagating it.

**Comment by wsw70** [comment]
@mendhak no, I just have the Authorization header

**Comment by mendhak** [comment]
I went in today to modify the page but it looks like the setup has changed - you can now get a webhook generated from Home Automation, it seems so.

The new page is at:  https://www.home-assistant.io/components/gpslogger/

Looking at the instructions on that page, no Authorization header is required, the webhook is unique for your component setup.
