### ISSUE TITLE
Save all the data from passive provider

### ISSUE THREAD

**Issue by iandees** [mendhak/gpslogger#705]
My GPS Logger configuration pulls in data once every 30 seconds if I'm moving. This works great for when I'm walking or biking, but when I'm driving I usually have navigation running with the GPS system on the whole time. Since the polling time in GPS Logger is set to 30 seconds, it only grabs one of those locations every 30 seconds and doesn't log the rest of them. I'd like to have a way to save *all* the data from a passive provider. I'm already paying the energy price for it, so we might as well save it.

I realize that it probably makes the most sense to figure out how to get this working with some external state-tracking app like Tasker, but I thought I'd put the idea here to see what you think.

**Comment by iandees** [comment]
Thanks for trying this out! I'll have to give the branch a try later this week.

I agree that adding this might make configuration more complicated than intended. I don't have a great suggestion for that, other than to say your implementation makes sense – ignoring the time filter for passive provider-sourced data is what I had in mind.

**Comment by mendhak** [comment]
Updated version with the Passive toggle as a its own preference


[APK](https://drive.google.com/file/d/1yRhEkvxf7WCooFeZ9CQ_YxtIIv7z1ZwK/view?usp=sharing),
[signature](https://drive.google.com/file/d/1MgpYcPUf2re2YJw1xxOv6BdkqbHqPIPn/view?usp=sharing),
[checksum](https://drive.google.com/file/d/1bmY1UudmIcNwIXhrdj0UV2FMBEpvFGwC/view?usp=sharing)

**Comment by mendhak** [comment]
v100 has been released to market.
