### ISSUE TITLE
Feature Request: list of connected bluetooth devices

### ISSUE THREAD

**Issue by wsw70** [mendhak/gpslogger#707]
It would be very useful to have, as part of the available parameters, the ability to send in the Custom URL the list of the bluetooth devices currently connected.

It would allow to filter / process positions based on some context. In my case the fact that my car BT is connected would man that I am driving, if this is the headset, it would be biking, etc.

**Comment by mendhak** [comment]
I've been thinking about both this as well as [wifi SSID](https://github.com/mendhak/gpslogger/issues/697).  I'm not looking to implement either, the complexity that these introduce is just too high. And with SSID logging I'm just uncomfortable doing it, even though to be honest I'm struggling to articulate why.  On the other hand, logging a tower ID, if such a thing is available, is a little less uncomfortable for me.  So I am closing this now and sorry for the late reply.

**Comment by wsw70** [comment]
Thank you for having considered this.

I was hoping to be able to send detailed, contextual location information to make decisions upon them but never mind, I will find a way to send them independently as well.

Thanks a lot for your program!
