### ISSUE TITLE
GeoJSON log file, numerical values without quotation marks

### ISSUE THREAD

**Issue by KEGustafsson** [mendhak/gpslogger#711]
Would it be possible to change GeoJSON file so that all numerical value properties (time_long, accuracy, altitude, bearing, speed) would be without quotation marks?
When importing file to e.g. Influxdb, values within quotation marks are strings, not values (float). 

Current files format:
      "properties": {
        "bearing":"76.85463",
        "speed":"0.020238776"
      }

Proposed format:
      "properties": {
        "bearing":76.85463,
        "speed":0.020238776
      }

**Comment by mendhak** [comment]
I've changed the formatting so now the quotes should be gone for the numeric values. 

If you are able to sideload you can try the APK already:

[APK](https://drive.google.com/file/d/1yRhEkvxf7WCooFeZ9CQ_YxtIIv7z1ZwK/view?usp=sharing),
[signature](https://drive.google.com/file/d/1MgpYcPUf2re2YJw1xxOv6BdkqbHqPIPn/view?usp=sharing),
[checksum](https://drive.google.com/file/d/1bmY1UudmIcNwIXhrdj0UV2FMBEpvFGwC/view?usp=sharing)

**Comment by KEGustafsson** [comment]
Tested and working!

**Comment by mendhak** [comment]
v100 has been released to market.
