### ISSUE TITLE
Logging to CSV at more decimal places

### ISSUE THREAD

**Issue by idelac** [mendhak/gpslogger#713]
It would be nice if coordinates logged in CSV file are stored at more than 6 decimal places. Seven would be enough (1 cm precision) but why not make it 8 to be identical to GPX.
There is a need for that because phones with dual-frequency GNSS are showing-up and testing them requires coordinates to be stored at more than 6 decimal places.

**Comment by mendhak** [comment]
Sorry for late reply . 

I don't believe I'm formatting or truncating the decimals, are you observing the _same_ coordinates stored differently in GPX vs CSV?  I could investigate if you notice differences but the code is simply taking what the OS provides and writing that to file.

**Comment by idelac** [comment]
Yes, I am observing the same coordinates stored at the same time but differently in GPX and CSV. Meanwhile I tried another app which stores in CSV in 8 decimal places. Also tried on another phone, same thing there.

**Comment by fpczk** [comment]
I can confirm this behaviour. In the csv logger, the `String.format` method is being used to build the output string, while in the gpx logger, the `String.valueOf` method is being used. Both seem to default to different precisions, the default of  `String.format` being 6 digits.

**Comment by mendhak** [comment]
Got it - I'm seeing it now.  I'll have a look at why this is happening as @fpczk said it's likely related to `String.format`

**Comment by mendhak** [comment]
v100 has been released to market.

**Comment by mendhak** [comment]
Forgot to comment - try the CSV precision in v100. Shouldn't be a problem anymore
