### ISSUE TITLE
Don't display passwords in clear text

### ISSUE THREAD

**Issue by semperor** [mendhak/gpslogger#716]
If using the send to custom URL method with authentication one has to enter user name and password into the URL field. One would prefer a secure storage of the password.

**Comment by mendhak** [comment]
Can you clarify this - the SharedPreferences is limited to the application that controls it.  So as far as the SDK is concerned the storage is secure.   If it's encrypted and stored in SharedPreferences then the decryption key will be in the application itself, so the purpose is defeated.

Or do you mean don't _display_ the password in the URL field, which is different?  If that's what you mean I think a separate 'basic authentication' field can be created, but it only solves one use case,  many users also have API Tokens that needs to go in there.

**Comment by semperor** [comment]
After thinking about your objection, I clearly meant "Don't display...". :)

**Comment by mendhak** [comment]
OK I am dealing with #715 and #716 together.  I think the #715 is more relevant, will post there soon so closing this one.
