### ISSUE TITLE
Help/FAQ - suggested clarification

### ISSUE THREAD

**Issue by MikeParfitt** [mendhak/gpslogger#717]
In the help/FAQ screen there is a topic with the title "Don't log if I'm not moving"

I suggest that the text of this item be re-written as follows :-

**Some Android device have motion sensors.  If you enable this setting and the motion sensors indicate that you have stopped, then GPSLogger will not log any points for ## seconds, even if you start moving before then.**

The performance page where the "Don't log if I'm not moving" setting is enabled/disabled could be re-written as follows :-

**If there is no accelerometer movement since the last point, active logging will pause for ## seconds, even if you start moving before then.  Passive points may still be logged.**

Please insert the value for ## seconds in both of the texts above.

These clarifications will better explain how GPSLogger behaves if this option is enabled.  My incorrect interpretation of the current text was that logging would re-start almost immediately after the accelerometer next detected movement - provided that the point met the criteria set by the other time/distance/accuracy settings.

A suggested enhancement would be to allow the user to specify their own value for the period between accelerometer checks.

Regards,

Mike

**Comment by MikeParfitt** [comment]
What would you like to discuss ?

**Comment by mendhak** [comment]
Thanks for the better wording.  I've now added those in, but without the numbers substituted in.  The Help/FAQ bit is generated from some Markdown which also appears on the main gpslogger.app site.

**Comment by mendhak** [comment]
v100 has been released to market.

**Comment by MikeParfitt** [comment]
Hi,

I see the changes in v100.  Glad to help.

Only one thing to note, my Logging Interval is set to 1 second, but active logging was pausing for up to a minute when I had the "Don't log if i'm not moving" setting enabled.

I have the "Absolute time to GPS fix" set to 60 seconds.  Is GPSLogger actually using this for the "Don't log if i'm not moving" pause period ?

Regards,

Mike

FYI : points are typically logged every 2-5 seconds while driving, given my distance/accuracy settings.
________________________________

**Comment by mendhak** [comment]
Hey the app is using the same value as the GPS logging interval

https://github.com/mendhak/gpslogger/blob/8f31c48b960e338d9be7a055e71f9d47608c4515/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L103-L104

Now the bit that may be confusing is that although the interval _requested_ is matching the GPS interval, the OS can decide otherwise. 

> Activities may arrive several seconds after the requested detectionIntervalMillis if the activity detection service requires more samples to make a more accurate prediction.

> To conserve battery, activity reporting may stop when the device is 'STILL' for an extended period of time. It will resume once the device moves again. This only happens on devices that support the Sensor.TYPE_SIGNIFICANT_MOTION hardware.

> Beginning in API 21, activities may be received less frequently than the detectionIntervalMillis parameter if the device is in power save mode and the screen is off

In my testing this lack of updates can go on for up to 20-30 minutes, but I've got no way to predict per-phone behavior.
