### ISSUE TITLE
Feature Request - Smaller Time Intervals

### ISSUE THREAD

**Issue by Sunnmann** [mendhak/gpslogger#718]
In setting for Auto Send it states to put time intervals in minutes. I was wondering if it was possible to change this to seconds? I would like to get this down to 10-15 seconds.

I would like to use this while working with an Community Emergency Response Team and send the tracks to an OpenGTS server I have set up. This way we can track our assets on the ground when searching for someone or helping someone at one of our events. We are non profit and volunteer based, so free is always good for us.

Your GPSLogger program works great with my OpenGTS server, except the auto send intervals.

**Comment by mendhak** [comment]
You should already be able to do this - the key is in the difference between logging and sending. 

The OpenGTS screen still allows for logging and logging will follow the logging interval that you set.  eg you can set it to 10 seconds and you should get OpenGTS logs roughly 10-15 seconds.  The app will get a fix after waiting 10 seconds... should take a few seconds to get a fix, then send to your OpenGTS server.    

You can fill in the values in the OpenGTS screen and turn off that 'Allow auto sending' at the top. The auto send feature is only for full-file sends.  In the case of OpenGTS it re-reads the entire GPX file and re-sends all requests.  So it can be confusing.  It makes more sense with the other senders, like Google Drive - it reuploads the file over and over every _x_ minutes.  For that reason, auto-sending is in minutes to avoid abuse, and logging is more flexible.

**Comment by Sunnmann** [comment]
After posting I did notice the logging interval under performance, but did not know the difference. Now I do and I thank you very much. 

So, now back to other sites to get some answers on customizing OpenGTS.

Once again, thank you very much for clearing this up for me.

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
