### ISSUE TITLE
Put some filter on data from passive provider

### ISSUE THREAD

**Issue by Helium314** [mendhak/gpslogger#720]
The changes in passive provider introduced in v100 result in my position jumping frequently between my 'real' position (determined from WiFi) and the nearest cell tower.

Would it be possible to implement some rough filter for the passive provider to avoid such jumps?

For example: only save the new point if
* either the accuracy is better than the previous one
* or if the traveled distance is bigger than the added accuracy of old and new points

This would allow to use most data of the passive provider, but discards 'useless' points.
And by the way, you might want to remove the description of the passive provider from 'location providers'.

**Comment by mendhak** [comment]
Can you explain the 2nd point, I'm not understanding it.  Example - the old point has accuracy 10m, the new point has 15m, and the measured distance is 12m.  It still appears to be a valid point.


I've already got a filter on the points being logged, which does apply to passive

https://github.com/mendhak/gpslogger/blob/8f31c48b960e338d9be7a055e71f9d47608c4515/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L817-L826

however it's only testing for a ridiculous distance.

**Comment by mendhak** [comment]
I'm going to reapply the accuracy filter to passive locations but ignore the distance filter. 

I've put an APK to test here:  https://github.com/mendhak/gpslogger/releases/tag/v102

**Comment by mendhak** [comment]
v102 pushed to market
