### ISSUE TITLE
unable to upload to nextcloud

### ISSUE THREAD

**Issue by r100gs** [mendhak/gpslogger#721]
Hello,

I get an error message if I try to upload a file to nextcloud 14.

Error:
Tut uns Leid

Datei konnte nicht hochgeladen werden

Local file does not exist

I have included the debuglog. I am using a oneplus 6 with android 9.
[debuglog (1).txt](https://github.com/mendhak/gpslogger/files/2944680/debuglog.1.txt)

Best regards, 
Stefan

**Comment by mendhak** [comment]
In a [past issue](https://github.com/mendhak/gpslogger/issues/381) this was due to the target directory not existing on the OwnCloud/NextCloud instance.  Can you try creating the dir then uploading to it?

**Comment by r100gs** [comment]
Ok, thx! I created a new directory on my nextcloud and now its working again!

THX!

**Comment by mendhak** [comment]
Good to know, thanks.
