### ISSUE TITLE
Report; Custom URL, php, SQL

### ISSUE THREAD

**Issue by zotz** [mendhak/gpslogger#722]
Not so much an issue as a short Report.

Last night I posted a comment to:

Send data to CartoDB server #310
https://github.com/mendhak/gpslogger/issues/310

Just reporting back the results of some quick experiments this afternoon.

I made changes  to the Log to Custom URL area.
I changed the URl to point to a PHP file that I tweaked a bit for this testing.
I changed the HTTP Body to send in 2 parameters, key= and query=, where key controls if the php script deals with the query or not and query is basically a json/geojson string containing the data I want to send in.
PHP Headers I left alone. (IIRC.)
HTTP Methog I changed to POST.
My SSLCert validated.

I have at this point succeeded in having GPSLogger post gps data to my php file which then successfully inserts the info into a MariaDB/MYSQL database (it remains to test inserting into postgis) and having the data shown as features on an openlayers map using an openstreetmap base map.

I thought someone might like to know this.

drew

**Comment by mendhak** [comment]
Thanks for sharing that.  Just for reference I've also written a sample codebase which can receive requests and writes to a CSV file, just as a starting point. 

https://github.com/mendhak/gpslogger-customurl-receiver

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
