### ISSUE TITLE
Creation of new logo

### ISSUE THREAD

**Issue by debpedrano** [mendhak/gpslogger#725]
Good day project owner, 

About the enhancement of the project, it would be better to have its own logo for a clearer view and can be recognized easily. Just my opinion, just mention me and im ready to create a new one!.

**Comment by mendhak** [comment]
HI do you mean for the app (eg app icon, menu icons etc) or this project itself (eg the README, Play Store banner, etc)

Sure if you have time any logos would be good to look at.  I've got zero graphics skills so this app look has just been cobbled together.  The current logo, I got it from fiverr and seems to do the job.

**Comment by debpedrano** [comment]
The project itself, the logo will signify the whole project that can be recognize easily. Ill be sending logo samples, and it is you to choose what design that really fits on the project. Thanks a lot!
