### ISSUE TITLE
Cannot change location providers since last update

### ISSUE THREAD

**Issue by ChlorideCull** [mendhak/gpslogger#726]
Since the last update on the Play Store, I can't change location providers in the settings.

I did finally manage to get it working again by manually removing "passive" from the listeners set in the settings file, so it most likely has something to do with that.

**Comment by mendhak** [comment]
What was happening when you tried saving, would it refuse to save or would it reset to the original settings?

**Comment by ChlorideCull** [comment]
It would straight up crash the app. Once I restarted the app, it wouldn't have saved any changes.

I can reproduce it again, if you want a crash dump.

**Comment by mendhak** [comment]
What would be helpful is if you can try to reproduce the problem but with this APK here - only if you are willing and able to sideload APKs.  It's signed with the release key so you'll still get the Play store updates

[APK](https://drive.google.com/file/d/1AIKjc7jzUyoaL2COOXCdoMKj4NZ_31aC/view?usp=sharing), [signature](https://drive.google.com/file/d/1kOpV29S_TQuxt_pSQL-z2wmYfd7-YJJY/view?usp=sharing), [checksum](https://drive.google.com/file/d/1a852eHMsg17aX4F8LYJE46HEiNaL25H8/view?usp=sharing)


If you're not comfortable with that, that's OK too, in that case the [debuglog.txt](https://gpslogger.app/#troubleshooting) should be useful, though I hope this change I've just pushed is the correct fix. 

In this change I've now removed the checkboxes selection, now GPS, Network and Passive are each their own menu item. 


![image](https://user-images.githubusercontent.com/746276/55037293-32e64d80-5015-11e9-9c99-54cd2a4b08d5.png)

The `listeners` key in the settings file is no longer valid.
On app startup the app will once read from `listeners` and migrate it to the new preferences.

**Comment by mendhak** [comment]
v101 pushed to market.
