### ISSUE TITLE
Bug? Cannot switch storage path

### ISSUE THREAD

**Issue by slideup-benni** [mendhak/gpslogger#727]
Hello,

i reinstalled my android and therefore i created a backup of gpslogger with titanium backup and restored it after.
I decided to use my sd card as internal storage and not as portable storage (as before).
The problem is, that gpslogger logged all data to the sd card, that isn't available now. I tried to change the path, but nothing happend. When i click "ok" an error occurs, that gpslogger has no write-rights in the selected folder.

Is there any config file where i can change the path manually until this bug has been corrected?

**Comment by mendhak** [comment]
What is the 'stored' path versus what are you trying to change it to? 

Can you do two things - 

First is go to general settings, enable debug log.  Then try changing your storage path and let it fail.  What this will do is record the error, if any, in the debug log file.  Can you email that to me, `gpslogger @ mendhak.com`.  Of course turn off debug logging after that. 

Second, what you can do to reset is...  you can [follow these instructions](https://gpslogger.app/#howcanidefineapresetfilewithmyownvalues).  By creating a `gpslogger.properties` file, you should be able to set 

    gpslogger_folder = /storage/emulated/0/Android/data/com.mendhak.gpslogger/files

for example and on the app start it should read that value and set it. 

If that also doesn't work, worst case scenario, you'll have to reset the app storage, which will delete all the preferences including storage path

**Comment by mendhak** [comment]
OK I am working on an idea.  I'll remove the directory picker and present a text field. 

![image](https://user-images.githubusercontent.com/746276/56079999-7c93ae00-5df3-11e9-85fc-3781c5a779ae.png)

After clicking OK, I'll create the directory path and test if the app `canWrite` to that path, if it cannot then I show an error

![image](https://user-images.githubusercontent.com/746276/56080018-a77e0200-5df3-11e9-9afc-2c5ca01d3f3e.png)

and restore the old path

**Comment by mendhak** [comment]
I've updated the prerelease APK with the above change:

https://github.com/mendhak/gpslogger/releases/tag/v101

**Comment by mendhak** [comment]
v101 pushed to market.
