### ISSUE TITLE
Android Q - Scoped Storage is coming

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#731]
This affects permissions regarding files.  Will need to research what the fix entails. 

https://commonsware.com/blog/2019/03/25/death-external-storage-what-now.html
https://developer.android.com/preview/privacy/scoped-storage

**Comment by VarunBatraIT** [comment]
Looks like this is why we can't edit the custom default folder path.

**Comment by mendhak** [comment]
The latest version has a custom file picker/folder picker and asks for manage storage permissions so I've worked around it in that way. 

In the future, I might have to look at using SAF libraries for writing files, but right now it's not possible to write to specific random locations.
