### ISSUE TITLE
Passive Location

### ISSUE THREAD

**Issue by gregg098** [mendhak/gpslogger#735]
I've been using GPS Logger for passive location updates to Home Assistant for a long time now. Recently, passive location updates was broken out and no filters are applied. I can deal with this, even though it sends a ton of updates to Home Assistant. As of the latest update, the app will not send any updates at all unless either GPS or network location is selected. I do not wish to use GPS logging because it drains my battery faster (and not required in my use case) and network location is not very accurate. 
Can you re-allow passive-only updates? This worked fine for periodic updates to Home Assistant. Allowing filters would be even better.

Thanks.

**Comment by mendhak** [comment]
OK I have reset to allow passive only, so the forced satellite vs network won't happen now. 

There's an APK you can test with here:  https://github.com/mendhak/gpslogger/releases/tag/v102

**Comment by mendhak** [comment]
I'm going to reapply the accuracy filter to passive locations but ignore the distance filter. 

APK has been updated:  https://github.com/mendhak/gpslogger/releases/tag/v102

**Comment by gregg098** [comment]
Just downloaded and installed. Was able to turn off network and GPS location updates. Location seems to have updated properly after I went into Google Maps to simulate a passive location.

Thanks for the quick turn around. Really appreciated. Going to donate a coffee!

**Comment by mendhak** [comment]
v102 pushed to market
