### ISSUE TITLE
Logging tracking info to my postgres database

### ISSUE THREAD

**Issue by kjibran** [mendhak/gpslogger#739]
I have been using your great app on my smartphone and it works really well. I have PostgreSQL 10 installed at my Windows 8 machine. I would like to make GPSLogger and Postgres talk to each other. However, I am not postgres expert so seeking your help!

I see PostgreSQL has an extension 'http' as HTTP client for PostgreSQL database. I would like to send GPS logging info (via GPSLogger custom URL feature) to my PostgreSQL server, and save it in respective database (via postgres HTTP extension). I haven't seen such examples (Postgres http + GPSLogger) available online, so, could you please explain a bit how this can be achieved? Would you also suggest alternative ways to do the same?

My GPSLogger already points to the following URL:

`http://my_ip_address:my_port/log?lat=%LAT&longitude=%LON&time=%TIME&s=%SPD`

**Comment by mendhak** [comment]
I don't think the HTTP client for Postgres will help you - that's simply a way to query an HTTP endoing _from_ Postgres.  

    SELECT status, content_type FROM http_get('http://httpbin.org/');

But you are looking to send information _to_ your database. I think what you are looking for is [PostgREST](http://postgrest.org/en/v5.2/) which puts a web server in front of your DB.  

You can follow the docs there, generate a token, and then you can see the kind of request to make

http://postgrest.org/en/v5.2/tutorials/tut1.html#step-4-make-a-request

**Comment by kjibran** [comment]
Thanks a lot for your response and suggestion.

PostgREST API is up and running at the top of my Postgres database. I generated tokens, and via this command, I am able to insert a "test" record into my postgres database.

`curl -X POST -d "{\"task\": \"this a test\"}" -H "Authorization: Bearer %my_token%" -H "Content-Type: application/json" http://localhost:3000/test_table`

The table `test_table` also has columns `lat (double precision)`, `lon (double precision)`, `time (timestamp without time zone)`. GPSLogger sends the GPS data via this link to my machine (port 3000):

`http://my_ip_address:my_port/log?lat=%LAT&longitude=%LON&time=%TIME`

I tried to insert this data into my postgres `test_table` via:

`curl -X POST -d "{\"lat\": \"%LAT\", \"lon\": \"%LON\", \"time\": \"%TIME\"}" -H "Authorization: Bearer %my_token%" -H "Content-Type: application/json" http://localhost:3000/test_table`

I get this error:
```
{
  "hint": null,
  "details": null,
  "code": "22P02",
  "message": "invalid input syntax for type double precision: \"%LAT\""
}
```
The [postgres error 22P02](https://www.postgresql.org/docs/current/errcodes-appendix.html) shows "invalid text representation". I tried changing `lat, lon` datatype to `flaot8 `but no success. Can you please help to resolve this input syntax error?

**Comment by mendhak** [comment]
curl is just sending the `%LAT` as-is, curl has no way of substituting that value for you.  If you want to test it you should put a real value in like 123.45 instead of `%LAT`

The `%LAT` is a string that GPSLogger will substitute with a 'real value' when you try your in-app testing

**Comment by kjibran** [comment]
You are right, curl was sending `%LAT` instead of its value. So, I already made some tests. They went well. For example, inserting real values in postgres database (via PostgREST and curl) worked:

`curl -X POST -H "Content-Type: application/json" -d '{"id": "1", "lat": "1.123456789", "lon": "36.123456789", "time": "2019-05-16T22:07:23.015Z"}' http://localhost:3000/test_table | jq ""
`

In above case, columns `lat` and `lon` in postgres table had data type `double precision`. Please note that I am using curl inside GitBash so you don't see `\` with `""`.

Then, I tried to set `lat, lon `values as a variable (please note `export` and `$` here in gitbash instead of `SET `and `%%` in Windows):

```
$ export lat=1.1425698
$ export lon=36.1425698
```

and sending them to postgres using following command worked.

`curl -X POST -H "Content-Type: application/json" -d '{"id": "2", "lat": '"$lat"', "lon": '"$lon"', "time": "2019-05-16T22:07:23.015Z"}' http://localhost:3000/test_table | jq ""`

Above example inserted a row in my postgres database with corresponding variable values. Then, I switched to header `-H "Content-Type: application/x-www-form-urlencoded"` to account for data sent by GPSLogger and used the following command:

`curl -X POST -H "Content-Type: application/x-www-form-urlencoded" -G --data-urlencode 'lat=$LAT' -G --data-urlencode 'lon=$LON' http://127.0.0.1:3000/gps_tbl | jq ""`

It worked !! and yielded no errors. However, a blank row was inserted into my postgres database :( I don't understand why.

I further tried to play with single and double quotes and tried this:

`$ curl -H "Content-Type: application/x-www-form-urlencoded" -G --data-urlencode '"lat"="$LAT"' -G --data-urlencode '"lon"="$LON"' http://127.0.0.1:3000/gps_tbl | jq ""`

Above command yielded error:

```
{
  "details": "unexpected \"\\\"\" expecting \"not\" or operator (eq, gt, ...)",
  "message": "\"failed to parse filter (\"$LAT\")\" (line 1, column 1)"
}
```

I think, I am close to giving up as I have no idea where I am making the mess. 

Do you have any suggestions to work around?

Referring to your comment above, did you mean it is not possible to send data (grabbed from custom URL) to postgres using CURL?

**Comment by mendhak** [comment]
You don't need to switch your header to 

> -H "Content-Type: application/x-www-form-urlencoded"

You should stay with the header you originally had

> -H "Content-Type: application/json"

So what you have done is you've proven that you can insert into the DB using:

    curl -X POST -H "Content-Type: application/json" -d '{"id": "1", "lat": "1.123456789", "lon": "36.123456789", "time": "2019-05-16T22:07:23.015Z"}' http://localhost:3000/test_table 

What you should do next is actually use GPSLogger.   Go into Custom URL screen and set your URL in there to

    http://192.x.x.x:3000/test_table

Where 192.x.x.x is your computer's IP

Then, in the headers setting, remove the existing header there and make it your own

    Content-Type: application/json

Then set the body to 

    {"id": "1", "lat": "1.123456789", "lon": "36.123456789", "time": "2019-05-16T22:07:23.015Z"}

Yep, hardcode it to begin with. 

Then go to main screen and log a single point.  Assuming your phone + computer are on the same network you should receive a request on the computer side.  If you have logging enabled of some sort then you can stare at the logs. 

Once you get that working, in the GPS screen, begin substituting values.  Change the body to


    {"id": "1", "lat": "%LAT", "lon": "36.123456789", "time": "2019-05-16T22:07:23.015Z"}

Then test that, make sure an actual latitude is sent. 

Then keep substituting.

**Comment by mendhak** [comment]
> Referring to your comment above, did you mean it is not possible to send data (grabbed from custom URL) to postgres using CURL?

Right, the URL that you enter in the Custom URL screen is actually not a real URL, it's a templated URL, all the `%things` are just placeholders.  GPSLogger will process that URL and subsitute values in the URL/Body before sending it.  What you're doing with your curl command is simply ensuring that the PostgREST interface actually works.  Then you give it to GPSLogger, a fixed, working URL, to prove that the mobile device can hit the PostgREST interface.  Then you start giving it actual values with the `%LAT`

**Comment by kjibran** [comment]
Thanks a lot for your detailed response and tips!! I am happy to tell you that things moved forward (but with some errors).

So, as a first step, I changed URL and headers in GPSLogger app, configured PostgREST and tried sending following:

`{"id": "1", "lat": "1.123456789", "lon": "36.123456789", "time": "2019-05-16T22:07:23.015Z"}`

It worked, and I could see log at my PostgREST API console with some HTTP codes.

You suggested that both my laptop and smartphone need to be on the same network. I went one step further and tested both scenarios (same and not same network).

Here is what happened.

**Using smartphone 1 (HUAWEI, from external network)**

Here is PostgREST API console log. The log messages appear with a delay at console in this case (I don't know why).

```
[23/May/2019:22:47:30 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:30 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:30 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:32 +0200] "POST /test_api.gps_tbl HTTP/1.1" 404 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:33 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:47:34 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
```

Out of so many `HTTP 404s (not found)` and `HTTP 409s (conflict)`, you see only one `HTTP/1.1 201` code which means at least one row was posted. It is here in my postgres db:

```
id     lat                            lon                           time            
1	"1.123456789" 	"36.123456789"	"2019-05-17 00:07:23.015+02"
```

**Using smartphone 2 (Samsung, same WIFI network):**

Only `HTTP 409s `here

```
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:11 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"
[23/May/2019:22:51:12 +0200] "POST /gps_tbl HTTP/1.1" 409 - "" "okhttp/3.7.0"

```
I don't why it throws **`HTTP 409 (conflict)`** error. Any hints/suggestions?

**Comment by mendhak** [comment]
Hang on, your table has id, lat, lon, time. But your message body contains an ID as well.  Is that ID your primary key in the table? That could explain a conflict, that would explain why you have a 201 followed by lots of 409s.   If the ID is a primary key you shouldn't be inserting it, it should be auto generated for each new row that you insert

**Comment by kjibran** [comment]
You are so right, ID is serial (primary key/not null). I removed "id" from body and use "lat": "%LAT" etc. and BOOM !!! It worked.

```
[23/May/2019:23:35:11 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:23:35:11 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:23:35:18 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:23:35:24 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:23:35:31 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"
[23/May/2019:23:35:37 +0200] "POST /gps_tbl HTTP/1.1" 201 - "" "okhttp/3.7.0"

```
Now I have real-time lat lon data with timestamp in my postgres database and I am happy about it :)

But, there is a new problem. The ID numbers are not in order. They are random. For the first six logged records, IDs are:

![image](https://user-images.githubusercontent.com/6083619/58288653-8a562f00-7db4-11e9-9049-ccc61dc13927.png)

Do you have any idea why?

**Comment by mendhak** [comment]
Yes, that is by design.  For each request that you attempted, postgres generated an ID value. The insert failed because you were trying to force a `1` in that column, which was a primary key violation.  The transaction rolled back, but Postgres discards the ID it had generated.  Although it's possible to have [gapless sequences](https://wiki.postgresql.org/wiki/FAQ#Why_are_there_gaps_in_the_numbering_of_my_sequence.2FSERIAL_column.3F_Why_aren.27t_my_sequence_numbers_reused_on_transaction_abort.3F) in postgres, if you're not already familiar with Postgres/DBs then it is better to stick to the default behavior.  The purpose of the ID column is to give you a unique value, so it could be anything.

**Comment by kjibran** [comment]
I recall I deleted few rows while playing with CURL, PostgREST etc. so they were following the default previous sequence. I created a new table, and everything seems to be in perfect order !! :)

Thanks x 1000 for your help and tips! Saved me from a lot of headaches ;) I am a fan!

**Comment by mendhak** [comment]
Alright, glad to know it's working.  👍
