### ISSUE TITLE
Adding more headers to header settings

### ISSUE THREAD

**Issue by kjibran** [mendhak/gpslogger#744]
Hi,

I have a question with reference to my previous (closed) [issue](https://github.com/mendhak/gpslogger/issues/739). As you suggested, I added the following in the GPSLogger app in my phone:

`Content-Type: application/json`

PostgREST takes care of security by using following header:

` -H "Authorization: Bearer $TOKEN"`

Where, `$TOKEN` is the security token. Now, my question is: Is it allowed to add multiple headers in the header settings of GPSLogger App? If yes, how do I add above header?

**Comment by mendhak** [comment]
Just add a newline and then your new header.  

    Content-Type: application/json
    Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by kjibran** [comment]
I am back to update you on this issue. It actually worked! Now, my GPS logging is end-to-end secured.

Thank you for the suggestion. I would now close this issue.

**Comment by mendhak** [comment]
Hey thanks for the update glad you got it working.  :)

**Comment by mendhak** [comment]
v103 released to market (removed the example header)
