### ISSUE TITLE
Stealth Hidden Mode Feature Request for GPSLogger

### ISSUE THREAD

**Issue by cyberpine** [mendhak/gpslogger#75]
Requesting a feature that enables GPSlogger to run in the background and not show up under task manager for Stealth Mode.

**Comment by giacecco** [comment]
@mendhak can you confirm that there is no way to hide the app in Android 6? Lots of other applications happen to use GPS (e.g. Fitbit when going for a run) but there is nothing showing that it is happening.

GPSLogger instead appears both in the status bar at the top and in the notification screen, as shown below:

![screenshot_20160429-142018](https://cloud.githubusercontent.com/assets/303693/14917364/92b07afe-0e16-11e6-8d68-56267964c524.png)

![screenshot_20160429-142025](https://cloud.githubusercontent.com/assets/303693/14917359/8f5921e4-0e16-11e6-8741-82fba418d118.png)

Enjoy the coffee, btw!

**Comment by mendhak** [comment]
In order to run continuously, the app needs a persistent notification.  You're not allowed to have a persistently running app without an icon though.   Although other apps can use GPS, they normally use  it short term (because you don't run for days) or wakelocks (keep CPU awake for a bit).

**Comment by giacecco** [comment]
Understood, however I'm using the "Don't log if I'm not moving" option. I expected GPSLogger not to check for GPS signal continuously when the mobile phone is still on my desk, for example. Is that a bug perhaps? Or GPSLogger keeps (without a reason) checking for signal but simply does not write anything in the logs?
