### ISSUE TITLE
gpslogger suddenly logs every second

### ISSUE THREAD

**Issue by lenzp** [mendhak/gpslogger#751]
I  am on a long trip, and gpslogger worked very well for a few days. Now  suddenly it logs every second from time to time. I can not see any  pattern in thie misbehaviour. gpslogger should log a point every 5 minutes and send a logfile via  e-mail every 15 minutes. Attached you find some normal log files and in  the middle a big wrong one. Also the file from 14::27 contains one wrong  point!
[Logfiles.zip](https://github.com/mendhak/gpslogger/files/3294214/Logfiles.zip)

**Comment by lenzp** [comment]
I am on a long trip, and gpslogger worked very well for a few days. Now suddenly it logs every second from time to time. I can not see any pattern in thie misbehaviour.
gpslogger should log a point every 5 minutes and send a logfile via e-mail every 15 minutes. Attached you find some normal log files and in the middle a wrong one. Also the file from 14::27 contains one wrong point!

**Comment by mendhak** [comment]
What is the new file creation setting?  Are you using a custom file name?  Also do you have passive logging enabled?

I think here the [debug log](https://gpslogger.app/#troubleshooting) would help 

If I were to guess this looks like the GPSLogging service is being killed by Android continuously and restarted, so each restart corresponds to a new file.

**Comment by lenzp** [comment]
I never changed the settings:
- recording interval = 300 seconds
- distance between measure points = 5 m
- send e-mail every 15 minutes

Your theory seems to be wrong because there are many useless measurements in one file. Today gpslogger created about 150 logfiles during 2.5 hours.

I attach one of these log files and the error log.

[debuglog.2019-06-16.txt](https://github.com/mendhak/gpslogger/files/3294765/debuglog.2019-06-16.txt)

[201906161946.zip](https://github.com/mendhak/gpslogger/files/3294768/201906161946.zip)

**Comment by mendhak** [comment]
From the debug log I see a lot of passive locations are enabled and being logged and also dynamic file names are enabled.  So the file name is changing every minute and passive locations are being received from another application very frequently.  

Can you check what your custom file name setting is? Are you only using passive location manager and not using GPS/network at all? 

Although the passive location would explain the frequency of locations being received that doesn't explain why a new file is being created so frequently.  I am asking for application settings so I can try recreating the problem on my own devices.

You can also try just disabling passive locations and see if that stops creating a new file every minute.

**Comment by lenzp** [comment]
You are right, I had passive locations enabled and I was using a navigation app on the same time. But IMHO this should not matter. If my log interval is 300 seconds, also passive locations should not ignore this interval.

And you are also right about the file name. It is %YEAR%MONTH%DAY%HOUR%MIN which is IMHO correct if I want logfiles every 15 minutes.

**Comment by mendhak** [comment]
Passive is a special listener - most of your filters will be ignored in passive.  This is because if you've spent the energy to get a location, you can optionally get GPSLogger to record those  as well.  Having a time interval on passive can't happen since other applications won't match the time interval that you'd like nor can those locations be stored without incurring an overhead.  So the best option here for you is to disable Passive. 

Now with that file name you've set, you should get a new log file every _5_ minutes.  Although you have asked for autosend every 15 minutes, because file name changes 3 times, each filename change should result in another email being sent, and you are probably receiving an email every 5 minutes.  It's a compromise because bunching up files at the correct interval often results in some SMTP servers rejecting the email so it's safer to just send the email when the filename changes.

**Comment by mendhak** [comment]
Just for safety I have deleted the debug log you posted.  For next time it is safer to just email me the debug log.

**Comment by lenzp** [comment]
Thank you very much for explanation. There seem to be some details which work copletely different than I suppose they should work. But I also suppose you have good reasons to do so. I will try to find out how do l get filename changes every 15 minutes. Or perhaps better if I send e-mails every hour.

Thank you for deleting my logfile, but there are no secrets. I am publishing all locations on my site www.ba-bo.de

Sorry, I don't know how to send you an e-mail, the address seems to be a bis secret and of course there are good reasons to keep it secret. But I have annother question (what happens if gpslogger tries to send e-mails, but the internet connection is interrupted?) and this is off-topic here and it is not a bug, it is perhaps a FAQ.

**Comment by mendhak** [comment]
Ah yeah my email is usually in the commits but it is:  `gpslogger @ mendhak.com` - only needed if there's a new issue and  a debug log is required.  

OK your question now.  It's pretty much same as [custom URL](https://gpslogger.app/#usingthecustomurlfeature).   If your phone is offline, then the email request is queued up.  When you next get an internet connection _and_ the app is running, then the email will be sent.  

There's a caveat - if Android OS thinks it has an internet connection but in fact it's a weird network or a captive protal or loopback VPN or something that interferes with internet access, then the attempts will still be made to send your fail, but it will fail and GPSLogger will give up.

**Comment by lenzp** [comment]
Thank you again for your excellent support!

**Comment by mehrdadn** [comment]
@mendhak I'm running into a similar issue, but by the time I remember and go back to check, the Log View has already scrolled past the time I'm interested in. Is there any chance you could make the Log View have a slightly larger window than just a few hours? Maybe like a few days? It would be really helpful.

**Comment by mendhak** [comment]
The log view is a list in memory so any increase would have a big effect on memory.  Everything that appears in the log view is in the debuglog anyway so if you're looking to do more investigating it's better to enable that and have a look.
