### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by jkalousek** [mendhak/gpslogger#752]
I'm using GPS logger for about a year non stop on my Galaxy S7 with position acquisition every 90s, max  waiting time about 60s and I never really had a problem, sure there is some battery consumption but nothing that I would not expect. In last 3 weeks hovewer Android started telling me that GPS logger is "overloading" CPU (sorry for language):
![Screenshot_20190616-172102_Device maintenance](https://user-images.githubusercontent.com/8996764/59566088-699f9300-905b-11e9-9869-48a0d380e43c.jpg)
So I do get constant notification about GPS logger using 14-20% of CPU.
At first I thought that it is just some random notification because I travel a lot. But than this notification started showing even at night when my phone was stationary (I had turned on the option which disables tracking while phone is not detecting movement) and I also noticed that my phone is constantly little warmer than normal and my battery is draining like never before.

I tried to change location acquisition time from 90  to 180s, lowered accuracy and bunch other stuff but I still have same notification and battery drain.

I have debug log but it is full of http request/urls to my cloud instance so I would like to not post it publicly.

**Comment by mendhak** [comment]
Can you email the debug log to `gpslogger at mendhak.com` and link to this issue so I'll know it's this one

Do you have some application installed that informs about CPU usage, is this part of Samsung's Android OS?  I've never seen such a thing so I don't know how it's determining this

**Comment by jkalousek** [comment]
> Can you email the debug log to `gpslogger at mendhak.com` and link to this issue so I'll know it's this one
> 
> Do you have some application installed that informs about CPU usage, is this part of Samsung's Android OS? I've never seen such a thing so I don't know how it's determining this

Thank you for quick reaction, I just send the email.

Yes this is part of Samsuns's Android flavor (I assume that stock Android 8 does not have that). I have GPS logger "unmonitored" so Android does not care about it's background activities and will not kill it but this notification comes up only if something really power hungry runs in background to inform user about it (I saw it really a handful of times before GPS logger).

**Comment by mendhak** [comment]
I received your email with a debuglog. 

The log definitely shows OpenGTS logging is occurring every 1 second.  Also passive logging is enabled. 

To find out the issue can you first of all disable passive logging and see if that helps any.  (I don't think it will)

Next for OpenGTS logging do you have just logging or do you also have its auto-send also enabled?   How frequently is auto send set to?

The way OpenGTS auto send works is it reads the GPX file and sends the location for each line in there.  What you can try here is disable OpenGTS auto send, just use the OpenGTS logging feature.

**Comment by jkalousek** [comment]
Ok, I disabled the passive locations - I was thinking that, well If some other app acquires location I might as well save it.
I have Auto send turned on and set to 30 + when I click stop and in OpenGTS I have Automatic sending also enabled - I was under impression that it needs to be enabled in both places.

Ok I disabled Auto send under OpenGTS, I will let you klnow if I get any additional warnings.

**Comment by jkalousek** [comment]
So It started to look promising but during afternoon notification started poping up again. I will send another debug log to your email tomorrow.

**Comment by jkalousek** [comment]
By the way Is there any way to send you config file so you can see all of the parameters?

**Comment by mendhak** [comment]
> By the way Is there any way to send you config file so you can see all of the parameters?

Yes but it's a bit convoluted.  In the menu drawer click 'default profile' then click `+` then add a new profile, give it any name like 'test'. Then click 'default profile' again and switch to the 'test' profile. 

Now go to the GPSLogger directory in your file explorer, and you should see a 'Default Properties' file.  You can email that to me as well if you want.

**Comment by mendhak** [comment]
Looking at the 2nd log file you have sent I still see OpenGTS going at full throttle and requests going almost every 1second.  Also passive locations are still enabled.  You're saying you have disabled them but if you check again are they still enabled?

**Comment by jkalousek** [comment]
> > By the way Is there any way to send you config file so you can see all of the parameters?
> 
> Yes but it's a bit convoluted. In the menu drawer click 'default profile' then click `+` then add a new profile, give it any name like 'test'. Then click 'default profile' again and switch to the 'test' profile.
> 
> Now go to the GPSLogger directory in your file explorer, and you should see a 'Default Properties' file. You can email that to me as well if you want.

Ok, thank you. Attached you can find config file I redacted some data.
[default profile.txt](https://github.com/mendhak/gpslogger/files/3303184/default.profile.txt)

**Comment by jkalousek** [comment]
> Looking at the 2nd log file you have sent I still see OpenGTS going at full throttle and requests going almost every 1second. Also passive locations are still enabled. You're saying you have disabled them but if you check again are they still enabled?

You can check in previously attached file `that log_passive_locations=false`

**Comment by jkalousek** [comment]
> Looking at the 2nd log file you have sent I still see OpenGTS going at full throttle and requests going almost every 1second. Also passive locations are still enabled. You're saying you have disabled them but if you check again are they still enabled?

And If I check setting inside the app I can see that they are turned off.
![InkedScreenshot_20190618-215600_GPSLogger_LI](https://user-images.githubusercontent.com/8996764/59715418-158bde80-9214-11e9-9e83-6efa0b2ab22f.jpg)

**Comment by mendhak** [comment]
I see it in the properties file, definitely passive and opengts are disabled.  But something is sticking and no clues in the debug log as to why.  

Best to start afresh to eliminate this.  If you are comfortable to clear the app storage/cache or uninstall/reinstall and then re-enter your preferences, try that.  

But if you want to preserve your settings then there is again a convoluted way to do it.  First take the Default Profile file (in your case it's called Vychozi) and copy it to another location and delete the original.  Then go to phone's app list, GPSLogger, clear storage/cache for the app so that it's all reset (or just uninstall reinstall).  

Open GPSLogger. Close it.  Copy the vychozi file back into the GPSLogger directory but rename it to `gpslogger.properties`.   So now when you open GPSLogger it will read that file and set the properties from that file.  Go back to the directory and delete gpslogger.properties



Either way after you're done, now try logging again.  This time it should be every 180s and no passive locations.  Then re-enable OpenGTS logging only.  

Observe.

**Comment by mendhak** [comment]
Or if I were to summarize: uninstall reinstall recreate preferences.

**Comment by jkalousek** [comment]
Ok, so after 24 hours since I recreated settings there are no notifications. So for now I assume that there was some bug. I will reopen issue if I notice anything strange. Thank you for your help and time!
