### ISSUE TITLE
First trkpt always missing most fields

### ISSUE THREAD

**Issue by BigBaaadBob** [mendhak/gpslogger#755]
All of the GPX logfiles I get seem to begin with a trkpt missing most fields, like this:

`<trkseg>
  <trkpt lat="34.58349831" lon="-118.32134039">
    <time>2019-01-27T20:07:27.284Z</time>
    <src>gps</src>
    <sat>12</sat>
  </trkpt>
  <trkpt lat="34.58345999" lon="-118.32163771">
    <ele>1006.0</ele>
    <time>2019-01-27T20:08:38.761Z</time>
    <geoidheight>-21.0</geoidheight>
    <src>gps</src>
    <hdop>0.9</hdop>
     <vdop>1.5</vdop>
     <pdop>1.7</pdop>
  </trkpt>`

This can cause problems when post-processing the GPX file due to the missing fields in the first trkpt. Mathematica, for example, assigns None to ele which generates an error if you try to find the max elevation in the file.

One can, of course, filter this first point out, and maybe that is what a lot of packages do.

But It seems like this might be a bug or misfeature since if the src is GPS with 12 satellites, you ought to have ele, geoidheight, hdop, vdop, etc available to put in the trkpt.

IOW, it seems like this first point should either be suppressed from the log or it should contain the fields the second one has.

**Comment by mendhak** [comment]
The pdop/vdop/geoid come from the NMEA listener, however the NMEA listener isn't the same as the GPS/GNSS listener.  Similarly if MSL feature is on, then elevations will be missing if a geoid is missing.  Passive and network locations can also be missing elevation.  

So there will be multiple points which will be missing those same attributes, this isn't a bug.  Also I can't really change the application to cater to specific application behaviors, as the current behavior is equally valid.
