### ISSUE TITLE
gpslogger.properties file updating

### ISSUE THREAD

**Issue by vad11** [mendhak/gpslogger#756]
Thanks for the great program!
I want to integrate the project for multiple users. To do this, I need to make a personal initialization of the gpslogger.properties file for everyone. How can I transfer the file to each user and how can he upload it to the application?

Can I do this automatically from my site by api?

If not please add custom url  for update parameters of application with update button or manually file selection to  profile. 

Please add option for file sharing with gpslogger.properties  to GPS Logger from messengers

Thank you!.

**Comment by mendhak** [comment]
Work in progress:  https://github.com/mendhak/gpslogger/pull/760

If you can help with testing that would be great

**Comment by vad11** [comment]
Thank you so much!
I would love to check it out, but I’m not a developer for Android, and I know how to add applications only through Google Play. When there will be an updated version on Google Play I will definitely work with it.

**Comment by mendhak** [comment]
v103 released to market
