### ISSUE TITLE
Feature request: Continue recording to previous log file, and enable pausing logging

### ISSUE THREAD

**Issue by ahgera** [mendhak/gpslogger#757]
Sometimes I want to log my way to a place, create a separate log when there, and then log my way home again (for example biking to a hiking trail). The two transport logs could be the same log file, but now I have to combine them afterwards in a separate program.

Another use case is prolonged pauses, when I'd rather stop logging to save battery but want to continue logging after the stop. This would probably be best implemented as a "Pause" button in the GUI but use the same continuation code in the background.

I guess this could be achieved with the user specified file name combined with ask for file name every time, but I don't think this works with dynamic file names, and I can't type in the full file name every time since I don't always know it.

**Comment by mendhak** [comment]
This is the kind of situation the custom file name feature was made for.  Although it's not a super convenient way of doing it, it's a way of doing it (sort of MVP);  the ability to pause introduced more maintenance overhead than the complexity was worth - I've given it a few gos but definitely stopped each time.

**Comment by ahgera** [comment]
But how am I supposed to know the name of the file I want to continue logging to when it has the time in the name? I don't want to have to make up a unique name each time, so I would use a dynamic name that includes date and time. Even if I did know the name it's very inconvenient to type it in on a mobile phone.

The functionality is pretty much there, I think a file picker like the one used when pressing the share button to pick a file to continue logging to would be fine. 

And likewise the pause functionality would only need to remember the previous file name and continue writing to that when the logging is resumed, but that's secondary to the ability to continue logging to files.

**Comment by mendhak** [comment]
I have an idea.  A cunning plan.  A minimal approach to this would be to offer previous entries in the custom file name dialog.  So not actually a file picker (I am avoiding those due to the overhead) but a list of previous entries stored in the application cache.  

Example 
![image](https://user-images.githubusercontent.com/746276/61252147-7f849e80-a754-11e9-853e-96373e008cff.png)

I've put an APK with this feature, just for custom file name, in the releases in case you have the ability to test by sideloading an APK. 

https://github.com/mendhak/gpslogger/releases/tag/v103

**Comment by ahgera** [comment]
I'm using version 102-milestone103, and I don't see that list when I start a new log. Even so, from your screenshot it doesn't seem to fix the issue I'm trying to describe.

I usually use GPS Logger for when I go biking, or take a walk or whatever. I don't want to give each activity a unique name, so I just use the auto name feature. Let's say I switch over to custom file name, ask every time. When I leave home I start the logging, and use the file name pattern "gpslogger %YEAR-%MONTH-%DAY %HOUR-%MIN". Then I reach my destination and do something else for a while. Maybe I log a hike that I biked to. Then when it's time to go back home I want to continue the bike log I started previously. I can't do that, since I don't know the name of the log file, since it's automatically generated using the time variables. In your screenshot the %HOUR variable isn't filled in for example, so if I would pick that file name it would start a new file.

I don't understand why a file picker would be extra overhead, you already have one when you press the share or upload button. Just add a button for "Open/Resume track", show the same list, and when a file is open, start writing to that instead of a new one when the user presses "Start logging".

Either way, I'm not going to push this issue any further, It's clear it's not aligned with your goals for the app, and that's fine. I'll just use a different app (probably [Geo Tracker](https://play.google.com/store/apps/details?id=com.ilyabogdanovich.geotracker)) that supports pause and resume, and use GPS Logger for when I need to preserve power and log less frequently, but all in one go. Thanks for your time.

**Comment by mendhak** [comment]
OK - your post still led to a nice idea of presenting previous entries.  So even if it can't match your use case it can still help with allowing reuse of previous entries.  I'm going to add the autocomplete to the annotations menu as well.  

The file tracker may appear simple but it's the complexity of the implementation within the workflows which makes it difficult. I've had to remove a few file picker lists in the past as it was causing more problems than it solved.

**Comment by mendhak** [comment]
v103 released to market
