### ISSUE TITLE
Feature Request - Overwrite previous location

### ISSUE THREAD

**Issue by SebaFns** [mendhak/gpslogger#767]
First, thanks for building such an amazing app, so far it has worked great, it's the only app that I know so far that can send current location in a kml file to a server automatically, which is exactly what I need, but here is a recent issue I found.
Up until yesterday I have been using a single kml file, which I use as a Network Link for Google Earth, so my device location is update automatically without having to change the file itself or having multiple copies in different PCs, and it works great, but only in Google Earth on PC.
It seems Google Earth on Android can only work with "simple" kml files, when I try to open the same Network link in Android it doesn't show anything.
Is it possible to have an option for the app to only log current location, and delete or overwrite the previous one in the file that's gonna be created?
This enables the app to be used in multiples devices and create a Network Link group on Google Earth for real time monitoring on the devices location.

**Comment by mendhak** [comment]
HI based on what I'm reading of Network Link and the deficiency of Google Earth mobile, what you're describing is really niche/specific so for that reason I can't really add an option to overwrite/delete a file.  You might be able to achieve something close if using some automation tool like Tasker/AutomateIt.  For example if you get Tasker to regularly delete the KML file then then GPSLogger needs to write a new point it will create a new file.
