### ISSUE TITLE
Feature request: configure settings using app url

### ISSUE THREAD

**Issue by andreasringdal** [mendhak/gpslogger#776]
We might potentially have to configure the app for use in multiple vehicles and to avoid misconfigurations a way of configuring the app through a custom URL and urlhandler within the would be helpful.

Example
gpslogger:config?customurl=http://myhost?lat?%LAT&lon?%LON&interval=60s

This will allow each user to click a link on their profile page and have the app configured automatically and reduce possible configuration errors.

This URL could also be included in QR code for quick config.

**Comment by andreasringdal** [comment]
Just discovered the autoprofile branch that seems to cover but no issue covering it was found

**Comment by andreasringdal** [comment]
And there I found the documentation.. this feature is actually already there

https://gpslogger.app/#whatareprofiles

**Comment by mendhak** [comment]
\---
*Closing as part of issues cleanup, market release, inactivity or inevitability.  Issue can be reopened if needed, or a new issue created.*
