### ISSUE TITLE
Error while generationg web service URL

### ISSUE THREAD

**Issue by tejashri123-maker** [mendhak/gpslogger#778]
![IMG-20191021-WA0045](https://user-images.githubusercontent.com/56831321/67208358-02dc1d00-f433-11e9-8dd2-42a13aad2bbf.jpg)

Hello,
I have created one URL it works on web browser but it gives error in log file as it attached Please check and give me a solution

Thank you

**Comment by mendhak** [comment]
Can you [generate a debug log](https://gpslogger.app/#troubleshooting) , then recreate the above error, then post/email the debug log to me?  The debug log will contain a larger error message and that larger message will indicate what the actual problem is.

**Comment by tejashri123-maker** [comment]
Error resolved..Actually its my mistake I forget to add http in url
