### ISSUE TITLE
missing elevation in recent files

### ISSUE THREAD

**Issue by biplaneguy** [mendhak/gpslogger#781]
I'm using gpslogger to record my airplane flights.  No problem until a week or two ago, when I stopped getting elevation data.  To the best of my knowledge I didn't change any settings.  I see in the older .gpx files it has elevation and the geoidheight.  Suddenly now, I don't get the elevation or the geoid height in the gpx file.  I also have "log passive locations" turned off, so it's not that it's getting the location from another app.  If I switch it to use WGS84 instead of MSL, I do get the elevation, but not the geoid height, which is understandable.

```
old file from may 2019: <trkpt lat="41.38673986" lon="-72.50757423"><ele>79.5303955078125</ele><time>2019-05-04T18:41:54.000Z</time><geoidheight>-36.2</geoidheight><src>gps</src><sat>10</sat><hdop>0.9</hdop><vdop>0.8</vdop><pdop>1.2</pdop></trkpt>
file from yesterday: <trkpt lat="41.38597611" lon="-72.50618644"><time>2019-10-24T20:25:29.000Z</time><src>gps</src><sat>14</sat></trkpt>
file with WGS84 instead of MSL: <trkpt lat="41.32227438" lon="-72.53393088"><ele>21.822021484375</ele><time>2019-10-25T11:37:09.000Z</time><src>gps</src></trkpt>
```

Has something changed in a recent update?  Or perhaps it was broken by a recent Android update that's not sending the geoidheight in the NMEA string from the internal GPS?

**Comment by mendhak** [comment]
Nothing changed in any recent update, see: https://gpslogger.app/#whyisthealtitudevaluemissing

So with MSL on you can get missing altitude values if the NMEA listener isn't working properly. 

There's a way to verify if something's odd with the NMEA; go to logging details, enable the 'Log to NMEA' - that file basically writes out NMEA sentences. If you see sparse or no sentences in that file, yes something has happened.  I can't say what though - my testing on android 9 shows it all works fine.  Phone model perhaps?

I do have a [work in progress](https://github.com/mendhak/gpslogger/compare/targetsdk29) for Android SDK 29 which will use a different NMEA listener, you can wait for that update, but, your best option now is to not use MSL and rely on the chipset provided altitude
