### ISSUE TITLE
Not uploading until phone is unlocked & app is foregrounded

### ISSUE THREAD

**Issue by Kevin-Prichard** [mendhak/gpslogger#782]
The app doesn't autosend to Google Drive (I configured it to every 60 minutes, and yes have permissioned the app with Drive, and successfully sent a test file).

I have to unlock the phone and foreground the app, and at that moment it uploads the last file.

I would like to help debug this, get it working properly - what do you need from me? I have enabled debug logs.

**Comment by mendhak** [comment]
That sounds like running into doze mode - during which not just location requeests but web requests are blocked as well.  

https://gpslogger.app/#sometimestheappwillnotlogforlongperiodsoftime

Try to whitelist the GPSLogger app and if your device is [on this list](https://dontkillmyapp.com/?app=GPSLogger), whatever additional steps are in there.

For completeness you can also mail me the debug log (assuming it covers the period of starting logging until the lack of sending to G Drive), you can email it to gpslogger @ mendhak.com, can you reference this issue in the email.

**Comment by Kevin-Prichard** [comment]
My phone's on Android 8.1.0, here's what I found-
Battery & Performance > Battery Saver > (choose apps) GPSLogger > Battery Saver (default)

I switched GPSLogger to "No restrictions." Overnight it recorded and sent files.

Thanks for your help!
