### ISSUE TITLE
Escape apostrophe in  gpslogger/gpslogger/src/main/res/values-fr/strings.xml 

### ISSUE THREAD

**Issue by sekarpdkt** [mendhak/gpslogger#789]
hi
You may need to escape apostrophe in line 326
Tous les langues ne sont pas entièrement traduites ! Vous devrez redémarrer **_l’applica_**

Thanks
S.Sekar

**Comment by mendhak** [comment]
Thanks I will make the correction on Crowdin. 

Question, if you're still there, I noticed the line has two different kinds of apostrophes.  

> Une ou plusieurs autorisations requises par cette application ont été refusées. Il sera nécessaire d’aller à l’écran des paramètres de l'application pour les lui accorder.

l’écran does not produce a problem, but l'application does. 

Is there a French-language specific distinction between those two apostrophes?

**Comment by mendhak** [comment]
v104 released to market.

**Comment by mendhak** [comment]
I've also asked a question on how to automate this:  https://stackoverflow.com/questions/60125988/how-to-fail-a-build-if-there-are-unescaped-apostrophes-in-strings-xml
