### ISSUE TITLE
GPSLogger unable to retrieve serial number

### ISSUE THREAD

**Issue by liljenstolpe** [mendhak/gpslogger#791]
Current phone is a pixel 3.  For a while, the %SER% tag in the filename was returning the valid serial number of the device.  In the last month or so, I've been through a few upgrades of Android, and somewhere along the way, I've lost the %SER% tag.  Now files are being stamped with 'unknown' in place of the serial number.  

Android 10
Build: QP1A 191105.003

**Comment by jantman** [comment]
I'm now having the same issue.

Galaxy S10
Android 10 / OneUI 2.0
Build QP1A.190711.020.G973U1UEU2CSKP

I can confirm that the problem started exactly when I upgraded from Android 9 to Android 10.

**Comment by mendhak** [comment]
I see that [Build.SERIAL has been deprecated](https://developer.android.com/reference/android/os/Build.html#SERIAL). 

The new method, [Build.getSerial()](https://developer.android.com/reference/android/os/Build.html#getSerial\(\)), looks onerous.  

> Requires Permission: READ_PRIVILEGED_PHONE_STATE, for the calling app to be the device or profile owner and have the READ_PHONE_STATE permission, or that the calling app has carrier privileges (see TelephonyManager.hasCarrierPrivileges()). The profile owner is an app that owns a managed profile on the device; for more details see Work profiles. Profile owner access is deprecated and will be removed in a future release.
> If the calling app does not meet one of these requirements then this method will behave as follows:
>    If the calling app's target SDK is API level 28 or lower and the app has the READ_PHONE_STATE permission then Build#UNKNOWN is returned.
>    If the calling app's target SDK is API level 28 or lower and the app does not have the READ_PHONE_STATE permission, or if the calling app is targeting API level 29 or higher, then a SecurityException is thrown.


I will test this out, I hope that I just need to ask for the `READ_PHONE_STATE` permission (but even that bothers me).  If it appears that the app needs to become a privileged profile owner on the device, then that's going too far...

**Comment by jantman** [comment]
Hmm, that's pretty upsetting. I haven't done any Android development since the platform first came out (maybe a decade ago?) but I can't see why they'd make it so hard just to get the serial.

For what it's worth, given all of that, personally I'd be fine just manually entering a unique string instead of using the serial...

**Comment by mendhak** [comment]
Tried it, and it didn't work.  Only system apps are allowed `READ_PRIVILEGED_PHONE_STATE`, and trying to `READ_PHONE_STATE` still yielded nothing. 

What I'm doing now: 

For Android 8 onwards, the [ANDROID_ID](https://developer.android.com/reference/android/provider/Settings.Secure.html#ANDROID_ID) is used.  Before that, Build.SERIAL is used as normal. 


            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
                return Build.SERIAL;
            }
            else {
                return Systems.getAndroidId();
            }

**Comment by mendhak** [comment]
v104 released to market.

**Comment by liljenstolpe** [comment]
Thank's Mendhak - I'm fine with just putting in a string (it's what I am
doing now).

**Comment by liljenstolpe** [comment]
Working for me.
