### ISSUE TITLE
Add 'name' to 'trk' tags in GPX

### ISSUE THREAD

**Issue by AigarsABCD** [mendhak/gpslogger#792]
Hello.
When logging to GPX, at the moment gpslogger does not add `<name>` tag to `<trk>`.
This causes some issues with the software that I use to read GPX files.
Would it be possible to add this tag? It could be the same as the file name for example.

The result would look something like this

`<?xml version="1.0" encoding="UTF-8" ?>`
`<gpx version="1.0" ...>`
`<trk>`
`<name>20200108</name>`
`<trkseg><trkpt ...>...</trkpt></trkseg>`
`</trk>`
`</gpx>`

**Comment by KOTRET** [comment]
although optional per spec, this won't hurt

**Comment by mendhak** [comment]
v127 is on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and the [Releases](https://github.com/mendhak/gpslogger/releases/tag/v127) section.
