### ISSUE TITLE
HTTP on android 9

### ISSUE THREAD

**Issue by Damianuscz** [mendhak/gpslogger#793]
Hello

When i use HTTP send app say: cleartext communication not permitted by network security policy
https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted

I think it is problem of newest android and security policy.

Is there way how to solve this problem?

**Comment by mendhak** [comment]
I'd have to add

    android:usesCleartextTraffic="true"

to the `<application` manifest.  

From what I read, it looks like some components of Android will respect this but not all.  That means, in a while, this attribute will either be discouraged or it will be outright ignored in more components. 

I'll have a look at adding it in.

Regardless - are you able to add a certificate to your server?  You can self sign one.

**Comment by mendhak** [comment]
Commit: https://github.com/mendhak/gpslogger/commit/7b09a95511b84419b7b7362188bb34f0980ea471

**Comment by Damianuscz** [comment]
thx for solving.

About certificate i think not.. I want use gpslogger for this app: https://github.com/715209/gps-logger

to show my gps map on Twitch stream.

**Comment by mendhak** [comment]
I understand; and yeah a self signed won't work with an IP address either.  It seems Android team is happy to push secure transmission protocols but aren't considering all use cases.  

I can't say when v104 will be released.  This has been one of the most difficult compatibility-maintaining issue sets so there's still testing and work to finish before releasing 104. 

Until then if you need this functionality to work, you'll need to get a domain.  It could be a dynamic DNS or a custom DNS.  With either dynamic or custom DNS, it should be possible to issue a free Let's Encrypt certificate which lasts 90 days.  You'd then need to run a web server like nginx listening on `:443` on your machine and proxy it to your `:3000` node application.  If you haven't done this before it can be daunting but just thought I'd mention it.

**Comment by mendhak** [comment]
v104 released to market.
