### ISSUE TITLE
Repeated "Success" dialogs when setting the a custom URL

### ISSUE THREAD

**Issue by mrantala** [mendhak/gpslogger#798]
When I go into the custom URL screen, I repeatedly get a pop-up that says "Success". It makes it very difficult to work on this screen--I've had to go into Airplane mode to disable this.

**Comment by mendhak** [comment]
Oh I figured out what this is. The custom url screen has a listener for a custom url test.  I think the test was removed a while ago so the listener can be removed too.  I am checking.

**Comment by mendhak** [comment]
v104 released to market.
