### ISSUE TITLE
CSV files stored in Google Drive are now Sheets / Excel?

### ISSUE THREAD

**Issue by NelsonMinar** [mendhak/gpslogger#802]
I've been syncing GPSLogger to Google Drive for awhile now. I just looked today and now all my CSV files in Google Drive are listed as Google Sheets links. If I click them in Google Drive's webapp it opens Google Sheets (screenshot attached). If I download them from the webapp it downloads an XLSX file. I also tried using a couple of tools to sync my Google Drive to a filesystem. rclone ends up with XLSX files on my Linux system, and the Windows official client creates files named ".csv.sheet" which seem to just be URLs to launch in a browser.

The key thing here is I can't find any easy way to just get the CSV text file back from Google Drive.

I can swear last May this wasn't happening with GPSLogger. Also I can still upload CSV files to other folders in my Google Drive and they seem to survive intact as CSV; it's only the GPSLogger files that seem to be converted. I don't think that's something I set up myself, could it possibly be the way GPSLogger uploads to Google Drive that's encouraging it to convert to a Google Sheet?

Note: Google Drive has a top level option for "Convert uploaded files to Google Docs editor format". I do not have that enabled. I do have "Google Sheets" enabled as an app with access to Google Drive; I tried temporarily disabling this and it didn't change the behavior, at least for old files.

See also issue #509 

![Screenshot_1](https://user-images.githubusercontent.com/382136/74560258-0c761d00-4f1b-11ea-82b8-c77c5c81f267.png)

**Comment by iandees** [comment]
It's interesting to note that opening my Google Drive webapp and uploading a .csv from my laptop creates a file ending in .csv that I can then download as a CSV file. So the behavior described here seems to be happening because the data is being written via API?

**Comment by NelsonMinar** [comment]
While chatting with iandees he pointed out this bit of GPSLogger code might be relevant:

https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/java/com/mendhak/gpslogger/senders/googledrive/GoogleDriveJob.java#L312

**Comment by mendhak** [comment]
Sorry for no attention on this.  GDrive feature was removed so I'm closing related tickets.
