### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by bol-van** [mendhak/gpslogger#803]
GPSlogger seem to be one of the most cpu intensive app on my system.
One of its forks has enormous CPU usage.
During one night (~12 hours) it consumed 38 minutes of cpu time.

I ran htop utility and watched this situation. Process can be idle for minutes, then eat ~60% of one core for ~1 min, then goes back to idle. During gpslogger activity system_server also eats lot of time

v104

**Comment by mendhak** [comment]
I've rolled back v104 due to some System UI issue.  v105 should undo some of these problems.

**Comment by mendhak** [comment]
v106 released to market.
