### ISSUE TITLE
v105 - plain HTTP URLs not being sent due to Android 9+ restrictions

### ISSUE THREAD

**Issue by spiteri** [mendhak/gpslogger#806]
Hi @mendhak , after the latest version i'm having a problem logging to custom URL (an HTTP server - not https), it was all working until a few days ago. I get these log entries now:

> error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@<job-id>

> Custom URL: attempt <x> failed, maximum 5 attempts

I tried disabling the deep battery optimization, tried a network settings reset, the obvious uninstall/install with reboots in between, nothing seems to work. I can successfully send GET requests from other Android apps on the same URL, and this same app on a Samsung tablet works fine too with the same URL.

**EDIT**: I reverted to v103 via the manual apk download. Works fine.

**Comment by fuxoft** [comment]
I have the same problem with version 105. Custom URL HTTP requests (previously working) now fail with:

`error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@`

Note that HTTPS requests still work correctly. Only HTTP requests fail.

**Comment by georgerappel** [comment]
Are you on Android 9? I have the same issues, from my degbug log, I got that:

> ERROR AppSettings$1.e:97 - error while executing job com.mendhak.gpslogger.loggers.customurl.CustomUrlJob@1a86ab1
> java.net.UnknownServiceException: CLEARTEXT communication to 18.231.184.23 not permitted by network security policy

Which seems to be something with more recent Android versions blocking non-https requests, maybe SDK 29.

Returning to v103 solved the issue indeed, but I didn't try v104.

**Comment by fuxoft** [comment]
> Are you on Android 9?

Yes, I am on Android 9 (Nokia 7.1). But I am on Android 9 for many months and until a few days ago, the HTTP requests worked.

**Comment by georgerappel** [comment]
> a few days ago, the HTTP requests worked.

Hum... It's not an issue with the version on the phone, apparently. Probably an issue with the target version on the app, given that v105 was released 14 days ago and had this change.

**Comment by sven3** [comment]
Same problem here. OnePlus 6T running LineageOS 16 (Android 9) with gpslogger v105. Will also return to v103.

**Comment by mendhak** [comment]
Yes it's an Android 9+ requirement  https://github.com/mendhak/gpslogger/issues/793

I've had to rollback v104 due to a System UI crash issue.  I'm now dealing with a messy merge.  At some point I will be able to release a new version with the plaintext http URL reinstated.

**Comment by mendhak** [comment]
v106 released to market.

**Comment by sven3** [comment]
v106 solved the problem for me. Many thanks!
