### ISSUE TITLE
russian translation error

### ISSUE THREAD

**Issue by ztad** [mendhak/gpslogger#809]
hello, there's error in translation of "Absolute time to GPS fix". It must be "**Время определения местоположения.** Количество секунд , по прошествии которых приложение перестанет пытаться получит местоположение, не зависимо от других параметров. Это особоенно полезно внутри зданий, чтобы не разряжать батарею."

**Comment by mendhak** [comment]
Oops, I missed this.  I've added this translation to Crowdin.com now. 

Время определения местоположения. Количество секунд , по прошествии которых приложение перестанет пытаться получит местоположение, не зависимо от других параметров. Это особоенно полезно внутри зданий, чтобы не разряжать батарею. Установите 0 если задержка не требуется.
