### ISSUE TITLE
v106 - Location not updating unless app open

### ISSUE THREAD

**Issue by FuzzyMistborn** [mendhak/gpslogger#810]
Running 106 for a few days and noticing that my location isn't updating like it did on prior versions, unless the app is opened (not just open, has to be opened or change the screen display from simple to advanced, for example).  Don't have battery optimizations on and I've cleared cache.

Can't seem to attach a log (app crashes when I try to export).  Running Android 10 latest patches on a Pixel 3

**Comment by dshanske** [comment]
I had this problem.. somehow location only when open was set.

**Comment by FuzzyMistborn** [comment]
@dshanske how the heck did that get changed?  Changed the app permissions back and it seems to be working again.  Closing unless I see another problem.
