### ISSUE TITLE
Position only updating when app in foreground

### ISSUE THREAD

**Issue by jantman** [mendhak/gpslogger#816]
This _may_ be a duplicate of either #813 or #814 but I'm not sure.

Yesterday my Verizon Samsung Galaxy S10 received an update. Since then, gpslogger is only POSTing to my custom URL when the app is actively in the foreground. Other than that, it's not updating at all.

I'm currently on Android 10, build QP1A.190711.020.G973U1UEU3DTC9

in Settings -> Apps -> GPSLogger -> Battery, it's set to "Not optimized" under Optimize battery usage.

**However**, since some recent update there's a whole new settings section that I've never noticed before:

Settings -> Device care -> Battery -> App power management. This has an "Adaptive battery" slider that's set to "on". It also has items for "Sleeping apps", "Deep sleeping apps", and "Apps that won't be put to sleep". GPSLogger is not in any of these lists. However, there's an option to "Add apps" on the "Apps that won't be put to sleep" screen, but GPSLogger doesn't appear on that list...

I'm happy to help debug however I can, but I'm not really sure where to start.

**Comment by dror3go** [comment]
I had a similar issue on OnePlus 7T, and after a long struggle - I found that denying all permissions for GPSLogger (from the system's settings) and re-allowing them after opening the app did the trick, and now the GPSLogger logs locations just as I expect it to.
I did also a reboot to the device after denying all permissions and before re-allowing them, but I suspect it had no affect.

**Comment by mendhak** [comment]
Yes thanks @dror3go that's correct.  I don't know why but sometimes the location permission is only given when the app is in the foreground - could be a quickly-clicking-thing or it could be a targetting SDK thing. You'll need to revoke permissions then when redoing the permissions allow it to run in the background.

**Comment by jantman** [comment]
It appears as though that fixed it, thanks so much @dror3go !!! I haven't left the house yet, but I stopped the app, denied all permissions, re-started it, and granted them all again... and my web server logs show it POSTing as configured! Thank you so much!
