### ISSUE TITLE
Show feedback from server

### ISSUE THREAD

**Issue by claudiorivetti** [mendhak/gpslogger#819]
I could not find a way to see if the custom server is receiving data correctly beside looking in the log file on custom server.  Is the app capable to read a json response from server such as:
{success: true/false, error: "error message if any"}
and give a sign in the app screen. For example at each data sent to the custom server if success is true turn the small icon <-> at the bottom (that showing the custom url) in blue else turn it gray.

**Comment by mendhak** [comment]
The logging view should show the status (eg HTTP 200/400/etc), the simple/detailed view aren't meant for this. 

But I've limited the server response to the debug log file though, that information on a misconfigured server can overwhelm or pollute the log box, and normally it's meant for troubleshooting a connection.  So two ways to view it if needed, either enable debug log file (but it grows quickly) or get a logcat viewer and it should be visible there.
