### ISSUE TITLE
Export files log every 6 minutes when app says 30 sec.

### ISSUE THREAD

**Issue by antoineouellet** [mendhak/gpslogger#826]
I'm sorry if this is some battery optimization issue I did not understand.
My GPSlogger is set to log position every 30 seconds and the app home screen displays a number of points recorded consistent with this. However every output file that is created (gpx, csv, kmz) logs every 6 minutes (tried various parameters, same results). 
It seems to be related to exporting files as the display says a number of points consistent with 30s intervals but the export is much smaller.

EDIT: Moto G7 plus, Android 9, GPSLogger 106

**Comment by mendhak** [comment]
If you keep the app in front of you and let it log, does it log all the points?

It could be that there aren't permissions to log in the background?  Try to go in to app settings, revoke all GPSLogger permissions.  Then reopen GPSLogger.  You should get prompted again for permissions, when it comes to the location permission, allow it to log while in the background (all the time).

**Comment by Ligence** [comment]
I had the same issue; interval was set to 60 (s) yet the app only logged data once every 6 minutes. My device is also a Motorola, though different model (One Zoom), running Android 9.

Looking at the GPX files, I noticed some irregularities to this; the app has occasionally been continuously logging once per minute, for some length of time. I realized this is happening when the device is plugged in to a charger, which led me to consider that a power saving feature might be the cause of this issue.

I went into Settings > Apps > GPSLogger > Advanced > Battery > Battery optimisation and set it to "Not optimised". Now it's logging once per minute, even when not plugged in.

**Comment by antoineouellet** [comment]
Ok so thank you Ligence, though I understood I had already done that, it wasn't really the case, just because of the confusing way my phones battery settings are displayed... Oh well let this be a testimony to my foolishness.

And mendhak, sorry for the confusion I should have resolved more easily. I love the app, I sync my tracking with nextcloud and now I keep the convenience I had in Google Maps tracking while owning my data! thanks
