### ISSUE TITLE
Cound not send email

### ISSUE THREAD

**Issue by lvhailong** [mendhak/gpslogger#836]
I tried to use the button to send test messages, and I did get messages without attachments. 
However, it has never been successful to send mail automatically after the logging is stopped. Looking at the log shows that there should be a problem on the attachment uploading. Any one have the same issue?
![Screenshot_2020-06-26-18-03-37-74](https://user-images.githubusercontent.com/9078308/85846601-a8bd0400-b7d8-11ea-989a-e6581928b8f7.png)

**Comment by mendhak** [comment]
Could you record a debug log (it has more details):  https://gpslogger.app/#troubleshooting

If you attempt the email send again, and it fails, there could be a clue in the debug log about what may have happened.  You can post it here as well but be sure to XXXXXXX your email address in the log file.

**Comment by lvhailong** [comment]
Thanks for your reply! Here is the log file.
[debuglog.txt](https://github.com/mendhak/gpslogger/files/4874465/debuglog.txt)

**Comment by lvhailong** [comment]
Thanks for your reply! Here is the log file.
[debuglog.txt](https://github.com/mendhak/gpslogger/files/4874466/debuglog.txt)


> Could you record a debug log (it has more details): https://gpslogger.app/#troubleshooting
> 
> If you attempt the email send again, and it fails, there could be a clue in the debug log about what may have happened. You can post it here as well but be sure to XXXXXXX your email address in the log file.

**Comment by mendhak** [comment]
So I'm not sure what's going on - the test definitely looks like it succeeds.   Then when trying to send, this error appears. 

> javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:444) ~[na:0.0]
	at org.apache.commons.net.smtp.SMTPSClient.performSSLNegotiation(SMTPSClient.java:215) ~[na:0.0]
	at org.apache.commons.net.smtp.SMTPSClient._connectAction_(SMTPSClient.java:171) ~[na:0.0]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:189) ~[na:0.0]
	at org.apache.commons.net.SocketClient.connect(SocketClient.java:209) ~[na:0.0]
	at com.mendhak.gpslogger.senders.email.AutoEmailJob.onRun(AutoEmailJob.java:128) ~[na:0.0]
	at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) ~[na:0.0]
	at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) ~[na:0.0]
	at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) ~[na:0.0]
	at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7eaaa26000: Failure in SSL library, usually a protocol error
error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0x7ec6ff6379:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:362) ~[na:0.0]
	... 13 common frames omitted


So you can check, are you connecting to the SSL port of your mail server?  According to [this page](https://getmailspring.com/setup/access-126-com-via-imap-smtp) it should be smtp.126.com port 465.  When you do that, do test again, and make sure you validate the SSL certificate. 

Also you can try with and without the Implicit SSL checked. 

Even though the test worked, the automated send did not work, and I can't see why that would happen, that's why I'm saying to try the SSL port and Implicit SSL and Validate Cert.

**Comment by lvhailong** [comment]
> So I'm not sure what's going on - the test definitely looks like it succeeds. Then when trying to send, this error appears.
> 
> > javax.net.ssl.SSLHandshakeException: Handshake failed
> > at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:444) ~[na:0.0]
> > at org.apache.commons.net.smtp.SMTPSClient.performSSLNegotiation(SMTPSClient.java:215) ~[na:0.0]
> > at org.apache.commons.net.smtp.SMTPSClient._connectAction_(SMTPSClient.java:171) ~[na:0.0]
> > at org.apache.commons.net.SocketClient.connect(SocketClient.java:189) ~[na:0.0]
> > at org.apache.commons.net.SocketClient.connect(SocketClient.java:209) ~[na:0.0]
> > at com.mendhak.gpslogger.senders.email.AutoEmailJob.onRun(AutoEmailJob.java:128) ~[na:0.0]
> > at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) ~[na:0.0]
> > at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) ~[na:0.0]
> > at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) ~[na:0.0]
> > at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) ~[na:0.0]
> > at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) ~[na:0.0]
> > at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) ~[na:0.0]
> > at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) ~[na:0.0]
> > at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
> > Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7eaaa26000: Failure in SSL library, usually a protocol error
> > error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0x7ec6ff6379:0x00000000)
> > at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
> > at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:362) ~[na:0.0]
> > ... 13 common frames omitted
> 
> So you can check, are you connecting to the SSL port of your mail server? According to [this page](https://getmailspring.com/setup/access-126-com-via-imap-smtp) it should be smtp.126.com port 465. When you do that, do test again, and make sure you validate the SSL certificate.
> 
> Also you can try with and without the Implicit SSL checked.
> 
> Even though the test worked, the automated send did not work, and I can't see why that would happen, that's why I'm saying to try the SSL port and Implicit SSL and Validate Cert.

You are amazing! That is the point. It finally worked after I turned on the SSL button and changed port to 465. Thank you so much!
