### ISSUE TITLE
/Delete

### ISSUE THREAD

**Issue by Guamaboy** [mendhak/gpslogger#838]

**Comment by OgreTransporter** [comment]
I have already asked to send a whole file to one address (see #377). But currently you can only send values continuously to one address (https://gpslogger.app/#usingthecustomurlfeature). Continuously sending data to an address consumes more battery and traffic than uploading a file at the end. Also, you don't have internet everywhere you go.

**Comment by Guamaboy** [comment]
@OgreTransporter Would you be up to showing me how to implement this in a web app project I've been working on?
Basically I want it to continuously send gps coordinate and update position on a map.
I am using mapbox's api but besides that all I really cant figure out is how to get the lat and the long from mobile device to web app.
LMK?
