### ISSUE TITLE
GPSLogger does not get GPS-Position since several days

### ISSUE THREAD

**Issue by Wolfgang67** [mendhak/gpslogger#847]
GPSLogger was running perfect for several months, but since some days the app does not get any gps-positions. :-(
When „log network location“ is activated it get some Positions, when only „log GPS/GNSS location” is activated (like before) I dos not get any positions. “Google Map” does get the accurate gps-position.

I have already tried:
1)	GPS-Logger ist bei Akku/Energieüberwachung  ausgenommen
2)	Android / Settings / doze mode: set GPSlogger to the whitelist to not be supervised
3)	Android / Settings / doze mode / Extendes settings / App-Engergiecontrol: deactivated
4)	Performance / Distance filter: Set down from 30 m to 1m
5)	Performance / Accurancy filter:  Set up from 500m to 1000m
6)	Performance / Duration to match accuracy:  Set up from 10 to 20 sec.
7)	Performance / Absolute time to GPS fix:  Set up from 60 to 120 sec.
8)	Performance / Don’t log if I’m not moving:  now deactivated

Attached a screenshot of the protokol:
![2020-09-15 09 08 45](https://user-images.githubusercontent.com/71311567/93177627-65b56180-f733-11ea-9fb2-d9f224316fce.jpg)

**Comment by lwis** [comment]
Does the app have permission to get your location?

**Comment by Wolfgang67** [comment]
Thank you for your answer !

A view days ago, after comparing all settings with my old Smartphone I found the error:

In the GPS-Settings of the phone the Settings for then Search mode was to “safe energy”.
After I changed this to “high accuracy” the gps-logger app gets the gps-position 😊

Greetings from Austria
Wolfgang


Gesendet: Dienstag, 06. Oktober 2020 um 10:15 Uhr
Von: "Lewis Juggins" <notifications@github.com>
An: "mendhak/gpslogger" <gpslogger@noreply.github.com>
Cc: "Wolfgang67" <wolfgang.ortner@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [mendhak/gpslogger] GPSLogger does not get GPS-Position since several days (#847)


 

Does the app have permission to get your location?

**Comment by mendhak** [comment]
Late reply - in v110 I've now added a permission prompt that will ask for battery optimization to be disabled.  It was long overdue.
