### ISSUE TITLE
Removed from Google Play?

### ISSUE THREAD

**Issue by magma1447** [mendhak/gpslogger#848]
Is there a good reason that the app has been removed from Google Play? Is the ambition to get it back there?

https://play.google.com/store/apps/details?id=com.mendhak.gpslogger&hl=en

PS! Awesome app, I love it.

**Comment by mendhak** [comment]
Hey I was just writing up a description, I'll close your issue in favor of:  https://github.com/mendhak/gpslogger/issues/849
