### ISSUE TITLE
Publish app to SkyDroid

### ISSUE THREAD

**Issue by redsolver** [mendhak/gpslogger#850]
[SkyDroid](https://skydroid.app) is a decentralized domain-based App Store for Android. 

An app is published on a domain name by adding a TXT record, for example `app.example.com`, and the user can then install the app by entering `app.example.com` in the SkyDroid app or by simply clicking a link (like in a web browser). So it's basically a direct APK download with the added convenience of auto-updates, rich metadata and more security. 

Publishing on SkyDroid is really fast and you only need a domain name and the [SkyDroid CLI](https://github.com/redsolver/skydroid-cli). Then just follow the instructions in the CLI Repo.

**Comment by mendhak** [comment]
Hey thanks for this suggestion - I did briefly consider it but went for F-Droid, one store is enough.
