### ISSUE TITLE
Can't run cloned git

### ISSUE THREAD

**Issue by emsici** [mendhak/gpslogger#854]
I just clone this git, i click run, and i receive 

```
D:\AA\gpslogger\src\main\java\com\mendhak\gpslogger\common\Strings.java:374: error: cannot find symbol
        String[] availableLocales = BuildConfig.TRANSLATION_ARRAY;
                                               ^
  symbol:   variable TRANSLATION_ARRAY
  location: class BuildConfig
```

Why?

Thanks.

**Comment by mendhak** [comment]
Did you do a gradle build first?  The gradle build, when successful, creates the dynamic `BuildConfig.TRANSLATION_ARRAY` based on the files inside src/main/res/ - it creates a `BuildConfig.java` and in there you'll see 

```
public static final String[] TRANSLATION_ARRAY = new String[]{"sr","es-CO","es-MX","...
```

**Comment by mendhak** [comment]
The code is here: https://github.com/mendhak/gpslogger/blob/master/gpslogger/build.gradle#L252

**Comment by emsici** [comment]
It was mine mistake, sorry and thanks.

**Comment by vsevjednom-cz** [comment]
I've got same problem. I'm trying to do gradle build first. Is it Build -> Make Project? Rebuild Project ends with "cannot find symbol" too.

**Comment by mendhak** [comment]
I'm not sure with the UI (I don't have Android Studio right now) but can you try `./gradlew build` first.

**Comment by vsevjednom-cz** [comment]
Thanks!

But:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':gpslogger:lintVitalRelease'.
> > This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
>   The following AndroidX dependencies are detected: androidx.test:monitor:1.2.0, androidx.test:rules:1.2.0, androidx.test:runner:1.2.0, androidx.annotation:annotation:1.0.0

😰
I'm trying to set `android.useAndroidX=true` but there is another error 😨.
