### ISSUE TITLE
compile with profile

### ISSUE THREAD

**Issue by emsici** [mendhak/gpslogger#855]
how can i compile with a SFTP profile? I want to compiled application to have SFTP details configured

**Comment by mendhak** [comment]
Hey there, if you're looking to preconfigure the app, have a look at [profiles](https://gpslogger.app/#whatareprofiles) in the FAQ.  You can have a `gpslogger.properties` file with your settings in it and the app should read it and load it.  You can even load it from a URL if you want.  

You could compile the app yourself, with hardcoded values if you wanted to, probably the easiest way to do it would be to modify the values in this XML file:  https://github.com/mendhak/gpslogger/blob/master/gpslogger/src/main/res/xml/sftpsettings.xml
