### ISSUE TITLE
Not getting any coordinates.

### ISSUE THREAD

**Issue by snehasanghavi** [mendhak/gpslogger#857]
I cannot able to load data, am getting message as  
"Requesting cell and wifi updates" ,
"only accuracy of 1817.0 m.point discarded,Inaccurate point discarded."MY GPS and location is on..Still am facing this issue

**Comment by mendhak** [comment]
Have you allowed the app to always run in the background?  I believe you need to go into the settings, and specifically allow the app to always get location in the background.

**Comment by mendhak** [comment]
In v110 I've added a permission prompt that asks for background location permission and battery optimization to be disabled.
