### ISSUE TITLE
GPS Logger stops logging to custom URL after screen is off..

### ISSUE THREAD

**Issue by b3ck** [mendhak/gpslogger#858]
Using S10E with Android 10, I can't remember when.. but a while back I was able to turn my screen off and it would still log to my custom URL, but for some reason after a while it stops.

Please advise, thanks.

**Comment by mendhak** [comment]
It could be that during screen off, the app is not in use, so the OS denies it location access. 

Have a look in app settings, under its permissions there should be an option to allow the app to access location 'all the time', not just when the app is in use.  This lets GPSLogger keep logging even if it's in the background.

If you're seeing gaps like 20 minutes, up to a few hours, that's most likely [doze mode](https://gpslogger.app/#sometimestheappwillnotlogforlongperiodsoftime)

**Comment by b3ck** [comment]
Copy that, I went in the phone settings and did my best to keep GPS Logger alive, so far so good with the screen off, it's been logging since my first post while the screen if off, let's hope I've found the issue 🤞 

Thanks again!

P.S. - I've been using GPS Logger to provide information to a node.js app with Weather and Location APIs which in turn provides dynamic information to an overlay I have setup in OBS while I stream IRL content on Twitch, it's amazing! Thank you again for GPS Logger it literally is quite amazing 😄

**Comment by b3ck** [comment]
still going strong after 2+ hours, I think I figured it out 😄

**Comment by mendhak** [comment]
Nice, glad to hear. That's a pretty neat setup you've described, quite a chain!  From GPSLogger --> Node --> OBS --> Twitch.

**Comment by b3ck** [comment]
So it looks like I can officially say I solved the problem, I just went into my Android Phone Settings > Device Care > Battery > App power management > Disabled "Adaptive Battery", Disabled "Put unused apps to sleep", then I added "GPS Logger" to my "Apps that won't be put to sleep" list.  It seems to have done the trick 😄

**Comment by mendhak** [comment]
A bit late, but:  in v110 I've added more annoying permission prompts that will ask for the battery optimization to be ignored and to allow the app to run in the background.
