### ISSUE TITLE
Logging stops after 1 hour in background

### ISSUE THREAD

**Issue by ioctl-user** [mendhak/gpslogger#859]
I am running GPSLogger from F-Droid on device with LineageOS 17.1

GPSLogger work fine for exactly 1 hour after application goes background last time, and then it stop logging.

I have tried to manually disable "Battery Optimization" for this app in settings, but didn't succeed.

May be app should request "Disable Battery Optimization" permission on installation?

**Comment by mendhak** [comment]
v110 has been released and is available now on F-Droid, there is now a prompt at the beginning now which asks for battery optimization to be disabled.  It also asks for background location permission.  

This should help a bit with the sporadic logging you are seeing.

**Comment by ioctl-user** [comment]
Thanks! I hope it will help for someone.

In my case problem was in Deep Doze mode. Phone goes to it after one hour regardless of working GPS logging apps (there was the same problem with other apps too). It was only fixed with root-permissions app disabling Deep Doze.
