### ISSUE TITLE
Translation issue in Italian

### ISSUE THREAD

**Issue by mfrancesconi** [mendhak/gpslogger#864]
Hello,
in version 107-fdroid inside "Dettagli Registrazione", "Creazione di nuovi file" the first option "Once a month" is written in English.

**Comment by mendhak** [comment]
There's no translation for it on Crowdin.  If you tell me what to put there I could add it in.  

https://crowdin.com/translate/gpslogger-for-android/17476/en-it?filter=basic&value=2#q=month

**Comment by mendhak** [comment]
I've put "Un file al mese"
