### ISSUE TITLE
Send to URL function only sends over HTTP protocol

### ISSUE THREAD

**Issue by doublenick** [mendhak/gpslogger#869]
I also tried back 3 versions, but the error occurred everywhere.
In the log I see this:
HTTP request complete with unexpected response code Response{protocoll=http/1.1, code400 message=Bad Request, url=https://home.myopenhab.org/gpstracker/gpslogger}

Is it possible not to call the URL with http / 1.1?

Thanks,
Zsolt

**Comment by mendhak** [comment]
This is the behavior of the OKHttp library that's used:

https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/protocols/

> By default this client will prefer the most efficient transport available, falling back to more ubiquitous protocols. Applications should only call this method to avoid specific compatibility problems, such as web servers that behave incorrectly when HTTP/2 is enabled.

It sounds like it tries HTTP 2, then HTTP 1.1.   HTTP 1.0 is not allowed.

**Comment by doublenick** [comment]
I want to send data to OpenHab, the gpslogger app was recommended. 
Do you have experience with others how it works properly?
Would you like me to send you more information?

**Comment by doublenick** [comment]
The problem is solved.
I entered the incorrect
HTTP Body involved.
Here's how: {"_type": "location", "lat":% LAT, "lon":% LON, "tid": "XY", "acc":% ACC, "batt":% BATT, "tst ":% TIMESTAMP}

It was missing {}
