### ISSUE TITLE
V110 cannot write to previously granted folder on Android 11.

### ISSUE THREAD

**Issue by DazzyWalkman** [mendhak/gpslogger#880]
My phone runs Android 11. I upgraded GpsLogger from v109 to v110. The app have been granted "Files and media access rights" before upgrade. 
When I tried to start recording, GpsLogger v110 complained about my previously set folder on the external SD unwritable, and refused to work. There is no prompt for me to grant folder access. Downgrade to v109, all went fine again.

**Comment by mendhak** [comment]
Ah not good... sorry about that... I think I found out why.   I know that the SDK upgrade has more restrictive storage, but I have added  [`android:requestLegacyExternalStorage`](https://github.com/mendhak/gpslogger/blob/e6fc351587e606ef2672e74ed9260f9e6619e61f/gpslogger/src/main/AndroidManifest.xml#L38) - I thought that should have allowed it, but I see this:

> Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.

I had to target SDK 30 to accommodate for the various background permissions that is being required.  

I did some testing on an emulator, and the file does get written to if I'm using the path like this:

```
/storage/18EE-2110/Android/data/com.mendhak.gpslogger/files/
```

18EE-2110 - I had to figure that out from looking at the SDCard's properties.  Can you try something like that?

![image](https://user-images.githubusercontent.com/746276/120539869-f2966d00-c3df-11eb-8133-b8e2c7908a42.png)

**Comment by DazzyWalkman** [comment]
Thanks for the pointer. I'll do some more test when I have time, probably this weekend, with debug log.
I've got the mount point of my external sd. My prefer path is /storage/2099-8403/gpslog. I'll see if the scope storage path work. A bit inconvenience for not been top level folder, though.

**Comment by joergRossdeutscher** [comment]
I got into sn issue loop here, because I use the app "Folder Sync" to put the local GPX folder on my webserver. So, wherever I put the data, either GPSlogger or FolderSync was not allowed to use that folder.
I ended up remembering that the "Downloads' folder is kind of public and switched to ~/Downloads/gpx succesfully.

**Comment by DazzyWalkman** [comment]
I tried V111 on Android 11 with following file paths and results:

 ` /storage/2099-8403/gpslog `
Failed with MediaProvider complaining "Writing to a non-default top level directory is not allowed!"

`/storage/2099-8403/Android/data/com.mendhak.gpslogger/files` 
Success

`/storage/2099-8403/DCIM/gpslog` 
Success

`/storage/2099-8403/Download/gpslog` 
Success

V111 is essentially the same as V110 on local storage access. I used a logcat app running in root mode since the built-in debug.txt of GpsLogger is only written to the writable file path. 
Not much detail about storage access revealed anyway.

**Comment by mendhak** [comment]
Thanks for that troubleshooting, it is useful.  I've updated the list in the FAQ:  https://gpslogger.app/#howtologtoanexternalsdcard

Maybe it could be made easier for the user if the path were printed in the dialog. Or I could bring back the folder picker, I used to have one and had to remove it as it was causing a lot of problems.  Might be worth revisiting this.  Anyway that's another topic, so I'll close this.

**Comment by mendhak** [comment]
Hi all, finally v117 is on F-Droid.  The app will now ask for a manage storage permission (on Android 11+) when you choose the 'save to folder' setting.  In my emulator testing, only on Android 11+, I was also able to save to SD card.  But not on any other OS version. 

There's also a graphical folder picker for files and folders so you don't have to type it in anymore.  The folder picker is for saving the log location, the file picker is for SFTP private key path.  

I'm now going around and closing a bunch of issues related to folder permissions.
