### ISSUE TITLE
Sending Username and Password with http own Cloud

### ISSUE THREAD

**Issue by ranjeewainfo** [mendhak/gpslogger#888]
Hello to everyone ! 
I have my own cloud api php file on www.sitename.com/api/gps.php 
But I am having a trouble to identify user name ?
GPSLogger Settings Shows me " GPSLogger Version 106"
Some one can help me ?

**Comment by mendhak** [comment]
I don't believe this app's OwnCloud implementation will work with what you're showing.  Only a base OwnCloud URL.  

What you're showing seems to be a custom API URL?  In that case you might be looking for the Custom URL feature, not OwnCloud.

**Comment by ranjeewainfo** [comment]
0 Hi, Friend, I am glad your respond, Please check following Image. If I am in a wrong settings please correct me 
![WhatsApp Image 2021-08-06 at 21 30 36](https://user-images.githubusercontent.com/69750705/128539525-286bd714-71c4-4796-b4f2-4013d04b902d.jpeg)
