### ISSUE TITLE
Version 111 is not available on the API 23 platform

### ISSUE THREAD

**Issue by wowhhh** [mendhak/gpslogger#889]
Hi, there, I found gpslogger(version 111) can't start logging on API 23 platform.
### Description
I run gpslogger on my Samsung device which API level is 23, but when I click the start logging button nothing happened. 

But in my Huawei device which API level is 29, the function is fine.

I think this problem is due to getGpsStatus API. 

Because in API 29 device, the log is"D/GeneralLocationListener: onGpsStatusChanged:136 - 35 satellites". But in API 23 device, it always returns 0 satellites.

The callchain about getGpsStatus API is:
```
CALLCHAIN:
	com.mendhak.gpslogger.GeneralLocationListener.onGpsStatusChanged(int)void
	 android.location.LocationManager.getGpsStatus(android.location.GpsStatus)android.location.GpsStatus
```
### Reproduce
Left: API 29; Right: API 23

Step 1: enter the app from the home screen 
Step 2: allow location and storage permission requests.
Step 3: click the start logging button

As we can see, only API 29 devices have location data.

https://user-images.githubusercontent.com/26241319/124872601-0e50ec80-dff8-11eb-8f7b-8a72f958357f.mp4

Could you help me review this issue? Thanks!!!

**Comment by mendhak** [comment]
Hi thanks for that, I didn't know you could embed videos on Github!

I found my old Nexus 5 with API 23, and tested it, and I was able to get satellites.  

![image](https://user-images.githubusercontent.com/746276/124975795-52f37c80-e026-11eb-923b-b60bd0aadf4d.png)

I also tried with GPS Data app to see satellites 

![image](https://user-images.githubusercontent.com/746276/124977973-16755000-e029-11eb-968a-bfceec1d3c94.png)


So the satellites _should_ be working for you, but the 0 feels like something is missing.  

There are a few things you can try, based on stuff I've read in the past.  

The first thing to try, is to remove the SIM and reinsert the SIM.  Even though this is about satellites.  

The next thing to try is to refresh the AGPS data.  Have a look at [GPS Status](https://play.google.com/store/apps/details?id=com.eclipsim.gpsstatus2&hl=en_GB&gl=US) or [GPS Data](https://play.google.com/store/apps/details?id=com.pierwiastek.gpsdata&hl=en_GB&gl=US) and then from there, delete and refresh the AGPS data.  These apps linked should also show you satellite visualisation so you'll know if it's working or not.  

Warning though, this can take a long time for the phone to recover the 'almanac' of satellites.  See this [note](https://gpslogger.app/gps-fix-details.html).  Once the AGPS data is deleted, it takes a long time, probably 30 minutes, to get it back.  I've done this a few times and I sometimes have to restart.  

Finally when trying to hit a location fix for the first time, leave the app running for up to 30 minutes by a window.

**Comment by wowhhh** [comment]
OK! 👍 
Thanks for your reply!
I will test it again with your suggestion.

Thanks.

**Comment by mendhak** [comment]
I assume this is working now?  I'll close this issue as I'm doing some cleanup
