### ISSUE TITLE
GPSLogger continues logging to same file past midnight

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpslogger#89]
I've received several emails/comments telling me that if you start logging to a file, yyyymmdd, the file name remains the same even when it's yyyymmdd+1.

**Comment by FoboCasteR** [comment]
Hi!
I'm using GPSLogger ver. 66 on Android 5.0. I'm faced with a situation when logging to gpx file was stopped after midnight. The 'New file creation' was set at 'Every time I start'.
