### ISSUE TITLE
GPSLogger instalation error on f-droid

### ISSUE THREAD

**Issue by thomaswhite** [mendhak/gpslogger#890]
At the moment there is an installation error about missing file _107.apk
I do hope you will have time to upload the missing file. 
Thank you for your great work

**Comment by mendhak** [comment]
It looks like FDroid removes versions of an app older than 3 releases. 
I managed to find the older APK, I've uploaded it here: https://github.com/mendhak/gpslogger/releases/tag/v107


Direct link: https://github.com/mendhak/gpslogger/releases/download/v107/FDROID_ARCHIVE_com.mendhak.gpslogger_107.apk
