### ISSUE TITLE
feature request: limit log rate with "log passive locations"

### ISSUE THREAD

**Issue by relaystar** [mendhak/gpslogger#892]
I use GPSlogger as a device tracker for my home assistant configuration.  This uses a custom url configuration.

Without passive locations enabled, it seems to work as expected (thanks!).

I'm guessing here, but with passive locationes enabled it seems to log as fast as it possibly can, to a queuing system.  The queue appears to only actually call the custom url once every 10 seconds (according to my web server logs).  Thus the queue gets very long when, for instance, the user is playing pokemon go, or driving using google maps as their satnav.  

The result of this is that my location in home assistant can lag _hours_ behind reality, with my phone logging to home assistant every 10 seconds, when it was presumably receiving passive locations much, much faster.

So ideally I'd like a 2nd configurable interval, ie the current one, plus a 2nd one for passive updates, which I would set to be much shorter.

Thanks

**Comment by mendhak** [comment]
Although I've not got plans to add more timers/intervals, I've added a change in the upcoming Milestone 130 (and just before that), which should limit how much passive points get logged

**Comment by mendhak** [comment]
v130 is now on FDroid and the releases. 
Passive location will now match the criteria, eg satellite/network.  If neither satellite nor network is selected, any passive location will be logged.
