### ISSUE TITLE
Custom url problem

### ISSUE THREAD

**Issue by klap14** [mendhak/gpslogger#894]
Hi, i have problem sending data with url: ---
With old domain it worked but now it is not saving data to database.
If i use that URL in my browser, it works.

Thanks for any help

**Comment by mendhak** [comment]
When the app writes to that URL, are there any errors appearing in the log view?  If no errors are appearing, in other words if the HTTP request is successful, then the error will be on your server side.  Have a look in the web logs, or if this is a custom website, ensure that your app-load.php is logging errors to a file so you can see if anything's going wrong during the DB write.

**Comment by klap14** [comment]
In app arent any errors. Problem is that i cant log errors on my website. But it is weird that when i use url that app generated (i mean data that app generated) it works... It doesnt make any sense for me...
