### ISSUE TITLE
An adaptation problem of layout

### ISSUE THREAD

**Issue by yuhuitech** [mendhak/gpslogger#896]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the simple view page, **texts of latitude could not be seen fully**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 112, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts of latitude, and in this circumstance, part of them ("N") seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the "simple view" page, and click "start logging", then click "stop logging"
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/129159958-85d690c4-027b-4191-a848-dad40c1db729.png" alt="Screenshot_1628673224 copy" width="250"/>

**Environment**

1. Version of gpslogger: 112
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by franklinbill** [comment]
Unfortunately, I also encountered the same issue. After font adjustment, the text is incomplete.

**Comment by mendhak** [comment]
Hey thanks for the issue details and the PR.  I was able to recreate the problem on a 3A XL and emulator too.  I'm testing out the PR now.

**Comment by mendhak** [comment]
The PR has been merged, thanks for all the work you did on that.  I've [created a tag for this](https://github.com/mendhak/gpslogger/releases/tag/v113).  It usually takes about a week for F-Droid to pick up the new tag and publish it on their store, so please be patient. 

@yuhuitech  I would also like to add that I'm genuinely impressed with the effort you're putting into fixing display problems with various applications.  Yes it'll be a little slow and may not always turn out the way you want, but perseverance is key.  You found a problem that affected you, and you pursued solutions to those problems or find ways to improve the situation, I think you're demonstrating a great example of the spirit of open source.  Kudos to you. :+1:

**Comment by yuhuitech** [comment]
Thanks again for your comments!! It truly takes time to fix display issues in this circumstance, but I still find this progress exciting and fun. What's more, I have learned a lot from fixing those applications as well. I will keep on working on open-source applications and try to enhance their experience. :)

**Comment by mendhak** [comment]
It's in F-Droid so I'm closing this.
