### ISSUE TITLE
Can't upload to FTP with path containing non-english characters

### ISSUE THREAD

**Issue by jenda69** [mendhak/gpslogger#901]
Hello,
I'm occasionally uploading GPX using FTP but I stumbled upon this problem. If I set Folder on server to something with non-english characters (e.g. letters with diacritics [ěščřžýáíé...] my language frequently uses), GPSLogger just ignores whole path and tries to upload the file to the root `/` directory.
Specifically I'm trying to upload the file to `ftp://nas-ip` server with `/My_Passport/Fotky/Výlety/2021/` as Folder where all my photos from current year get uploaded from my phone, camera etc.
If I set Folder to `/My_Passport/Fotky/`, it uploads fine, but as soon as I add `Výlety/`, it uploads to the root directory.
Other apps have no problem with upload to this path since the server uses UTF-8 file names.

I also tried typing out `%C3%BD` istead of `ý` (as in encoded uri) but that didn't help.

Is possible to fix this? I'd rather not rename the directory, it would ruin indexes of various photo managers etc. I use.

Log from upload here. Looks like it actually tries to change the directory but fails.
```
17:33:02 DEBUG LoggingOutputStream.flush:79 - 220 Welcome to ASUS RT-AX56U FTP service.

17:33:02 DEBUG LoggingOutputStream.flush:79 - USER ovecka

17:33:02 DEBUG LoggingOutputStream.flush:79 - 331 Please specify the password.

17:33:02 DEBUG LoggingOutputStream.flush:79 - PASS ********

17:33:02 DEBUG LoggingOutputStream.flush:79 - 230 Login successful.

17:33:02 DEBUG FtpJob.upload:142 - Uploading file to FTP server 192.168.1.253
17:33:02 DEBUG FtpJob.upload:143 - Checking for FTP directory /My_Passport/Fotky/Výlety
17:33:02 DEBUG LoggingOutputStream.flush:79 - SYST

17:33:02 DEBUG LoggingOutputStream.flush:79 - 215 UNIX Type: L8

17:33:02 DEBUG LoggingOutputStream.flush:79 - PASV

17:33:02 DEBUG LoggingOutputStream.flush:79 - 227 Entering Passive Mode (192,168,1,253,211,187).

17:33:02 DEBUG LoggingOutputStream.flush:79 - LIST /My_Passport/Fotky/Výlety

17:33:02 DEBUG LoggingOutputStream.flush:79 - 150 Here comes the directory listing.

17:33:02 DEBUG LoggingOutputStream.flush:79 - 226 Directory send OK.

17:33:02 DEBUG LoggingOutputStream.flush:79 - CWD /My_Passport/Fotky/Výlety

17:33:02 DEBUG LoggingOutputStream.flush:79 - 550 Failed to change directory.

17:33:02 DEBUG LoggingOutputStream.flush:79 - TYPE I

17:33:02 DEBUG LoggingOutputStream.flush:79 - 200 Switching to Binary mode.

17:33:02 DEBUG LoggingOutputStream.flush:79 - PASV

17:33:02 DEBUG LoggingOutputStream.flush:79 - 227 Entering Passive Mode (192,168,1,253,157,82).

17:33:02 DEBUG LoggingOutputStream.flush:79 - STOR gpslogger_test.xml

17:33:02 DEBUG LoggingOutputStream.flush:79 - 550 Permission denied (restricted operation).

17:33:02 DEBUG FtpJob.upload:163 - Failed to FTP file gpslogger_test.xml
17:33:02 DEBUG LoggingOutputStream.flush:79 - QUIT

17:33:02 DEBUG LoggingOutputStream.flush:79 - 221 Goodbye.

17:33:02 DEBUG AppSettings$1.d:92 - safeRunResult for com.mendhak.gpslogger.senders.ftp.FtpJob@eec4a0e : true. re run:false. cancelled: false
```

Maybe this could be relevant? https://stackoverflow.com/questions/9535925/filename-encoding-in-apache-commons-net-ftpclient

Final edit: I actually solved my issue in a hacky way. If you save UTF-8 file with `ý` in it and reopen it as Windows-1252 file, content shows up as `Ã½`. So I put `.../VÃ½lety/...`  in the Folder setting and logs upload correctly now. LOL

**Comment by mendhak** [comment]
Hey there, nice one, you even supplied the solution haha. 
I was able to recreate the problem in an emulator and then apply the fix and test it with some more UTF-8 examples. 

![image](https://user-images.githubusercontent.com/746276/131913002-2013cf59-9fa0-45e3-89b1-03f3d6420909.png)

I also tested SFTP just to make sure, that was fine.

**Comment by mendhak** [comment]
I've tagged [release v115](https://github.com/mendhak/gpslogger/releases/tag/v115) and I think F-Droid can take up to a week to pick it up and make it available in the F-Droid store.

**Comment by mendhak** [comment]
It's in F-Droid now, v115.
