### ISSUE TITLE
[FEATURE REQUEST] Option to change data delimiter symbol and decimal separator symbol in output files

### ISSUE THREAD

**Issue by 3Domse3** [mendhak/gpslogger#921]

**Comment by 3Domse3** [comment]
@mendhak 
This would be important because, for example, in Germany the comma is used as the decimal separator, so importing the CSV in EXCEL always needs the user to manually exchange the commas and dots before.

**Comment by mendhak** [comment]
OK I was going to ask for some explanation.   

So in CSVs, how is the distinction made?  How do you represent: 

    15.1314, 86.24194, 55, "some annotation"

**Comment by 3Domse3** [comment]
Looks good :D

**Comment by mendhak** [comment]
v119 is now on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [in the releases](https://github.com/mendhak/gpslogger/releases/tag/v119).  I'm going around and closing some issues.
