### ISSUE TITLE
Custom URL Send data when get response from server

### ISSUE THREAD

**Issue by PersianCoders** [mendhak/gpslogger#923]
Hi 
I want to use Custom URL But my problem is: When Network Data Connection is poor , data is lost at the time of sending.
Could you tell me, how can I get response from server when data sent successfully?

thanks a lot

**Comment by mendhak** [comment]
v119 is now on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [in the releases](https://github.com/mendhak/gpslogger/releases/tag/v119).  I'm going around and closing some issues.
