### ISSUE TITLE
Upload to ownCloud -> error on custom URL

### ISSUE THREAD

**Issue by andreapx** [mendhak/gpslogger#929]
Sometimes my data doesn't get uploaded to ownCloud and when I try to upload them manually, it waits and then it says
`"Could` not send to custom URL"
and it shows the URL which has nothing to do with ownCloud.

**Comment by mendhak** [comment]
Any other information which could help me recreate the issue?  Is Custom URL enabled? Does the ownCloud upload succeed despite the Custom URL error?  

I've tried a few different combinations but I'm not seeing any Custom URL related errors when I upload to ownCloud.  

You could also try a [debug log](https://gpslogger.app/#troubleshooting) and mail it to me `gpslogger` at mendhak.com, and I could have a look at any clues in there.

**Comment by andreapx** [comment]
I'm sorry, but I've missed the notification about your response. Sorry.
It returned that error for a couple of days and then it started working normally again. I don't remember if the automatic upload to ownCloud was working, but I guess not.
Sorry if I can't be of any help...
