### ISSUE TITLE
can detect device is charging or not?

### ISSUE THREAD

**Issue by PersianCoders** [mendhak/gpslogger#931]
Hello

how can I detect device is charging or not ?
on custom URL or other options.
could you add this item on the next version?

thanks a lot

**Comment by mendhak** [comment]
Alright this looks simple enough :  https://developer.android.com/training/monitoring-device-state/battery-monitoring#java

And this feature has been requested several times so I'll have a look at adding it.

**Comment by mendhak** [comment]
I've got an APK here:  https://github.com/mendhak/gpslogger/releases/tag/v120-rc1  if you are able to test it.  Note that the APK is not compatible with F-Droid so if you install it you will lose all previous GPSLogger data.  

It's got a CSV field `battery_charging` and a Custom URL parameter `%ISCHARGING`

**Comment by PersianCoders** [comment]
> I've got an APK here: https://github.com/mendhak/gpslogger/releases/tag/v120-rc1 if you are able to test it. Note that the APK is not compatible with F-Droid so if you install it you will lose all previous GPSLogger data.
> 
> It's got a CSV field `battery_charging` and a Custom URL parameter `%ISCHARGING`

that's work well , thanks a lot.
when phone in charging , get true , and when phone is not charging , get false;

**Comment by normaligator** [comment]
Awesome I love to see this new feature. This will come in handy for my project. Thank you for this great app and all the effort.

I wanted to ask, since now we know the phones charging state. Would it be possible to get two different logging interval settings.
One for when the phone is charging and for when the phone is on battery.
That would be really cool to have.
During charging the logging could be every second. And on battery back to power saving eg. every 60 seconds.

**Comment by mendhak** [comment]
It's too complicated to implement that in GPSLogger.  I think a better way to accomplish that would be via an automation tool like Tasker or Llama Automate.  They can trigger events when charging events occur, and they can send commands to stop logging, switch profile, start logging.  What you'd need to do is prepare two profiles, each with different timings.

**Comment by normaligator** [comment]
Thank you for getting back to me and thanks for this idea. I will try this approach with two profiles👌🏼

**Comment by mendhak** [comment]
v120 is in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v120) and [on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)

**Comment by normaligator** [comment]
@Suncatcher it wouldn't hurt to be a bit nicer. The only thing being ridiculous is the fact that you didn't even understand what this change is about. And yes it is implemented, I use it a lot.
If you still don't understand this change, go and read the code.

**Comment by Suncatcher** [comment]
Sorry for being rough, but I did inspect your website, your github and you Readme, and none of them mention this feature. I did install the app and inspected the app settings and didn't find "start on charge" capability either. Would you be so kind to explain how to use this feature? It would help a lot.
I maybe was a little rude, but I fairly don't understand the approach where user must install third-party (paid!) apps to enable such a simple and essential feature. If you want money, just make a premium version of your app and include this feature there. It would be more honest to your users. Not to mention that Tasker does not work on Android GO, so is not available to me.

**Comment by normaligator** [comment]
Just for clarification, this is not my website or my app. I'm only a user of this app. Who responded to your message.

I'm very sorry to tell you, you still haven't understood the change which got implemented. This is not the same thing what you are asking for. The topic might be related, but it is not the same.

If you were a bit nicer to people, I would be happy to help you and give advice. But I have the feeling this is not worth it.
