### ISSUE TITLE
Replace MyTracks references with OpenTracks?

### ISSUE THREAD

**Issue by dennisguse** [mendhak/gpslogger#932]
:wave: 

Technically, MyTracks is not really existing anymore, right?
There are some references to MyTracks in the docs of GPSLogger and it would be a nice advertisement for OpenTracks would be replaced :sunglasses: 

PS/ the wakelock is still used in OpenTracks :)

**Comment by mendhak** [comment]
[Version 122 is on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/).  References to MyTracks have been replaced with OpenTracks in the [documentation](https://gpslogger.app/).

**Comment by dennisguse** [comment]
@mendhak :sunglasses:
