### ISSUE TITLE
Can't set file name in Logging details prefs

### ISSUE THREAD

**Issue by mtalexander** [mendhak/gpslogger#935]
I just upgraded gpslogger to version 119 on a Pixel 3 XL running Android 12 with the October security patch.  It seems to be working fine with one exception.  The three preference items "Custom file name", "Allow custom file name to change dynamically", and "Ask for a file name on every start" are grayed out and can't be changed.  Furthermore, the custom file name is set to "gpslogger" but the files created are named with just the date as an eight digit number (e.g. 20211210.gpx).  This is prefixed with the machine ID if "Prefix unique string to file name" is set so at least this much is working.

**Comment by mendhak** [comment]
Yes that's right, those three options will only be enabled if you pick "Custom file" under the "New file creation" menu. 

As soon as you pick once a day/month/everytime I start, then those options you mentioned will get disabled again.  

![image](https://user-images.githubusercontent.com/746276/146534992-204d1d1f-39ff-4ca2-838e-132ec0f78544.png)

**Comment by mendhak** [comment]
In case it was already enabled could you try unsetting it then setting it again?

**Comment by mtalexander** [comment]
OK, I see how it's supposed to work.  I must have accidentally turned the "Every Day" option on and didn't realize it would have this side effect.
