### ISSUE TITLE
Speed GPX1.1

### ISSUE THREAD

**Issue by romakh80** [mendhak/gpslogger#940]
Hello!
Please, add code to write speed information while logging in GPX 1.1 format.

>>gpslogger/loggers/gpx/Gpx11FileLogger.java
>>// course and speed are not part of the GPX 1.1 specification
     // We could put them in an extensions such if we really wanted.
Wanted!

Thanks!

**Comment by mendhak** [comment]
What will you be using to process the speed?  Do you know what extension it is expecting.  Or a better question is, what's the most common extension that popular GPX parsing software would expect? 

I did some searching I was able to find that Garmin has a `<xxxxx:speed>` extensions.  

https://www8.garmin.com/xmlschemas/TrackPointExtensionv2.xsd

But I don't know if this is widely used.

**Comment by romakh80** [comment]
Hi!
I'm currently using software which creates gpx1.1 files with speed data in extensions: <extensions><speed></speed></extensions>. But as you rightly noticed Garmin requires smth like: <extensions><gpxtpx:speed></gpxtpx:speed></extensions>. Suggest to maintain Preferences switches: "Write gpx 1.1 speed info (yes|no)", "Use speed or gpxtpx:speed tags... maybe both".

**Comment by dennisguse** [comment]
@mendhak Here is how we do this in OpenTracks:
* GPX header: https://github.com/OpenTracksApp/OpenTracks/blob/46cf7f9acf328c4d4541a38429fbffc3ca45b03c/src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java#L217
* writing data: https://github.com/OpenTracksApp/OpenTracks/blob/46cf7f9acf328c4d4541a38429fbffc3ca45b03c/src/main/java/de/dennisguse/opentracks/io/file/exporter/GPXTrackExporter.java#L292

**Comment by mendhak** [comment]
Thanks for that @dennisguse , it's very useful for me to go through that code. I'm going to try adding this  `gpxtpx` Garmin extension since OpenTracks uses it too.

**Comment by mendhak** [comment]
If you are able to test I have uploaded an APK here:  https://github.com/mendhak/gpslogger/releases/tag/v120-rc2 under Assets.  

This APK is incompatible with F-Droid so if you install it you will lose all your GPSLogger data and files.

**Comment by mendhak** [comment]
v120 is in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v120) and [on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/)
