### ISSUE TITLE
Rows in csv

### ISSUE THREAD

**Issue by gyorfi97** [mendhak/gpslogger#957]
Hi,

Is it possible, when generating a csv file and saving it to deopbox, that the csv file overwrites the old one?

Now, as the app saves the csv, you get a bigger and bigger file with multiple rows.

It would have grate potential to use your app in GIS projects, if the csv would contain only the newest data.

Thanks
Zoli

**Comment by mendhak** [comment]
I'm not sure if I understood properly but the CSV file should be overwriting the previous CSV file of the same name, so as long as you pick a relatively static name, it should just keep getting overwritten.  Yes the file would get bigger and bigger.  

If what you're looking for is something more custom/dynamic where that file being overwritten only has latest data, then that is not a use case suitable for dropbox or a file upload, that's better served by the Custom URL logging feature (which can also do an auto-send at regular intervals).
