### ISSUE TITLE
Openstreetmap: can not grant permisson

### ISSUE THREAD

**Issue by datenbank-projekt** [mendhak/gpslogger#960]
Hi,

I try to upload automatically to my osm account.
I am trying to give permissions: click in the auto upload osm aection opens openatreetmap. I can sign in and grant permission ... and then nothing happes.
When I check oauth permissions on the osm page, GPS logger is registered there. Nothing changes however in gpslogger.

![screenshot of settings](https://user-images.githubusercontent.com/29085761/160646152-330e5023-a1f1-4c02-8d8c-54f06141fbad.jpg)

**Comment by mendhak** [comment]
What should be happening is you click authorize, it opens the browser, you sign in to OSM, you click the grant button.  Sounds like you're getting up to here.  Then when the grant/allow button is clicked, the browser is supposed to send the response back to the GPSLogger app, and that part must be messing up somehow: the browser to app communication. 

Could this be related to the browser you're using?  Could you try Chrome or Firefox.     
If you're already using one of those, are there any other things installed on the system which could be intercepting intents?

**Comment by datenbank-projekt** [comment]
Hi,
thanh you for pointing in the right direction. 
I am using Vivaldi as my system browser and there one can find the option to open app specific links.directly in Vivaldi. I had the setting enabled. After your reply I disabled this setting and the activation of osm works as is supposed to (after clicking allow gpslogger is reactivated).
Maybe it is an idea to add this information the docs?
In the current Vivaldi it is the last setting "about Vivaldi" (German: "Über Vivaldi"): Stay in browser (im Browser bleiben) needs to be off.
You can close this ticket. Thank you very much for this great app!

![Imagepipe_12](https://user-images.githubusercontent.com/29085761/160770370-f88b2314-c95b-4c02-95aa-b3e02e601414.jpg)

**Comment by mendhak** [comment]
Thanks, will keep it in mind or consider adding something if this is more frequent
