### ISSUE TITLE
Log of %TIMEOFFSET to custom URL not escaped

### ISSUE THREAD

**Issue by TilmanJimenez** [mendhak/gpslogger#963]
Using `%TIMEOFFSET` when logging to a custom URL does not encode the `+` sign (`%2B`) which causes problems when trying to parse it on the backend.
Do to the missing encoding the resulting string is `2011-12-25T11:27:33 04:00` instead of the expected `2011-12-25T11:27:33+04:00`

Thanks for the awesome app!

**Comment by mendhak** [comment]
Thanks!  OK so added URL Encoding:

    ...&timeoffset=2022-04-22T20:19:53.228%2B01:00&time=2022-04-22T19:19:53.228Z...

I added it to [the latest milestone branch](https://github.com/mendhak/gpslogger/pull/953), I should probably merge and tag it soon and do a release.

**Comment by mendhak** [comment]
v121 is now in [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and the [releases](https://github.com/mendhak/gpslogger/releases/tag/v121).
