### ISSUE TITLE
Detailed View jumps around (cosmetic)

### ISSUE THREAD

**Issue by QJKX** [mendhak/gpslogger#968]
The number of decimal places on the coordinates is usually 4, but sometimes 3.

On this particular device this causes the break in the coordinates to randomly switch between looking like:

    00° 00'
    00.0000" N

and

    00° 00' 00.000"
    N

Likewise for Longitude.

**Comment by mendhak** [comment]
I've adjusted the label size, main font size ever so slightly, and the lat/long is a bit closer to the label now. I think it should fit on a single line.   

![image](https://user-images.githubusercontent.com/746276/168475640-b8e45163-2819-45e5-a274-1ac36ac7006c.png)

![image](https://user-images.githubusercontent.com/746276/168475705-bc8ba59e-9206-4b6d-97fe-ffd2ea3f0480.png)

**Comment by QJKX** [comment]
Thanks :-)

**Comment by mendhak** [comment]
[Version 122 is on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and [the releases](https://github.com/mendhak/gpslogger/releases/tag/v122).
