### ISSUE TITLE
Short logging interval not working properly on Android 12

### ISSUE THREAD

**Issue by JanHellwig** [mendhak/gpslogger#969]
Since I started using an S21 with Android 12, I noticed a "bug" with one of my logging profiles. The logging interval is set to 60 seconds, but the app only attempts to log a point after 90 seconds or so. Considering that this wasn't an issue on my old phone, I think it's related to Google's attempts to improve battery life. Turning off battery optimizations for GPSLogger hasn't helped though.

I've dug a bit into the code and documentation to see if I can find something.

In [`setAlarmForNextPoint()`](https://github.com/mendhak/gpslogger/blob/cb7a8e793d0abce043b47d8f1e3c8a987174dfc9/gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java#L1004), there is a check do see if the device is dozing. Considering that I've set battery optimizations for the app to "Unrestricted", I assume that [`isDozing()`](https://github.com/mendhak/gpslogger/blob/cb7a8e793d0abce043b47d8f1e3c8a987174dfc9/gpslogger/src/main/java/com/mendhak/gpslogger/common/Systems.java#L119) always returns `false`.
In that case, the alarm for the next recording would be set using [`AlarmManager.set()`](https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20android.app.PendingIntent)), which according to the documentation "may be deferred and delivered some time later" since API 19.
On the other hand, if `isDozing()` returns `true`, the next alarm is set using [`AlarmManager.setExactAndAllowWhileIdle`](https://developer.android.com/reference/android/app/AlarmManager#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)) which does not seem to be impacted by the random delays.
There is also [`AlarmManager.setExact()`](https://developer.android.com/reference/android/app/AlarmManager#setExact(int,%20long,%20android.app.PendingIntent)) with which "the alarm will be delivered as nearly as possible to the requested trigger time", whatever that means. Google lists an Alarm clock as an example, but I would have expected those to use `setExactAndAllowWhileIdle()`.

Now, I don't have much experience developing on Android, but based on the documentation I'm wondering if it would make sense to replace the `set()` call with either `setExact()` or `setExactAndAllowWhileIdle()`. Yes, it could have an impact on battery usage on modern Android versions, but personally I think that users of an app like this one are aware that short logging intervals will use more battery. Maybe it could also make sense to add a setting to allow per-profile customization of how precise one wants the interval to be?

**Comment by mendhak** [comment]
Hey @JanHellwig  thanks for digging through that logic, it was quite useful.  I think what you have said sounds reasonable.  If you are setting a short logging interval, it will use more battery.  In this commit https://github.com/mendhak/gpslogger/commit/ee96c9bd17f77db4b7061a061585346c992976eb you will see I've just replaced both types of calls with `setExactAndAllowWhileIdle`.  

If you're able to test, I've put an APK here:  https://github.com/mendhak/gpslogger/releases/tag/v122-rc1

I'll try running this with short intervals like 1s, 5s, and normal intervals like 60s, 120s, to see how it does.

**Comment by JanHellwig** [comment]
I did a quick check and it seems to work properly with my 60s interval profile. Thank you.

Unrelated to this, but I did have to uninstall the app before installing the RC as Android was complaining about it conflicting with the version from F-Droid. Is it possible to have them compatible somehow? That would make testing RCs a bit easier.

**Comment by mendhak** [comment]
Hey thanks for testing, that will be useful to others. I'm still going to try it out a bit more before publishing.

It's not possible to have the APKs compatible.  The F-Ddroid version is signed by F-Droid developers (they even build it themselves), and the APK I post on Github is signed by me.  That's why Android OS complains about it.

**Comment by mendhak** [comment]
[Version 122 is on F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/).
