### ISSUE TITLE
Feature Request: Only Send Latest Location to Custom URL

### ISSUE THREAD

**Issue by RealDudePerson** [mendhak/gpslogger#986]
I plan on using gpslogger to share my current location with family members and potentially friends. Right now I have it in a working state with the custom URL feature, thank you! What I have noticed is that it sends all recorded locations to the custom server when sending logs. One feature change I would like is an option under 'Log to custom URL' to only send one http request at each auto send interval.

When the intent is to share current location, only the most recent recorded location is relevant. Ideally there would be a way to query the local gpslogs and find the most recent data point and send that one.  This would save on time updating the custom url, data, and battery life.

I made a crude mock up of how the UI could be updated with the new toggle.
![index](https://user-images.githubusercontent.com/4443705/176242392-21051e0c-4fc7-414e-9823-3bb5b532f633.jpg)

**Comment by RealDudePerson** [comment]
I don't know if this is poor form or not, but I will put a ~100k sat bounty on this feature (minus a few hundred sats miner fee, or lightning tx fee).

**Comment by RealDudePerson** [comment]
I guess it was a misunderstanding on my part. It sounds like I was duplicating the sends by enabling 'log to custom url' and enabling 'auto sending'

'Auto sending' is a bulk log send feature, and 'logging to custom url' will only send the current location at the set interval.

My application is set to only receive lat/lon/acc and I made the logic set the time to the servers recieve time. Probably not the best, but I'm not a software engineer. This was causing problems when I had 'auto sending' enabled as it would treat historical points as current points. 

I will test with disabled 'auto send' and close the issue.

Thanks!

**Comment by theraser** [comment]
Thanks for the explanation, I just hit the same "issue" and wondered why my mobile data usage exploded after enabling both modes :-)

Is there any way to record a track using an (local) interval of i.e. 5 seconds and send only the last location i.e. every 10 minutes using the "logging to custom url" option? Did I miss something or is this not possible without an external app? OsmAnd got this feature but it is a battery killer for me, GPS Logger is way more efficient...

**Comment by mendhak** [comment]
So if you've hit this issue too, that means there's a communication issue. I'll probably need to add a label against the options to clarify what they are doing.  

It's not possible to have separate time intervals for custom URL vs local logging.  It's done for efficiency as making it independent would be harder to maintain but also a bigger battery drain too.

**Comment by mendhak** [comment]
How's this summary

![image](https://user-images.githubusercontent.com/746276/192164751-9ca9c8f8-235b-424b-99a9-414ee016d765.png)

**Comment by theraser** [comment]
Thanks, the first one is easy to understand for me.

For "Allow auto sending" I would suggest to add something like "bulk sending". This way everybody should know that this is a collection of data points and "log to custom URL" will send only single points.

**Comment by mendhak** [comment]
Yes good one, bulk is a good word to use.  I'll go with that.

![image](https://user-images.githubusercontent.com/746276/193446637-4f578a0d-218d-4796-902d-547cdf8c5564.png)

**Comment by mendhak** [comment]
v124 is now on [F-Droid](https://f-droid.org/en/packages/com.mendhak.gpslogger/) and in the [releases](https://github.com/mendhak/gpslogger/releases/tag/v124).  To be clear, only the extra labels are in F-Droid to clarify the difference.
