### ISSUE TITLE
HTTP URL requests occur more often than the given interval

### ISSUE THREAD

**Issue by WirelessRoth** [mendhak/gpslogger#988]
Hi,
I only use HTTP-Get-Request to submit the current location, i.e. disable all file logging.

The Interval was set to 600 s (10 min). If "Distance between measurements" was set to 0
BUT: the HTTP-Get request occur more often than any 10 min (it is not a clear period, sometime once a minute, sometime every 3 min).
I then set "Distance between measurements" to 50 meters. 
- Not moving, the HTTP-Get only occurs once (at all).
- When moving,  HTTP-Get appears again more often more often than every 10min.

It seems, using HTTP only, the Interval was simply ignored.
The question is, how to force to app to log not more than every 10 min.

Regards

Jörg

**Comment by WirelessRoth** [comment]
Ah,

because of a malformed HTTP response, that seemed to be the HTTP retries. After reply 200 OK all was fine.

Regards

Jörg

**Comment by mendhak** [comment]
Sorry my late reply but glad you found it.  Yes the Custom URL, and other senders, have a retry mechanism, so that's what you were seeing.
