### ISSUE TITLE
Create KMZ with embedded photos

### ISSUE THREAD

**Issue by dnmtsn** [mendhak/gpslogger#99]
To me, the output of a trip is a file that I can share with people and that shows them where I've been and what photos I took and where. You can only do that now by using a GPX file in some desktop app, which is a time-consuming and messy process AND you need to use a PC. 
I have searched for something that can do all that on a mobile device for months and it simply doesn't exist. 

Ideally the app should allow the user to point to a folder where photos are stored then create the KML with GPS track + photos in that folder that correspond to points on the track. This would allow creating KML's using photos not taken with the phone (photos transfered via eye-fi for example) as well as those taken with the phone .

**Comment by mendhak** [comment]
Sorry, this is too niche, not the aim of GPSLogger.
